// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasNewHighLowRequest 는 미국주식 신고가/신저가(주식/업종)(usa24100) 요청이다.
type GetOverseasNewHighLowRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목구분 (0:전체, 1:주식)
	StkTp string `json:"stk_tp"`
	// 업종코드 (000:전체, usa10101 API 참고, stk_tp(종목구분) 1일 경우)
	IndsCd string `json:"inds_cd"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 신고가신저가구분 (1:신고가, 2:신저가)
	NtlTp string `json:"ntl_tp"`
	// 고저기준 (1:고가저가기준,2:종가기준)
	HighLowTp string `json:"high_low_tp"`
	// 기간입력 (n일 기간(최대250), 일자구분과 동시사용 안됨)
	Dt string `json:"dt"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasNewHighLowResponse 는 미국주식 신고가/신저가(주식/업종)(usa24100) 응답이다.
type GetOverseasNewHighLowResponse struct {
	// 결과리스트
	ResultList []GetOverseasNewHighLowResultListItem `json:"result_list"`
}

// GetOverseasNewHighLowResultListItem 는 ResultList 의 원소다.
type GetOverseasNewHighLowResultListItem struct {
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량
	AccTrdeQty string `json:"acc_trde_qty"`
	// 전일거래대비 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PreTrdeRt string `json:"pre_trde_rt"`
	// 매도호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	BuyBid string `json:"buy_bid"`
	// 250일고가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 250일저가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 전일거래량
	PredTrdeQty string `json:"pred_trde_qty"`
}

// GetOverseasNewHighLow 는 미국주식 신고가/신저가(주식/업종)(usa24100) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 신고가/신저가(주식/업종)(usa24100)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasNewHighLow(ctx context.Context, req GetOverseasNewHighLowRequest, opts ...transport.Option) (*GetOverseasNewHighLowResponse, transport.Meta, error) {
	var out GetOverseasNewHighLowResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa24100",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
