// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasPriceByBandRequest 는 미국주식 가격대별주가(주식/업종)(usa20570) 요청이다.
type GetOverseasPriceByBandRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목구분 (0:전체, 1:주식)
	StkTp string `json:"stk_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 업종코드 (000:전체, usa10101 API 참고, stk_tp(종목구분) 1일 경우)
	IndsCd string `json:"inds_cd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 가격조건1 (최대 999999.99)
	PricCnd1 string `json:"pric_cnd1"`
	// 가격조건2 (최대 999999.99)
	PricCnd2 string `json:"pric_cnd2"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasPriceByBandResponse 는 미국주식 가격대별주가(주식/업종)(usa20570) 응답이다.
type GetOverseasPriceByBandResponse struct {
	// 종목수
	StkNum string `json:"stk_num"`
	// 상승
	RisingStkNum string `json:"rising_stk_num"`
	// 보합
	FlatStkNum string `json:"flat_stk_num"`
	// 하락
	FallStkNum string `json:"fall_stk_num"`
	// 결과리스트
	ResultList []GetOverseasPriceByBandResultListItem `json:"result_list"`
}

// GetOverseasPriceByBandResultListItem 는 ResultList 의 원소다.
type GetOverseasPriceByBandResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 매도호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	BuyBid string `json:"buy_bid"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
}

// GetOverseasPriceByBand 는 미국주식 가격대별주가(주식/업종)(usa20570) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 가격대별주가(주식/업종)(usa20570)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasPriceByBand(ctx context.Context, req GetOverseasPriceByBandRequest, opts ...transport.Option) (*GetOverseasPriceByBandResponse, transport.Meta, error) {
	var out GetOverseasPriceByBandResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20570",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
