// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasSectorListRequest 는 미국주식 업종리스트(usa10101) 요청이다.
type GetOverseasSectorListRequest struct {
	// 구분 (%:전체, 1:미국)
	Gubun string `json:"gubun"`
}

// GetOverseasSectorListResponse 는 미국주식 업종리스트(usa10101) 응답이다.
type GetOverseasSectorListResponse struct {
	// 결과리스트
	List []GetOverseasSectorListListItem `json:"list"`
}

// GetOverseasSectorListListItem 는 List 의 원소다.
type GetOverseasSectorListListItem struct {
	// 업종코드
	IndsCd string `json:"inds_cd"`
	// 업종명
	IndsNm string `json:"inds_nm"`
	// 업종영문명
	IndsEnm string `json:"inds_enm"`
}

// GetOverseasSectorList 는 미국주식 업종리스트(usa10101) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 업종리스트(usa10101)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasSectorList(ctx context.Context, req GetOverseasSectorListRequest, opts ...transport.Option) (*GetOverseasSectorListResponse, transport.Meta, error) {
	var out GetOverseasSectorListResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa10101",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
