// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasYearlyChangeRateRequest 는 미국주식 연도별 등락률(종목)(usa26410) 요청이다.
type GetOverseasYearlyChangeRateRequest struct {
	// 거래소구분 (필수)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasYearlyChangeRateResponse 는 미국주식 연도별 등락률(종목)(usa26410) 응답이다.
type GetOverseasYearlyChangeRateResponse struct {
	// 결과리스트
	ResultList []GetOverseasYearlyChangeRateResultListItem `json:"result_list"`
}

// GetOverseasYearlyChangeRateResultListItem 는 ResultList 의 원소다.
type GetOverseasYearlyChangeRateResultListItem struct {
	// 연도 (0:평균, YYYY:년도)
	Dt string `json:"dt"`
	// 1월 수익률
	M01PrftRt string `json:"m01_prft_rt"`
	// 2월 수익률
	M02PrftRt string `json:"m02_prft_rt"`
	// 3월 수익률
	M03PrftRt string `json:"m03_prft_rt"`
	// 4월 수익률
	M04PrftRt string `json:"m04_prft_rt"`
	// 5월 수익률
	M05PrftRt string `json:"m05_prft_rt"`
	// 6월 수익률
	M06PrftRt string `json:"m06_prft_rt"`
	// 7월 수익률
	M07PrftRt string `json:"m07_prft_rt"`
	// 8월 수익률
	M08PrftRt string `json:"m08_prft_rt"`
	// 9월 수익률
	M09PrftRt string `json:"m09_prft_rt"`
	// 10월 수익률
	M10PrftRt string `json:"m10_prft_rt"`
	// 11월 수익률
	M11PrftRt string `json:"m11_prft_rt"`
	// 12월 수익률
	M12PrftRt string `json:"m12_prft_rt"`
}

// GetOverseasYearlyChangeRate 는 미국주식 연도별 등락률(종목)(usa26410) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 연도별 등락률(종목)(usa26410)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasYearlyChangeRate(ctx context.Context, req GetOverseasYearlyChangeRateRequest, opts ...transport.Option) (*GetOverseasYearlyChangeRateResponse, transport.Meta, error) {
	var out GetOverseasYearlyChangeRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa26410",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
