// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasExchangeTypesRequest 는 미국주식 거래소구분 조회(usa10098) 요청이다.
type GetOverseasExchangeTypesRequest struct {
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasExchangeTypesResponse 는 미국주식 거래소구분 조회(usa10098) 응답이다.
type GetOverseasExchangeTypesResponse struct {
	// 결과리스트
	List []GetOverseasExchangeTypesListItem `json:"list"`
}

// GetOverseasExchangeTypesListItem 는 List 의 원소다.
type GetOverseasExchangeTypesListItem struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 거래소명
	Mkgb string `json:"mkgb"`
	// 업종명
	Upgb string `json:"upgb"`
	// ETF 여부
	IsEtf string `json:"isEtf"`
}

// GetOverseasExchangeTypes 는 미국주식 거래소구분 조회(usa10098) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 거래소구분 조회(usa10098)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasExchangeTypes(ctx context.Context, req GetOverseasExchangeTypesRequest, opts ...transport.Option) (*GetOverseasExchangeTypesResponse, transport.Meta, error) {
	var out GetOverseasExchangeTypesResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa10098",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
