// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasIndexListRequest 는 미국지수 리스트(usa10102) 요청이다.
type GetOverseasIndexListRequest struct {
	// 업종지수구분 (%:전체,NQ:나스닥,NS:S&P500,NW:다우)
	IndexQryTp string `json:"index_qry_tp"`
}

// GetOverseasIndexListResponse 는 미국지수 리스트(usa10102) 응답이다.
type GetOverseasIndexListResponse struct {
	// 결과리스트
	List []GetOverseasIndexListListItem `json:"list"`
}

// GetOverseasIndexListListItem 는 List 의 원소다.
type GetOverseasIndexListListItem struct {
	// 지수코드
	IndexCd string `json:"index_cd"`
	// 지수명
	IndexNm string `json:"index_nm"`
	// 지수영문명
	IndexEnm string `json:"index_enm"`
}

// GetOverseasIndexList 는 미국지수 리스트(usa10102) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국지수 리스트(usa10102)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasIndexList(ctx context.Context, req GetOverseasIndexListRequest, opts ...transport.Option) (*GetOverseasIndexListResponse, transport.Meta, error) {
	var out GetOverseasIndexListResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa10102",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
