// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasHighLowProximityWatchlistRequest 는 미국주식 고가/저가 접근(관심종목)(usa20972) 요청이다.
type GetOverseasHighLowProximityWatchlistRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// 관심종목코드 ([{'stex_tp':'거래소구분','stk_cd':'종목코드'},...])
	StkCd string `json:"stk_cd"`
	// 고가,저가구분 (1:고가,2:저가)
	HighLowTp string `json:"high_low_tp"`
	// 근접률 (0.5:0.5%, 1.0:1.0%, 1.5:1.5%, 2.0:2.0%, 2.5:2.5%, 3.5:3.5%)
	AlaccRt string `json:"alacc_rt"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 시작 (USD, 가격조건 끝으로만 조회할 경우 0)
	PricCndSt string `json:"pric_cnd_st"`
	// 가격조건 끝 (USD, 가격조건 시작으로만 조회할 경우 0)
	PricCndEd string `json:"pric_cnd_ed"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricCndSt string `json:"trde_pric_cnd_st"`
	// 거래량조건 (0:전체 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyCndFr string `json:"trde_qty_cnd_fr"`
}

// GetOverseasHighLowProximityWatchlistResponse 는 미국주식 고가/저가 접근(관심종목)(usa20972) 응답이다.
type GetOverseasHighLowProximityWatchlistResponse struct {
	// 결과리스트
	ResultList []GetOverseasHighLowProximityWatchlistResultListItem `json:"result_list"`
}

// GetOverseasHighLowProximityWatchlistResultListItem 는 ResultList 의 원소다.
type GetOverseasHighLowProximityWatchlistResultListItem struct {
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 누적거래량
	AccTrdeQty string `json:"acc_trde_qty"`
	// 신종목구분자
	Tp string `json:"tp"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// (최우선)매도호가 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	SelBid string `json:"sel_bid"`
	// (최우선)매수호가 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BuyBid string `json:"buy_bid"`
	// 고가 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	HighPric string `json:"high_pric"`
	// 저가 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	LowPric string `json:"low_pric"`
}

// GetOverseasHighLowProximityWatchlist 는 미국주식 고가/저가 접근(관심종목)(usa20972) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 고가/저가 접근(관심종목)(usa20972)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasHighLowProximityWatchlist(ctx context.Context, req GetOverseasHighLowProximityWatchlistRequest, opts ...transport.Option) (*GetOverseasHighLowProximityWatchlistResponse, transport.Meta, error) {
	var out GetOverseasHighLowProximityWatchlistResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20972",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
