// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockListRequest 는 미국주식 종목리스트(usa10099) 요청이다.
type GetOverseasStockListRequest struct {
	// 거래소구분 (필수, %:전체,NA:AMEX,ND:NASDAQ,NY:NYSE)
	StexTp string `json:"stex_tp"`
}

// GetOverseasStockListResponse 는 미국주식 종목리스트(usa10099) 응답이다.
type GetOverseasStockListResponse struct {
	// 결과리스트
	List []GetOverseasStockListListItem `json:"list"`
}

// GetOverseasStockListListItem 는 List 의 원소다.
type GetOverseasStockListListItem struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 거래소명
	Mkgb string `json:"mkgb"`
	// 업종명
	Upgb string `json:"upgb"`
	// ETF 여부
	IsEtf string `json:"isEtf"`
}

// GetOverseasStockList 는 미국주식 종목리스트(usa10099) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 종목리스트(usa10099)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasStockList(ctx context.Context, req GetOverseasStockListRequest, opts ...transport.Option) (*GetOverseasStockListResponse, transport.Meta, error) {
	var out GetOverseasStockListResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa10099",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
