// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasYearlyChangeRateByEtfCategoryRequest 는 미국주식 연도별 ETF 카테고리별 종목등락률(usa26412) 요청이다.
type GetOverseasYearlyChangeRateByEtfCategoryRequest struct {
	// ETF카테고리코드1 (stk_tp(종목구분) 2일 경우 ETF 대카테고리코드 (ETF이고 대분류일 경우 사용), usa10105 cate1 속성 참고)
	EtfCat1 string `json:"etf_cat1"`
	// ETF카테고리코드2 (stk_tp(종목구분) 2일 경우 ETF 중카테고리코드 (ETF이고 중분류일 경우 사용), usa10105 cate2 속성 참고)
	EtfCat2 string `json:"etf_cat2"`
	// 조회연도 (YYYY)
	SrchYr string `json:"srch_yr"`
}

// GetOverseasYearlyChangeRateByEtfCategoryResponse 는 미국주식 연도별 ETF 카테고리별 종목등락률(usa26412) 응답이다.
type GetOverseasYearlyChangeRateByEtfCategoryResponse struct {
	// 결과리스트
	ResultList []GetOverseasYearlyChangeRateByEtfCategoryResultListItem `json:"result_list"`
}

// GetOverseasYearlyChangeRateByEtfCategoryResultListItem 는 ResultList 의 원소다.
type GetOverseasYearlyChangeRateByEtfCategoryResultListItem struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 1월 수익률
	M01PrftRt string `json:"m01_prft_rt"`
	// 2월 수익률
	M02PrftRt string `json:"m02_prft_rt"`
	// 3월 수익률
	M03PrftRt string `json:"m03_prft_rt"`
	// 4월 수익률
	M04PrftRt string `json:"m04_prft_rt"`
	// 5월 수익률
	M05PrftRt string `json:"m05_prft_rt"`
	// 6월 수익률
	M06PrftRt string `json:"m06_prft_rt"`
	// 7월 수익률
	M07PrftRt string `json:"m07_prft_rt"`
	// 8월 수익률
	M08PrftRt string `json:"m08_prft_rt"`
	// 9월 수익률
	M09PrftRt string `json:"m09_prft_rt"`
	// 10월 수익률
	M10PrftRt string `json:"m10_prft_rt"`
	// 11월 수익률
	M11PrftRt string `json:"m11_prft_rt"`
	// 12월 수익률
	M12PrftRt string `json:"m12_prft_rt"`
}

// GetOverseasYearlyChangeRateByEtfCategory 는 미국주식 연도별 ETF 카테고리별 종목등락률(usa26412) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 연도별 ETF 카테고리별 종목등락률(usa26412)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasYearlyChangeRateByEtfCategory(ctx context.Context, req GetOverseasYearlyChangeRateByEtfCategoryRequest, opts ...transport.Option) (*GetOverseasYearlyChangeRateByEtfCategoryResponse, transport.Meta, error) {
	var out GetOverseasYearlyChangeRateByEtfCategoryResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa26412",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
