// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasPriceSurgeDropWatchlistRequest 는 미국주식 가격급등락(관심종목)(usa20932) 요청이다.
type GetOverseasPriceSurgeDropWatchlistRequest struct {
	// 거래소 구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// 관심종목 ([{'stex_tp':'거래소구분','stk_cd':'종목코드'},...])
	StkCd string `json:"stk_cd"`
	// 정렬 구분 (1:급등(기본값),2:급락)
	FluTp string `json:"flu_tp"`
	// 기준 구분 (1:분전(기본값),2:일전,3:지정일)
	TmTp string `json:"tm_tp"`
	// 분전 값 (XX분전(최대30) or XX일전(최대30) or tm_tp :3 입력 시, 기간(1:1일전,2:5일전,3:1개월전,4:3개월전,5:6개월전,6:연중,7:1년전,8:3년전,9:5년전))
	Tm string `json:"tm"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasPriceSurgeDropWatchlistResponse 는 미국주식 가격급등락(관심종목)(usa20932) 응답이다.
type GetOverseasPriceSurgeDropWatchlistResponse struct {
	// 결과리스트
	ResultList []GetOverseasPriceSurgeDropWatchlistResultListItem `json:"result_list"`
}

// GetOverseasPriceSurgeDropWatchlistResultListItem 는 ResultList 의 원소다.
type GetOverseasPriceSurgeDropWatchlistResultListItem struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 기준가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BasePric string `json:"base_pric"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 기준가 대비 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BasePre string `json:"base_pre"`
	// 누적거래량
	AccTrdeQty string `json:"acc_trde_qty"`
	// 급등락율
	SdninRt string `json:"sdnin_rt"`
}

// GetOverseasPriceSurgeDropWatchlist 는 미국주식 가격급등락(관심종목)(usa20932) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국주식 가격급등락(관심종목)(usa20932)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasPriceSurgeDropWatchlist(ctx context.Context, req GetOverseasPriceSurgeDropWatchlistRequest, opts ...transport.Option) (*GetOverseasPriceSurgeDropWatchlistResponse, transport.Meta, error) {
	var out GetOverseasPriceSurgeDropWatchlistResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20932",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
