// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasEtfEtnListRequest 는 미국 ETF,ETN 리스트(usa10104) 요청이다.
type GetOverseasEtfEtnListRequest struct {
	// 거래소구분 (%:전체,NA:AMEX,ND:NASDAQ,NY:NYSE)
	StexTp string `json:"stex_tp"`
}

// GetOverseasEtfEtnListResponse 는 미국 ETF,ETN 리스트(usa10104) 응답이다.
type GetOverseasEtfEtnListResponse struct {
	// 결과리스트
	List []GetOverseasEtfEtnListListItem `json:"list"`
}

// GetOverseasEtfEtnListListItem 는 List 의 원소다.
type GetOverseasEtfEtnListListItem struct {
	// 거래소구분
	StexTp string `json:"stex_tp"`
	// 종목코드
	Code string `json:"code"`
	// 카테고리1
	Cate1 string `json:"cate1"`
	// 카테고리2
	Cate2 string `json:"cate2"`
	// ETN여부
	Etn string `json:"etn"`
	// 거래소명
	Mkgb string `json:"mkgb"`
	// 업종명
	Upnm string `json:"upnm"`
}

// GetOverseasEtfEtnList 는 미국 ETF,ETN 리스트(usa10104) 이다.
//
// 메뉴: 미국주식 > 종목정보 > 미국 ETF,ETN 리스트 (usa10104)
// URL:  /api/us/stkinfo
func (c *Client) GetOverseasEtfEtnList(ctx context.Context, req GetOverseasEtfEtnListRequest, opts ...transport.Option) (*GetOverseasEtfEtnListResponse, transport.Meta, error) {
	var out GetOverseasEtfEtnListResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa10104",
		Path:  "/api/us/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
