// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// CheckDomesticCreditLoanableRequest 는 신용융자 가능문의(kt20017) 요청이다.
type CheckDomesticCreditLoanableRequest struct {
	// 종목코드 (필수, 12자, 종목 코드 입력)
	StkCd string `json:"stk_cd"`
}

// CheckDomesticCreditLoanableResponse 는 신용융자 가능문의(kt20017) 응답이다.
type CheckDomesticCreditLoanableResponse struct {
	// 신용가능여부 (40자)
	CrdAlowYn string `json:"crd_alow_yn"`
}

// CheckDomesticCreditLoanable 는 신용융자 가능문의(kt20017) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 신용융자 가능문의(kt20017)
// URL:  /api/dostk/stkinfo
func (c *Client) CheckDomesticCreditLoanable(ctx context.Context, req CheckDomesticCreditLoanableRequest, opts ...transport.Option) (*CheckDomesticCreditLoanableResponse, transport.Meta, error) {
	var out CheckDomesticCreditLoanableResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt20017",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
