// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockBrokersRequest 는 주식거래원요청(ka10002) 요청이다.
type GetDomesticStockBrokersRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockBrokersResponse 는 주식거래원요청(ka10002) 응답이다.
type GetDomesticStockBrokersResponse struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 등락부호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	FluSmbol string `json:"flu_smbol"`
	// 기준가 (20자, 단위: 원)
	BasePric string `json:"base_pric"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 매도거래원명1 (20자)
	SelTrdeOriNm1 string `json:"sel_trde_ori_nm_1"`
	// 매도거래원1 (20자)
	SelTrdeOri1 string `json:"sel_trde_ori_1"`
	// 매도거래량1 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty1 string `json:"sel_trde_qty_1"`
	// 매수거래원명1 (20자)
	BuyTrdeOriNm1 string `json:"buy_trde_ori_nm_1"`
	// 매수거래원1 (20자)
	BuyTrdeOri1 string `json:"buy_trde_ori_1"`
	// 매수거래량1 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty1 string `json:"buy_trde_qty_1"`
	// 매도거래원명2 (20자)
	SelTrdeOriNm2 string `json:"sel_trde_ori_nm_2"`
	// 매도거래원2 (20자)
	SelTrdeOri2 string `json:"sel_trde_ori_2"`
	// 매도거래량2 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty2 string `json:"sel_trde_qty_2"`
	// 매수거래원명2 (20자)
	BuyTrdeOriNm2 string `json:"buy_trde_ori_nm_2"`
	// 매수거래원2 (20자)
	BuyTrdeOri2 string `json:"buy_trde_ori_2"`
	// 매수거래량2 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty2 string `json:"buy_trde_qty_2"`
	// 매도거래원명3 (20자)
	SelTrdeOriNm3 string `json:"sel_trde_ori_nm_3"`
	// 매도거래원3 (20자)
	SelTrdeOri3 string `json:"sel_trde_ori_3"`
	// 매도거래량3 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty3 string `json:"sel_trde_qty_3"`
	// 매수거래원명3 (20자)
	BuyTrdeOriNm3 string `json:"buy_trde_ori_nm_3"`
	// 매수거래원3 (20자)
	BuyTrdeOri3 string `json:"buy_trde_ori_3"`
	// 매수거래량3 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty3 string `json:"buy_trde_qty_3"`
	// 매도거래원명4 (20자)
	SelTrdeOriNm4 string `json:"sel_trde_ori_nm_4"`
	// 매도거래원4 (20자)
	SelTrdeOri4 string `json:"sel_trde_ori_4"`
	// 매도거래량4 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty4 string `json:"sel_trde_qty_4"`
	// 매수거래원명4 (20자)
	BuyTrdeOriNm4 string `json:"buy_trde_ori_nm_4"`
	// 매수거래원4 (20자)
	BuyTrdeOri4 string `json:"buy_trde_ori_4"`
	// 매수거래량4 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty4 string `json:"buy_trde_qty_4"`
	// 매도거래원명5 (20자)
	SelTrdeOriNm5 string `json:"sel_trde_ori_nm_5"`
	// 매도거래원5 (20자)
	SelTrdeOri5 string `json:"sel_trde_ori_5"`
	// 매도거래량5 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty5 string `json:"sel_trde_qty_5"`
	// 매수거래원명5 (20자)
	BuyTrdeOriNm5 string `json:"buy_trde_ori_nm_5"`
	// 매수거래원5 (20자)
	BuyTrdeOri5 string `json:"buy_trde_ori_5"`
	// 매수거래량5 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty5 string `json:"buy_trde_qty_5"`
}

// GetDomesticStockBrokers 는 주식거래원요청(ka10002) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 주식거래원요청(ka10002)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticStockBrokers(ctx context.Context, req GetDomesticStockBrokersRequest, opts ...transport.Option) (*GetDomesticStockBrokersResponse, transport.Meta, error) {
	var out GetDomesticStockBrokersResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10002",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
