// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockInfoRequest 는 주식기본정보요청(ka10001) 요청이다.
type GetDomesticStockInfoRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockInfoResponse 는 주식기본정보요청(ka10001) 응답이다.
type GetDomesticStockInfoResponse struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 결산월 (20자)
	SetlMm string `json:"setl_mm"`
	// 액면가 (20자, 단위: 원)
	Fav string `json:"fav"`
	// 자본금 (20자, 단위: 억원)
	Cap string `json:"cap"`
	// 상장주식 (20자, 단위: 천원)
	FloStk string `json:"flo_stk"`
	// 신용비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CrdRt string `json:"crd_rt"`
	// 연중최고 (20자, 단위: 원, 부호가 포함된 숫자)
	OyrHgst string `json:"oyr_hgst"`
	// 연중최저 (20자, 단위: 원, 부호가 포함된 숫자)
	OyrLwst string `json:"oyr_lwst"`
	// 시가총액 (20자, 단위: 억원)
	Mac string `json:"mac"`
	// 시가총액비중 (20자)
	MacWght string `json:"mac_wght"`
	// 외인소진률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForExhRt string `json:"for_exh_rt"`
	// 대용가 (20자, 단위: 원)
	ReplPric string `json:"repl_pric"`
	// PER (20자, [ 주의 ] PER, ROE 값들은 외부벤더사에서 제공되는 데이터이며 일주일에 한번 또는 실적발표 시즌에 업데이트 됨)
	Per string `json:"per"`
	// EPS (20자)
	Eps string `json:"eps"`
	// ROE (20자, [ 주의 ] PER, ROE 값들은 외부벤더사에서 제공되는 데이터이며 일주일에 한번 또는 실적발표 시즌에 업데이트 됨)
	Roe string `json:"roe"`
	// PBR (20자)
	Pbr string `json:"pbr"`
	// EV (20자)
	Ev string `json:"ev"`
	// BPS (20자)
	Bps string `json:"bps"`
	// 매출액 (20자, 단위: 억원)
	SaleAmt string `json:"sale_amt"`
	// 영업이익 (20자, 단위: 억원)
	BusPro string `json:"bus_pro"`
	// 당기순이익 (20자, 단위: 억원)
	CupNga string `json:"cup_nga"`
	// 250최고 (20자, 단위: 원, 부호가 포함된 숫자)
	N250hgst string `json:"250hgst"`
	// 250최저 (20자, 단위: 원, 부호가 포함된 숫자)
	N250lwst string `json:"250lwst"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 상한가 (20자, 단위: 원, 부호가 포함된 숫자)
	UplPric string `json:"upl_pric"`
	// 하한가 (20자, 단위: 원, 부호가 포함된 숫자)
	LstPric string `json:"lst_pric"`
	// 기준가 (20자, 단위: 원)
	BasePric string `json:"base_pric"`
	// 예상체결가 (20자)
	ExpCntrPric string `json:"exp_cntr_pric"`
	// 예상체결수량 (20자)
	ExpCntrQty string `json:"exp_cntr_qty"`
	// 250최고가일 (20자, YYYYMMDD)
	N250hgstPricDt string `json:"250hgst_pric_dt"`
	// 250최고가대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N250hgstPricPreRt string `json:"250hgst_pric_pre_rt"`
	// 250최저가일 (20자, YYYYMMDD)
	N250lwstPricDt string `json:"250lwst_pric_dt"`
	// 250최저가대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N250lwstPricPreRt string `json:"250lwst_pric_pre_rt"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdePre string `json:"trde_pre"`
	// 액면가단위 (20자)
	FavUnit string `json:"fav_unit"`
	// 유통주식 (20자, 단위: 1주)
	DstrStk string `json:"dstr_stk"`
	// 유통비율 (20자, 단위: %, 부호 포함 소수점 첫째 자리까지 포맷된 백분율)
	DstrRt string `json:"dstr_rt"`
}

// GetDomesticStockInfo 는 주식기본정보요청(ka10001) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 주식기본정보요청(ka10001)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticStockInfo(ctx context.Context, req GetDomesticStockInfoRequest, opts ...transport.Option) (*GetDomesticStockInfoResponse, transport.Meta, error) {
	var out GetDomesticStockInfoResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10001",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
