// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticCreditTradeTrendRequest 는 신용매매동향요청(ka10013) 요청이다.
type GetDomesticCreditTradeTrendRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 일자 (필수, 8자, YYYYMMDD)
	Dt string `json:"dt"`
	// 조회구분 (필수, 1자, 1:융자, 2:대주)
	QryTp string `json:"qry_tp"`
}

// GetDomesticCreditTradeTrendResponse 는 신용매매동향요청(ka10013) 응답이다.
type GetDomesticCreditTradeTrendResponse struct {
	// 신용매매동향
	CrdTrdeTrend []GetDomesticCreditTradeTrendCrdTrdeTrendItem `json:"crd_trde_trend"`
}

// GetDomesticCreditTradeTrendCrdTrdeTrendItem 는 CrdTrdeTrend 의 원소다.
type GetDomesticCreditTradeTrendCrdTrdeTrendItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 신규 (20자, 융자단위: 백만원, 대주단위: 백만주)
	New string `json:"new"`
	// 상환 (20자, 융자단위: 백만원, 대주단위: 백만주)
	Rpya string `json:"rpya"`
	// 잔고 (20자, 융자단위: 백만원, 대주단위: 백만주)
	Remn string `json:"remn"`
	// 금액 (20자, 융자단위: 백만원, 대주단위: 백만주)
	Amt string `json:"amt"`
	// 대비 (20자, 융자단위: 백만원, 대주단위: 백만주, 부호가 포함된 숫자)
	Pre string `json:"pre"`
	// 공여율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ShrRt string `json:"shr_rt"`
	// 잔고율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	RemnRt string `json:"remn_rt"`
}

// GetDomesticCreditTradeTrend 는 신용매매동향요청(ka10013) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 신용매매동향요청(ka10013)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticCreditTradeTrend(ctx context.Context, req GetDomesticCreditTradeTrendRequest, opts ...transport.Option) (*GetDomesticCreditTradeTrendResponse, transport.Meta, error) {
	var out GetDomesticCreditTradeTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10013",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
