// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockExecutionInfoRequest 는 체결정보요청(ka10003) 요청이다.
type GetDomesticStockExecutionInfoRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockExecutionInfoResponse 는 체결정보요청(ka10003) 응답이다.
type GetDomesticStockExecutionInfoResponse struct {
	// 체결정보
	CntrInfr []GetDomesticStockExecutionInfoCntrInfrItem `json:"cntr_infr"`
}

// GetDomesticStockExecutionInfoCntrInfrItem 는 CntrInfr 의 원소다.
type GetDomesticStockExecutionInfoCntrInfrItem struct {
	// 시간 (20자, HHmmss)
	Tm string `json:"tm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PreRt string `json:"pre_rt"`
	// 우선매도호가단위 (20자, 단위: 원, 부호가 포함된 숫자)
	PriSelBidUnit string `json:"pri_sel_bid_unit"`
	// 우선매수호가단위 (20자, 단위: 원, 부호가 포함된 숫자)
	PriBuyBidUnit string `json:"pri_buy_bid_unit"`
	// 체결거래량 (20자, 단위: 1주, 부호가 포함된 숫자)
	CntrTrdeQty string `json:"cntr_trde_qty"`
	// sign (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	Sign string `json:"sign"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적거래대금 (20자, 단위: 원)
	AccTrdePrica string `json:"acc_trde_prica"`
	// 체결강도 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr string `json:"cntr_str"`
	// 거래소구분 (20자, KRX , NXT , 통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticStockExecutionInfo 는 체결정보요청(ka10003) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 체결정보요청(ka10003)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticStockExecutionInfo(ctx context.Context, req GetDomesticStockExecutionInfoRequest, opts ...transport.Option) (*GetDomesticStockExecutionInfoResponse, transport.Meta, error) {
	var out GetDomesticStockExecutionInfoResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10003",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
