// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticPriceSurgeDropStocksRequest 는 가격급등락요청(ka10019) 요청이다.
type GetDomesticPriceSurgeDropStocksRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥, 201:코스피200)
	MrktTp string `json:"mrkt_tp"`
	// 등락구분 (필수, 1자, 1:급등, 2:급락)
	FluTp string `json:"flu_tp"`
	// 시간구분 (필수, 1자, 1:분전, 2:일전)
	TmTp string `json:"tm_tp"`
	// 시간 (필수, 2자, 분 혹은 일입력)
	Tm string `json:"tm"`
	// 거래량구분 (필수, 4자, 00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (필수, 1자, 0:전체조회,1:관리종목제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기)
	StkCnd string `json:"stk_cnd"`
	// 신용조건 (필수, 1자, 0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체)
	CrdCnd string `json:"crd_cnd"`
	// 가격조건 (필수, 1자, 0:전체조회, 1:1천원미만, 2:1천원~2천원, 3:2천원~3천원, 4:5천원~1만원, 5:1만원이상, 8:1천원이상)
	PricCnd string `json:"pric_cnd"`
	// 상하한포함 (필수, 1자, 0:미포함, 1:포함)
	UpdownIncls string `json:"updown_incls"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticPriceSurgeDropStocksResponse 는 가격급등락요청(ka10019) 응답이다.
type GetDomesticPriceSurgeDropStocksResponse struct {
	// 가격급등락
	PricJmpflu []GetDomesticPriceSurgeDropStocksPricJmpfluItem `json:"pric_jmpflu"`
}

// GetDomesticPriceSurgeDropStocksPricJmpfluItem 는 PricJmpflu 의 원소다.
type GetDomesticPriceSurgeDropStocksPricJmpfluItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목분류 (20자)
	StkCls string `json:"stk_cls"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 기준가 (20자, 단위: 원)
	BasePric string `json:"base_pric"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 기준대비 (20자, 단위: 원)
	BasePre string `json:"base_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 급등률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	JmpRt string `json:"jmp_rt"`
}

// GetDomesticPriceSurgeDropStocks 는 가격급등락요청(ka10019) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 가격급등락요청(ka10019)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticPriceSurgeDropStocks(ctx context.Context, req GetDomesticPriceSurgeDropStocksRequest, opts ...transport.Option) (*GetDomesticPriceSurgeDropStocksResponse, transport.Meta, error) {
	var out GetDomesticPriceSurgeDropStocksResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10019",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
