// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticVolumeRecordUpdateRequest 는 거래량갱신요청(ka10024) 요청이다.
type GetDomesticVolumeRecordUpdateRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 주기구분 (필수, 1자, 5:5일, 10:10일, 20:20일, 60:60일, 250:250일)
	CycleTp string `json:"cycle_tp"`
	// 거래량구분 (필수, 1자, 5:5천주이상, 10:만주이상, 50:5만주이상, 100:10만주이상, 200:20만주이상, 300:30만주이상, 500:50만주이상, 1000:백만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticVolumeRecordUpdateResponse 는 거래량갱신요청(ka10024) 응답이다.
type GetDomesticVolumeRecordUpdateResponse struct {
	// 거래량갱신
	TrdeQtyUpdt []GetDomesticVolumeRecordUpdateTrdeQtyUpdtItem `json:"trde_qty_updt"`
}

// GetDomesticVolumeRecordUpdateTrdeQtyUpdtItem 는 TrdeQtyUpdt 의 원소다.
type GetDomesticVolumeRecordUpdateTrdeQtyUpdtItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 이전거래량 (20자, 단위: 1주)
	PrevTrdeQty string `json:"prev_trde_qty"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
}

// GetDomesticVolumeRecordUpdate 는 거래량갱신요청(ka10024) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 거래량갱신요청(ka10024)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticVolumeRecordUpdate(ctx context.Context, req GetDomesticVolumeRecordUpdateRequest, opts ...transport.Option) (*GetDomesticVolumeRecordUpdateResponse, transport.Meta, error) {
	var out GetDomesticVolumeRecordUpdateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10024",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
