// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticWatchlistStockInfoRequest 는 지정종목 정보요청(ka10095) 요청이다.
type GetDomesticWatchlistStockInfoRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL) 여러개의 종목코드 입력시 | 로 구분)
	StkCd string `json:"stk_cd"`
}

// GetDomesticWatchlistStockInfoResponse 는 지정종목 정보요청(ka10095) 응답이다.
type GetDomesticWatchlistStockInfoResponse struct {
	// 관심종목정보
	AtnStkInfr []GetDomesticWatchlistStockInfoAtnStkInfrItem `json:"atn_stk_infr"`
}

// GetDomesticWatchlistStockInfoAtnStkInfrItem 는 AtnStkInfr 의 원소다.
type GetDomesticWatchlistStockInfoAtnStkInfrItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 기준가 (20자, 단위: 원)
	BasePric string `json:"base_pric"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 체결량 (20자, 단위: 1주, 부호가 포함된 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결강도 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr string `json:"cntr_str"`
	// 전일거래량대비 (20자)
	PredTrdeQtyPre string `json:"pred_trde_qty_pre"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
	// 매도1차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Sel1thBid string `json:"sel_1th_bid"`
	// 매도2차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Sel2thBid string `json:"sel_2th_bid"`
	// 매도3차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Sel3thBid string `json:"sel_3th_bid"`
	// 매도4차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Sel4thBid string `json:"sel_4th_bid"`
	// 매도5차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Sel5thBid string `json:"sel_5th_bid"`
	// 매수1차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Buy1thBid string `json:"buy_1th_bid"`
	// 매수2차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Buy2thBid string `json:"buy_2th_bid"`
	// 매수3차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Buy3thBid string `json:"buy_3th_bid"`
	// 매수4차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Buy4thBid string `json:"buy_4th_bid"`
	// 매수5차호가 (20자, 단위: 원, 부호가 포함된 숫자)
	Buy5thBid string `json:"buy_5th_bid"`
	// 상한가 (20자, 단위: 원, 부호가 포함된 숫자)
	UplPric string `json:"upl_pric"`
	// 하한가 (20자, 단위: 원, 부호가 포함된 숫자)
	LstPric string `json:"lst_pric"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 체결시간 (20자, HHmmss)
	CntrTm string `json:"cntr_tm"`
	// 예상체결가 (20자, 단위: 원, 부호가 포함된 숫자)
	ExpCntrPric string `json:"exp_cntr_pric"`
	// 예상체결량 (20자, 단위: 1주)
	ExpCntrQty string `json:"exp_cntr_qty"`
	// 자본금 (20자, 단위: 억원)
	Cap string `json:"cap"`
	// 액면가 (20자, 단위: 원)
	Fav string `json:"fav"`
	// 시가총액 (20자, 단위: 억원)
	Mac string `json:"mac"`
	// 주식수 (20자, 단위: 1주)
	Stkcnt string `json:"stkcnt"`
	// 호가시간 (20자, HHmmss)
	BidTm string `json:"bid_tm"`
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 우선매도잔량 (20자, 단위: 1주)
	PriSelReq string `json:"pri_sel_req"`
	// 우선매수잔량 (20자, 단위: 1주)
	PriBuyReq string `json:"pri_buy_req"`
	// 우선매도건수 (20자)
	PriSelCnt string `json:"pri_sel_cnt"`
	// 우선매수건수 (20자)
	PriBuyCnt string `json:"pri_buy_cnt"`
	// 총매도잔량 (20자, 단위: 1주)
	TotSelReq string `json:"tot_sel_req"`
	// 총매수잔량 (20자, 단위: 1주)
	TotBuyReq string `json:"tot_buy_req"`
	// 총매도건수 (20자)
	TotSelCnt string `json:"tot_sel_cnt"`
	// 총매수건수 (20자)
	TotBuyCnt string `json:"tot_buy_cnt"`
	// 패리티 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Prty string `json:"prty"`
	// 기어링 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Gear string `json:"gear"`
	// 손익분기 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PlQutr string `json:"pl_qutr"`
	// 자본지지 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CapSupport string `json:"cap_support"`
	// ELW행사가 (20자, 단위: 원)
	ElwexecPric string `json:"elwexec_pric"`
	// 전환비율 (20자, 단위: %, 부호 포함 소수점 넷째 자리까지 포맷된 백분율)
	CnvtRt string `json:"cnvt_rt"`
	// ELW만기일 (20자, YYYYMMDD)
	ElwexprDt string `json:"elwexpr_dt"`
	// 미결제약정 (20자)
	CntrEngg string `json:"cntr_engg"`
	// 미결제전일대비 (20자)
	CntrPredPre string `json:"cntr_pred_pre"`
	// 이론가 (20자)
	TheoryPric string `json:"theory_pric"`
	// 내재변동성 (20자)
	InnrVltl string `json:"innr_vltl"`
	// 델타 (20자)
	Delta string `json:"delta"`
	// 감마 (20자)
	Gam string `json:"gam"`
	// 쎄타 (20자)
	Theta string `json:"theta"`
	// 베가 (20자)
	Vega string `json:"vega"`
	// 로 (20자)
	Law string `json:"law"`
}

// GetDomesticWatchlistStockInfo 는 지정종목 정보요청(ka10095) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 지정종목 정보요청(ka10095)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticWatchlistStockInfo(ctx context.Context, req GetDomesticWatchlistStockInfoRequest, opts ...transport.Option) (*GetDomesticWatchlistStockInfoResponse, transport.Meta, error) {
	var out GetDomesticWatchlistStockInfoResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10095",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
