// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticHighLowPerStocksRequest 는 고저PER요청(ka10026) 요청이다.
type GetDomesticHighLowPerStocksRequest struct {
	// PER구분 (필수, 1자, 1:저PBR, 2:고PBR, 3:저PER, 4:고PER, 5:저ROE, 6:고ROE)
	Pertp string `json:"pertp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticHighLowPerStocksResponse 는 고저PER요청(ka10026) 응답이다.
type GetDomesticHighLowPerStocksResponse struct {
	// 고저PER
	HighLowPer []GetDomesticHighLowPerStocksHighLowPerItem `json:"high_low_per"`
}

// GetDomesticHighLowPerStocksHighLowPerItem 는 HighLowPer 의 원소다.
type GetDomesticHighLowPerStocksHighLowPerItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// PER (20자)
	Per string `json:"per"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
}

// GetDomesticHighLowPerStocks 는 고저PER요청(ka10026) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 고저PER요청(ka10026)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticHighLowPerStocks(ctx context.Context, req GetDomesticHighLowPerStocksRequest, opts ...transport.Option) (*GetDomesticHighLowPerStocksResponse, transport.Meta, error) {
	var out GetDomesticHighLowPerStocksResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10026",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
