// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDailyTradeDetailRequest 는 일별거래상세요청(ka10015) 요청이다.
type GetDomesticDailyTradeDetailRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시작일자 (필수, 8자, YYYMMDD, 시작일자 기준으로 이전 일별 거래 정보를 조회)
	StrtDt string `json:"strt_dt"`
}

// GetDomesticDailyTradeDetailResponse 는 일별거래상세요청(ka10015) 응답이다.
type GetDomesticDailyTradeDetailResponse struct {
	// 일별거래상세
	DalyTrdeDtl []GetDomesticDailyTradeDetailDalyTrdeDtlItem `json:"daly_trde_dtl"`
}

// GetDomesticDailyTradeDetailDalyTrdeDtlItem 는 DalyTrdeDtl 의 원소다.
type GetDomesticDailyTradeDetailDalyTrdeDtlItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 장전거래량 (20자, 단위: 1주)
	BfMkrtTrdeQty string `json:"bf_mkrt_trde_qty"`
	// 장전거래비중 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	BfMkrtTrdeWght string `json:"bf_mkrt_trde_wght"`
	// 장중거래량 (20자, 단위: 1주)
	OpmrTrdeQty string `json:"opmr_trde_qty"`
	// 장중거래비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	OpmrTrdeWght string `json:"opmr_trde_wght"`
	// 장후거래량 (20자, 단위: 1주)
	AfMkrtTrdeQty string `json:"af_mkrt_trde_qty"`
	// 장후거래비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	AfMkrtTrdeWght string `json:"af_mkrt_trde_wght"`
	// 합계3 (20자)
	Tot3 string `json:"tot_3"`
	// 기간중거래량 (20자)
	PridTrdeQty string `json:"prid_trde_qty"`
	// 체결강도 (20자)
	CntrStr string `json:"cntr_str"`
	// 외인보유 (20자)
	ForPoss string `json:"for_poss"`
	// 외인비중 (20자)
	ForWght string `json:"for_wght"`
	// 외인순매수 (20자)
	ForNetprps string `json:"for_netprps"`
	// 기관순매수 (20자)
	OrgnNetprps string `json:"orgn_netprps"`
	// 개인순매수 (20자)
	IndNetprps string `json:"ind_netprps"`
	// 외국계 (20자)
	Frgn string `json:"frgn"`
	// 신용잔고율 (20자)
	CrdRemnRt string `json:"crd_remn_rt"`
	// 프로그램 (20자)
	Prm string `json:"prm"`
	// 장전거래대금 (20자, 단위: 백만원)
	BfMkrtTrdePrica string `json:"bf_mkrt_trde_prica"`
	// 장전거래대금비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BfMkrtTrdePricaWght string `json:"bf_mkrt_trde_prica_wght"`
	// 장중거래대금 (20자, 단위: 백만원)
	OpmrTrdePrica string `json:"opmr_trde_prica"`
	// 장중거래대금비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	OpmrTrdePricaWght string `json:"opmr_trde_prica_wght"`
	// 장후거래대금 (20자, 단위: 백만원)
	AfMkrtTrdePrica string `json:"af_mkrt_trde_prica"`
	// 장후거래대금비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	AfMkrtTrdePricaWght string `json:"af_mkrt_trde_prica_wght"`
}

// GetDomesticDailyTradeDetail 는 일별거래상세요청(ka10015) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 일별거래상세요청(ka10015)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticDailyTradeDetail(ctx context.Context, req GetDomesticDailyTradeDetailRequest, opts ...transport.Option) (*GetDomesticDailyTradeDetailResponse, transport.Meta, error) {
	var out GetDomesticDailyTradeDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10015",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
