// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticBrokerVolumeProfileAnalysisRequest 는 거래원매물대분석요청(ka10043) 요청이다.
type GetDomesticBrokerVolumeProfileAnalysisRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시작일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 조회기간구분 (필수, 1자, 0:기간으로 조회, 1:시작일자, 종료일자로 조회)
	QryDtTp string `json:"qry_dt_tp"`
	// 시점구분 (필수, 1자, 0:당일, 1:전일)
	PotTp string `json:"pot_tp"`
	// 기간 (필수, 4자, 5:5일, 10:10일, 20:20일, 40:40일, 60:60일, 120:120일)
	Dt string `json:"dt"`
	// 정렬기준 (필수, 1자, 1:종가순, 2:날짜순)
	SortBase string `json:"sort_base"`
	// 회원사코드 (필수, 3자, 회원사 코드는 ka10102 조회)
	MmcmCd string `json:"mmcm_cd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticBrokerVolumeProfileAnalysisResponse 는 거래원매물대분석요청(ka10043) 응답이다.
type GetDomesticBrokerVolumeProfileAnalysisResponse struct {
	// 거래원매물대분석
	TrdeOriPrpsAnly []GetDomesticBrokerVolumeProfileAnalysisTrdeOriPrpsAnlyItem `json:"trde_ori_prps_anly"`
}

// GetDomesticBrokerVolumeProfileAnalysisTrdeOriPrpsAnlyItem 는 TrdeOriPrpsAnly 의 원소다.
type GetDomesticBrokerVolumeProfileAnalysisTrdeOriPrpsAnlyItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종가 (20자, 단위: 원)
	ClosePric string `json:"close_pric"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 매도량 (20자, 단위: 1주)
	SelQty string `json:"sel_qty"`
	// 매수량 (20자, 단위: 1주)
	BuyQty string `json:"buy_qty"`
	// 순매수수량 (20자, 단위: 1주)
	NetprpsQty string `json:"netprps_qty"`
	// 거래량합 (20자, 단위: 1주)
	TrdeQtySum string `json:"trde_qty_sum"`
	// 거래비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeWght string `json:"trde_wght"`
}

// GetDomesticBrokerVolumeProfileAnalysis 는 거래원매물대분석요청(ka10043) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 거래원매물대분석요청(ka10043)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticBrokerVolumeProfileAnalysis(ctx context.Context, req GetDomesticBrokerVolumeProfileAnalysisRequest, opts ...transport.Option) (*GetDomesticBrokerVolumeProfileAnalysisResponse, transport.Meta, error) {
	var out GetDomesticBrokerVolumeProfileAnalysisResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10043",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
