// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticVolumeProfileClusterRequest 는 매물대집중요청(ka10025) 요청이다.
type GetDomesticVolumeProfileClusterRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 매물집중비율 (필수, 3자, 0~100 입력)
	PrpsCnctrRt string `json:"prps_cnctr_rt"`
	// 현재가진입 (필수, 1자, 0:현재가 매물대 진입 포함안함, 1:현재가 매물대 진입포함)
	CurPrcEntry string `json:"cur_prc_entry"`
	// 매물대수 (필수, 2자, 숫자입력)
	Prpscnt string `json:"prpscnt"`
	// 주기구분 (필수, 2자, 50:50일, 100:100일, 150:150일, 200:200일, 250:250일, 300:300일)
	CycleTp string `json:"cycle_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticVolumeProfileClusterResponse 는 매물대집중요청(ka10025) 응답이다.
type GetDomesticVolumeProfileClusterResponse struct {
	// 매물대집중
	PrpsCnctr []GetDomesticVolumeProfileClusterPrpsCnctrItem `json:"prps_cnctr"`
}

// GetDomesticVolumeProfileClusterPrpsCnctrItem 는 PrpsCnctr 의 원소다.
type GetDomesticVolumeProfileClusterPrpsCnctrItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 가격대시작 (20자, 단위: 원)
	PricStrt string `json:"pric_strt"`
	// 가격대끝 (20자, 단위: 원)
	PricEnd string `json:"pric_end"`
	// 매물량 (20자, 단위: 1주)
	PrpsQty string `json:"prps_qty"`
	// 매물비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PrpsRt string `json:"prps_rt"`
}

// GetDomesticVolumeProfileCluster 는 매물대집중요청(ka10025) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 매물대집중요청(ka10025)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticVolumeProfileCluster(ctx context.Context, req GetDomesticVolumeProfileClusterRequest, opts ...transport.Option) (*GetDomesticVolumeProfileClusterResponse, transport.Meta, error) {
	var out GetDomesticVolumeProfileClusterResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10025",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
