// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticNearHighLowStocksRequest 는 고저가근접요청(ka10018) 요청이다.
type GetDomesticNearHighLowStocksRequest struct {
	// 고저구분 (필수, 1자, 1:고가, 2:저가)
	HighLowTp string `json:"high_low_tp"`
	// 근접율 (필수, 2자, 05:0.5 10:1.0, 15:1.5, 20:2.0. 25:2.5, 30:3.0)
	AlaccRt string `json:"alacc_rt"`
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 거래량구분 (필수, 5자, 00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (필수, 1자, 0:전체조회,1:관리종목제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기)
	StkCnd string `json:"stk_cnd"`
	// 신용조건 (필수, 1자, 0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체)
	CrdCnd string `json:"crd_cnd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticNearHighLowStocksResponse 는 고저가근접요청(ka10018) 응답이다.
type GetDomesticNearHighLowStocksResponse struct {
	// 고저가근접
	HighLowPricAlacc []GetDomesticNearHighLowStocksHighLowPricAlaccItem `json:"high_low_pric_alacc"`
}

// GetDomesticNearHighLowStocksHighLowPricAlaccItem 는 HighLowPricAlacc 의 원소다.
type GetDomesticNearHighLowStocksHighLowPricAlaccItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
	// 당일고가 (20자, 단위: 원, 부호가 포함된 숫자)
	TdyHighPric string `json:"tdy_high_pric"`
	// 당일저가 (20자, 단위: 원, 부호가 포함된 숫자)
	TdyLowPric string `json:"tdy_low_pric"`
}

// GetDomesticNearHighLowStocks 는 고저가근접요청(ka10018) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 고저가근접요청(ka10018)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticNearHighLowStocks(ctx context.Context, req GetDomesticNearHighLowStocksRequest, opts ...transport.Option) (*GetDomesticNearHighLowStocksResponse, transport.Meta, error) {
	var out GetDomesticNearHighLowStocksResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10018",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
