// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticRealtimeStockRankRequest 는 실시간종목조회순위(ka00198) 요청이다.
type GetDomesticRealtimeStockRankRequest struct {
	// 구분 (필수, 1자, 1:1분, 2:10분, 3:1시간, 4:당일 누적, 5:30초)
	QryTp string `json:"qry_tp"`
}

// GetDomesticRealtimeStockRankResponse 는 실시간종목조회순위(ka00198) 응답이다.
type GetDomesticRealtimeStockRankResponse struct {
	// 실시간종목조회순위
	ItemInqRank []GetDomesticRealtimeStockRankItemInqRankItem `json:"item_inq_rank"`
}

// GetDomesticRealtimeStockRankItemInqRankItem 는 ItemInqRank 의 원소다.
type GetDomesticRealtimeStockRankItemInqRankItem struct {
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 빅데이터 순위 (20자, 0: 순위 변동 없음)
	BigdRank string `json:"bigd_rank"`
	// 순위 등락 (20자, 순위 변동 없음(rank_chg=0)인 경우 빈값('') 출력)
	RankChg string `json:"rank_chg"`
	// 순위 등락 부호 (20자, 순위상승: +, 순위하락: -, 순위변동없음: ')
	RankChgSign string `json:"rank_chg_sign"`
	// 과거 현재가 (20자, 기준 시점 주가, 부호가 포함된 원화 값)
	PastCurrPrc string `json:"past_curr_prc"`
	// 기준가 대비 부호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	BaseCompSign string `json:"base_comp_sign"`
	// 기준가 대비 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BaseCompChgr string `json:"base_comp_chgr"`
	// 직전 기준 대비 부호 (20자)
	PrevBaseSign string `json:"prev_base_sign"`
	// 직전 기준 대비 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PrevBaseChgr string `json:"prev_base_chgr"`
	// 일자 (20자, 기준 일자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시간 (20자, 기준 시간, HHmmss)
	Tm string `json:"tm"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticRealtimeStockRank 는 실시간종목조회순위(ka00198) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 실시간종목조회순위(ka00198)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticRealtimeStockRank(ctx context.Context, req GetDomesticRealtimeStockRankRequest, opts ...transport.Option) (*GetDomesticRealtimeStockRankResponse, transport.Meta, error) {
	var out GetDomesticRealtimeStockRankResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka00198",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
