// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticBrokerInstantVolumeRequest 는 거래원순간거래량요청(ka10052) 요청이다.
type GetDomesticBrokerInstantVolumeRequest struct {
	// 회원사코드 (필수, 3자, 회원사 코드는 ka10102 조회)
	MmcmCd string `json:"mmcm_cd"`
	// 종목코드 (20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시장구분 (필수, 1자, 0:전체, 1:코스피, 2:코스닥, 3:종목)
	MrktTp string `json:"mrkt_tp"`
	// 수량구분 (필수, 3자, 0:전체, 1:1000주, 2:2000주, 3:, 5:, 10:10000주, 30: 30000주, 50: 50000주, 100: 100000주)
	QtyTp string `json:"qty_tp"`
	// 가격구분 (필수, 1자, 0:전체, 1:1천원 미만, 8:1천원 이상, 2:1천원 ~ 2천원, 3:2천원 ~ 5천원, 4:5천원 ~ 1만원, 5:1만원 이상)
	PricTp string `json:"pric_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticBrokerInstantVolumeResponse 는 거래원순간거래량요청(ka10052) 응답이다.
type GetDomesticBrokerInstantVolumeResponse struct {
	// 거래원순간거래량
	TrdeOriMontTrdeQty []GetDomesticBrokerInstantVolumeTrdeOriMontTrdeQtyItem `json:"trde_ori_mont_trde_qty"`
}

// GetDomesticBrokerInstantVolumeTrdeOriMontTrdeQtyItem 는 TrdeOriMontTrdeQty 의 원소다.
type GetDomesticBrokerInstantVolumeTrdeOriMontTrdeQtyItem struct {
	// 시간 (20자, HHmmss)
	Tm string `json:"tm"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (20자)
	StkNm string `json:"stk_nm"`
	// 거래원명 (20자)
	TrdeOriNm string `json:"trde_ori_nm"`
	// 구분 (20자)
	Tp string `json:"tp"`
	// 순간거래량 (20자, 단위: 1주)
	MontTrdeQty string `json:"mont_trde_qty"`
	// 누적순매수 (20자, 단위: 1주)
	AccNetprps string `json:"acc_netprps"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
}

// GetDomesticBrokerInstantVolume 는 거래원순간거래량요청(ka10052) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 거래원순간거래량요청(ka10052)
// URL:  /api/dostk/stkinfo
func (c *Client) GetDomesticBrokerInstantVolume(ctx context.Context, req GetDomesticBrokerInstantVolumeRequest, opts ...transport.Option) (*GetDomesticBrokerInstantVolumeResponse, transport.Meta, error) {
	var out GetDomesticBrokerInstantVolumeResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10052",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
