// Code generated by tools/gen. DO NOT EDIT.

package stock

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// ListDomesticSectorCodesRequest 는 업종코드 리스트(ka10101) 요청이다.
type ListDomesticSectorCodesRequest struct {
	// 시장구분 (필수, 1자, 0:코스피(거래소),1:코스닥,2:KOSPI200,4:KOSPI100,7:KRX100(통합지수))
	MrktTp string `json:"mrkt_tp"`
}

// ListDomesticSectorCodesResponse 는 업종코드 리스트(ka10101) 응답이다.
type ListDomesticSectorCodesResponse struct {
	// 업종코드리스트
	List []ListDomesticSectorCodesListItem `json:"list"`
}

// ListDomesticSectorCodesListItem 는 List 의 원소다.
type ListDomesticSectorCodesListItem struct {
	// 시장구분코드
	MarketCode string `json:"marketCode"`
	// 코드
	Code string `json:"code"`
	// 업종명
	Name string `json:"name"`
	// 그룹
	Group string `json:"group"`
}

// ListDomesticSectorCodes 는 업종코드 리스트(ka10101) 이다.
//
// 메뉴: 국내주식 > 종목정보 > 업종코드 리스트(ka10101)
// URL:  /api/dostk/stkinfo
func (c *Client) ListDomesticSectorCodes(ctx context.Context, req ListDomesticSectorCodesRequest, opts ...transport.Option) (*ListDomesticSectorCodesResponse, transport.Meta, error) {
	var out ListDomesticSectorCodesResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10101",
		Path:  "/api/dostk/stkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
