// Code generated by tools/gen. DO NOT EDIT.

// Package investor 는 키움 국내주식 기관/외국인 API 그룹이다.
package investor

import "github.com/kenshin579/kiwoom-go/internal/transport"

// Client 는 국내주식 기관/외국인 하위 클라이언트다.
type Client struct {
	http *transport.Client
}

// New 는 kiwoom.NewClient 가 호출한다.
func New(hc *transport.Client) *Client { return &Client{http: hc} }
