// Code generated by tools/gen. DO NOT EDIT.

package investor

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockForeignInvestorTradeTrendRequest 는 주식외국인종목별매매동향(ka10008) 요청이다.
type GetDomesticStockForeignInvestorTradeTrendRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockForeignInvestorTradeTrendResponse 는 주식외국인종목별매매동향(ka10008) 응답이다.
type GetDomesticStockForeignInvestorTradeTrendResponse struct {
	// 주식외국인
	StkFrgnr []GetDomesticStockForeignInvestorTradeTrendStkFrgnrItem `json:"stk_frgnr"`
}

// GetDomesticStockForeignInvestorTradeTrendStkFrgnrItem 는 StkFrgnr 의 원소다.
type GetDomesticStockForeignInvestorTradeTrendStkFrgnrItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 변동수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	ChgQty string `json:"chg_qty"`
	// 보유주식수 (20자, 단위: 1주)
	PossStkcnt string `json:"poss_stkcnt"`
	// 비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Wght string `json:"wght"`
	// 취득가능주식수 (20자, 단위: 1주)
	GainPosStkcnt string `json:"gain_pos_stkcnt"`
	// 외국인한도 (20자, 단위: 1주)
	FrgnrLimit string `json:"frgnr_limit"`
	// 외국인한도증감 (20자)
	FrgnrLimitIrds string `json:"frgnr_limit_irds"`
	// 한도소진률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	LimitExhRt string `json:"limit_exh_rt"`
}

// GetDomesticStockForeignInvestorTradeTrend 는 주식외국인종목별매매동향(ka10008) 이다.
//
// 메뉴: 국내주식 > 기관/외국인 > 주식외국인종목별매매동향(ka10008)
// URL:  /api/dostk/frgnistt
func (c *Client) GetDomesticStockForeignInvestorTradeTrend(ctx context.Context, req GetDomesticStockForeignInvestorTradeTrendRequest, opts ...transport.Option) (*GetDomesticStockForeignInvestorTradeTrendResponse, transport.Meta, error) {
	var out GetDomesticStockForeignInvestorTradeTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10008",
		Path:  "/api/dostk/frgnistt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
