// Code generated by tools/gen. DO NOT EDIT.

package kiwoom

import (
	domesticaccount "github.com/kenshin579/kiwoom-go/domestic/account"
	domesticchart "github.com/kenshin579/kiwoom-go/domestic/chart"
	domesticcreditorder "github.com/kenshin579/kiwoom-go/domestic/creditorder"
	domesticelw "github.com/kenshin579/kiwoom-go/domestic/elw"
	domesticetf "github.com/kenshin579/kiwoom-go/domestic/etf"
	domesticinvestor "github.com/kenshin579/kiwoom-go/domestic/investor"
	domesticorder "github.com/kenshin579/kiwoom-go/domestic/order"
	domesticquote "github.com/kenshin579/kiwoom-go/domestic/quote"
	domesticranking "github.com/kenshin579/kiwoom-go/domestic/ranking"
	domesticsector "github.com/kenshin579/kiwoom-go/domestic/sector"
	domesticshortsale "github.com/kenshin579/kiwoom-go/domestic/shortsale"
	domesticstock "github.com/kenshin579/kiwoom-go/domestic/stock"
	domesticstocklending "github.com/kenshin579/kiwoom-go/domestic/stocklending"
	domestictheme "github.com/kenshin579/kiwoom-go/domestic/theme"
	domesticwatchlist "github.com/kenshin579/kiwoom-go/domestic/watchlist"
	"github.com/kenshin579/kiwoom-go/internal/transport"
	overseasaccount "github.com/kenshin579/kiwoom-go/overseas/account"
	overseaschart "github.com/kenshin579/kiwoom-go/overseas/chart"
	overseasexchange "github.com/kenshin579/kiwoom-go/overseas/exchange"
	overseasinfo "github.com/kenshin579/kiwoom-go/overseas/info"
	overseasorder "github.com/kenshin579/kiwoom-go/overseas/order"
	overseasquote "github.com/kenshin579/kiwoom-go/overseas/quote"
	overseasranking "github.com/kenshin579/kiwoom-go/overseas/ranking"
	overseassector "github.com/kenshin579/kiwoom-go/overseas/sector"
	overseasstock "github.com/kenshin579/kiwoom-go/overseas/stock"
	overseaswatchlist "github.com/kenshin579/kiwoom-go/overseas/watchlist"
)

// Clients 는 API 그룹별 하위 클라이언트다. Client 가 임베딩하므로
// c.DomesticQuote 처럼 바로 쓴다.
type Clients struct {
	// DomesticQuote 는 국내주식 시세.
	DomesticQuote *domesticquote.Client
	// DomesticChart 는 국내주식 차트.
	DomesticChart *domesticchart.Client
	// DomesticStock 는 국내주식 종목정보.
	DomesticStock *domesticstock.Client
	// DomesticAccount 는 국내주식 계좌.
	DomesticAccount *domesticaccount.Client
	// DomesticRanking 는 국내주식 순위정보.
	DomesticRanking *domesticranking.Client
	// DomesticELW 는 국내주식 ELW.
	DomesticELW *domesticelw.Client
	// DomesticETF 는 국내주식 ETF.
	DomesticETF *domesticetf.Client
	// DomesticOrder 는 국내주식 주문.
	DomesticOrder *domesticorder.Client
	// DomesticSector 는 국내주식 업종.
	DomesticSector *domesticsector.Client
	// DomesticCreditOrder 는 국내주식 신용주문.
	DomesticCreditOrder *domesticcreditorder.Client
	// DomesticStockLending 는 국내주식 대차거래.
	DomesticStockLending *domesticstocklending.Client
	// DomesticInvestor 는 국내주식 기관/외국인.
	DomesticInvestor *domesticinvestor.Client
	// DomesticTheme 는 국내주식 테마.
	DomesticTheme *domestictheme.Client
	// DomesticWatchlist 는 국내주식 관심종목.
	DomesticWatchlist *domesticwatchlist.Client
	// DomesticShortSale 는 국내주식 공매도.
	DomesticShortSale *domesticshortsale.Client
	// OverseasRanking 는 미국주식 순위정보.
	OverseasRanking *overseasranking.Client
	// OverseasStock 는 미국주식 종목정보.
	OverseasStock *overseasstock.Client
	// OverseasAccount 는 미국주식 계좌.
	OverseasAccount *overseasaccount.Client
	// OverseasChart 는 미국주식 차트.
	OverseasChart *overseaschart.Client
	// OverseasOrder 는 미국주식 주문.
	OverseasOrder *overseasorder.Client
	// OverseasQuote 는 미국주식 시세.
	OverseasQuote *overseasquote.Client
	// OverseasExchange 는 미국주식 환전.
	OverseasExchange *overseasexchange.Client
	// OverseasSector 는 미국주식 업종.
	OverseasSector *overseassector.Client
	// OverseasWatchlist 는 미국주식 관심종목.
	OverseasWatchlist *overseaswatchlist.Client
	// OverseasInfo 는 미국주식 투자정보.
	OverseasInfo *overseasinfo.Client
}

// newClients 는 NewClient 가 호출한다.
func newClients(tr *transport.Client) Clients {
	return Clients{
		DomesticQuote:        domesticquote.New(tr),
		DomesticChart:        domesticchart.New(tr),
		DomesticStock:        domesticstock.New(tr),
		DomesticAccount:      domesticaccount.New(tr),
		DomesticRanking:      domesticranking.New(tr),
		DomesticELW:          domesticelw.New(tr),
		DomesticETF:          domesticetf.New(tr),
		DomesticOrder:        domesticorder.New(tr),
		DomesticSector:       domesticsector.New(tr),
		DomesticCreditOrder:  domesticcreditorder.New(tr),
		DomesticStockLending: domesticstocklending.New(tr),
		DomesticInvestor:     domesticinvestor.New(tr),
		DomesticTheme:        domestictheme.New(tr),
		DomesticWatchlist:    domesticwatchlist.New(tr),
		DomesticShortSale:    domesticshortsale.New(tr),
		OverseasRanking:      overseasranking.New(tr),
		OverseasStock:        overseasstock.New(tr),
		OverseasAccount:      overseasaccount.New(tr),
		OverseasChart:        overseaschart.New(tr),
		OverseasOrder:        overseasorder.New(tr),
		OverseasQuote:        overseasquote.New(tr),
		OverseasExchange:     overseasexchange.New(tr),
		OverseasSector:       overseassector.New(tr),
		OverseasWatchlist:    overseaswatchlist.New(tr),
		OverseasInfo:         overseasinfo.New(tr),
	}
}
