// Code generated by tools/gen. DO NOT EDIT.

package shortsale

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticShortSaleTrendRequest 는 공매도추이요청(ka10014) 요청이다.
type GetDomesticShortSaleTrendRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시간구분 (1자, 0:시작일, 1:기간)
	TmTp string `json:"tm_tp"`
	// 시작일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
}

// GetDomesticShortSaleTrendResponse 는 공매도추이요청(ka10014) 응답이다.
type GetDomesticShortSaleTrendResponse struct {
	// 공매도추이
	ShrtsTrnsn []GetDomesticShortSaleTrendShrtsTrnsnItem `json:"shrts_trnsn"`
}

// GetDomesticShortSaleTrendShrtsTrnsnItem 는 ShrtsTrnsn 의 원소다.
type GetDomesticShortSaleTrendShrtsTrnsnItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 공매도량 (20자, 단위: 1주)
	ShrtsQty string `json:"shrts_qty"`
	// 누적공매도량 (20자, 설정 기간의 공매도량 합산데이터)
	OvrShrtsQty string `json:"ovr_shrts_qty"`
	// 매매비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeWght string `json:"trde_wght"`
	// 공매도거래대금 (20자, 단위: 천원)
	ShrtsTrdePrica string `json:"shrts_trde_prica"`
	// 공매도평균가 (20자, 단위: 원)
	ShrtsAvgPric string `json:"shrts_avg_pric"`
}

// GetDomesticShortSaleTrend 는 공매도추이요청(ka10014) 이다.
//
// 메뉴: 국내주식 > 공매도 > 공매도추이요청(ka10014)
// URL:  /api/dostk/shsa
func (c *Client) GetDomesticShortSaleTrend(ctx context.Context, req GetDomesticShortSaleTrendRequest, opts ...transport.Option) (*GetDomesticShortSaleTrendResponse, transport.Meta, error) {
	var out GetDomesticShortSaleTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10014",
		Path:  "/api/dostk/shsa",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
