// Code generated by tools/gen. DO NOT EDIT.

package order

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasOrderableQuantityRequest 는 미국주식 주문가능수량(종목/증거금률별)(ust31490) 요청이다.
type GetOverseasOrderableQuantityRequest struct {
	// 거래소구분 (2자, NA :AMEX, ND :NASDAQ, NY:NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수, 12자)
	StkCd string `json:"stk_cd"`
	// 매수가격 (필수, 12자)
	Uv string `json:"uv"`
}

// GetOverseasOrderableQuantityResponse 는 미국주식 주문가능수량(종목/증거금률별)(ust31490) 응답이다.
type GetOverseasOrderableQuantityResponse struct {
	// 종목증거금율 (15자)
	StkProfaRt string `json:"stk_profa_rt"`
	// 계좌증거금율 (15자)
	ProfaRt string `json:"profa_rt"`
	// 적용증거금율 (15자)
	AplcRt string `json:"aplc_rt"`
	// 원화주문신청여부 (1자, Y, N)
	KrwOrdRqstYn string `json:"krw_ord_rqst_yn"`
	// 증거금50%종목 원화주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	KrwOrdAlowa50 string `json:"krw_ord_alowa_50"`
	// 증거금50%종목 원화주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	KrwOrdAlowq50 string `json:"krw_ord_alowq_50"`
	// 증거금50%종목 주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	OrdAlowa50 string `json:"ord_alowa_50"`
	// 증거금50%종목 주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdAlowq50 string `json:"ord_alowq_50"`
	// 증거금50%종목 전일재사용금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	PredRebuyAlowa50 string `json:"pred_rebuy_alowa_50"`
	// 증거금50%종목 금일재사용금액 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	TdyRebuyAlowa50 string `json:"tdy_rebuy_alowa_50"`
	// 증거금100%종목원화주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	KrwOrdAlowa100 string `json:"krw_ord_alowa_100"`
	// 증거금100%종목원화주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	KrwOrdAlowq100 string `json:"krw_ord_alowq_100"`
	// 증거금100%종목 주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	OrdAlowa100 string `json:"ord_alowa_100"`
	// 증거금100%종목 주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdAlowq100 string `json:"ord_alowq_100"`
	// 증거금100%종목 전일재사용금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	PredRebuyAlowa100 string `json:"pred_rebuy_alowa_100"`
	// 증거금100%종목 금일재사용금액 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	TdyRebuyAlowa100 string `json:"tdy_rebuy_alowa_100"`
	// 미수불가 원화주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	MinKrwOrdAlowa string `json:"min_krw_ord_alowa"`
	// 미수불가 원화주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	MinKrwOrdAlowq string `json:"min_krw_ord_alowq"`
	// 미수불가 주문가능금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	MinOrdAlowa string `json:"min_ord_alowa"`
	// 미수불가 주문가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	MinOrdAlowq string `json:"min_ord_alowq"`
	// 미수불가 전일재사용금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	MinPredRebuyAlowa string `json:"min_pred_rebuy_alowa"`
	// 미수불가 금일재사용금액 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	MinTdyRebuyAlowa string `json:"min_tdy_rebuy_alowa"`
	// 원화예수금 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	KrwEntra string `json:"krw_entra"`
	// 외화예수금 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	FcEntra string `json:"fc_entra"`
	// 외화미수금 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	FcUnclAmt string `json:"fc_uncl_amt"`
	// 주문가능현금 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	OrdAlowa string `json:"ord_alowa"`
	// 해외원화주문설정금 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	KrwOrdSetAmt string `json:"krw_ord_set_amt"`
	// 해외원화주문평가금 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	KrwOrdEvltAmt string `json:"krw_ord_evlt_amt"`
	// 통화 (3자)
	CrncCode string `json:"crnc_code"`
}

// GetOverseasOrderableQuantity 는 미국주식 주문가능수량(종목/증거금률별)(ust31490) 이다.
//
// 메뉴: 미국주식 > 주문 > 미국주식 주문가능수량(종목/증거금률별)(ust31490)
// URL:  /api/us/ordr
func (c *Client) GetOverseasOrderableQuantity(ctx context.Context, req GetOverseasOrderableQuantityRequest, opts ...transport.Option) (*GetOverseasOrderableQuantityResponse, transport.Meta, error) {
	var out GetOverseasOrderableQuantityResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust31490",
		Path:  "/api/us/ordr",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
