// Code generated by tools/gen. DO NOT EDIT.

package elw

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticElwRemainingOrderRankRequest 는 ELW잔량순위요청(ka30010) 요청이다.
type GetDomesticElwRemainingOrderRankRequest struct {
	// 정렬구분 (필수, 1자, 1:순매수잔량상위, 2: 순매도 잔량상위)
	SortTp string `json:"sort_tp"`
	// 권리구분 (필수, 3자, 000: 전체, 001: 콜, 002: 풋, 003: DC, 004: DP, 006: 조기종료콜, 007: 조기종료풋)
	RghtTp string `json:"rght_tp"`
	// 거래종료제외 (필수, 1자, 1:거래종료제외, 0:거래종료포함)
	TrdeEndSkip string `json:"trde_end_skip"`
}

// GetDomesticElwRemainingOrderRankResponse 는 ELW잔량순위요청(ka30010) 응답이다.
type GetDomesticElwRemainingOrderRankResponse struct {
	// ELW잔량순위
	ElwreqRank []GetDomesticElwRemainingOrderRankElwreqRankItem `json:"elwreq_rank"`
}

// GetDomesticElwRemainingOrderRankElwreqRankItem 는 ElwreqRank 의 원소다.
type GetDomesticElwRemainingOrderRankElwreqRankItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 순위 (20자)
	Rank string `json:"rank"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 매도잔량 (20자, 단위: 1주)
	SelReq string `json:"sel_req"`
	// 매수잔량 (20자, 단위: 1주)
	BuyReq string `json:"buy_req"`
	// 순매수잔량 (20자, 단위: 1주)
	NetprpsReq string `json:"netprps_req"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
}

// GetDomesticElwRemainingOrderRank 는 ELW잔량순위요청(ka30010) 이다.
//
// 메뉴: 국내주식 > ELW > ELW잔량순위요청(ka30010)
// URL:  /api/dostk/elw
func (c *Client) GetDomesticElwRemainingOrderRank(ctx context.Context, req GetDomesticElwRemainingOrderRankRequest, opts ...transport.Option) (*GetDomesticElwRemainingOrderRankResponse, transport.Meta, error) {
	var out GetDomesticElwRemainingOrderRankResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka30010",
		Path:  "/api/dostk/elw",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
