// Code generated by tools/gen. DO NOT EDIT.

package elw

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticElwProximityRateRequest 는 ELW근접율요청(ka30011) 요청이다.
type GetDomesticElwProximityRateRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticElwProximityRateResponse 는 ELW근접율요청(ka30011) 응답이다.
type GetDomesticElwProximityRateResponse struct {
	// ELW근접율
	ElwalaccRt []GetDomesticElwProximityRateElwalaccRtItem `json:"elwalacc_rt"`
}

// GetDomesticElwProximityRateElwalaccRtItem 는 ElwalaccRt 의 원소다.
type GetDomesticElwProximityRateElwalaccRtItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 근접율 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	AlaccRt string `json:"alacc_rt"`
}

// GetDomesticElwProximityRate 는 ELW근접율요청(ka30011) 이다.
//
// 메뉴: 국내주식 > ELW > ELW근접율요청(ka30011)
// URL:  /api/dostk/elw
func (c *Client) GetDomesticElwProximityRate(ctx context.Context, req GetDomesticElwProximityRateRequest, opts ...transport.Option) (*GetDomesticElwProximityRateResponse, transport.Meta, error) {
	var out GetDomesticElwProximityRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka30011",
		Path:  "/api/dostk/elw",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
