// Code generated by tools/gen. DO NOT EDIT.

package elw

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticElwSensitivityIndicatorRequest 는 ELW민감도지표요청(ka10050) 요청이다.
type GetDomesticElwSensitivityIndicatorRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticElwSensitivityIndicatorResponse 는 ELW민감도지표요청(ka10050) 응답이다.
type GetDomesticElwSensitivityIndicatorResponse struct {
	// ELW민감도지표배열
	ElwsnstIxArray []GetDomesticElwSensitivityIndicatorElwsnstIxArrayItem `json:"elwsnst_ix_array"`
}

// GetDomesticElwSensitivityIndicatorElwsnstIxArrayItem 는 ElwsnstIxArray 의 원소다.
type GetDomesticElwSensitivityIndicatorElwsnstIxArrayItem struct {
	// 체결시간 (20자, HHmmss)
	CntrTm string `json:"cntr_tm"`
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// ELW이론가 (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"값은 26.58을 의미합니다.)
	ElwtheoryPric string `json:"elwtheory_pric"`
	// IV (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"값은 26.58을 의미합니다.)
	Iv string `json:"iv"`
	// 델타 (20자, 소수점 제거한 값으로 제공 예) "590470"값은 0.590470을 의미합니다.)
	Delta string `json:"delta"`
	// 감마 (20자, 소수점 제거한 값으로 제공 예) "163"값은 0.000163을 의미합니다.)
	Gam string `json:"gam"`
	// 쎄타 (20자, 소수점 제거한 값으로 제공 예) "-1057402"값은 -1.057402을 의미합니다.)
	Theta string `json:"theta"`
	// 베가 (20자, 소수점 제거한 값으로 제공 예) "290965"값은 0.290965을 의미합니다.)
	Vega string `json:"vega"`
	// 로 (20자, 소수점 제거한 값으로 제공 예) "73629"값은 0.073629을 의미합니다.)
	Law string `json:"law"`
	// LP (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"값은 26.58을 의미합니다.)
	Lp string `json:"lp"`
}

// GetDomesticElwSensitivityIndicator 는 ELW민감도지표요청(ka10050) 이다.
//
// 메뉴: 국내주식 > ELW > ELW민감도지표요청(ka10050)
// URL:  /api/dostk/elw
func (c *Client) GetDomesticElwSensitivityIndicator(ctx context.Context, req GetDomesticElwSensitivityIndicatorRequest, opts ...transport.Option) (*GetDomesticElwSensitivityIndicatorResponse, transport.Meta, error) {
	var out GetDomesticElwSensitivityIndicatorResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10050",
		Path:  "/api/dostk/elw",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
