// Code generated by tools/gen. DO NOT EDIT.

package elw

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticElwDailySensitivityIndicatorRequest 는 ELW일별민감도지표요청(ka10048) 요청이다.
type GetDomesticElwDailySensitivityIndicatorRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticElwDailySensitivityIndicatorResponse 는 ELW일별민감도지표요청(ka10048) 응답이다.
type GetDomesticElwDailySensitivityIndicatorResponse struct {
	// ELW일별민감도지표
	ElwdalySnstIx []GetDomesticElwDailySensitivityIndicatorElwdalySnstIxItem `json:"elwdaly_snst_ix"`
}

// GetDomesticElwDailySensitivityIndicatorElwdalySnstIxItem 는 ElwdalySnstIx 의 원소다.
type GetDomesticElwDailySensitivityIndicatorElwdalySnstIxItem struct {
	// 일자 (20자)
	Dt string `json:"dt"`
	// IV (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58를 의미합니다.)
	Iv string `json:"iv"`
	// 델타 (20자, 소수점 제거한 값으로 제공 예) "590470"값은 0.590470을 의미합니다.)
	Delta string `json:"delta"`
	// 감마 (20자, 소수점 제거한 값으로 제공 예) "167"값은 0.000167을 의미합니다.)
	Gam string `json:"gam"`
	// 쎄타 (20자, 소수점 제거한 값으로 제공 예) "-991554"값은 -0.991554를 의미합니다.)
	Theta string `json:"theta"`
	// 베가 (20자, 소수점 제거한 값으로 제공 예) "-991554"값은 -0.991554를 의미합니다.)
	Vega string `json:"vega"`
	// 로 (20자, 소수점 제거한 값으로 제공 예) "76850"값은 0.076850을 의미합니다.)
	Law string `json:"law"`
	// LP (20자, 소수점 제거 된 100배 값으로 제공 예) "6197"값은 61.87을 의미합니다.)
	Lp string `json:"lp"`
}

// GetDomesticElwDailySensitivityIndicator 는 ELW일별민감도지표요청(ka10048) 이다.
//
// 메뉴: 국내주식 > ELW > ELW일별민감도지표요청(ka10048)
// URL:  /api/dostk/elw
func (c *Client) GetDomesticElwDailySensitivityIndicator(ctx context.Context, req GetDomesticElwDailySensitivityIndicatorRequest, opts ...transport.Option) (*GetDomesticElwDailySensitivityIndicatorResponse, transport.Meta, error) {
	var out GetDomesticElwDailySensitivityIndicatorResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10048",
		Path:  "/api/dostk/elw",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
