// Code generated by tools/gen. DO NOT EDIT.

package elw

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticBrokerElwNetBuyTopRequest 는 거래원별ELW순매매상위요청(ka30002) 요청이다.
type GetDomesticBrokerElwNetBuyTopRequest struct {
	// 발행사코드 (필수, 3자, 3자리, 영웅문4 0273화면참조 (교보:001, 신한금융투자:002, 한국투자증권:003, 대신:004, 미래대우:005, ,,,))
	IsscompCd string `json:"isscomp_cd"`
	// 거래량구분 (필수, 4자, 0:전체, 5:5천주, 10:만주, 50:5만주, 100:10만주, 500:50만주, 1000:백만주)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 매매구분 (필수, 1자, 1:순매수, 2:순매도)
	TrdeTp string `json:"trde_tp"`
	// 기간 (필수, 2자, 1:전일, 5:5일, 10:10일, 40:40일, 60:60일)
	Dt string `json:"dt"`
	// 거래종료ELW제외 (필수, 1자, 0:포함, 1:제외)
	TrdeEndElwskip string `json:"trde_end_elwskip"`
}

// GetDomesticBrokerElwNetBuyTopResponse 는 거래원별ELW순매매상위요청(ka30002) 응답이다.
type GetDomesticBrokerElwNetBuyTopResponse struct {
	// 거래원별ELW순매매상위
	TrdeOriElwnettrdeUpper []GetDomesticBrokerElwNetBuyTopTrdeOriElwnettrdeUpperItem `json:"trde_ori_elwnettrde_upper"`
}

// GetDomesticBrokerElwNetBuyTopTrdeOriElwnettrdeUpperItem 는 TrdeOriElwnettrdeUpper 의 원소다.
type GetDomesticBrokerElwNetBuyTopTrdeOriElwnettrdeUpperItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 주가등락 (20자, 부호가 포함된 숫자)
	StkpcFlu string `json:"stkpc_flu"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 순매수 (20자, 단위: 1주, 부호가 포함된 숫자)
	Netprps string `json:"netprps"`
	// 매수거래량 (20자, 단위: 1주)
	BuyTrdeQty string `json:"buy_trde_qty"`
	// 매도거래량 (20자, 단위: 1주)
	SelTrdeQty string `json:"sel_trde_qty"`
}

// GetDomesticBrokerElwNetBuyTop 는 거래원별ELW순매매상위요청(ka30002) 이다.
//
// 메뉴: 국내주식 > ELW > 거래원별ELW순매매상위요청(ka30002)
// URL:  /api/dostk/elw
func (c *Client) GetDomesticBrokerElwNetBuyTop(ctx context.Context, req GetDomesticBrokerElwNetBuyTopRequest, opts ...transport.Option) (*GetDomesticBrokerElwNetBuyTopResponse, transport.Meta, error) {
	var out GetDomesticBrokerElwNetBuyTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka30002",
		Path:  "/api/dostk/elw",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
