// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockInstitutionTradeTrendRequest 는 종목별기관매매추이요청(ka10045) 요청이다.
type GetDomesticStockInstitutionTradeTrendRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시작일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 기관추정단가구분 (필수, 1자, 1:매수단가, 2:매도단가)
	OrgnPrsmUnpTp string `json:"orgn_prsm_unp_tp"`
	// 외인추정단가구분 (필수, 1자, 1:매수단가, 2:매도단가)
	ForPrsmUnpTp string `json:"for_prsm_unp_tp"`
}

// GetDomesticStockInstitutionTradeTrendResponse 는 종목별기관매매추이요청(ka10045) 응답이다.
type GetDomesticStockInstitutionTradeTrendResponse struct {
	// 기관추정평균가 (단위: 원)
	OrgnPrsmAvgPric string `json:"orgn_prsm_avg_pric"`
	// 외인추정평균가 (단위: 원)
	ForPrsmAvgPric string `json:"for_prsm_avg_pric"`
	// 종목별기관매매추이
	StkOrgnTrdeTrnsn []GetDomesticStockInstitutionTradeTrendStkOrgnTrdeTrnsnItem `json:"stk_orgn_trde_trnsn"`
}

// GetDomesticStockInstitutionTradeTrendStkOrgnTrdeTrnsnItem 는 StkOrgnTrdeTrnsn 의 원소다.
type GetDomesticStockInstitutionTradeTrendStkOrgnTrdeTrnsnItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 기관기간누적 (20자)
	OrgnDtAcc string `json:"orgn_dt_acc"`
	// 기관일별순매매수량 (20자, 단위: 1주)
	OrgnDalyNettrdeQty string `json:"orgn_daly_nettrde_qty"`
	// 외인기간누적 (20자)
	ForDtAcc string `json:"for_dt_acc"`
	// 외인일별순매매수량 (20자, 단위: 1주)
	ForDalyNettrdeQty string `json:"for_daly_nettrde_qty"`
	// 한도소진율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	LimitExhRt string `json:"limit_exh_rt"`
}

// GetDomesticStockInstitutionTradeTrend 는 종목별기관매매추이요청(ka10045) 이다.
//
// 메뉴: 국내주식 > 시세 > 종목별기관매매추이요청(ka10045)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticStockInstitutionTradeTrend(ctx context.Context, req GetDomesticStockInstitutionTradeTrendRequest, opts ...transport.Option) (*GetDomesticStockInstitutionTradeTrendResponse, transport.Meta, error) {
	var out GetDomesticStockInstitutionTradeTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10045",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
