// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotQuoteInfoRequest 는 금현물 시세정보(ka50100) 요청이다.
type GetDomesticGoldSpotQuoteInfoRequest struct {
	// 종목코드 (필수, 20자, M04020000: 금 99.99_1kg, M04020100: 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
}

// GetDomesticGoldSpotQuoteInfoResponse 는 금현물 시세정보(ka50100) 응답이다.
type GetDomesticGoldSpotQuoteInfoResponse struct {
	// 전일대비기호 (20자)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 전일비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PredRt string `json:"pred_rt"`
	// 상한가 (20자, 단위: 원, 부호가 포함된 숫자)
	UplPric string `json:"upl_pric"`
	// 하한가 (20자, 단위: 원, 부호가 포함된 숫자)
	LstPric string `json:"lst_pric"`
	// 전일종가 (20자, 단위: 원)
	PredClosePric string `json:"pred_close_pric"`
}

// GetDomesticGoldSpotQuoteInfo 는 금현물 시세정보(ka50100) 이다.
//
// 메뉴: 국내주식 > 시세 > 금현물 시세정보(ka50100)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticGoldSpotQuoteInfo(ctx context.Context, req GetDomesticGoldSpotQuoteInfoRequest, opts ...transport.Option) (*GetDomesticGoldSpotQuoteInfoResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotQuoteInfoResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50100",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
