// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockProgramIntradayTrendRequest 는 종목시간별프로그램매매추이요청(ka90008) 요청이다.
type GetDomesticStockProgramIntradayTrendRequest struct {
	// 금액수량구분 (필수, 1자, 1:금액, 2:수량)
	AmtQtyTp string `json:"amt_qty_tp"`
	// 종목코드 (필수, 6자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 날짜 (필수, 8자, YYYYMMDD)
	Date string `json:"date"`
}

// GetDomesticStockProgramIntradayTrendResponse 는 종목시간별프로그램매매추이요청(ka90008) 응답이다.
type GetDomesticStockProgramIntradayTrendResponse struct {
	// 종목시간별프로그램매매추이
	StkTmPrmTrdeTrnsn []GetDomesticStockProgramIntradayTrendStkTmPrmTrdeTrnsnItem `json:"stk_tm_prm_trde_trnsn"`
}

// GetDomesticStockProgramIntradayTrendStkTmPrmTrdeTrnsnItem 는 StkTmPrmTrdeTrnsn 의 원소다.
type GetDomesticStockProgramIntradayTrendStkTmPrmTrdeTrnsnItem struct {
	// 시간 (20자, HHmmss)
	Tm string `json:"tm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 프로그램매도금액 (20자, 단위: 백만원)
	PrmSellAmt string `json:"prm_sell_amt"`
	// 프로그램매수금액 (20자, 단위: 백만원)
	PrmBuyAmt string `json:"prm_buy_amt"`
	// 프로그램순매수금액 (20자, 단위: 백만원, 부호가 포함된 숫자)
	PrmNetprpsAmt string `json:"prm_netprps_amt"`
	// 프로그램순매수금액증감 (20자, 단위: 백만원, 부호가 포함된 숫자)
	PrmNetprpsAmtIrds string `json:"prm_netprps_amt_irds"`
	// 프로그램매도수량 (20자, 단위: 1주)
	PrmSellQty string `json:"prm_sell_qty"`
	// 프로그램매수수량 (20자, 단위: 1주)
	PrmBuyQty string `json:"prm_buy_qty"`
	// 프로그램순매수수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	PrmNetprpsQty string `json:"prm_netprps_qty"`
	// 프로그램순매수수량증감 (20자, 단위: 1주, 부호가 포함된 숫자)
	PrmNetprpsQtyIrds string `json:"prm_netprps_qty_irds"`
	// 기준가시간 (20자, HHmmss)
	BasePricTm string `json:"base_pric_tm"`
	// 대차거래상환주수합 (20자)
	DbrtTrdeRpySum string `json:"dbrt_trde_rpy_sum"`
	// 잔고수주합 (20자)
	RemnRcvordSum string `json:"remn_rcvord_sum"`
	// 거래소구분 (20자, KRX , NXT , 통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticStockProgramIntradayTrend 는 종목시간별프로그램매매추이요청(ka90008) 이다.
//
// 메뉴: 국내주식 > 시세 > 종목시간별프로그램매매추이요청(ka90008)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticStockProgramIntradayTrend(ctx context.Context, req GetDomesticStockProgramIntradayTrendRequest, opts ...transport.Option) (*GetDomesticStockProgramIntradayTrendResponse, transport.Meta, error) {
	var out GetDomesticStockProgramIntradayTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka90008",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
