// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDailyStockPriceRequest 는 일별주가요청(ka10086) 요청이다.
type GetDomesticDailyStockPriceRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 조회일자 (필수, 8자, YYYYMMDD)
	QryDt string `json:"qry_dt"`
	// 표시구분 (필수, 1자, 0:수량, 1:금액(백만원))
	IndcTp string `json:"indc_tp"`
}

// GetDomesticDailyStockPriceResponse 는 일별주가요청(ka10086) 응답이다.
type GetDomesticDailyStockPriceResponse struct {
	// 일별주가
	DalyStkpc []GetDomesticDailyStockPriceDalyStkpcItem `json:"daly_stkpc"`
}

// GetDomesticDailyStockPriceDalyStkpcItem 는 DalyStkpc 의 원소다.
type GetDomesticDailyStockPriceDalyStkpcItem struct {
	// 날짜 (20자, YYYYMMDD)
	Date string `json:"date"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 전일비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredRt string `json:"pred_rt"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 금액(백만) (20자, 단위: 백만원)
	AmtMn string `json:"amt_mn"`
	// 신용비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CrdRt string `json:"crd_rt"`
	// 개인 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	Ind string `json:"ind"`
	// 기관 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	Orgn string `json:"orgn"`
	// 외인수량 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	ForQty string `json:"for_qty"`
	// 외국계 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	Frgn string `json:"frgn"`
	// 프로그램 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	Prm string `json:"prm"`
	// 외인비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForRt string `json:"for_rt"`
	// 외인보유 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForPoss string `json:"for_poss"`
	// 외인비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForWght string `json:"for_wght"`
	// 외인순매수 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	ForNetprps string `json:"for_netprps"`
	// 기관순매수 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	OrgnNetprps string `json:"orgn_netprps"`
	// 개인순매수 (20자, 단위: 백만원, 1주, 부호가 포함된 숫자)
	IndNetprps string `json:"ind_netprps"`
	// 신용잔고율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CrdRemnRt string `json:"crd_remn_rt"`
}

// GetDomesticDailyStockPrice 는 일별주가요청(ka10086) 이다.
//
// 메뉴: 국내주식 > 시세 > 일별주가요청(ka10086)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticDailyStockPrice(ctx context.Context, req GetDomesticDailyStockPriceRequest, opts ...transport.Option) (*GetDomesticDailyStockPriceResponse, transport.Meta, error) {
	var out GetDomesticDailyStockPriceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10086",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
