// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticTradeStrengthDailyTrendRequest 는 체결강도추이일별요청(ka10047) 요청이다.
type GetDomesticTradeStrengthDailyTrendRequest struct {
	// 종목코드 (필수, 6자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticTradeStrengthDailyTrendResponse 는 체결강도추이일별요청(ka10047) 응답이다.
type GetDomesticTradeStrengthDailyTrendResponse struct {
	// 체결강도일별
	CntrStrDaly []GetDomesticTradeStrengthDailyTrendCntrStrDalyItem `json:"cntr_str_daly"`
}

// GetDomesticTradeStrengthDailyTrendCntrStrDalyItem 는 CntrStrDaly 의 원소다.
type GetDomesticTradeStrengthDailyTrendCntrStrDalyItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 누적거래대금 (20자, 단위: 백만원)
	AccTrdePrica string `json:"acc_trde_prica"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 체결강도 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr string `json:"cntr_str"`
	// 체결강도5일 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr5min string `json:"cntr_str_5min"`
	// 체결강도20일 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr20min string `json:"cntr_str_20min"`
	// 체결강도60일 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr60min string `json:"cntr_str_60min"`
}

// GetDomesticTradeStrengthDailyTrend 는 체결강도추이일별요청(ka10047) 이다.
//
// 메뉴: 국내주식 > 시세 > 체결강도추이일별요청(ka10047)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticTradeStrengthDailyTrend(ctx context.Context, req GetDomesticTradeStrengthDailyTrendRequest, opts ...transport.Option) (*GetDomesticTradeStrengthDailyTrendResponse, transport.Meta, error) {
	var out GetDomesticTradeStrengthDailyTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10047",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
