// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAfterCloseInvestorTradeRequest 는 장마감후투자자별매매요청(ka10066) 요청이다.
type GetDomesticAfterCloseInvestorTradeRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 금액수량구분 (필수, 1자, 1:금액, 2:수량)
	AmtQtyTp string `json:"amt_qty_tp"`
	// 매매구분 (필수, 1자, 0:순매수, 1:매수, 2:매도)
	TrdeTp string `json:"trde_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticAfterCloseInvestorTradeResponse 는 장마감후투자자별매매요청(ka10066) 응답이다.
type GetDomesticAfterCloseInvestorTradeResponse struct {
	// 장중투자자별매매차트
	OpafInvsrTrde []GetDomesticAfterCloseInvestorTradeOpafInvsrTrdeItem `json:"opaf_invsr_trde"`
}

// GetDomesticAfterCloseInvestorTradeOpafInvsrTrdeItem 는 OpafInvsrTrde 의 원소다.
type GetDomesticAfterCloseInvestorTradeOpafInvsrTrdeItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 개인투자자 (20자, 단위: 백만원, 1주)
	IndInvsr string `json:"ind_invsr"`
	// 외국인투자자 (20자, 단위: 백만원, 1주)
	FrgnrInvsr string `json:"frgnr_invsr"`
	// 기관계 (20자, 단위: 백만원, 1주)
	Orgn string `json:"orgn"`
	// 금융투자 (20자, 단위: 백만원, 1주)
	FnncInvt string `json:"fnnc_invt"`
	// 보험 (20자, 단위: 백만원, 1주)
	Insrnc string `json:"insrnc"`
	// 투신 (20자, 단위: 백만원, 1주)
	Invtrt string `json:"invtrt"`
	// 기타금융 (20자, 단위: 백만원, 1주)
	EtcFnnc string `json:"etc_fnnc"`
	// 은행 (20자, 단위: 백만원, 1주)
	Bank string `json:"bank"`
	// 연기금등 (20자, 단위: 백만원, 1주)
	PenfndEtc string `json:"penfnd_etc"`
	// 사모펀드 (20자, 단위: 백만원, 1주)
	SamoFund string `json:"samo_fund"`
	// 국가 (20자, 단위: 백만원, 1주)
	Natn string `json:"natn"`
	// 기타법인 (20자, 단위: 백만원, 1주)
	EtcCorp string `json:"etc_corp"`
}

// GetDomesticAfterCloseInvestorTrade 는 장마감후투자자별매매요청(ka10066) 이다.
//
// 메뉴: 국내주식 > 시세 > 장마감후투자자별매매요청(ka10066)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticAfterCloseInvestorTrade(ctx context.Context, req GetDomesticAfterCloseInvestorTradeRequest, opts ...transport.Option) (*GetDomesticAfterCloseInvestorTradeResponse, transport.Meta, error) {
	var out GetDomesticAfterCloseInvestorTradeResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10066",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
