// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticProgramTradeDailyTrendRequest 는 프로그램매매추이요청 일자별(ka90010) 요청이다.
type GetDomesticProgramTradeDailyTrendRequest struct {
	// 날짜 (필수, 8자, YYYYMMDD)
	Date string `json:"date"`
	// 금액수량구분 (필수, 1자, 1:금액(백만원), 2:수량(천주))
	AmtQtyTp string `json:"amt_qty_tp"`
	// 시장구분 (필수, 10자, 코스피- 거래소구분값 1일경우:P00101, 2일경우:P001_NX01, 3일경우:P001_AL01 코스닥- 거래소구분값 1일경우:P10102, 2일경우:P101_NX02, 3일경우:P001_AL02)
	MrktTp string `json:"mrkt_tp"`
	// 분틱구분 (필수, 1자, 0:틱, 1:분)
	MinTicTp string `json:"min_tic_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticProgramTradeDailyTrendResponse 는 프로그램매매추이요청 일자별(ka90010) 응답이다.
type GetDomesticProgramTradeDailyTrendResponse struct {
	// 프로그램매매추이
	PrmTrdeTrnsn []GetDomesticProgramTradeDailyTrendPrmTrdeTrnsnItem `json:"prm_trde_trnsn"`
}

// GetDomesticProgramTradeDailyTrendPrmTrdeTrnsnItem 는 PrmTrdeTrnsn 의 원소다.
type GetDomesticProgramTradeDailyTrendPrmTrdeTrnsnItem struct {
	// 체결시간 (20자, YYYYMMDDHHmmss)
	CntrTm string `json:"cntr_tm"`
	// 차익거래매도 (20자, 단위: 백만원)
	DfrtTrdeSel string `json:"dfrt_trde_sel"`
	// 차익거래매수 (20자, 단위: 백만원)
	DfrtTrdeBuy string `json:"dfrt_trde_buy"`
	// 차익거래순매수 (20자, 단위: 백만원, 부호가 포함된 숫자)
	DfrtTrdeNetprps string `json:"dfrt_trde_netprps"`
	// 비차익거래매도 (20자, 단위: 백만원)
	NdiffproTrdeSel string `json:"ndiffpro_trde_sel"`
	// 비차익거래매수 (20자, 단위: 백만원)
	NdiffproTrdeBuy string `json:"ndiffpro_trde_buy"`
	// 비차익거래순매수 (20자, 단위: 백만원, 부호가 포함된 숫자)
	NdiffproTrdeNetprps string `json:"ndiffpro_trde_netprps"`
	// 차익거래매도수량 (20자, 단위: 1000주)
	DfrtTrdeSellQty string `json:"dfrt_trde_sell_qty"`
	// 차익거래매수수량 (20자, 단위: 1000주)
	DfrtTrdeBuyQty string `json:"dfrt_trde_buy_qty"`
	// 차익거래순매수수량 (20자, 단위: 1000주, 부호가 포함된 숫자)
	DfrtTrdeNetprpsQty string `json:"dfrt_trde_netprps_qty"`
	// 비차익거래매도수량 (20자, 단위: 1000주)
	NdiffproTrdeSellQty string `json:"ndiffpro_trde_sell_qty"`
	// 비차익거래매수수량 (20자, 단위: 1000주)
	NdiffproTrdeBuyQty string `json:"ndiffpro_trde_buy_qty"`
	// 비차익거래순매수수량 (20자, 단위: 1000주, 부호가 포함된 숫자)
	NdiffproTrdeNetprpsQty string `json:"ndiffpro_trde_netprps_qty"`
	// 전체매도 (20자, 단위: 백만원)
	AllSel string `json:"all_sel"`
	// 전체매수 (20자, 단위: 백만원)
	AllBuy string `json:"all_buy"`
	// 전체순매수 (20자, 단위: 백만원, 부호가 포함된 숫자)
	AllNetprps string `json:"all_netprps"`
	// KOSPI200 (20자, 부호 포함 소수점 둘째 자리까지 포맷된 숫자)
	Kospi200 string `json:"kospi200"`
	// BASIS (20자, 소수점 둘째 자리까지 포맷된 숫자)
	Basis string `json:"basis"`
}

// GetDomesticProgramTradeDailyTrend 는 프로그램매매추이요청 일자별(ka90010) 이다.
//
// 메뉴: 국내주식 > 시세 > 프로그램매매추이요청 일자별(ka90010)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticProgramTradeDailyTrend(ctx context.Context, req GetDomesticProgramTradeDailyTrendRequest, opts ...transport.Option) (*GetDomesticProgramTradeDailyTrendResponse, transport.Meta, error) {
	var out GetDomesticProgramTradeDailyTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka90010",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
