// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotTradeTrendRequest 는 금현물체결추이(ka50010) 요청이다.
type GetDomesticGoldSpotTradeTrendRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
}

// GetDomesticGoldSpotTradeTrendResponse 는 금현물체결추이(ka50010) 응답이다.
type GetDomesticGoldSpotTradeTrendResponse struct {
	// 금현물체결추이
	GoldCntr []GetDomesticGoldSpotTradeTrendGoldCntrItem `json:"gold_cntr"`
}

// GetDomesticGoldSpotTradeTrendGoldCntrItem 는 GoldCntr 의 원소다.
type GetDomesticGoldSpotTradeTrendGoldCntrItem struct {
	// 체결가 (20자, 단위: 원, 부호가 포함된 숫자)
	CntrPric string `json:"cntr_pric"`
	// 전일 대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 누적 거래대금 (20자, 단위: 원)
	AccTrdePrica string `json:"acc_trde_prica"`
	// 거래량(체결량) (20자, 단위: 1주)
	CntrTrdeQty string `json:"cntr_trde_qty"`
	// 체결시간 (20자, HHmmss)
	Tm string `json:"tm"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	PriSelBidUnit string `json:"pri_sel_bid_unit"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	PriBuyBidUnit string `json:"pri_buy_bid_unit"`
	// 전일 거래량 대비 비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdePre string `json:"trde_pre"`
	// 전일 거래량 대비 순간 거래량 비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeTernRt string `json:"trde_tern_rt"`
	// 체결강도 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr string `json:"cntr_str"`
}

// GetDomesticGoldSpotTradeTrend 는 금현물체결추이(ka50010) 이다.
//
// 메뉴: 국내주식 > 시세 > 금현물체결추이(ka50010)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticGoldSpotTradeTrend(ctx context.Context, req GetDomesticGoldSpotTradeTrendRequest, opts ...transport.Option) (*GetDomesticGoldSpotTradeTrendResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotTradeTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50010",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
