// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotExpectedExecutionRequest 는 금현물예상체결(ka50087) 요청이다.
type GetDomesticGoldSpotExpectedExecutionRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
}

// GetDomesticGoldSpotExpectedExecutionResponse 는 금현물예상체결(ka50087) 응답이다.
type GetDomesticGoldSpotExpectedExecutionResponse struct {
	// 금현물예상체결
	GoldExptExec []GetDomesticGoldSpotExpectedExecutionGoldExptExecItem `json:"gold_expt_exec"`
}

// GetDomesticGoldSpotExpectedExecutionGoldExptExecItem 는 GoldExptExec 의 원소다.
type GetDomesticGoldSpotExpectedExecutionGoldExptExecItem struct {
	// 예상 체결가 (20자, 단위: 원, 부호가 포함된 숫자)
	ExpCntrPric string `json:"exp_cntr_pric"`
	// 예상 체결가 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	ExpPredPre string `json:"exp_pred_pre"`
	// 예상 체결가 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ExpFluRt string `json:"exp_flu_rt"`
	// 예상 체결 수량(누적) (20자)
	ExpAccTrdeQty string `json:"exp_acc_trde_qty"`
	// 예상 체결 수량 (20자)
	ExpCntrTrdeQty string `json:"exp_cntr_trde_qty"`
	// 예상 체결 시간 (20자, HHmmss)
	ExpTm string `json:"exp_tm"`
	// 예상 체결가 전일대비기호 (20자)
	ExpPreSig string `json:"exp_pre_sig"`
	// 거래소 구분
	StexTp string `json:"stex_tp"`
}

// GetDomesticGoldSpotExpectedExecution 는 금현물예상체결(ka50087) 이다.
//
// 메뉴: 국내주식 > 시세 > 금현물예상체결(ka50087)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticGoldSpotExpectedExecution(ctx context.Context, req GetDomesticGoldSpotExpectedExecutionRequest, opts ...transport.Option) (*GetDomesticGoldSpotExpectedExecutionResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotExpectedExecutionResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50087",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
