// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticIntradayInvestorTradeRequest 는 장중투자자별매매요청(ka10063) 요청이다.
type GetDomesticIntradayInvestorTradeRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 금액수량구분 (필수, 1자, 1: 금액&수량)
	AmtQtyTp string `json:"amt_qty_tp"`
	// 투자자별 (필수, 1자, 6:외국인, 7:기관계, 1:투신, 0:보험, 2:은행, 3:연기금, 4:국가, 5:기타법인)
	Invsr string `json:"invsr"`
	// 외국계전체 (필수, 1자, 1:체크, 0:미체크)
	FrgnAll string `json:"frgn_all"`
	// 동시순매수구분 (필수, 1자, 1:체크, 0:미체크)
	SmtmNetprpsTp string `json:"smtm_netprps_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticIntradayInvestorTradeResponse 는 장중투자자별매매요청(ka10063) 응답이다.
type GetDomesticIntradayInvestorTradeResponse struct {
	// 장중투자자별매매
	OpmrInvsrTrde []GetDomesticIntradayInvestorTradeOpmrInvsrTrdeItem `json:"opmr_invsr_trde"`
}

// GetDomesticIntradayInvestorTradeOpmrInvsrTrdeItem 는 OpmrInvsrTrde 의 원소다.
type GetDomesticIntradayInvestorTradeOpmrInvsrTrdeItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 순매수금액 (20자, 단위: 백만원)
	NetprpsAmt string `json:"netprps_amt"`
	// 이전순매수금액 (20자, 단위: 백만원)
	PrevNetprpsAmt string `json:"prev_netprps_amt"`
	// 매수금액 (20자, 단위: 백만원)
	BuyAmt string `json:"buy_amt"`
	// 순매수금액증감 (20자, 단위: 백만원)
	NetprpsAmtIrds string `json:"netprps_amt_irds"`
	// 매수금액증감 (20자, 단위: 백만원)
	BuyAmtIrds string `json:"buy_amt_irds"`
	// 매도금액 (20자, 단위: 백만원)
	SellAmt string `json:"sell_amt"`
	// 매도금액증감 (20자, 단위: 백만원)
	SellAmtIrds string `json:"sell_amt_irds"`
	// 순매수수량 (20자, 단위: 1주)
	NetprpsQty string `json:"netprps_qty"`
	// 이전시점순매수수량 (20자, 단위: 1주)
	PrevPotNetprpsQty string `json:"prev_pot_netprps_qty"`
	// 순매수증감 (20자, 단위: 1주)
	NetprpsIrds string `json:"netprps_irds"`
	// 매수수량 (20자, 단위: 1주)
	BuyQty string `json:"buy_qty"`
	// 매수수량증감 (20자, 단위: 1주)
	BuyQtyIrds string `json:"buy_qty_irds"`
	// 매도수량 (20자, 단위: 1주)
	SellQty string `json:"sell_qty"`
	// 매도수량증감 (20자, 단위: 1주)
	SellQtyIrds string `json:"sell_qty_irds"`
}

// GetDomesticIntradayInvestorTrade 는 장중투자자별매매요청(ka10063) 이다.
//
// 메뉴: 국내주식 > 시세 > 장중투자자별매매요청(ka10063)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticIntradayInvestorTrade(ctx context.Context, req GetDomesticIntradayInvestorTradeRequest, opts ...transport.Option) (*GetDomesticIntradayInvestorTradeResponse, transport.Meta, error) {
	var out GetDomesticIntradayInvestorTradeResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10063",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
