// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockOhlcvByPeriodRequest 는 주식일주월시분요청(ka10005) 요청이다.
type GetDomesticStockOhlcvByPeriodRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockOhlcvByPeriodResponse 는 주식일주월시분요청(ka10005) 응답이다.
type GetDomesticStockOhlcvByPeriodResponse struct {
	// 주식일주월시분
	StkDdwkmm []GetDomesticStockOhlcvByPeriodStkDdwkmmItem `json:"stk_ddwkmm"`
}

// GetDomesticStockOhlcvByPeriodStkDdwkmmItem 는 StkDdwkmm 의 원소다.
type GetDomesticStockOhlcvByPeriodStkDdwkmmItem struct {
	// 날짜 (20자, YYYYMMDD)
	Date string `json:"date"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 대비 (20자, 단위: 원, 부호가 포함된 숫자)
	Pre string `json:"pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 외인보유 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForPoss string `json:"for_poss"`
	// 외인비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ForWght string `json:"for_wght"`
	// 외인순매수 (20자)
	ForNetprps string `json:"for_netprps"`
	// 기관순매수 (20자)
	OrgnNetprps string `json:"orgn_netprps"`
	// 개인순매수 (20자)
	IndNetprps string `json:"ind_netprps"`
	// 외국계 (20자, 단위: 1주, 부호가 포함된 숫자)
	Frgn string `json:"frgn"`
	// 신용잔고율 (20자)
	CrdRemnRt string `json:"crd_remn_rt"`
	// 프로그램 (20자, 단위: 1주, 부호가 포함된 숫자)
	Prm string `json:"prm"`
}

// GetDomesticStockOhlcvByPeriod 는 주식일주월시분요청(ka10005) 이다.
//
// 메뉴: 국내주식 > 시세 > 주식일주월시분요청(ka10005)
// URL:  /api/dostk/mrkcond
func (c *Client) GetDomesticStockOhlcvByPeriod(ctx context.Context, req GetDomesticStockOhlcvByPeriodRequest, opts ...transport.Option) (*GetDomesticStockOhlcvByPeriodResponse, transport.Meta, error) {
	var out GetDomesticStockOhlcvByPeriodResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10005",
		Path:  "/api/dostk/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
