// Code generated by tools/gen. DO NOT EDIT.

package exchange

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasExchangeRateRequest 는 환율 조회(ust31301) 요청이다.
type GetOverseasExchangeRateRequest struct {
	// 환전구분 (필수, 1자, 1:원화(KRW)->달러(USD), 2:달러(USD)->원화(KRW))
	ExchTp string `json:"exch_tp"`
}

// GetOverseasExchangeRateResponse 는 환율 조회(ust31301) 응답이다.
type GetOverseasExchangeRateResponse struct {
	// 매도적용환율 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	SellAplcExrt string `json:"sell_aplc_exrt"`
	// 매수적용환율 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyAplcExrt string `json:"buy_aplc_exrt"`
	// 적용환율 (12자, 실제 환전에 적용되는 환율입니다. 다만, 환전시점 시 환율 변동으로 인해 조회 환율과 적용 환율이 다를 수 있으며 환전 신청 전 꼭 환율을 확인해주시기 바랍니다)
	AplcExrt string `json:"aplc_exrt"`
	// 환율구분명 (40자)
	ExrtTpNm string `json:"exrt_tp_nm"`
	// 우대율 적용 전 환율 (12자, 환율 우대율을 적용하기 전 환율 입니다. 실제 환전은 aplc_exrt (적용환율)로 진행됩니다)
	SpclBfExrt string `json:"spcl_bf_exrt"`
	// 환율우대율 (12자)
	ExrtSpclRt string `json:"exrt_spcl_rt"`
}

// GetOverseasExchangeRate 는 환율 조회(ust31301) 이다.
//
// 메뉴: 미국주식 > 환전 > 환율 조회(ust31301)
// URL:  /api/us/exchange
func (c *Client) GetOverseasExchangeRate(ctx context.Context, req GetOverseasExchangeRateRequest, opts ...transport.Option) (*GetOverseasExchangeRateResponse, transport.Meta, error) {
	var out GetOverseasExchangeRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust31301",
		Path:  "/api/us/exchange",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
