// Code generated by tools/gen. DO NOT EDIT.

package exchange

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasExchangeEstimateRequest 는 환전 예상 금액 조회(ust31300) 요청이다.
type GetOverseasExchangeEstimateRequest struct {
	// 환전구분 (필수, 1자, 1:원화(KRW)->달러(USD), 2:달러(USD)->원화(KRW))
	ExchTp string `json:"exch_tp"`
	// 매도통화기준 환전금액 (12자, (EXCH_TP = 1 인 경우, 매도통화는 KRW 이며, 입력한 금액의 원화를 달러로 환전합니다) (EXCH_TP = 2 인 경우, 매도통화: USD이며, 입력한 금액의 달러를 원화로 환전합니다.))
	FcExmnAmt string `json:"fc_exmn_amt"`
}

// GetOverseasExchangeEstimateResponse 는 환전 예상 금액 조회(ust31300) 응답이다.
type GetOverseasExchangeEstimateResponse struct {
	// 매도적용환율 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	SellAplcExrt string `json:"sell_aplc_exrt"`
	// 매수적용환율 (12자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyAplcExrt string `json:"buy_aplc_exrt"`
	// 적용환율 (12자, 소수점 여섯째 자리까지 포맷된 숫자)
	AplcExrt string `json:"aplc_exrt"`
	// 매도통화예수금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	SellCrncEntraNowrm string `json:"sell_crnc_entra_nowrm"`
	// 매도통화현금미수금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	SellCrncChUnclaNowrm string `json:"sell_crnc_ch_uncla_nowrm"`
	// 매도통화기타대여금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	SellCrncEtcLoanaNowrm string `json:"sell_crnc_etc_loana_nowrm"`
	// 매도통화환전가능금액 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	SellCrncExmnAlowAmt string `json:"sell_crnc_exmn_alow_amt"`
	// 매수통화예수금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyCrncEntraNowrm string `json:"buy_crnc_entra_nowrm"`
	// 매수통화현금미수금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyCrncChUnclaNowrm string `json:"buy_crnc_ch_uncla_nowrm"`
	// 매수통화기타대여금금잔 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyCrncEtcLoanaNowrm string `json:"buy_crnc_etc_loana_nowrm"`
	// 매수통화환전가능금액 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyCrncExmnAlowAmt string `json:"buy_crnc_exmn_alow_amt"`
	// 원화미수금액 (15자, 단위: 원, 좌측 0-padding 처리된 15자리 숫자)
	KrwUnclAmt string `json:"krw_uncl_amt"`
	// 매도예상금액 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	SellExpcAmt string `json:"sell_expc_amt"`
	// 매수예상금액 (17자, 소수점 둘째 자리까지 포맷된 숫자)
	BuyExpcAmt string `json:"buy_expc_amt"`
}

// GetOverseasExchangeEstimate 는 환전 예상 금액 조회(ust31300) 이다.
//
// 메뉴: 미국주식 > 환전 > 환전 예상 금액 조회(ust31300)
// URL:  /api/us/exchange
func (c *Client) GetOverseasExchangeEstimate(ctx context.Context, req GetOverseasExchangeEstimateRequest, opts ...transport.Option) (*GetOverseasExchangeEstimateResponse, transport.Meta, error) {
	var out GetOverseasExchangeEstimateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust31300",
		Path:  "/api/us/exchange",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
