// Code generated by tools/gen. DO NOT EDIT.

package exchange

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// RequestOverseasCurrencyExchangeRequest 는 환전 신청(ust31302) 요청이다.
type RequestOverseasCurrencyExchangeRequest struct {
	// 환전구분 (필수, 1자, 1:원화(KRW)->달러(USD), 2:달러(USD)->원화(KRW))
	ExchTp string `json:"exch_tp"`
	// 매도통화기준 환전금액 (필수, 12자, 매도통화기준 환전금액 (EXCH_TP = 1 인 경우, 매도통화는 KRW 이며, 입력한 금액의 원화를 달러로 환전합니다) (EXCH_TP = 2 인 경우, 매도통화: USD이며, 입력한 금액의 달러를 원화로 환전합니다.))
	FcExmnAmt string `json:"fc_exmn_amt"`
}

// RequestOverseasCurrencyExchangeResponse 는 환전 신청(ust31302) 응답이다.
type RequestOverseasCurrencyExchangeResponse struct {
	// 매도적용환율 (12자)
	SellAplcExrt string `json:"sell_aplc_exrt"`
	// 매수적용환율 (12자)
	BuyAplcExrt string `json:"buy_aplc_exrt"`
	// 적용환율 (12자)
	AplcExrt string `json:"aplc_exrt"`
	// 예수금전잔 (15자)
	EntraPrerm string `json:"entra_prerm"`
	// 현금미수금전잔 (15자)
	ChUnclaPrerm string `json:"ch_uncla_prerm"`
	// 기타대여금전잔 (15자)
	EtcLoanaPrerm string `json:"etc_loana_prerm"`
	// 예수금금잔 (15자)
	EntraNowrm string `json:"entra_nowrm"`
	// 현금미수금금잔 (15자)
	ChUnclaNowrm string `json:"ch_uncla_nowrm"`
	// 기타대여금금잔 (15자)
	EtcLoanaNowrm string `json:"etc_loana_nowrm"`
	// 원화환전가능금액 (15자)
	KrwExmnAlowAmt string `json:"krw_exmn_alow_amt"`
	// 현금미수변제금 (15자)
	ChUnclRpymAmt string `json:"ch_uncl_rpym_amt"`
	// 현금미수연체료 (15자)
	ChUnclDlfe string `json:"ch_uncl_dlfe"`
	// 기타대여미납변제금 (15자)
	EtcLoanNpayRpymAmt string `json:"etc_loan_npay_rpym_amt"`
	// 기타대여미납연체료 (15자)
	EtcLoanNpayDlfe string `json:"etc_loan_npay_dlfe"`
	// 외화예수금전잔 (12자)
	FcEntraPrerm string `json:"fc_entra_prerm"`
	// 외화현금미수금전잔 (12자)
	FcChUnclaPrerm string `json:"fc_ch_uncla_prerm"`
	// 외화기타대여금전잔 (12자)
	FcEtcLoanaPrerm string `json:"fc_etc_loana_prerm"`
	// 외화예수금금잔 (12자)
	FcEntraNowrm string `json:"fc_entra_nowrm"`
	// 외화현금미수금금잔 (12자)
	FcChUnclaNowrm string `json:"fc_ch_uncla_nowrm"`
	// 외화기타대여금금잔 (12자)
	FcEtcLoanaNowrm string `json:"fc_etc_loana_nowrm"`
	// 외화환전가능금액 (12자)
	FcExmnAlowAmt string `json:"fc_exmn_alow_amt"`
	// 외화현금미수변제금 (12자)
	FcChUnclRpymAmt string `json:"fc_ch_uncl_rpym_amt"`
	// 외화현금미수연체료 (12자)
	FcChUnclDlfe string `json:"fc_ch_uncl_dlfe"`
	// 외화기타대여미납변제금 (12자)
	FcEtcLoanNpayRpymAmt string `json:"fc_etc_loan_npay_rpym_amt"`
	// 외화기타대여미납연체료 (12자)
	FcEtcLoanNpayDlfe string `json:"fc_etc_loan_npay_dlfe"`
	// 원화환전금액 (15자)
	KrwExmnAmt string `json:"krw_exmn_amt"`
	// 매도외화금액 (17자)
	SellFcAmt string `json:"sell_fc_amt"`
	// 매수외화금액 (17자)
	BuyFcAmt string `json:"buy_fc_amt"`
}

// RequestOverseasCurrencyExchange 는 환전 신청(ust31302) 이다.
//
// 메뉴: 미국주식 > 환전 > 환전 신청(ust31302)
// URL:  /api/us/exchange
func (c *Client) RequestOverseasCurrencyExchange(ctx context.Context, req RequestOverseasCurrencyExchangeRequest, opts ...transport.Option) (*RequestOverseasCurrencyExchangeResponse, transport.Meta, error) {
	var out RequestOverseasCurrencyExchangeResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust31302",
		Path:  "/api/us/exchange",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
