// Code generated by tools/gen. DO NOT EDIT.

package creditorder

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// CancelDomesticCreditStockOrderRequest 는 신용 취소주문(kt10009) 요청이다.
type CancelDomesticCreditStockOrderRequest struct {
	// 국내거래소구분 (필수, 3자, KRX,NXT,SOR)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 원주문번호 (필수, 7자, 매수/매도 주문 요청 응답 결과로 받은 7자리 주문번호)
	OrigOrdNo string `json:"orig_ord_no"`
	// 종목코드 (필수, 12자)
	StkCd string `json:"stk_cd"`
	// 취소수량 (필수, 12자, 단위: 1주, '0' 입력시 잔량 전부 취소)
	CnclQty string `json:"cncl_qty"`
}

// CancelDomesticCreditStockOrderResponse 는 신용 취소주문(kt10009) 응답이다.
type CancelDomesticCreditStockOrderResponse struct {
	// 주문번호 (7자, 새 주문번호)
	OrdNo string `json:"ord_no"`
	// 모주문번호 (7자, 원 주문번호)
	BaseOrigOrdNo string `json:"base_orig_ord_no"`
	// 취소수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CnclQty string `json:"cncl_qty"`
}

// CancelDomesticCreditStockOrder 는 신용 취소주문(kt10009) 이다.
//
// 메뉴: 국내주식 > 신용주문 > 신용 취소주문(kt10009)
// URL:  /api/dostk/crdordr
func (c *Client) CancelDomesticCreditStockOrder(ctx context.Context, req CancelDomesticCreditStockOrderRequest, opts ...transport.Option) (*CancelDomesticCreditStockOrderResponse, transport.Meta, error) {
	var out CancelDomesticCreditStockOrderResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt10009",
		Path:  "/api/dostk/crdordr",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
