// Code generated by tools/gen. DO NOT EDIT.

package creditorder

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// ModifyDomesticCreditStockOrderRequest 는 신용 정정주문(kt10008) 요청이다.
type ModifyDomesticCreditStockOrderRequest struct {
	// 국내거래소구분 (필수, 3자, KRX,NXT,SOR)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 원주문번호 (필수, 7자, 매수/매도 주문 요청 응답 결과로 받은 7자리 주문번호)
	OrigOrdNo string `json:"orig_ord_no"`
	// 종목코드 (필수, 12자)
	StkCd string `json:"stk_cd"`
	// 정정수량 (필수, 12자, 단위: 1주, '0' 입력시 잔량 전부 정정)
	MdfyQty string `json:"mdfy_qty"`
	// 정정단가 (필수, 12자, 단위: 원)
	MdfyUv string `json:"mdfy_uv"`
	// 정정조건단가 (12자, 단위: 원)
	MdfyCondUv string `json:"mdfy_cond_uv"`
}

// ModifyDomesticCreditStockOrderResponse 는 신용 정정주문(kt10008) 응답이다.
type ModifyDomesticCreditStockOrderResponse struct {
	// 주문번호 (7자, 새 주문번호)
	OrdNo string `json:"ord_no"`
	// 모주문번호 (7자, 원 주문번호)
	BaseOrigOrdNo string `json:"base_orig_ord_no"`
	// 정정수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	MdfyQty string `json:"mdfy_qty"`
	// 국내거래소구분 (6자, KRX, NXT, SOR)
	DmstStexTp string `json:"dmst_stex_tp"`
}

// ModifyDomesticCreditStockOrder 는 신용 정정주문(kt10008) 이다.
//
// 메뉴: 국내주식 > 신용주문 > 신용 정정주문(kt10008)
// URL:  /api/dostk/crdordr
func (c *Client) ModifyDomesticCreditStockOrder(ctx context.Context, req ModifyDomesticCreditStockOrderRequest, opts ...transport.Option) (*ModifyDomesticCreditStockOrderResponse, transport.Meta, error) {
	var out ModifyDomesticCreditStockOrderResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt10008",
		Path:  "/api/dostk/crdordr",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
