// Code generated by tools/gen. DO NOT EDIT.

package stocklending

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockLendingTop10StocksRequest 는 대차거래상위10종목요청(ka10069) 요청이다.
type GetDomesticStockLendingTop10StocksRequest struct {
	// 시작일자 (필수, 8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	EndDt string `json:"end_dt"`
	// 시장구분 (필수, 3자, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
}

// GetDomesticStockLendingTop10StocksResponse 는 대차거래상위10종목요청(ka10069) 응답이다.
type GetDomesticStockLendingTop10StocksResponse struct {
	// 대차거래체결주수합 (단위: 1주)
	DbrtTrdeCntrcntSum string `json:"dbrt_trde_cntrcnt_sum"`
	// 대차거래상환주수합 (단위: 1주)
	DbrtTrdeRpySum string `json:"dbrt_trde_rpy_sum"`
	// 잔고주수합 (단위: 1주)
	RmndSum string `json:"rmnd_sum"`
	// 잔고금액합 (단위: 백만원)
	RemnAmtSum string `json:"remn_amt_sum"`
	// 대차거래체결주수비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58%를 의미합니다.)
	DbrtTrdeCntrcntRt string `json:"dbrt_trde_cntrcnt_rt"`
	// 대차거래상환주수비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58%를 의미합니다.)
	DbrtTrdeRpyRt string `json:"dbrt_trde_rpy_rt"`
	// 잔고주수비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58%를 의미합니다.)
	RmndRt string `json:"rmnd_rt"`
	// 잔고금액비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58%를 의미합니다.)
	RemnAmtRt string `json:"remn_amt_rt"`
	// 대차거래상위10종목
	DbrtTrdeUpper10stk []GetDomesticStockLendingTop10StocksDbrtTrdeUpper10stkItem `json:"dbrt_trde_upper_10stk"`
}

// GetDomesticStockLendingTop10StocksDbrtTrdeUpper10stkItem 는 DbrtTrdeUpper10stk 의 원소다.
type GetDomesticStockLendingTop10StocksDbrtTrdeUpper10stkItem struct {
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 대차거래체결주수 (20자, 단위: 1주)
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	// 대차거래상환주수 (20자, 단위: 1주)
	DbrtTrdeRpy string `json:"dbrt_trde_rpy"`
	// 잔고주수 (20자, 단위: 1주)
	Rmnd string `json:"rmnd"`
	// 잔고금액 (20자, 단위: 백만원)
	RemnAmt string `json:"remn_amt"`
}

// GetDomesticStockLendingTop10Stocks 는 대차거래상위10종목요청(ka10069) 이다.
//
// 메뉴: 국내주식 > 대차거래 > 대차거래상위10종목요청(ka10069)
// URL:  /api/dostk/slb
func (c *Client) GetDomesticStockLendingTop10Stocks(ctx context.Context, req GetDomesticStockLendingTop10StocksRequest, opts ...transport.Option) (*GetDomesticStockLendingTop10StocksResponse, transport.Meta, error) {
	var out GetDomesticStockLendingTop10StocksResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10069",
		Path:  "/api/dostk/slb",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
