// Code generated by tools/gen. DO NOT EDIT.

package stocklending

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockLendingTradeTrendRequest 는 대차거래추이요청(ka10068) 요청이다.
type GetDomesticStockLendingTradeTrendRequest struct {
	// 시작일자 (8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 전체구분 (필수, 6자, 1: 전체표시)
	AllTp string `json:"all_tp"`
}

// GetDomesticStockLendingTradeTrendResponse 는 대차거래추이요청(ka10068) 응답이다.
type GetDomesticStockLendingTradeTrendResponse struct {
	// 대차거래추이
	DbrtTrdeTrnsn []GetDomesticStockLendingTradeTrendDbrtTrdeTrnsnItem `json:"dbrt_trde_trnsn"`
}

// GetDomesticStockLendingTradeTrendDbrtTrdeTrnsnItem 는 DbrtTrdeTrnsn 의 원소다.
type GetDomesticStockLendingTradeTrendDbrtTrdeTrnsnItem struct {
	// 일자 (8자, YYYYMMDD)
	Dt string `json:"dt"`
	// 대차거래체결주수 (12자, 단위: 1주)
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	// 대차거래상환주수 (18자, 단위: 1주)
	DbrtTrdeRpy string `json:"dbrt_trde_rpy"`
	// 대차거래증감 (60자, 단위: 1주)
	DbrtTrdeIrds string `json:"dbrt_trde_irds"`
	// 잔고주수 (18자, 단위: 1주)
	Rmnd string `json:"rmnd"`
	// 잔고금액 (18자, 단위: 백만원)
	RemnAmt string `json:"remn_amt"`
}

// GetDomesticStockLendingTradeTrend 는 대차거래추이요청(ka10068) 이다.
//
// 메뉴: 국내주식 > 대차거래 > 대차거래추이요청(ka10068)
// URL:  /api/dostk/slb
func (c *Client) GetDomesticStockLendingTradeTrend(ctx context.Context, req GetDomesticStockLendingTradeTrendRequest, opts ...transport.Option) (*GetDomesticStockLendingTradeTrendResponse, transport.Meta, error) {
	var out GetDomesticStockLendingTradeTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10068",
		Path:  "/api/dostk/slb",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
