// Code generated by tools/gen. DO NOT EDIT.

package stocklending

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockLendingTradeTrendByStockRequest 는 대차거래추이요청(종목별)(ka20068) 요청이다.
type GetDomesticStockLendingTradeTrendByStockRequest struct {
	// 시작일자 (8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 전체구분 (1자, 0:종목코드 입력종목만 표시)
	AllTp string `json:"all_tp"`
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticStockLendingTradeTrendByStockResponse 는 대차거래추이요청(종목별)(ka20068) 응답이다.
type GetDomesticStockLendingTradeTrendByStockResponse struct {
	// 대차거래추이
	DbrtTrdeTrnsn []GetDomesticStockLendingTradeTrendByStockDbrtTrdeTrnsnItem `json:"dbrt_trde_trnsn"`
}

// GetDomesticStockLendingTradeTrendByStockDbrtTrdeTrnsnItem 는 DbrtTrdeTrnsn 의 원소다.
type GetDomesticStockLendingTradeTrendByStockDbrtTrdeTrnsnItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 대차거래체결주수 (20자, 단위: 1주)
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	// 대차거래상환주수 (20자, 단위: 1주)
	DbrtTrdeRpy string `json:"dbrt_trde_rpy"`
	// 대차거래증감 (20자, 단위: 1주)
	DbrtTrdeIrds string `json:"dbrt_trde_irds"`
	// 잔고주수 (20자, 단위: 1주)
	Rmnd string `json:"rmnd"`
	// 잔고금액 (20자, 단위: 백만원)
	RemnAmt string `json:"remn_amt"`
}

// GetDomesticStockLendingTradeTrendByStock 는 대차거래추이요청(종목별)(ka20068) 이다.
//
// 메뉴: 국내주식 > 대차거래 > 대차거래추이요청(종목별)(ka20068)
// URL:  /api/dostk/slb
func (c *Client) GetDomesticStockLendingTradeTrendByStock(ctx context.Context, req GetDomesticStockLendingTradeTrendByStockRequest, opts ...transport.Option) (*GetDomesticStockLendingTradeTrendByStockResponse, transport.Meta, error) {
	var out GetDomesticStockLendingTradeTrendByStockResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20068",
		Path:  "/api/dostk/slb",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
