// Code generated by tools/gen. DO NOT EDIT.

package stocklending

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockLendingTradeHistoryRequest 는 대차거래내역요청(ka90012) 요청이다.
type GetDomesticStockLendingTradeHistoryRequest struct {
	// 일자 (필수, 8자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시장구분 (필수, 3자, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
}

// GetDomesticStockLendingTradeHistoryResponse 는 대차거래내역요청(ka90012) 응답이다.
type GetDomesticStockLendingTradeHistoryResponse struct {
	// 대차거래내역
	DbrtTrdePrps []GetDomesticStockLendingTradeHistoryDbrtTrdePrpsItem `json:"dbrt_trde_prps"`
}

// GetDomesticStockLendingTradeHistoryDbrtTrdePrpsItem 는 DbrtTrdePrps 의 원소다.
type GetDomesticStockLendingTradeHistoryDbrtTrdePrpsItem struct {
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 대차거래체결주수 (20자, 단위: 1주)
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	// 대차거래상환주수 (20자, 단위: 1주)
	DbrtTrdeRpy string `json:"dbrt_trde_rpy"`
	// 잔고주수 (20자, 단위: 1주)
	Rmnd string `json:"rmnd"`
	// 잔고금액 (20자, 단위: 백만원)
	RemnAmt string `json:"remn_amt"`
}

// GetDomesticStockLendingTradeHistory 는 대차거래내역요청(ka90012) 이다.
//
// 메뉴: 국내주식 > 대차거래 > 대차거래내역요청(ka90012)
// URL:  /api/dostk/slb
func (c *Client) GetDomesticStockLendingTradeHistory(ctx context.Context, req GetDomesticStockLendingTradeHistoryRequest, opts ...transport.Option) (*GetDomesticStockLendingTradeHistoryResponse, transport.Meta, error) {
	var out GetDomesticStockLendingTradeHistoryResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka90012",
		Path:  "/api/dostk/slb",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
