// Code generated by tools/gen. DO NOT EDIT.

package order

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// BuyDomesticGoldSpotRequest 는 금현물 매수주문(kt50000) 요청이다.
type BuyDomesticGoldSpotRequest struct {
	// 종목코드 (필수, 12자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
	// 주문수량 (필수, 12자, 단위: 1주)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (12자, 단위: 원)
	OrdUv string `json:"ord_uv"`
	// 매매구분 (필수, 2자, 00:보통, 10:보통(IOC), 20:보통(FOK))
	TrdeTp string `json:"trde_tp"`
}

// BuyDomesticGoldSpotResponse 는 금현물 매수주문(kt50000) 응답이다.
type BuyDomesticGoldSpotResponse struct {
	// 주문번호 (7자, 7자리 주문번호)
	OrdNo string `json:"ord_no"`
}

// BuyDomesticGoldSpot 는 금현물 매수주문(kt50000) 이다.
//
// 메뉴: 국내주식 > 주문 > 금현물 매수주문(kt50000)
// URL:  /api/dostk/ordr
func (c *Client) BuyDomesticGoldSpot(ctx context.Context, req BuyDomesticGoldSpotRequest, opts ...transport.Option) (*BuyDomesticGoldSpotResponse, transport.Meta, error) {
	var out BuyDomesticGoldSpotResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt50000",
		Path:  "/api/dostk/ordr",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
