// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAllSectorIndicesRequest 는 전업종지수요청(ka20003) 요청이다.
type GetDomesticAllSectorIndicesRequest struct {
	// 업종코드 (필수, 3자, 001:종합(KOSPI), 101:종합(KOSDAQ))
	IndsCd string `json:"inds_cd"`
}

// GetDomesticAllSectorIndicesResponse 는 전업종지수요청(ka20003) 응답이다.
type GetDomesticAllSectorIndicesResponse struct {
	// 전업종지수
	AllIndsIdex []GetDomesticAllSectorIndicesAllIndsIdexItem `json:"all_inds_idex"`
}

// GetDomesticAllSectorIndicesAllIndsIdexItem 는 AllIndsIdex 의 원소다.
type GetDomesticAllSectorIndicesAllIndsIdexItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 지수, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 지수, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1000주)
	TrdeQty string `json:"trde_qty"`
	// 비중 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Wght string `json:"wght"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 상한 (20자, 단위: 종목수)
	Upl string `json:"upl"`
	// 상승 (20자, 단위: 종목수)
	Rising string `json:"rising"`
	// 보합 (20자, 단위: 종목수)
	Stdns string `json:"stdns"`
	// 하락 (20자, 단위: 종목수)
	Fall string `json:"fall"`
	// 하한 (20자, 단위: 종목수)
	Lst string `json:"lst"`
	// 상장종목수 (20자, 단위: 종목수)
	FloStkNum string `json:"flo_stk_num"`
}

// GetDomesticAllSectorIndices 는 전업종지수요청(ka20003) 이다.
//
// 메뉴: 국내주식 > 업종 > 전업종지수요청(ka20003)
// URL:  /api/dostk/sect
func (c *Client) GetDomesticAllSectorIndices(ctx context.Context, req GetDomesticAllSectorIndicesRequest, opts ...transport.Option) (*GetDomesticAllSectorIndicesResponse, transport.Meta, error) {
	var out GetDomesticAllSectorIndicesResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20003",
		Path:  "/api/dostk/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
