// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorStockPriceRequest 는 업종별주가요청(ka20002) 요청이다.
type GetDomesticSectorStockPriceRequest struct {
	// 시장구분 (필수, 1자, 0:코스피, 1:코스닥, 2:코스피200)
	MrktTp string `json:"mrkt_tp"`
	// 업종코드 (필수, 3자, 001:종합(KOSPI), 002:대형주, 003:중형주, 004:소형주 101:종합(KOSDAQ), 201:KOSPI200, 302:KOSTAR, 701: KRX100 나머지 ※ 업종코드 참고)
	IndsCd string `json:"inds_cd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticSectorStockPriceResponse 는 업종별주가요청(ka20002) 응답이다.
type GetDomesticSectorStockPriceResponse struct {
	// 업종별주가
	IndsStkpc []GetDomesticSectorStockPriceIndsStkpcItem `json:"inds_stkpc"`
}

// GetDomesticSectorStockPriceIndsStkpcItem 는 IndsStkpc 의 원소다.
type GetDomesticSectorStockPriceIndsStkpcItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
	// 시가 (20자, 단위: 원, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
}

// GetDomesticSectorStockPrice 는 업종별주가요청(ka20002) 이다.
//
// 메뉴: 국내주식 > 업종 > 업종별주가요청(ka20002)
// URL:  /api/dostk/sect
func (c *Client) GetDomesticSectorStockPrice(ctx context.Context, req GetDomesticSectorStockPriceRequest, opts ...transport.Option) (*GetDomesticSectorStockPriceResponse, transport.Meta, error) {
	var out GetDomesticSectorStockPriceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20002",
		Path:  "/api/dostk/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
