// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorPriceRequest 는 업종현재가요청(ka20001) 요청이다.
type GetDomesticSectorPriceRequest struct {
	// 시장구분 (필수, 1자, 0:코스피, 1:코스닥, 2:코스피200)
	MrktTp string `json:"mrkt_tp"`
	// 업종코드 (필수, 3자, 001:종합(KOSPI), 002:대형주, 003:중형주, 004:소형주 101:종합(KOSDAQ), 201:KOSPI200, 302:KOSTAR, 701: KRX100 나머지 ※ 업종코드 참고)
	IndsCd string `json:"inds_cd"`
}

// GetDomesticSectorPriceResponse 는 업종현재가요청(ka20001) 응답이다.
type GetDomesticSectorPriceResponse struct {
	// 현재가 (20자, 단위: 지수, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 지수, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1000주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 거래형성종목수 (20자, 단위: 종목수)
	TrdeFrmatnStkNum string `json:"trde_frmatn_stk_num"`
	// 거래형성비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeFrmatnRt string `json:"trde_frmatn_rt"`
	// 시가 (20자, 단위: 지수, 부호가 포함된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 지수, 부호가 포함된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 지수, 부호가 포함된 숫자)
	LowPric string `json:"low_pric"`
	// 상한 (20자, 단위: 종목수)
	Upl string `json:"upl"`
	// 상승 (20자, 단위: 종목수)
	Rising string `json:"rising"`
	// 보합 (20자, 단위: 종목수)
	Stdns string `json:"stdns"`
	// 하락 (20자, 단위: 종목수)
	Fall string `json:"fall"`
	// 하한 (20자, 단위: 종목수)
	Lst string `json:"lst"`
	// 52주최고가 (20자, 단위: 지수, 부호가 포함된 숫자)
	N52wkHgstPric string `json:"52wk_hgst_pric"`
	// 52주최고가일 (20자, YYYYMMDD)
	N52wkHgstPricDt string `json:"52wk_hgst_pric_dt"`
	// 52주최고가대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N52wkHgstPricPreRt string `json:"52wk_hgst_pric_pre_rt"`
	// 52주최저가 (20자, 단위: 지수, 부호가 포함된 숫자)
	N52wkLwstPric string `json:"52wk_lwst_pric"`
	// 52주최저가일 (20자, YYYYMMDD)
	N52wkLwstPricDt string `json:"52wk_lwst_pric_dt"`
	// 52주최저가대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N52wkLwstPricPreRt string `json:"52wk_lwst_pric_pre_rt"`
	// 업종현재가_시간별
	IndsCurPrcTm []GetDomesticSectorPriceIndsCurPrcTmItem `json:"inds_cur_prc_tm"`
}

// GetDomesticSectorPriceIndsCurPrcTmItem 는 IndsCurPrcTm 의 원소다.
type GetDomesticSectorPriceIndsCurPrcTmItem struct {
	// 시간n (20자, HHmmss)
	TmN string `json:"tm_n"`
	// 현재가n (20자, 단위: 지수, 부호가 포함된 숫자)
	CurPrcN string `json:"cur_prc_n"`
	// 전일대비기호n (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSigN string `json:"pred_pre_sig_n"`
	// 전일대비n (20자, 단위: 지수, 부호가 포함된 숫자)
	PredPreN string `json:"pred_pre_n"`
	// 등락률n (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRtN string `json:"flu_rt_n"`
	// 거래량n (20자, 단위: 1000주)
	TrdeQtyN string `json:"trde_qty_n"`
	// 누적거래량n (20자, 단위: 1000주)
	AccTrdeQtyN string `json:"acc_trde_qty_n"`
}

// GetDomesticSectorPrice 는 업종현재가요청(ka20001) 이다.
//
// 메뉴: 국내주식 > 업종 > 업종현재가요청(ka20001)
// URL:  /api/dostk/sect
func (c *Client) GetDomesticSectorPrice(ctx context.Context, req GetDomesticSectorPriceRequest, opts ...transport.Option) (*GetDomesticSectorPriceResponse, transport.Meta, error) {
	var out GetDomesticSectorPriceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20001",
		Path:  "/api/dostk/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
