// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorProgramRequest 는 업종프로그램요청(ka10010) 요청이다.
type GetDomesticSectorProgramRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticSectorProgramResponse 는 업종프로그램요청(ka10010) 응답이다.
type GetDomesticSectorProgramResponse struct {
	// 차익위탁매도수량 (20자)
	DfrtTrstSellQty string `json:"dfrt_trst_sell_qty"`
	// 차익위탁매도금액 (20자)
	DfrtTrstSellAmt string `json:"dfrt_trst_sell_amt"`
	// 차익위탁매수수량 (20자)
	DfrtTrstBuyQty string `json:"dfrt_trst_buy_qty"`
	// 차익위탁매수금액 (20자)
	DfrtTrstBuyAmt string `json:"dfrt_trst_buy_amt"`
	// 차익위탁순매수수량 (20자)
	DfrtTrstNetprpsQty string `json:"dfrt_trst_netprps_qty"`
	// 차익위탁순매수금액 (20자)
	DfrtTrstNetprpsAmt string `json:"dfrt_trst_netprps_amt"`
	// 비차익위탁매도수량 (20자)
	NdiffproTrstSellQty string `json:"ndiffpro_trst_sell_qty"`
	// 비차익위탁매도금액 (20자)
	NdiffproTrstSellAmt string `json:"ndiffpro_trst_sell_amt"`
	// 비차익위탁매수수량 (20자)
	NdiffproTrstBuyQty string `json:"ndiffpro_trst_buy_qty"`
	// 비차익위탁매수금액 (20자)
	NdiffproTrstBuyAmt string `json:"ndiffpro_trst_buy_amt"`
	// 비차익위탁순매수수량 (20자)
	NdiffproTrstNetprpsQty string `json:"ndiffpro_trst_netprps_qty"`
	// 비차익위탁순매수금액 (20자)
	NdiffproTrstNetprpsAmt string `json:"ndiffpro_trst_netprps_amt"`
	// 전체차익위탁매도수량 (20자)
	AllDfrtTrstSellQty string `json:"all_dfrt_trst_sell_qty"`
	// 전체차익위탁매도금액 (20자)
	AllDfrtTrstSellAmt string `json:"all_dfrt_trst_sell_amt"`
	// 전체차익위탁매수수량 (20자)
	AllDfrtTrstBuyQty string `json:"all_dfrt_trst_buy_qty"`
	// 전체차익위탁매수금액 (20자)
	AllDfrtTrstBuyAmt string `json:"all_dfrt_trst_buy_amt"`
	// 전체차익위탁순매수수량 (20자)
	AllDfrtTrstNetprpsQty string `json:"all_dfrt_trst_netprps_qty"`
	// 전체차익위탁순매수금액 (20자)
	AllDfrtTrstNetprpsAmt string `json:"all_dfrt_trst_netprps_amt"`
}

// GetDomesticSectorProgram 는 업종프로그램요청(ka10010) 이다.
//
// 메뉴: 국내주식 > 업종 > 업종프로그램요청(ka10010)
// URL:  /api/dostk/sect
func (c *Client) GetDomesticSectorProgram(ctx context.Context, req GetDomesticSectorProgramRequest, opts ...transport.Option) (*GetDomesticSectorProgramResponse, transport.Meta, error) {
	var out GetDomesticSectorProgramResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10010",
		Path:  "/api/dostk/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
