// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorInvestorNetBuyRequest 는 업종별투자자순매수요청(ka10051) 요청이다.
type GetDomesticSectorInvestorNetBuyRequest struct {
	// 시장구분 (필수, 1자, 코스피:0, 코스닥:1)
	MrktTp string `json:"mrkt_tp"`
	// 금액수량구분 (필수, 1자, 금액:0, 수량:1)
	AmtQtyTp string `json:"amt_qty_tp"`
	// 기준일자 (8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticSectorInvestorNetBuyResponse 는 업종별투자자순매수요청(ka10051) 응답이다.
type GetDomesticSectorInvestorNetBuyResponse struct {
	// 업종별순매수
	IndsNetprps []GetDomesticSectorInvestorNetBuyIndsNetprpsItem `json:"inds_netprps"`
}

// GetDomesticSectorInvestorNetBuyIndsNetprpsItem 는 IndsNetprps 의 원소다.
type GetDomesticSectorInvestorNetBuyIndsNetprpsItem struct {
	// 업종코드 (20자)
	IndsCd string `json:"inds_cd"`
	// 업종명 (20자)
	IndsNm string `json:"inds_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비부호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSmbol string `json:"pre_smbol"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 증권순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	ScNetprps string `json:"sc_netprps"`
	// 보험순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	InsrncNetprps string `json:"insrnc_netprps"`
	// 투신순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	InvtrtNetprps string `json:"invtrt_netprps"`
	// 은행순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	BankNetprps string `json:"bank_netprps"`
	// 종신금순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	JnsinkmNetprps string `json:"jnsinkm_netprps"`
	// 기금순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	EndwNetprps string `json:"endw_netprps"`
	// 기타법인순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	EtcCorpNetprps string `json:"etc_corp_netprps"`
	// 개인순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	IndNetprps string `json:"ind_netprps"`
	// 외국인순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	FrgnrNetprps string `json:"frgnr_netprps"`
	// 내국인대우외국인순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	NativeTrmtFrgnrNetprps string `json:"native_trmt_frgnr_netprps"`
	// 국가순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	NatnNetprps string `json:"natn_netprps"`
	// 사모펀드순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	SamoFundNetprps string `json:"samo_fund_netprps"`
	// 기관계순매수 (20자, 단위: 억원 혹은 1000주, 부호가 포함된 숫자)
	OrgnNetprps string `json:"orgn_netprps"`
}

// GetDomesticSectorInvestorNetBuy 는 업종별투자자순매수요청(ka10051) 이다.
//
// 메뉴: 국내주식 > 업종 > 업종별투자자순매수요청(ka10051)
// URL:  /api/dostk/sect
func (c *Client) GetDomesticSectorInvestorNetBuy(ctx context.Context, req GetDomesticSectorInvestorNetBuyRequest, opts ...transport.Option) (*GetDomesticSectorInvestorNetBuyResponse, transport.Meta, error) {
	var out GetDomesticSectorInvestorNetBuyResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10051",
		Path:  "/api/dostk/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
