// Code generated by tools/gen. DO NOT EDIT.

package watchlist

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasWatchlistGroupDetailRequest 는 미국주식 관심종목 그룹 상세 조회(usa20201) 요청이다.
type GetOverseasWatchlistGroupDetailRequest struct {
	// 그룹SEQ (3자, usa20200 응답 결과의 gcod값을 입력)
	ArnGrpID string `json:"arn_grp_id"`
}

// GetOverseasWatchlistGroupDetailResponse 는 미국주식 관심종목 그룹 상세 조회(usa20201) 응답이다.
type GetOverseasWatchlistGroupDetailResponse struct {
	// 처리 결과 (1자, S:성공 F:실패)
	Rtcd string `json:"rtcd"`
	// 종목 갯수
	Nofj []GetOverseasWatchlistGroupDetailNofjItem `json:"nofj"`
}

// GetOverseasWatchlistGroupDetailNofjItem 는 Nofj 의 원소다.
type GetOverseasWatchlistGroupDetailNofjItem struct {
	// 종목코드 (18자)
	Cod2 string `json:"cod2"`
	// 북마크 구분 (1자)
	Bgb string `json:"bgb"`
	// 북마크 컬러 (9자)
	BgbClr string `json:"bgb_clr"`
	// 거래소구분 (2자, ND:NASDAQ,NY:NYSE,NA:AMEX)
	StexTp string `json:"stex_tp"`
}

// GetOverseasWatchlistGroupDetail 는 미국주식 관심종목 그룹 상세 조회(usa20201) 이다.
//
// 메뉴: 미국주식 > 관심종목 > 미국주식 관심종목 그룹 상세 조회(usa20201)
// URL:  /api/us/watchlist
func (c *Client) GetOverseasWatchlistGroupDetail(ctx context.Context, req GetOverseasWatchlistGroupDetailRequest, opts ...transport.Option) (*GetOverseasWatchlistGroupDetailResponse, transport.Meta, error) {
	var out GetOverseasWatchlistGroupDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20201",
		Path:  "/api/us/watchlist",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
