// Code generated by tools/gen. DO NOT EDIT.

package watchlist

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasWatchlistGroupsRequest 는 미국주식 관심종목 그룹 리스트 조회(usa20200) 요청이다.
type GetOverseasWatchlistGroupsRequest struct {
}

// GetOverseasWatchlistGroupsResponse 는 미국주식 관심종목 그룹 리스트 조회(usa20200) 응답이다.
type GetOverseasWatchlistGroupsResponse struct {
	// 처리결과 (1자, S:성공 F:실패)
	Rtcd string `json:"rtcd"`
	// 그룹갯수
	Nofi []GetOverseasWatchlistGroupsNofiItem `json:"nofi"`
}

// GetOverseasWatchlistGroupsNofiItem 는 Nofi 의 원소다.
type GetOverseasWatchlistGroupsNofiItem struct {
	// 그룹코드 (3자)
	Gcod string `json:"gcod"`
	// 그룹명 (20자)
	Name string `json:"name"`
}

// GetOverseasWatchlistGroups 는 미국주식 관심종목 그룹 리스트 조회(usa20200) 이다.
//
// 메뉴: 미국주식 > 관심종목 > 미국주식 관심종목 그룹 리스트 조회(usa20200)
// URL:  /api/us/watchlist
func (c *Client) GetOverseasWatchlistGroups(ctx context.Context, req GetOverseasWatchlistGroupsRequest, opts ...transport.Option) (*GetOverseasWatchlistGroupsResponse, transport.Meta, error) {
	var out GetOverseasWatchlistGroupsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20200",
		Path:  "/api/us/watchlist",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
