// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotWeeklyChartRequest 는 금현물주봉차트조회요청(ka50082) 요청이다.
type GetDomesticGoldSpotWeeklyChartRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
	// 기준일자 (필수, 8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 수정주가구분 (필수, 1자, 0 or 1)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
}

// GetDomesticGoldSpotWeeklyChartResponse 는 금현물주봉차트조회요청(ka50082) 응답이다.
type GetDomesticGoldSpotWeeklyChartResponse struct {
	// 금현물일봉차트조회
	GdsWeekChartQry []GetDomesticGoldSpotWeeklyChartGdsWeekChartQryItem `json:"gds_week_chart_qry"`
}

// GetDomesticGoldSpotWeeklyChartGdsWeekChartQryItem 는 GdsWeekChartQry 의 원소다.
type GetDomesticGoldSpotWeeklyChartGdsWeekChartQryItem struct {
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 누적 거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적 거래대금 (20자, 단위: 백만원)
	AccTrdePrica string `json:"acc_trde_prica"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 일자 (20자, YYYYMMDDHHmmss)
	Dt string `json:"dt"`
}

// GetDomesticGoldSpotWeeklyChart 는 금현물주봉차트조회요청(ka50082) 이다.
//
// 메뉴: 국내주식 > 차트 > 금현물주봉차트조회요청(ka50082)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticGoldSpotWeeklyChart(ctx context.Context, req GetDomesticGoldSpotWeeklyChartRequest, opts ...transport.Option) (*GetDomesticGoldSpotWeeklyChartResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotWeeklyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50082",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
