// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorMinuteChartRequest 는 업종분봉조회요청(ka20005) 요청이다.
type GetDomesticSectorMinuteChartRequest struct {
	// 업종코드 (필수, 3자, 001:종합(KOSPI), 002:대형주, 003:중형주, 004:소형주 101:종합(KOSDAQ), 201:KOSPI200, 302:KOSTAR, 701: KRX100 나머지 ※ 업종코드 참고)
	IndsCd string `json:"inds_cd"`
	// 틱범위 (필수, 2자, 1:1분, 3:3분, 5:5분, 10:10분, 15:15분, 30:30분, 45:45분, 60:60분)
	TicScope string `json:"tic_scope"`
	// 기준일자 (8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
}

// GetDomesticSectorMinuteChartResponse 는 업종분봉조회요청(ka20005) 응답이다.
type GetDomesticSectorMinuteChartResponse struct {
	// 업종코드 (20자)
	IndsCd string `json:"inds_cd"`
	// 업종분봉조회
	IndsMinPoleQry []GetDomesticSectorMinuteChartIndsMinPoleQryItem `json:"inds_min_pole_qry"`
}

// GetDomesticSectorMinuteChartIndsMinPoleQryItem 는 IndsMinPoleQry 의 원소다.
type GetDomesticSectorMinuteChartIndsMinPoleQryItem struct {
	// 현재가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자)
	TrdeQty string `json:"trde_qty"`
	// 체결시간 (20자)
	CntrTm string `json:"cntr_tm"`
	// 시가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	LowPric string `json:"low_pric"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 전일대비 (20자, 현재가 - 전일종가)
	PredPre string `json:"pred_pre"`
	// 전일대비 기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetDomesticSectorMinuteChart 는 업종분봉조회요청(ka20005) 이다.
//
// 메뉴: 국내주식 > 차트 > 업종분봉조회요청(ka20005)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticSectorMinuteChart(ctx context.Context, req GetDomesticSectorMinuteChartRequest, opts ...transport.Option) (*GetDomesticSectorMinuteChartResponse, transport.Meta, error) {
	var out GetDomesticSectorMinuteChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20005",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
