// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockYearlyChartRequest 는 주식년봉차트조회요청(ka10094) 요청이다.
type GetDomesticStockYearlyChartRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 기준일자 (필수, 8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 수정주가구분 (필수, 1자, 0 or 1)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
}

// GetDomesticStockYearlyChartResponse 는 주식년봉차트조회요청(ka10094) 응답이다.
type GetDomesticStockYearlyChartResponse struct {
	// 종목코드 (6자)
	StkCd string `json:"stk_cd"`
	// 주식년봉차트조회
	StkYrPoleChartQry []GetDomesticStockYearlyChartStkYrPoleChartQryItem `json:"stk_yr_pole_chart_qry"`
}

// GetDomesticStockYearlyChartStkYrPoleChartQryItem 는 StkYrPoleChartQry 의 원소다.
type GetDomesticStockYearlyChartStkYrPoleChartQryItem struct {
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 원)
	TrdePrica string `json:"trde_prica"`
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
}

// GetDomesticStockYearlyChart 는 주식년봉차트조회요청(ka10094) 이다.
//
// 메뉴: 국내주식 > 차트 > 주식년봉차트조회요청(ka10094)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticStockYearlyChart(ctx context.Context, req GetDomesticStockYearlyChartRequest, opts ...transport.Option) (*GetDomesticStockYearlyChartResponse, transport.Meta, error) {
	var out GetDomesticStockYearlyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10094",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
