// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorWeeklyChartRequest 는 업종주봉조회요청(ka20007) 요청이다.
type GetDomesticSectorWeeklyChartRequest struct {
	// 업종코드 (필수, 8자, 001:종합(KOSPI), 002:대형주, 003:중형주, 004:소형주 101:종합(KOSDAQ), 201:KOSPI200, 302:KOSTAR, 701: KRX100 나머지 ※ 업종코드 참고)
	IndsCd string `json:"inds_cd"`
	// 기준일자 (필수, 3자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
}

// GetDomesticSectorWeeklyChartResponse 는 업종주봉조회요청(ka20007) 응답이다.
type GetDomesticSectorWeeklyChartResponse struct {
	// 업종코드 (20자)
	IndsCd string `json:"inds_cd"`
	// 업종주봉조회
	IndsStkPoleQry []GetDomesticSectorWeeklyChartIndsStkPoleQryItem `json:"inds_stk_pole_qry"`
}

// GetDomesticSectorWeeklyChartIndsStkPoleQryItem 는 IndsStkPoleQry 의 원소다.
type GetDomesticSectorWeeklyChartIndsStkPoleQryItem struct {
	// 현재가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	LowPric string `json:"low_pric"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
}

// GetDomesticSectorWeeklyChart 는 업종주봉조회요청(ka20007) 이다.
//
// 메뉴: 국내주식 > 차트 > 업종주봉조회요청(ka20007)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticSectorWeeklyChart(ctx context.Context, req GetDomesticSectorWeeklyChartRequest, opts ...transport.Option) (*GetDomesticSectorWeeklyChartResponse, transport.Meta, error) {
	var out GetDomesticSectorWeeklyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20007",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
