// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotTodayMinuteChartRequest 는 금현물당일분봉차트조회요청(ka50092) 요청이다.
type GetDomesticGoldSpotTodayMinuteChartRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
	// 틱범위 (필수, 2자, 1:1분, 3:3분, 5:5분, 10:10분, 15:15분, 30:30분, 45:45분, 60:60분)
	TicScope string `json:"tic_scope"`
}

// GetDomesticGoldSpotTodayMinuteChartResponse 는 금현물당일분봉차트조회요청(ka50092) 응답이다.
type GetDomesticGoldSpotTodayMinuteChartResponse struct {
	// 금현물일봉차트조회
	GdsMinChartQry []GetDomesticGoldSpotTodayMinuteChartGdsMinChartQryItem `json:"gds_min_chart_qry"`
}

// GetDomesticGoldSpotTodayMinuteChartGdsMinChartQryItem 는 GdsMinChartQry 의 원소다.
type GetDomesticGoldSpotTodayMinuteChartGdsMinChartQryItem struct {
	// 체결가 (20자, 단위: 원)
	CntrPric string `json:"cntr_pric"`
	// 전일 대비(원) (20자, 단위: 원)
	PredPre string `json:"pred_pre"`
	// 누적 거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적 거래대금 (20자, 단위: 백만원)
	AccTrdePrica string `json:"acc_trde_prica"`
	// 거래량(체결량) (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 체결시간 (20자, YYYYMMDDHHmmss)
	CntrTm string `json:"cntr_tm"`
	// 일자 (20자, YYYYMMDDHHmmss)
	Dt string `json:"dt"`
	// 전일대비기호 (20자)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetDomesticGoldSpotTodayMinuteChart 는 금현물당일분봉차트조회요청(ka50092) 이다.
//
// 메뉴: 국내주식 > 차트 > 금현물당일분봉차트조회요청(ka50092)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticGoldSpotTodayMinuteChart(ctx context.Context, req GetDomesticGoldSpotTodayMinuteChartRequest, opts ...transport.Option) (*GetDomesticGoldSpotTodayMinuteChartResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotTodayMinuteChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50092",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
