// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockDailyChartRequest 는 주식일봉차트조회요청(ka10081) 요청이다.
type GetDomesticStockDailyChartRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 기준일자 (필수, 8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 수정주가구분 (필수, 1자, 0 or 1 / 수정주가 적용을 원하시는 경우, 권리발생일 이후 일자를 base_dt에 넣어 조회 또는 연속조회해주시기 바랍니다. 예를 들어 삼성전자 2018년 05월 04일 (액면분할 권리발생일)을 base_dt에 넣고 수정주가적용(1)로 조회하면 2018년 05월 04일 이전 데이터는 수정주가 적용된 3만원대 가격이 나옵니다. 연속조회도 동일합니다. 권리 발생일 이전인 2018년 05월 03일 이전 일자로 base_dt 조회 시 수정주가 적용되지 않아 200만원 이상 가격대가 나옵니다. 수정주가 적용을 원하는 과거 차트 데이터 조회를 위해서는 해당 권리발생일 이후로 base_dt를 세팅하고, 수정주가 적용(1)로 세팅하고 조회 및 연속조회하여야합니다.)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
}

// GetDomesticStockDailyChartResponse 는 주식일봉차트조회요청(ka10081) 응답이다.
type GetDomesticStockDailyChartResponse struct {
	// 종목코드 (6자)
	StkCd string `json:"stk_cd"`
	// 주식일봉차트조회
	StkDtPoleChartQry []GetDomesticStockDailyChartStkDtPoleChartQryItem `json:"stk_dt_pole_chart_qry"`
}

// GetDomesticStockDailyChartStkDtPoleChartQryItem 는 StkDtPoleChartQry 의 원소다.
type GetDomesticStockDailyChartStkDtPoleChartQryItem struct {
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 전일대비 (20자, 현재가 - 전일종가)
	PredPre string `json:"pred_pre"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 거래회전율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeTernRt string `json:"trde_tern_rt"`
}

// GetDomesticStockDailyChart 는 주식일봉차트조회요청(ka10081) 이다.
//
// 메뉴: 국내주식 > 차트 > 주식일봉차트조회요청(ka10081)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticStockDailyChart(ctx context.Context, req GetDomesticStockDailyChartRequest, opts ...transport.Option) (*GetDomesticStockDailyChartResponse, transport.Meta, error) {
	var out GetDomesticStockDailyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10081",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
