// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockWeeklyChartRequest 는 주식주봉차트조회요청(ka10082) 요청이다.
type GetDomesticStockWeeklyChartRequest struct {
	// 종목코드 (필수, 20자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 기준일자 (필수, 8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 수정주가구분 (필수, 1자, 0 or 1)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
}

// GetDomesticStockWeeklyChartResponse 는 주식주봉차트조회요청(ka10082) 응답이다.
type GetDomesticStockWeeklyChartResponse struct {
	// 종목코드 (6자)
	StkCd string `json:"stk_cd"`
	// 주식주봉차트조회
	StkStkPoleChartQry []GetDomesticStockWeeklyChartStkStkPoleChartQryItem `json:"stk_stk_pole_chart_qry"`
}

// GetDomesticStockWeeklyChartStkStkPoleChartQryItem 는 StkStkPoleChartQry 의 원소다.
type GetDomesticStockWeeklyChartStkStkPoleChartQryItem struct {
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (20자, 단위: 원)
	TrdePrica string `json:"trde_prica"`
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 전일대비 (20자, 현재가 - 전일종가)
	PredPre string `json:"pred_pre"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 거래회전율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeTernRt string `json:"trde_tern_rt"`
}

// GetDomesticStockWeeklyChart 는 주식주봉차트조회요청(ka10082) 이다.
//
// 메뉴: 국내주식 > 차트 > 주식주봉차트조회요청(ka10082)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticStockWeeklyChart(ctx context.Context, req GetDomesticStockWeeklyChartRequest, opts ...transport.Option) (*GetDomesticStockWeeklyChartResponse, transport.Meta, error) {
	var out GetDomesticStockWeeklyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10082",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
