// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotTodayTickChartRequest 는 금현물당일틱차트조회요청(ka50091) 요청이다.
type GetDomesticGoldSpotTodayTickChartRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
	// 틱범위 (필수, 2자, 1:1틱, 3:3틱, 5:5틱, 10:10틱, 30:30틱)
	TicScope string `json:"tic_scope"`
}

// GetDomesticGoldSpotTodayTickChartResponse 는 금현물당일틱차트조회요청(ka50091) 응답이다.
type GetDomesticGoldSpotTodayTickChartResponse struct {
	// 금현물일봉차트조회
	GdsTicChartQry []GetDomesticGoldSpotTodayTickChartGdsTicChartQryItem `json:"gds_tic_chart_qry"`
}

// GetDomesticGoldSpotTodayTickChartGdsTicChartQryItem 는 GdsTicChartQry 의 원소다.
type GetDomesticGoldSpotTodayTickChartGdsTicChartQryItem struct {
	// 체결가 (20자, 단위: 원)
	CntrPric string `json:"cntr_pric"`
	// 전일 대비(원) (20자, 단위: 원)
	PredPre string `json:"pred_pre"`
	// 거래량(체결량) (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 체결시간 (20자, YYYYMMDDHHmmss)
	CntrTm string `json:"cntr_tm"`
	// 일자 (20자, YYYYMMDDHHmmss)
	Dt string `json:"dt"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetDomesticGoldSpotTodayTickChart 는 금현물당일틱차트조회요청(ka50091) 이다.
//
// 메뉴: 국내주식 > 차트 > 금현물당일틱차트조회요청(ka50091)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticGoldSpotTodayTickChart(ctx context.Context, req GetDomesticGoldSpotTodayTickChartRequest, opts ...transport.Option) (*GetDomesticGoldSpotTodayTickChartResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotTodayTickChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50091",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
