// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotMinuteChartRequest 는 금현물분봉차트조회요청(ka50080) 요청이다.
type GetDomesticGoldSpotMinuteChartRequest struct {
	// 종목코드 (필수, 20자, M04020000 금 99.99_1kg, M04020100 미니금 99.99_100g)
	StkCd string `json:"stk_cd"`
	// 틱범위 (필수, 3자, 1:1분, 3:3분, 5:5분, 10:10분, 15:15분, 30:30분, 45:45분, 60:60분)
	TicScope string `json:"tic_scope"`
	// 수정주가구분 (1자, 0 or 1)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
}

// GetDomesticGoldSpotMinuteChartResponse 는 금현물분봉차트조회요청(ka50080) 응답이다.
type GetDomesticGoldSpotMinuteChartResponse struct {
	// 금현물분봉차트조회
	GdsMinChartQry []GetDomesticGoldSpotMinuteChartGdsMinChartQryItem `json:"gds_min_chart_qry"`
}

// GetDomesticGoldSpotMinuteChartGdsMinChartQryItem 는 GdsMinChartQry 의 원소다.
type GetDomesticGoldSpotMinuteChartGdsMinChartQryItem struct {
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (20자, 단위: 원)
	PredPre string `json:"pred_pre"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 시가 (20자, 단위: 원)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 원)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 원)
	LowPric string `json:"low_pric"`
	// 체결시간 (20자, YYYYMMDDHHmmss)
	CntrTm string `json:"cntr_tm"`
	// 일자 (20자, YYYYMMDDHHmmss)
	Dt string `json:"dt"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetDomesticGoldSpotMinuteChart 는 금현물분봉차트조회요청(ka50080) 이다.
//
// 메뉴: 국내주식 > 차트 > 금현물분봉차트조회요청(ka50080)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticGoldSpotMinuteChart(ctx context.Context, req GetDomesticGoldSpotMinuteChartRequest, opts ...transport.Option) (*GetDomesticGoldSpotMinuteChartResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotMinuteChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka50080",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
