// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSectorTickChartRequest 는 업종틱차트조회요청(ka20004) 요청이다.
type GetDomesticSectorTickChartRequest struct {
	// 업종코드 (필수, 3자, 001:종합(KOSPI), 002:대형주, 003:중형주, 004:소형주 101:종합(KOSDAQ), 201:KOSPI200, 302:KOSTAR, 701: KRX100 나머지 ※ 업종코드 참고)
	IndsCd string `json:"inds_cd"`
	// 틱범위 (필수, 2자, 1:1틱, 3:3틱, 5:5틱, 10:10틱, 30:30틱)
	TicScope string `json:"tic_scope"`
}

// GetDomesticSectorTickChartResponse 는 업종틱차트조회요청(ka20004) 응답이다.
type GetDomesticSectorTickChartResponse struct {
	// 업종코드 (20자)
	IndsCd string `json:"inds_cd"`
	// 업종틱차트조회
	IndsTicChartQry []GetDomesticSectorTickChartIndsTicChartQryItem `json:"inds_tic_chart_qry"`
}

// GetDomesticSectorTickChartIndsTicChartQryItem 는 IndsTicChartQry 의 원소다.
type GetDomesticSectorTickChartIndsTicChartQryItem struct {
	// 현재가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	CurPrc string `json:"cur_prc"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 체결시간 (20자, YYYYMMDDHHmmss)
	CntrTm string `json:"cntr_tm"`
	// 시가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	OpenPric string `json:"open_pric"`
	// 고가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	HighPric string `json:"high_pric"`
	// 저가 (20자, 단위: 지수 ※ 지수 값은 소수점 제거 된 100배 값으로 제공됩니다.)
	LowPric string `json:"low_pric"`
	// 전일대비 (20자, 현재가 - 전일종가)
	PredPre string `json:"pred_pre"`
	// 전일대비 기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetDomesticSectorTickChart 는 업종틱차트조회요청(ka20004) 이다.
//
// 메뉴: 국내주식 > 차트 > 업종틱차트조회요청(ka20004)
// URL:  /api/dostk/chart
func (c *Client) GetDomesticSectorTickChart(ctx context.Context, req GetDomesticSectorTickChartRequest, opts ...transport.Option) (*GetDomesticSectorTickChartResponse, transport.Meta, error) {
	var out GetDomesticSectorTickChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka20004",
		Path:  "/api/dostk/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
