// Code generated by tools/gen. DO NOT EDIT.

package theme

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticThemeGroupsRequest 는 테마그룹별요청(ka90001) 요청이다.
type GetDomesticThemeGroupsRequest struct {
	// 검색구분 (필수, 1자, 0:전체검색, 1:테마검색, 2:종목검색)
	QryTp string `json:"qry_tp"`
	// 종목코드 (6자, 검색하려는 종목코드)
	StkCd string `json:"stk_cd"`
	// 날짜구분 (필수, 2자, n일전 (1일 ~ 99일 날짜입력))
	DateTp string `json:"date_tp"`
	// 테마명 (50자, 검색하려는 테마명)
	ThemaNm string `json:"thema_nm"`
	// 등락수익구분 (필수, 1자, 1:상위기간수익률, 2:하위기간수익률, 3:상위등락률, 4:하위등락률)
	FluPlAmtTp string `json:"flu_pl_amt_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticThemeGroupsResponse 는 테마그룹별요청(ka90001) 응답이다.
type GetDomesticThemeGroupsResponse struct {
	// 테마그룹별
	ThemaGrp []GetDomesticThemeGroupsThemaGrpItem `json:"thema_grp"`
}

// GetDomesticThemeGroupsThemaGrpItem 는 ThemaGrp 의 원소다.
type GetDomesticThemeGroupsThemaGrpItem struct {
	// 테마그룹코드 (20자)
	ThemaGrpCd string `json:"thema_grp_cd"`
	// 테마명 (20자)
	ThemaNm string `json:"thema_nm"`
	// 종목수 (20자)
	StkNum string `json:"stk_num"`
	// 등락기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	FluSig string `json:"flu_sig"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 상승종목수 (20자)
	RisingStkNum string `json:"rising_stk_num"`
	// 하락종목수 (20자)
	FallStkNum string `json:"fall_stk_num"`
	// 기간수익률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	DtPrftRt string `json:"dt_prft_rt"`
	// 주요종목 (20자)
	MainStk string `json:"main_stk"`
}

// GetDomesticThemeGroups 는 테마그룹별요청(ka90001) 이다.
//
// 메뉴: 국내주식 > 테마 > 테마그룹별요청(ka90001)
// URL:  /api/dostk/thme
func (c *Client) GetDomesticThemeGroups(ctx context.Context, req GetDomesticThemeGroupsRequest, opts ...transport.Option) (*GetDomesticThemeGroupsResponse, transport.Meta, error) {
	var out GetDomesticThemeGroupsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka90001",
		Path:  "/api/dostk/thme",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
