// Code generated by tools/gen. DO NOT EDIT.

package sector

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasSectorPeriodReturnsRequest 는 미국주식 업종별 기간별 수익률 조회(usa23000) 요청이다.
type GetOverseasSectorPeriodReturnsRequest struct {
	// 거래소 구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// 업종 코드 (0:전체, usa10101 참고)
	IndsCd string `json:"inds_cd"`
}

// GetOverseasSectorPeriodReturnsResponse 는 미국주식 업종별 기간별 수익률 조회(usa23000) 응답이다.
type GetOverseasSectorPeriodReturnsResponse struct {
	// 결과리스트
	ResultList []GetOverseasSectorPeriodReturnsResultListItem `json:"result_list"`
}

// GetOverseasSectorPeriodReturnsResultListItem 는 ResultList 의 원소다.
type GetOverseasSectorPeriodReturnsResultListItem struct {
	// 업종코드
	IndsCd string `json:"inds_cd"`
	// 업종명
	IndsNm string `json:"inds_nm"`
	// 1일 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf1d string `json:"perf_1d"`
	// 5일 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf5d string `json:"perf_5d"`
	// 1개월 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf1m string `json:"perf_1m"`
	// 3개월 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf3m string `json:"perf_3m"`
	// 6개월 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf6m string `json:"perf_6m"`
	// 연중 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	PerfYtd string `json:"perf_ytd"`
	// 1년 수익률 (소수점 둘째 자리까지 포맷된 숫자)
	Perf1y string `json:"perf_1y"`
}

// GetOverseasSectorPeriodReturns 는 미국주식 업종별 기간별 수익률 조회(usa23000) 이다.
//
// 메뉴: 미국주식 > 업종 > 미국주식 업종별 기간별 수익률 조회(usa23000)
// URL:  /api/us/sect
func (c *Client) GetOverseasSectorPeriodReturns(ctx context.Context, req GetOverseasSectorPeriodReturnsRequest, opts ...transport.Option) (*GetOverseasSectorPeriodReturnsResponse, transport.Meta, error) {
	var out GetOverseasSectorPeriodReturnsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa23000",
		Path:  "/api/us/sect",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
