// Code generated by tools/gen. DO NOT EDIT.

package watchlist

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticWatchlistGroupDetailRequest 는 관심종목 그룹 상세 조회(ka01301) 요청이다.
type GetDomesticWatchlistGroupDetailRequest struct {
	// 그룹SEQ (필수, 3자, ka01300 응답 결과의 gcod값을 입력)
	ArnGrpID string `json:"arn_grp_id"`
}

// GetDomesticWatchlistGroupDetailResponse 는 관심종목 그룹 상세 조회(ka01301) 응답이다.
type GetDomesticWatchlistGroupDetailResponse struct {
	// 처리 결과 (1자, S:성공 F:실패)
	Rtcd string `json:"rtcd"`
	// 종목 갯수
	Nofj []GetDomesticWatchlistGroupDetailNofjItem `json:"nofj"`
}

// GetDomesticWatchlistGroupDetailNofjItem 는 Nofj 의 원소다.
type GetDomesticWatchlistGroupDetailNofjItem struct {
	// 종목코드 (18자)
	Cod2 string `json:"cod2"`
	// 북마크 구분 (1자)
	Bgb string `json:"bgb"`
	// 북마크 컬러 (9자)
	BgbClr string `json:"bgb_clr"`
}

// GetDomesticWatchlistGroupDetail 는 관심종목 그룹 상세 조회(ka01301) 이다.
//
// 메뉴: 국내주식 > 관심종목 > 관심종목 그룹 상세 조회(ka01301)
// URL:  /api/dostk/watchlist
func (c *Client) GetDomesticWatchlistGroupDetail(ctx context.Context, req GetDomesticWatchlistGroupDetailRequest, opts ...transport.Option) (*GetDomesticWatchlistGroupDetailResponse, transport.Meta, error) {
	var out GetDomesticWatchlistGroupDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka01301",
		Path:  "/api/dostk/watchlist",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
