// Code generated by tools/gen. DO NOT EDIT.

package watchlist

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticWatchlistGroupsRequest 는 관심종목 그룹 리스트 조회(ka01300) 요청이다.
type GetDomesticWatchlistGroupsRequest struct {
}

// GetDomesticWatchlistGroupsResponse 는 관심종목 그룹 리스트 조회(ka01300) 응답이다.
type GetDomesticWatchlistGroupsResponse struct {
	// 처리결과 (1자, S:성공 F:실패)
	Rtcd string `json:"rtcd"`
	// 그룹갯수
	Nofi []GetDomesticWatchlistGroupsNofiItem `json:"nofi"`
}

// GetDomesticWatchlistGroupsNofiItem 는 Nofi 의 원소다.
type GetDomesticWatchlistGroupsNofiItem struct {
	// 그룹코드 (3자)
	Gcod string `json:"gcod"`
	// 그룹명 (2자)
	Name string `json:"name"`
}

// GetDomesticWatchlistGroups 는 관심종목 그룹 리스트 조회(ka01300) 이다.
//
// 메뉴: 국내주식 > 관심종목 > 관심종목 그룹 리스트 조회(ka01300)
// URL:  /api/dostk/watchlist
func (c *Client) GetDomesticWatchlistGroups(ctx context.Context, req GetDomesticWatchlistGroupsRequest, opts ...transport.Option) (*GetDomesticWatchlistGroupsResponse, transport.Meta, error) {
	var out GetDomesticWatchlistGroupsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka01300",
		Path:  "/api/dostk/watchlist",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
