// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticTradingValueTopRequest 는 거래대금상위요청(ka10032) 요청이다.
type GetDomesticTradingValueTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 관리종목포함 (필수, 1자, 0:관리종목 미포함, 1:관리종목 포함)
	MangStkIncls string `json:"mang_stk_incls"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticTradingValueTopResponse 는 거래대금상위요청(ka10032) 응답이다.
type GetDomesticTradingValueTopResponse struct {
	// 거래대금상위
	TrdePricaUpper []GetDomesticTradingValueTopTrdePricaUpperItem `json:"trde_prica_upper"`
}

// GetDomesticTradingValueTopTrdePricaUpperItem 는 TrdePricaUpper 의 원소다.
type GetDomesticTradingValueTopTrdePricaUpperItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 현재순위 (20자)
	NowRank string `json:"now_rank"`
	// 전일순위 (20자)
	PredRank string `json:"pred_rank"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 전일거래량 (20자, 단위: 1주)
	PredTrdeQty string `json:"pred_trde_qty"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
}

// GetDomesticTradingValueTop 는 거래대금상위요청(ka10032) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 거래대금상위요청(ka10032)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticTradingValueTop(ctx context.Context, req GetDomesticTradingValueTopRequest, opts ...transport.Option) (*GetDomesticTradingValueTopResponse, transport.Meta, error) {
	var out GetDomesticTradingValueTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10032",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
