// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticForeignInstitutionTradeTopRequest 는 외국인기관매매상위요청(ka90009) 요청이다.
type GetDomesticForeignInstitutionTradeTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 금액수량구분 (필수, 1자, 1:금액(천만), 2:수량(천))
	AmtQtyTp string `json:"amt_qty_tp"`
	// 조회일자구분 (필수, 1자, 0:조회일자 미포함, 1:조회일자 포함)
	QryDtTp string `json:"qry_dt_tp"`
	// 날짜 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	Date string `json:"date"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticForeignInstitutionTradeTopResponse 는 외국인기관매매상위요청(ka90009) 응답이다.
type GetDomesticForeignInstitutionTradeTopResponse struct {
	// 외국인기관매매상위
	FrgnrOrgnTrdeUpper []GetDomesticForeignInstitutionTradeTopFrgnrOrgnTrdeUpperItem `json:"frgnr_orgn_trde_upper"`
}

// GetDomesticForeignInstitutionTradeTopFrgnrOrgnTrdeUpperItem 는 FrgnrOrgnTrdeUpper 의 원소다.
type GetDomesticForeignInstitutionTradeTopFrgnrOrgnTrdeUpperItem struct {
	// 외인순매도종목코드 (20자)
	ForNetslmtStkCd string `json:"for_netslmt_stk_cd"`
	// 외인순매도종목명 (20자)
	ForNetslmtStkNm string `json:"for_netslmt_stk_nm"`
	// 외인순매도금액 (20자, 단위: 천만, 부호가 포함된 숫자)
	ForNetslmtAmt string `json:"for_netslmt_amt"`
	// 외인순매도수량 (20자, 단위: 1000주(천주), 부호가 포함된 숫자)
	ForNetslmtQty string `json:"for_netslmt_qty"`
	// 외인순매수종목코드 (20자)
	ForNetprpsStkCd string `json:"for_netprps_stk_cd"`
	// 외인순매수종목명 (20자)
	ForNetprpsStkNm string `json:"for_netprps_stk_nm"`
	// 외인순매수금액 (20자, 단위: 천만, 부호가 포함된 숫자)
	ForNetprpsAmt string `json:"for_netprps_amt"`
	// 외인순매수수량 (20자, 단위: 1000주(천주), 부호가 포함된 숫자)
	ForNetprpsQty string `json:"for_netprps_qty"`
	// 기관순매도종목코드 (20자)
	OrgnNetslmtStkCd string `json:"orgn_netslmt_stk_cd"`
	// 기관순매도종목명 (20자)
	OrgnNetslmtStkNm string `json:"orgn_netslmt_stk_nm"`
	// 기관순매도금액 (20자, 단위: 천만, 부호가 포함된 숫자)
	OrgnNetslmtAmt string `json:"orgn_netslmt_amt"`
	// 기관순매도수량 (20자, 단위: 1000주(천주), 부호가 포함된 숫자)
	OrgnNetslmtQty string `json:"orgn_netslmt_qty"`
	// 기관순매수종목코드 (20자)
	OrgnNetprpsStkCd string `json:"orgn_netprps_stk_cd"`
	// 기관순매수종목명 (20자)
	OrgnNetprpsStkNm string `json:"orgn_netprps_stk_nm"`
	// 기관순매수금액 (20자, 단위: 천만, 부호가 포함된 숫자)
	OrgnNetprpsAmt string `json:"orgn_netprps_amt"`
	// 기관순매수수량 (20자, 단위: 1000주(천주), 부호가 포함된 숫자)
	OrgnNetprpsQty string `json:"orgn_netprps_qty"`
}

// GetDomesticForeignInstitutionTradeTop 는 외국인기관매매상위요청(ka90009) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 외국인기관매매상위요청(ka90009)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticForeignInstitutionTradeTop(ctx context.Context, req GetDomesticForeignInstitutionTradeTopRequest, opts ...transport.Option) (*GetDomesticForeignInstitutionTradeTopResponse, transport.Meta, error) {
	var out GetDomesticForeignInstitutionTradeTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka90009",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
