// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticBrokerTradeTopRequest 는 증권사별매매상위요청(ka10039) 요청이다.
type GetDomesticBrokerTradeTopRequest struct {
	// 회원사코드 (필수, 3자, 회원사 코드는 ka10102 조회)
	MmcmCd string `json:"mmcm_cd"`
	// 거래량구분 (필수, 4자, 0:전체, 5:5000주, 10:1만주, 50:5만주, 100:10만주, 500:50만주, 1000: 100만주)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 매매구분 (필수, 2자, 1:순매수, 2:순매도)
	TrdeTp string `json:"trde_tp"`
	// 기간 (필수, 2자, 0:당일, 1:전일, 5:5일, 10:10일, 60:60일)
	Dt string `json:"dt"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticBrokerTradeTopResponse 는 증권사별매매상위요청(ka10039) 응답이다.
type GetDomesticBrokerTradeTopResponse struct {
	// 증권사별매매상위
	SecTrdeUpper []GetDomesticBrokerTradeTopSecTrdeUpperItem `json:"sec_trde_upper"`
}

// GetDomesticBrokerTradeTopSecTrdeUpperItem 는 SecTrdeUpper 의 원소다.
type GetDomesticBrokerTradeTopSecTrdeUpperItem struct {
	// 순위 (20자)
	Rank string `json:"rank"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 기간중주가등락 (20자, 단위: 원, 부호가 포함된 숫자)
	PridStkpcFlu string `json:"prid_stkpc_flu"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 기간중거래량 (20자, 단위: 1주)
	PridTrdeQty string `json:"prid_trde_qty"`
	// 순매수 (20자, 단위: 1주, 부호가 포함된 숫자)
	Netprps string `json:"netprps"`
	// 매수거래량 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyTrdeQty string `json:"buy_trde_qty"`
	// 매도거래량 (20자, 단위: 1주, 부호가 포함된 숫자)
	SelTrdeQty string `json:"sel_trde_qty"`
	// 순매수금액 (20자, 단위: 천원, 부호가 포함된 숫자)
	NetprpsAmt string `json:"netprps_amt"`
	// 매수금액 (20자, 단위: 천원, 부호가 포함된 숫자)
	BuyAmt string `json:"buy_amt"`
	// 매도금액 (20자, 단위: 천원, 부호가 포함된 숫자)
	SellAmt string `json:"sell_amt"`
}

// GetDomesticBrokerTradeTop 는 증권사별매매상위요청(ka10039) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 증권사별매매상위요청(ka10039)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticBrokerTradeTop(ctx context.Context, req GetDomesticBrokerTradeTopRequest, opts ...transport.Option) (*GetDomesticBrokerTradeTopResponse, transport.Meta, error) {
	var out GetDomesticBrokerTradeTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10039",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
