// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticTodayMajorBrokersRequest 는 당일주요거래원요청(ka10040) 요청이다.
type GetDomesticTodayMajorBrokersRequest struct {
	// 종목코드 (필수, 6자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
}

// GetDomesticTodayMajorBrokersResponse 는 당일주요거래원요청(ka10040) 응답이다.
type GetDomesticTodayMajorBrokersResponse struct {
	// 매도거래원별증감1 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriIrds1 string `json:"sel_trde_ori_irds_1"`
	// 매도거래원수량1 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriQty1 string `json:"sel_trde_ori_qty_1"`
	// 매도거래원1
	SelTrdeOri1 string `json:"sel_trde_ori_1"`
	// 매도거래원코드1
	SelTrdeOriCd1 string `json:"sel_trde_ori_cd_1"`
	// 매수거래원1
	BuyTrdeOri1 string `json:"buy_trde_ori_1"`
	// 매수거래원코드1
	BuyTrdeOriCd1 string `json:"buy_trde_ori_cd_1"`
	// 매수거래원수량1 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriQty1 string `json:"buy_trde_ori_qty_1"`
	// 매수거래원별증감1 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriIrds1 string `json:"buy_trde_ori_irds_1"`
	// 매도거래원별증감2 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriIrds2 string `json:"sel_trde_ori_irds_2"`
	// 매도거래원수량2 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriQty2 string `json:"sel_trde_ori_qty_2"`
	// 매도거래원2
	SelTrdeOri2 string `json:"sel_trde_ori_2"`
	// 매도거래원코드2
	SelTrdeOriCd2 string `json:"sel_trde_ori_cd_2"`
	// 매수거래원2
	BuyTrdeOri2 string `json:"buy_trde_ori_2"`
	// 매수거래원코드2
	BuyTrdeOriCd2 string `json:"buy_trde_ori_cd_2"`
	// 매수거래원수량2 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriQty2 string `json:"buy_trde_ori_qty_2"`
	// 매수거래원별증감2 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriIrds2 string `json:"buy_trde_ori_irds_2"`
	// 매도거래원별증감3 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriIrds3 string `json:"sel_trde_ori_irds_3"`
	// 매도거래원수량3 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriQty3 string `json:"sel_trde_ori_qty_3"`
	// 매도거래원3
	SelTrdeOri3 string `json:"sel_trde_ori_3"`
	// 매도거래원코드3
	SelTrdeOriCd3 string `json:"sel_trde_ori_cd_3"`
	// 매수거래원3
	BuyTrdeOri3 string `json:"buy_trde_ori_3"`
	// 매수거래원코드3
	BuyTrdeOriCd3 string `json:"buy_trde_ori_cd_3"`
	// 매수거래원수량3 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriQty3 string `json:"buy_trde_ori_qty_3"`
	// 매수거래원별증감3 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriIrds3 string `json:"buy_trde_ori_irds_3"`
	// 매도거래원별증감4 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriIrds4 string `json:"sel_trde_ori_irds_4"`
	// 매도거래원수량4 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriQty4 string `json:"sel_trde_ori_qty_4"`
	// 매도거래원4
	SelTrdeOri4 string `json:"sel_trde_ori_4"`
	// 매도거래원코드4
	SelTrdeOriCd4 string `json:"sel_trde_ori_cd_4"`
	// 매수거래원4
	BuyTrdeOri4 string `json:"buy_trde_ori_4"`
	// 매수거래원코드4
	BuyTrdeOriCd4 string `json:"buy_trde_ori_cd_4"`
	// 매수거래원수량4 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriQty4 string `json:"buy_trde_ori_qty_4"`
	// 매수거래원별증감4 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriIrds4 string `json:"buy_trde_ori_irds_4"`
	// 매도거래원별증감5 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriIrds5 string `json:"sel_trde_ori_irds_5"`
	// 매도거래원수량5 (단위: 1주, 부호가 포함된 숫자)
	SelTrdeOriQty5 string `json:"sel_trde_ori_qty_5"`
	// 매도거래원5
	SelTrdeOri5 string `json:"sel_trde_ori_5"`
	// 매도거래원코드5
	SelTrdeOriCd5 string `json:"sel_trde_ori_cd_5"`
	// 매수거래원5
	BuyTrdeOri5 string `json:"buy_trde_ori_5"`
	// 매수거래원코드5
	BuyTrdeOriCd5 string `json:"buy_trde_ori_cd_5"`
	// 매수거래원수량5 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriQty5 string `json:"buy_trde_ori_qty_5"`
	// 매수거래원별증감5 (단위: 1주, 부호가 포함된 숫자)
	BuyTrdeOriIrds5 string `json:"buy_trde_ori_irds_5"`
	// 외국계매도추정합변동 (단위: 1주, 부호가 포함된 숫자)
	FrgnSelPrsmSumChang string `json:"frgn_sel_prsm_sum_chang"`
	// 외국계매도추정합 (단위: 1주, 부호가 포함된 숫자)
	FrgnSelPrsmSum string `json:"frgn_sel_prsm_sum"`
	// 외국계매수추정합 (단위: 1주, 부호가 포함된 숫자)
	FrgnBuyPrsmSum string `json:"frgn_buy_prsm_sum"`
	// 외국계매수추정합변동 (단위: 1주, 부호가 포함된 숫자)
	FrgnBuyPrsmSumChang string `json:"frgn_buy_prsm_sum_chang"`
	// 당일주요거래원
	TdyMainTrdeOri []GetDomesticTodayMajorBrokersTdyMainTrdeOriItem `json:"tdy_main_trde_ori"`
}

// GetDomesticTodayMajorBrokersTdyMainTrdeOriItem 는 TdyMainTrdeOri 의 원소다.
type GetDomesticTodayMajorBrokersTdyMainTrdeOriItem struct {
	// 매도이탈시간 (20자)
	SelScesnTm string `json:"sel_scesn_tm"`
	// 매도수량 (20자)
	SellQty string `json:"sell_qty"`
	// 매도상위이탈원 (20자)
	SelUpperScesnOri string `json:"sel_upper_scesn_ori"`
	// 매수이탈시간 (20자)
	BuyScesnTm string `json:"buy_scesn_tm"`
	// 매수수량 (20자)
	BuyQty string `json:"buy_qty"`
	// 매수상위이탈원 (20자)
	BuyUpperScesnOri string `json:"buy_upper_scesn_ori"`
	// 조회일자 (20자)
	QryDt string `json:"qry_dt"`
	// 조회시간 (20자)
	QryTm string `json:"qry_tm"`
}

// GetDomesticTodayMajorBrokers 는 당일주요거래원요청(ka10040) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 당일주요거래원요청(ka10040)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticTodayMajorBrokers(ctx context.Context, req GetDomesticTodayMajorBrokersRequest, opts ...transport.Option) (*GetDomesticTodayMajorBrokersResponse, transport.Meta, error) {
	var out GetDomesticTodayMajorBrokersResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10040",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
