// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticPrevDayChangeRateTopRequest 는 전일대비등락률상위요청(ka10027) 요청이다.
type GetDomesticPrevDayChangeRateTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 정렬구분 (필수, 1자, 1:상승률, 2:상승폭, 3:하락률, 4:하락폭, 5:보합)
	SortTp string `json:"sort_tp"`
	// 거래량조건 (필수, 5자, 0000:전체조회, 0010:만주이상, 0050:5만주이상, 0100:10만주이상, 0150:15만주이상, 0200:20만주이상, 0300:30만주이상, 0500:50만주이상, 1000:백만주이상)
	TrdeQtyCnd string `json:"trde_qty_cnd"`
	// 종목조건 (필수, 2자, 0:전체조회, 1:관리종목제외, 4:우선주+관리주제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기, 11:정리매매종목제외, 12:증50만보기, 13:증60만보기, 14:ETF제외, 15:스펙제외, 16:ETF+ETN제외)
	StkCnd string `json:"stk_cnd"`
	// 신용조건 (필수, 1자, 0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체)
	CrdCnd string `json:"crd_cnd"`
	// 상하한포함 (필수, 2자, 0:불 포함, 1:포함)
	UpdownIncls string `json:"updown_incls"`
	// 가격조건 (필수, 2자, 0:전체조회, 1:1천원미만, 2:1천원~2천원, 3:2천원~5천원, 4:5천원~1만원, 5:1만원이상, 8:1천원이상, 10: 1만원미만)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (필수, 4자, 0:전체조회, 3:3천만원이상, 5:5천만원이상, 10:1억원이상, 30:3억원이상, 50:5억원이상, 100:10억원이상, 300:30억원이상, 500:50억원이상, 1000:100억원이상, 3000:300억원이상, 5000:500억원이상)
	TrdePricaCnd string `json:"trde_prica_cnd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticPrevDayChangeRateTopResponse 는 전일대비등락률상위요청(ka10027) 응답이다.
type GetDomesticPrevDayChangeRateTopResponse struct {
	// 전일대비등락률상위
	PredPreFluRtUpper []GetDomesticPrevDayChangeRateTopPredPreFluRtUpperItem `json:"pred_pre_flu_rt_upper"`
}

// GetDomesticPrevDayChangeRateTopPredPreFluRtUpperItem 는 PredPreFluRtUpper 의 원소다.
type GetDomesticPrevDayChangeRateTopPredPreFluRtUpperItem struct {
	// 종목분류 (20자)
	StkCls string `json:"stk_cls"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 매도잔량 (20자, 단위: 1주)
	SelReq string `json:"sel_req"`
	// 매수잔량 (20자, 단위: 1주)
	BuyReq string `json:"buy_req"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
	// 체결강도 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CntrStr string `json:"cntr_str"`
	// 횟수 (20자)
	Cnt string `json:"cnt"`
}

// GetDomesticPrevDayChangeRateTop 는 전일대비등락률상위요청(ka10027) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 전일대비등락률상위요청(ka10027)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticPrevDayChangeRateTop(ctx context.Context, req GetDomesticPrevDayChangeRateTopRequest, opts ...transport.Option) (*GetDomesticPrevDayChangeRateTopResponse, transport.Meta, error) {
	var out GetDomesticPrevDayChangeRateTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10027",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
