// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticTodayVolumeTopRequest 는 당일거래량상위요청(ka10030) 요청이다.
type GetDomesticTodayVolumeTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 정렬구분 (필수, 1자, 1:거래량, 2:거래회전율, 3:거래대금)
	SortTp string `json:"sort_tp"`
	// 관리종목포함 (필수, 1자, 0:관리종목 포함, 1:관리종목 미포함, 3:우선주제외, 11:정리매매종목제외, 4:관리종목, 우선주제외, 5:증100제외, 6:증100마나보기, 13:증60만보기, 12:증50만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기, 14:ETF제외, 15:스팩제외, 16:ETF+ETN제외)
	MangStkIncls string `json:"mang_stk_incls"`
	// 신용구분 (필수, 1자, 0:전체조회, 9:신용융자전체, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 8:신용대주)
	CrdTp string `json:"crd_tp"`
	// 거래량구분 (필수, 1자, 0:전체조회, 5:5천주이상, 10:1만주이상, 50:5만주이상, 100:10만주이상, 200:20만주이상, 300:30만주이상, 500:500만주이상, 1000:백만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 가격구분 (필수, 1자, 0:전체조회, 1:1천원미만, 2:1천원이상, 3:1천원~2천원, 4:2천원~5천원, 5:5천원이상, 6:5천원~1만원, 10:1만원미만, 7:1만원이상, 8:5만원이상, 9:10만원이상)
	PricTp string `json:"pric_tp"`
	// 거래대금구분 (필수, 1자, 0:전체조회, 1:1천만원이상, 3:3천만원이상, 4:5천만원이상, 10:1억원이상, 30:3억원이상, 50:5억원이상, 100:10억원이상, 300:30억원이상, 500:50억원이상, 1000:100억원이상, 3000:300억원이상, 5000:500억원이상)
	TrdePricaTp string `json:"trde_prica_tp"`
	// 장운영구분 (필수, 1자, 0:전체조회, 1:장중, 2:장전시간외, 3:장후시간외)
	MrktOpenTp string `json:"mrkt_open_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticTodayVolumeTopResponse 는 당일거래량상위요청(ka10030) 응답이다.
type GetDomesticTodayVolumeTopResponse struct {
	// 당일거래량상위
	TdyTrdeQtyUpper []GetDomesticTodayVolumeTopTdyTrdeQtyUpperItem `json:"tdy_trde_qty_upper"`
}

// GetDomesticTodayVolumeTopTdyTrdeQtyUpperItem 는 TdyTrdeQtyUpper 의 원소다.
type GetDomesticTodayVolumeTopTdyTrdeQtyUpperItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 전일비 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PredRt string `json:"pred_rt"`
	// 거래회전율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeTernRt string `json:"trde_tern_rt"`
	// 거래금액 (20자, 단위: 백만원)
	TrdeAmt string `json:"trde_amt"`
	// 장중거래량 (20자)
	OpmrTrdeQty string `json:"opmr_trde_qty"`
	// 장중전일비 (20자)
	OpmrPredRt string `json:"opmr_pred_rt"`
	// 장중거래회전율 (20자)
	OpmrTrdeRt string `json:"opmr_trde_rt"`
	// 장중거래금액 (20자)
	OpmrTrdeAmt string `json:"opmr_trde_amt"`
	// 장후거래량 (20자)
	AfMkrtTrdeQty string `json:"af_mkrt_trde_qty"`
	// 장후전일비 (20자)
	AfMkrtPredRt string `json:"af_mkrt_pred_rt"`
	// 장후거래회전율 (20자)
	AfMkrtTrdeRt string `json:"af_mkrt_trde_rt"`
	// 장후거래금액 (20자)
	AfMkrtTrdeAmt string `json:"af_mkrt_trde_amt"`
	// 장전거래량 (20자)
	BfMkrtTrdeQty string `json:"bf_mkrt_trde_qty"`
	// 장전전일비 (20자)
	BfMkrtPredRt string `json:"bf_mkrt_pred_rt"`
	// 장전거래회전율 (20자)
	BfMkrtTrdeRt string `json:"bf_mkrt_trde_rt"`
	// 장전거래금액 (20자)
	BfMkrtTrdeAmt string `json:"bf_mkrt_trde_amt"`
}

// GetDomesticTodayVolumeTop 는 당일거래량상위요청(ka10030) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 당일거래량상위요청(ka10030)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticTodayVolumeTop(ctx context.Context, req GetDomesticTodayVolumeTopRequest, opts ...transport.Option) (*GetDomesticTodayVolumeTopResponse, transport.Meta, error) {
	var out GetDomesticTodayVolumeTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10030",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
