// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticNetBuyBrokerRankRequest 는 순매수거래원순위요청(ka10042) 요청이다.
type GetDomesticNetBuyBrokerRankRequest struct {
	// 종목코드 (필수, 6자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시작일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	EndDt string `json:"end_dt"`
	// 조회기간구분 (필수, 1자, 0:기간으로 조회, 1:시작일자, 종료일자로 조회)
	QryDtTp string `json:"qry_dt_tp"`
	// 시점구분 (필수, 1자, 0:당일, 1:전일)
	PotTp string `json:"pot_tp"`
	// 기간 (4자, 5:5일, 10:10일, 20:20일, 40:40일, 60:60일, 120:120일)
	Dt string `json:"dt"`
	// 정렬기준 (필수, 1자, 1:종가순, 2:날짜순)
	SortBase string `json:"sort_base"`
}

// GetDomesticNetBuyBrokerRankResponse 는 순매수거래원순위요청(ka10042) 응답이다.
type GetDomesticNetBuyBrokerRankResponse struct {
	// 순매수거래원순위
	NetprpsTrdeOriRank []GetDomesticNetBuyBrokerRankNetprpsTrdeOriRankItem `json:"netprps_trde_ori_rank"`
}

// GetDomesticNetBuyBrokerRankNetprpsTrdeOriRankItem 는 NetprpsTrdeOriRank 의 원소다.
type GetDomesticNetBuyBrokerRankNetprpsTrdeOriRankItem struct {
	// 순위 (20자)
	Rank string `json:"rank"`
	// 회원사코드 (20자)
	MmcmCd string `json:"mmcm_cd"`
	// 회원사명 (20자)
	MmcmNm string `json:"mmcm_nm"`
}

// GetDomesticNetBuyBrokerRank 는 순매수거래원순위요청(ka10042) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 순매수거래원순위요청(ka10042)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticNetBuyBrokerRank(ctx context.Context, req GetDomesticNetBuyBrokerRankRequest, opts ...transport.Option) (*GetDomesticNetBuyBrokerRankResponse, transport.Meta, error) {
	var out GetDomesticNetBuyBrokerRankResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10042",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
