// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticSameDirectionNetTradeRankRequest 는 동일순매매순위요청(ka10062) 요청이다.
type GetDomesticSameDirectionNetTradeRankRequest struct {
	// 시작일자 (필수, 8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	EndDt string `json:"end_dt"`
	// 시장구분 (필수, 3자, 000:전체, 001: 코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 매매구분 (필수, 1자, 1:순매수, 2:순매도)
	TrdeTp string `json:"trde_tp"`
	// 정렬조건 (필수, 1자, 1:수량, 2:금액)
	SortCnd string `json:"sort_cnd"`
	// 단위구분 (필수, 1자, 1:단주, 1000:천주)
	UnitTp string `json:"unit_tp"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticSameDirectionNetTradeRankResponse 는 동일순매매순위요청(ka10062) 응답이다.
type GetDomesticSameDirectionNetTradeRankResponse struct {
	// 동일순매매순위
	EqlNettrdeRank []GetDomesticSameDirectionNetTradeRankEqlNettrdeRankItem `json:"eql_nettrde_rank"`
}

// GetDomesticSameDirectionNetTradeRankEqlNettrdeRankItem 는 EqlNettrdeRank 의 원소다.
type GetDomesticSameDirectionNetTradeRankEqlNettrdeRankItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 순위 (20자)
	Rank string `json:"rank"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량 (20자, 단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 기관순매매수량 (20자, 단위: 1주 혹은 1000주(unit_tp파라미터로 설정), 부호가 포함된 숫자)
	OrgnNettrdeQty string `json:"orgn_nettrde_qty"`
	// 기관순매매금액 (20자, 단위: 백만원, 부호가 포함된 숫자)
	OrgnNettrdeAmt string `json:"orgn_nettrde_amt"`
	// 기관순매매평균가 (20자, 단위: 백만원)
	OrgnNettrdeAvgPric string `json:"orgn_nettrde_avg_pric"`
	// 외인순매매수량 (20자, 단위: 1주 혹은 1000주(unit_tp파라미터로 설정), 부호가 포함된 숫자)
	ForNettrdeQty string `json:"for_nettrde_qty"`
	// 외인순매매금액 (20자, 단위: 백만원, 부호가 포함된 숫자)
	ForNettrdeAmt string `json:"for_nettrde_amt"`
	// 외인순매매평균가 (20자, 단위: 백만원)
	ForNettrdeAvgPric string `json:"for_nettrde_avg_pric"`
	// 순매매수량 (20자, 단위: 1주 혹은 1000주(unit_tp파라미터로 설정), 부호가 포함된 숫자)
	NettrdeQty string `json:"nettrde_qty"`
	// 순매매금액 (20자, 단위: 백만원, 부호가 포함된 숫자)
	NettrdeAmt string `json:"nettrde_amt"`
}

// GetDomesticSameDirectionNetTradeRank 는 동일순매매순위요청(ka10062) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 동일순매매순위요청(ka10062)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticSameDirectionNetTradeRank(ctx context.Context, req GetDomesticSameDirectionNetTradeRankRequest, opts ...transport.Option) (*GetDomesticSameDirectionNetTradeRankResponse, transport.Meta, error) {
	var out GetDomesticSameDirectionNetTradeRankResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10062",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
