// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticOrderBookDepthTopRequest 는 호가잔량상위요청(ka10020) 요청이다.
type GetDomesticOrderBookDepthTopRequest struct {
	// 시장구분 (필수, 3자, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 정렬구분 (필수, 1자, 1:순매수잔량순, 2:순매도잔량순, 3:매수비율순, 4:매도비율순)
	SortTp string `json:"sort_tp"`
	// 거래량구분 (필수, 4자, 0000:장시작전(0주이상), 0010:만주이상, 0050:5만주이상, 00100:10만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (필수, 1자, 0:전체조회, 1:관리종목제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기)
	StkCnd string `json:"stk_cnd"`
	// 신용조건 (필수, 1자, 0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체)
	CrdCnd string `json:"crd_cnd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticOrderBookDepthTopResponse 는 호가잔량상위요청(ka10020) 응답이다.
type GetDomesticOrderBookDepthTopResponse struct {
	// 호가잔량상위
	BidReqUpper []GetDomesticOrderBookDepthTopBidReqUpperItem `json:"bid_req_upper"`
}

// GetDomesticOrderBookDepthTopBidReqUpperItem 는 BidReqUpper 의 원소다.
type GetDomesticOrderBookDepthTopBidReqUpperItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 총매도잔량 (20자, 단위: 1주)
	TotSelReq string `json:"tot_sel_req"`
	// 총매수잔량 (20자, 단위: 1주)
	TotBuyReq string `json:"tot_buy_req"`
	// 순매수잔량 (20자, 단위: 1주)
	NetprpsReq string `json:"netprps_req"`
	// 매수비율 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	BuyRt string `json:"buy_rt"`
}

// GetDomesticOrderBookDepthTop 는 호가잔량상위요청(ka10020) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 호가잔량상위요청(ka10020)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticOrderBookDepthTop(ctx context.Context, req GetDomesticOrderBookDepthTopRequest, opts ...transport.Option) (*GetDomesticOrderBookDepthTopResponse, transport.Meta, error) {
	var out GetDomesticOrderBookDepthTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10020",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
