// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticOrderBookDepthSurgeRequest 는 호가잔량급증요청(ka10021) 요청이다.
type GetDomesticOrderBookDepthSurgeRequest struct {
	// 시장구분 (필수, 3자, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 매매구분 (필수, 1자, 1:매수잔량, 2:매도잔량)
	TrdeTp string `json:"trde_tp"`
	// 정렬구분 (필수, 1자, 1:급증량, 2:급증률)
	SortTp string `json:"sort_tp"`
	// 시간구분 (필수, 2자, 분 입력)
	TmTp string `json:"tm_tp"`
	// 거래량구분 (필수, 4자, 1:천주이상, 5:5천주이상, 10:만주이상, 50:5만주이상, 100:10만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (필수, 1자, 0:전체조회, 1:관리종목제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기)
	StkCnd string `json:"stk_cnd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticOrderBookDepthSurgeResponse 는 호가잔량급증요청(ka10021) 응답이다.
type GetDomesticOrderBookDepthSurgeResponse struct {
	// 호가잔량급증
	BidReqSdnin []GetDomesticOrderBookDepthSurgeBidReqSdninItem `json:"bid_req_sdnin"`
}

// GetDomesticOrderBookDepthSurgeBidReqSdninItem 는 BidReqSdnin 의 원소다.
type GetDomesticOrderBookDepthSurgeBidReqSdninItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 기준량 (20자, 단위: 1주)
	Int string `json:"int"`
	// 현재 (20자, 단위: 1주)
	Now string `json:"now"`
	// 급증수량 (20자, 단위: 1주)
	SdninQty string `json:"sdnin_qty"`
	// 급증률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	SdninRt string `json:"sdnin_rt"`
	// 총매수량 (20자, 단위: 1주)
	TotBuyQty string `json:"tot_buy_qty"`
}

// GetDomesticOrderBookDepthSurge 는 호가잔량급증요청(ka10021) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 호가잔량급증요청(ka10021)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticOrderBookDepthSurge(ctx context.Context, req GetDomesticOrderBookDepthSurgeRequest, opts ...transport.Option) (*GetDomesticOrderBookDepthSurgeResponse, transport.Meta, error) {
	var out GetDomesticOrderBookDepthSurgeResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10021",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
