// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopRequest 는 외인한도소진율증가상위(ka10036) 요청이다.
type GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 기간 (필수, 2자, 0:당일, 1:전일, 5:5일, 10;10일, 20:20일, 60:60일)
	Dt string `json:"dt"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopResponse 는 외인한도소진율증가상위(ka10036) 응답이다.
type GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopResponse struct {
	// 외인한도소진율증가상위
	ForLimitExhRtIncrsUpper []GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopForLimitExhRtIncrsUpperItem `json:"for_limit_exh_rt_incrs_upper"`
}

// GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopForLimitExhRtIncrsUpperItem 는 ForLimitExhRtIncrsUpper 의 원소다.
type GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopForLimitExhRtIncrsUpperItem struct {
	// 순위 (20자)
	Rank string `json:"rank"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 보유주식수 (20자, 단위: 1주)
	PossStkcnt string `json:"poss_stkcnt"`
	// 취득가능주식수 (20자, 단위: 1주)
	GainPosStkcnt string `json:"gain_pos_stkcnt"`
	// 기준한도소진율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BaseLimitExhRt string `json:"base_limit_exh_rt"`
	// 한도소진율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	LimitExhRt string `json:"limit_exh_rt"`
	// 소진율증가 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ExhRtIncrs string `json:"exh_rt_incrs"`
}

// GetDomesticForeignInvestorLimitExhaustionRateIncreaseTop 는 외인한도소진율증가상위(ka10036) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 외인한도소진율증가상위(ka10036)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticForeignInvestorLimitExhaustionRateIncreaseTop(ctx context.Context, req GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopRequest, opts ...transport.Option) (*GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopResponse, transport.Meta, error) {
	var out GetDomesticForeignInvestorLimitExhaustionRateIncreaseTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10036",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
