// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticForeignInvestorPeriodTradeTopRequest 는 외인기간별매매상위요청(ka10034) 요청이다.
type GetDomesticForeignInvestorPeriodTradeTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 매매구분 (필수, 1자, 1:순매도, 2:순매수, 3:순매매)
	TrdeTp string `json:"trde_tp"`
	// 기간 (필수, 2자, 0:당일, 1:전일, 5:5일, 10;10일, 20:20일, 60:60일)
	Dt string `json:"dt"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticForeignInvestorPeriodTradeTopResponse 는 외인기간별매매상위요청(ka10034) 응답이다.
type GetDomesticForeignInvestorPeriodTradeTopResponse struct {
	// 외인기간별매매상위
	ForDtTrdeUpper []GetDomesticForeignInvestorPeriodTradeTopForDtTrdeUpperItem `json:"for_dt_trde_upper"`
}

// GetDomesticForeignInvestorPeriodTradeTopForDtTrdeUpperItem 는 ForDtTrdeUpper 의 원소다.
type GetDomesticForeignInvestorPeriodTradeTopForDtTrdeUpperItem struct {
	// 순위 (20자)
	Rank string `json:"rank"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 매도호가 (20자, 단위: 원, 부호가 포함된 숫자)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 부호가 포함된 숫자)
	BuyBid string `json:"buy_bid"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 순매수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	NetprpsQty string `json:"netprps_qty"`
	// 취득가능주식수 (20자, 단위: 1주)
	GainPosStkcnt string `json:"gain_pos_stkcnt"`
}

// GetDomesticForeignInvestorPeriodTradeTop 는 외인기간별매매상위요청(ka10034) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 외인기간별매매상위요청(ka10034)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticForeignInvestorPeriodTradeTop(ctx context.Context, req GetDomesticForeignInvestorPeriodTradeTopRequest, opts ...transport.Option) (*GetDomesticForeignInvestorPeriodTradeTopResponse, transport.Meta, error) {
	var out GetDomesticForeignInvestorPeriodTradeTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10034",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
