// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticStockBrokerRankRequest 는 종목별증권사순위요청(ka10038) 요청이다.
type GetDomesticStockBrokerRankRequest struct {
	// 종목코드 (필수, 6자, 거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL))
	StkCd string `json:"stk_cd"`
	// 시작일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD (연도4자리, 월 2자리, 일 2자리 형식))
	EndDt string `json:"end_dt"`
	// 조회구분 (필수, 1자, 1:순매도순위정렬, 2:순매수순위정렬)
	QryTp string `json:"qry_tp"`
	// 기간 (2자, 1:전일, 4:5일, 9:10일, 19:20일, 39:40일, 59:60일, 119:120일 ※ 시작일자와 종료일자로 조회를 원하는 경우 기간(dt)값은 빈값('')으로 설정)
	Dt string `json:"dt"`
}

// GetDomesticStockBrokerRankResponse 는 종목별증권사순위요청(ka10038) 응답이다.
type GetDomesticStockBrokerRankResponse struct {
	// 기간별 누적 매수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	Rank1 string `json:"rank_1"`
	// 기간별 누적 매도량 (20자, 단위: 1주, 부호가 포함된 숫자)
	Rank2 string `json:"rank_2"`
	// 기간별 누적 순매수 (20자, 단위: 1주, 부호가 포함된 숫자)
	Rank3 string `json:"rank_3"`
	// 기간중거래량 (20자, 단위: 1주)
	PridTrdeQty string `json:"prid_trde_qty"`
	// 종목별증권사순위
	StkSecRank []GetDomesticStockBrokerRankStkSecRankItem `json:"stk_sec_rank"`
}

// GetDomesticStockBrokerRankStkSecRankItem 는 StkSecRank 의 원소다.
type GetDomesticStockBrokerRankStkSecRankItem struct {
	// 순위 (20자)
	Rank string `json:"rank"`
	// 회원사명 (20자)
	MmcmNm string `json:"mmcm_nm"`
	// 매수수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	BuyQty string `json:"buy_qty"`
	// 매도수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	SellQty string `json:"sell_qty"`
	// 누적순매수수량 (20자, 단위: 1주, 부호가 포함된 숫자)
	AccNetprpsQty string `json:"acc_netprps_qty"`
}

// GetDomesticStockBrokerRank 는 종목별증권사순위요청(ka10038) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 종목별증권사순위요청(ka10038)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticStockBrokerRank(ctx context.Context, req GetDomesticStockBrokerRankRequest, opts ...transport.Option) (*GetDomesticStockBrokerRankResponse, transport.Meta, error) {
	var out GetDomesticStockBrokerRankResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10038",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
