// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticCreditRatioTopRequest 는 신용비율상위요청(ka10033) 요청이다.
type GetDomesticCreditRatioTopRequest struct {
	// 시장구분 (필수, 3자, 000:전체, 001:코스피, 101:코스닥)
	MrktTp string `json:"mrkt_tp"`
	// 거래량구분 (필수, 3자, 0:전체조회, 10:만주이상, 50:5만주이상, 100:10만주이상, 200:20만주이상, 300:30만주이상, 500:50만주이상, 1000:백만주이상)
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (필수, 1자, 0:전체조회, 1:관리종목제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기)
	StkCnd string `json:"stk_cnd"`
	// 상하한포함 (필수, 1자, 0:상하한 미포함, 1:상하한포함)
	UpdownIncls string `json:"updown_incls"`
	// 신용조건 (필수, 1자, 0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체)
	CrdCnd string `json:"crd_cnd"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT 3.통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticCreditRatioTopResponse 는 신용비율상위요청(ka10033) 응답이다.
type GetDomesticCreditRatioTopResponse struct {
	// 신용비율상위
	CrdRtUpper []GetDomesticCreditRatioTopCrdRtUpperItem `json:"crd_rt_upper"`
}

// GetDomesticCreditRatioTopCrdRtUpperItem 는 CrdRtUpper 의 원소다.
type GetDomesticCreditRatioTopCrdRtUpperItem struct {
	// 종목정보 (20자)
	StkInfr string `json:"stk_infr"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 신용비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CrdRt string `json:"crd_rt"`
	// 매도잔량 (20자, 단위: 1주)
	SelReq string `json:"sel_req"`
	// 매수잔량 (20자, 단위: 1주)
	BuyReq string `json:"buy_req"`
	// 현재거래량 (20자, 단위: 1주)
	NowTrdeQty string `json:"now_trde_qty"`
}

// GetDomesticCreditRatioTop 는 신용비율상위요청(ka10033) 이다.
//
// 메뉴: 국내주식 > 순위정보 > 신용비율상위요청(ka10033)
// URL:  /api/dostk/rkinfo
func (c *Client) GetDomesticCreditRatioTop(ctx context.Context, req GetDomesticCreditRatioTopRequest, opts ...transport.Option) (*GetDomesticCreditRatioTopResponse, transport.Meta, error) {
	var out GetDomesticCreditRatioTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10033",
		Path:  "/api/dostk/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
