// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasCumulativeChangeRateTopRequest 는 미국주식 누적 등락률 상위(주식/업종)(usa20940) 요청이다.
type GetOverseasCumulativeChangeRateTopRequest struct {
	// 거래소 구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// 업종코드 (000:전체, usa10101 API 참고, stk_tp(종목구분) 1일 경우)
	IndsCd string `json:"inds_cd"`
	// 종목구분 (0:전체,1:주식)
	StkTp string `json:"stk_tp"`
	// 정렬기준구분 (0:상승률,1:상승폭,3:하락률,4:하락폭)
	SortTp string `json:"sort_tp"`
	// 가격1 구분
	PricCnd1 string `json:"pric_cnd1"`
	// 가격2 구분
	PricCnd2 string `json:"pric_cnd2"`
	// 기준일자 (YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 종목조건 (0:전체)
	StkCnd string `json:"stk_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 검색가격대 구분 (0:전체 1:5미만,2:10미만,3:10이상,4:10~20,5: 20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasCumulativeChangeRateTopResponse 는 미국주식 누적 등락률 상위(주식/업종)(usa20940) 응답이다.
type GetOverseasCumulativeChangeRateTopResponse struct {
	// 결과리스트
	ResultList []GetOverseasCumulativeChangeRateTopResultListItem `json:"result_list"`
}

// GetOverseasCumulativeChangeRateTopResultListItem 는 ResultList 의 원소다.
type GetOverseasCumulativeChangeRateTopResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 최고가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	HgstPric string `json:"hgst_pric"`
	// 종목최고일자 (YYYYMMDD)
	StkHighDt string `json:"stk_high_dt"`
	// 최저가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	LwstPric string `json:"lwst_pric"`
	// 종목최저일자 (YYYYMMDD)
	StkLowDt string `json:"stk_low_dt"`
	// 누적등락률 (단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	AccFluRt string `json:"acc_flu_rt"`
	// 누적등락폭 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	AccFluAmt string `json:"acc_flu_amt"`
}

// GetOverseasCumulativeChangeRateTop 는 미국주식 누적 등락률 상위(주식/업종)(usa20940) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 누적 등락률 상위(주식/업종)(usa20940)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasCumulativeChangeRateTop(ctx context.Context, req GetOverseasCumulativeChangeRateTopRequest, opts ...transport.Option) (*GetOverseasCumulativeChangeRateTopResponse, transport.Meta, error) {
	var out GetOverseasCumulativeChangeRateTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20940",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
