// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasHighLowPriceRiseFallEtfRequest 는 미국주식 최고최저가대비 상승하락(ETF)(usa24111) 요청이다.
type GetOverseasHighLowPriceRiseFallEtfRequest struct {
	// 거래소 구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// ETF카테고리코드1 (ETF 대카테고리코드 (ETF이고 대분류일 경우 사용), usa10105 cate1 속성 참고)
	EtfCat1 string `json:"etf_cat1"`
	// ETF카테고리코드2 (ETF 중카테고리코드 (ETF이고 중분류일 경우 사용), usa10105 cate2 속성 참고)
	EtfCat2 string `json:"etf_cat2"`
	// 정렬기준구분 (0:저가대비상승,1:고가대비하락)
	SortTp string `json:"sort_tp"`
	// 기간구분 (0:연중,1:52주)
	DtTp string `json:"dt_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 거래량조건 (0:전체 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 가격조건 (0:전체 1:5미만,2:10미만,3:10이상,4:10~20,5: 20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasHighLowPriceRiseFallEtfResponse 는 미국주식 최고최저가대비 상승하락(ETF)(usa24111) 응답이다.
type GetOverseasHighLowPriceRiseFallEtfResponse struct {
	// 결과리스트
	ResultList []GetOverseasHighLowPriceRiseFallEtfResultListItem `json:"result_list"`
}

// GetOverseasHighLowPriceRiseFallEtfResultListItem 는 ResultList 의 원소다.
type GetOverseasHighLowPriceRiseFallEtfResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 연중최고가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OyrHgst string `json:"oyr_hgst"`
	// 연중최저가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OyrLwst string `json:"oyr_lwst"`
	// 52주 최고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	N52wkHgstPric string `json:"52wk_hgst_pric"`
	// 52주 최저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	N52wkLwstPric string `json:"52wk_lwst_pric"`
	// 최저가/최고가 대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	HlPreSig string `json:"hl_pre_sig"`
	// 최저가/최고가대비
	HlPre string `json:"hl_pre"`
	// 대비등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PreFluRt string `json:"pre_flu_rt"`
	// 최고/최저일시 (YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 누적거래량
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetOverseasHighLowPriceRiseFallEtf 는 미국주식 최고최저가대비 상승하락(ETF)(usa24111) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 최고최저가대비 상승하락(ETF)(usa24111)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasHighLowPriceRiseFallEtf(ctx context.Context, req GetOverseasHighLowPriceRiseFallEtfRequest, opts ...transport.Option) (*GetOverseasHighLowPriceRiseFallEtfResponse, transport.Meta, error) {
	var out GetOverseasHighLowPriceRiseFallEtfResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa24111",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
