// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasConsecutiveRiseFallRankEtfRequest 는 미국주식 연속상승/하락 순위(ETF)(usa24161) 요청이다.
type GetOverseasConsecutiveRiseFallRankEtfRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// ETF카테고리코드1 (ETF 대카테고리코드 (ETF이고 대분류일 경우 사용), usa10105 cate1 속성 참고)
	EtfCat1 string `json:"etf_cat1"`
	// ETF카테고리코드2 (ETF 중카테고리코드 (ETF이고 중분류일 경우 사용), usa10105 cate2 속성 참고)
	EtfCat2 string `json:"etf_cat2"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
	// 정렬기준 (0:연속일수상승,1:연속일수보합,2:연속일수하락,3:기준일대비상승,4:기준일대비보합,5:기준일대비 하락)
	SortTp string `json:"sort_tp"`
}

// GetOverseasConsecutiveRiseFallRankEtfResponse 는 미국주식 연속상승/하락 순위(ETF)(usa24161) 응답이다.
type GetOverseasConsecutiveRiseFallRankEtfResponse struct {
	// 결과리스트
	ResultList []GetOverseasConsecutiveRiseFallRankEtfResultListItem `json:"result_list"`
}

// GetOverseasConsecutiveRiseFallRankEtfResultListItem 는 ResultList 의 원소다.
type GetOverseasConsecutiveRiseFallRankEtfResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량
	AccTrdeQty string `json:"acc_trde_qty"`
	// 기준일종가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BaseClosePric string `json:"base_close_pric"`
	// 기준일대비율 (단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	BasePreRt string `json:"base_pre_rt"`
	// 연속일수
	ContiDt string `json:"conti_dt"`
}

// GetOverseasConsecutiveRiseFallRankEtf 는 미국주식 연속상승/하락 순위(ETF)(usa24161) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 연속상승/하락 순위(ETF)(usa24161)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasConsecutiveRiseFallRankEtf(ctx context.Context, req GetOverseasConsecutiveRiseFallRankEtfRequest, opts ...transport.Option) (*GetOverseasConsecutiveRiseFallRankEtfResponse, transport.Meta, error) {
	var out GetOverseasConsecutiveRiseFallRankEtfResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa24161",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
