// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasOrderBookDepthTopEtfRequest 는 미국주식 호가잔량상위(ETF)(usa24201) 요청이다.
type GetOverseasOrderBookDepthTopEtfRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// ETF카테고리코드1 (ETF 대카테고리코드 (ETF이고 대분류일 경우 사용), usa10105 cate1 속성 참고)
	EtfCat1 string `json:"etf_cat1"`
	// ETF카테고리코드2 (ETF 중카테고리코드 (ETF이고 중분류일 경우 사용), usa10105 cate2 속성 참고)
	EtfCat2 string `json:"etf_cat2"`
	// 정렬기준 (1:순매수잔량순,2:순매도잔량순,3:순매수비율순,4: 순매도비율순)
	SortTp string `json:"sort_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasOrderBookDepthTopEtfResponse 는 미국주식 호가잔량상위(ETF)(usa24201) 응답이다.
type GetOverseasOrderBookDepthTopEtfResponse struct {
	// 결과리스트
	ResultList []GetOverseasOrderBookDepthTopEtfResultListItem `json:"result_list"`
}

// GetOverseasOrderBookDepthTopEtfResultListItem 는 ResultList 의 원소다.
type GetOverseasOrderBookDepthTopEtfResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 증거금률
	MgnType string `json:"mgn_type"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 매도호가총잔량 (단위: 1주)
	TotSelReq string `json:"tot_sel_req"`
	// 매수호가총잔량 (단위: 1주)
	TotBuyReq string `json:"tot_buy_req"`
	// 순매수잔량 (순매수잔량/매수비율 검색일 경우)
	BuyReq string `json:"buy_req"`
	// 매수비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58를 의미합니다.)
	BuyRt string `json:"buy_rt"`
	// 순매도잔량 (순매도잔량/매도비율 검색일 경우)
	SelReq string `json:"sel_req"`
	// 매도비율 (소수점 제거 된 100배 값으로 제공 예) "2658"는 26.58를 의미합니다.)
	SelRt string `json:"sel_rt"`
	// 시간 (HH:mm)
	CntrTm string `json:"cntr_tm"`
}

// GetOverseasOrderBookDepthTopEtf 는 미국주식 호가잔량상위(ETF)(usa24201) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 호가잔량상위(ETF)(usa24201)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasOrderBookDepthTopEtf(ctx context.Context, req GetOverseasOrderBookDepthTopEtfRequest, opts ...transport.Option) (*GetOverseasOrderBookDepthTopEtfResponse, transport.Meta, error) {
	var out GetOverseasOrderBookDepthTopEtfResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa24201",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
