// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasChangeRateTopVsOpenWatchlistRequest 는 미국주식 시가대비 등락률상위(관심종목)(usa20922) 요청이다.
type GetOverseasChangeRateTopVsOpenWatchlistRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// 관심종목코드 ([{'stex_tp':'거래소구분','stk_cd':'종목코드'},...])
	StkCd string `json:"stk_cd"`
	// 정렬기준 (1:상승률, 2:하락률)
	SortTp string `json:"sort_tp"`
	// 종목구분 (0:전체,1:주식,2:ETF)
	StkTp string `json:"stk_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
}

// GetOverseasChangeRateTopVsOpenWatchlistResponse 는 미국주식 시가대비 등락률상위(관심종목)(usa20922) 응답이다.
type GetOverseasChangeRateTopVsOpenWatchlistResponse struct {
	// 결과리스트
	ResultList []GetOverseasChangeRateTopVsOpenWatchlistResultListItem `json:"result_list"`
}

// GetOverseasChangeRateTopVsOpenWatchlistResultListItem 는 ResultList 의 원소다.
type GetOverseasChangeRateTopVsOpenWatchlistResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 시가대비 (단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	OpenPricPre string `json:"open_pric_pre"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 시간 (HH:mm)
	CntrTm string `json:"cntr_tm"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
}

// GetOverseasChangeRateTopVsOpenWatchlist 는 미국주식 시가대비 등락률상위(관심종목)(usa20922) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 시가대비 등락률상위(관심종목)(usa20922)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasChangeRateTopVsOpenWatchlist(ctx context.Context, req GetOverseasChangeRateTopVsOpenWatchlistRequest, opts ...transport.Option) (*GetOverseasChangeRateTopVsOpenWatchlistResponse, transport.Meta, error) {
	var out GetOverseasChangeRateTopVsOpenWatchlistResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20922",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
