// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasChangeRateTopVsOpenEtfRequest 는 미국주식 시가대비 등락률상위(ETF)(usa20921) 요청이다.
type GetOverseasChangeRateTopVsOpenEtfRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// ETF카테고리코드1 (ETF 대카테고리코드 (ETF이고 대분류일 경우 사용), usa10105 cate1 속성 참고)
	EtfCat1 string `json:"etf_cat1"`
	// ETF카테고리코드2 (ETF 중카테고리코드 (ETF이고 중분류일 경우 사용), usa10105 cate2 속성 참고)
	EtfCat2 string `json:"etf_cat2"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
	// 정렬기준 (1:상승률,2:하락률)
	SortTp string `json:"sort_tp"`
}

// GetOverseasChangeRateTopVsOpenEtfResponse 는 미국주식 시가대비 등락률상위(ETF)(usa20921) 응답이다.
type GetOverseasChangeRateTopVsOpenEtfResponse struct {
	// 결과리스트
	ResultList []GetOverseasChangeRateTopVsOpenEtfResultListItem `json:"result_list"`
}

// GetOverseasChangeRateTopVsOpenEtfResultListItem 는 ResultList 의 원소다.
type GetOverseasChangeRateTopVsOpenEtfResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 시가대비 등락률 (단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	OpenPricPre string `json:"open_pric_pre"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 체결시간 (HH:mm)
	CntrTm string `json:"cntr_tm"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
}

// GetOverseasChangeRateTopVsOpenEtf 는 미국주식 시가대비 등락률상위(ETF)(usa20921) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 시가대비 등락률상위(ETF)(usa20921)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasChangeRateTopVsOpenEtf(ctx context.Context, req GetOverseasChangeRateTopVsOpenEtfRequest, opts ...transport.Option) (*GetOverseasChangeRateTopVsOpenEtfResponse, transport.Meta, error) {
	var out GetOverseasChangeRateTopVsOpenEtfResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20921",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
