// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasTodayTradeValueTopRequest 는 미국주식 당일 거래대금 상위(주식/업종)(usa20540) 요청이다.
type GetOverseasTodayTradeValueTopRequest struct {
	// 거래소 구분 (0:전체,1:NYSE,2:NASDAQ,3:AMEX)
	StexTp string `json:"stex_tp"`
	// 업종코드 (000:전체, usa10101 API 참고, stk_tp(종목구분) 1일 경우)
	IndsCd string `json:"inds_cd"`
	// 종목 구분 (0:전체,1:주식)
	StkTp string `json:"stk_tp"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 종목필터 구분 (0:전체,1:증100%만보기,2:증50%만보기)
	StkCnd string `json:"stk_cnd"`
	// 검색가격대 구분 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5: 20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// GetOverseasTodayTradeValueTopResponse 는 미국주식 당일 거래대금 상위(주식/업종)(usa20540) 응답이다.
type GetOverseasTodayTradeValueTopResponse struct {
	// 결과리스트
	ResultList []GetOverseasTodayTradeValueTopResultListItem `json:"result_list"`
}

// GetOverseasTodayTradeValueTopResultListItem 는 ResultList 의 원소다.
type GetOverseasTodayTradeValueTopResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 거래소 구분 (ND:NASDAQ,NY:NYSE,NA:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 전일거래량 (단위: 1주)
	PredTrdeQty string `json:"pred_trde_qty"`
	// 거래대금 (단위: 천USD)
	TrdePrica string `json:"trde_prica"`
}

// GetOverseasTodayTradeValueTop 는 미국주식 당일 거래대금 상위(주식/업종)(usa20540) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 당일 거래대금 상위(주식/업종)(usa20540)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasTodayTradeValueTop(ctx context.Context, req GetOverseasTodayTradeValueTopRequest, opts ...transport.Option) (*GetOverseasTodayTradeValueTopResponse, transport.Meta, error) {
	var out GetOverseasTodayTradeValueTopResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20540",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
