// Code generated by tools/gen. DO NOT EDIT.

package ranking

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasRiseFallByDateRequest 는 미국주식 특정일자 상승/하락 (주식/업종)(usa24120) 요청이다.
type GetOverseasRiseFallByDateRequest struct {
	// 거래소구분 (0:전체,1:NYSE,2:AMEX,3:NASDAQ)
	StexTp string `json:"stex_tp"`
	// 업종코드 (000:전체, usa10101 API 참고, stk_tp(종목구분) 1일 경우)
	IndsCd string `json:"inds_cd"`
	// 종목구분 (0:전체,1:주식)
	StkTp string `json:"stk_tp"`
	// 종목조건 (0:전체,1:증100%,2:증50%)
	StkCnd string `json:"stk_cnd"`
	// 가격조건 (0:전체,1:5미만,2:10미만,3:10이상,4:10~20,5:20~50,6:50이상,7:50~100,8:100미만,9:100이상,10:500이상)
	PricCnd string `json:"pric_cnd"`
	// 거래량조건 (0:전체, 10,15,20,30,50,100,300,500(1만단위) 이상 (ex. 50: 50만 이상))
	TrdeQtyTp string `json:"trde_qty_tp"`
	// 거래대금조건 (0:전체 1,3,5,10,30,50,100,300,500,1000,3000,5000(USD, 1만단위) 이상 (ex. 50: USD 50만 이상))
	TrdePricaCnd string `json:"trde_prica_cnd"`
	// 기간 (YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 정렬기준 구분 (0:상승,2:하락)
	SortTp string `json:"sort_tp"`
}

// GetOverseasRiseFallByDateResponse 는 미국주식 특정일자 상승/하락 (주식/업종)(usa24120) 응답이다.
type GetOverseasRiseFallByDateResponse struct {
	// 결과리스트
	ResultList []GetOverseasRiseFallByDateResultListItem `json:"result_list"`
}

// GetOverseasRiseFallByDateResultListItem 는 ResultList 의 원소다.
type GetOverseasRiseFallByDateResultListItem struct {
	// 순위
	Rank string `json:"rank"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 기준일자 (YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적거래대금
	TrdePrica string `json:"trde_prica"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 등락률 (단위: %, 소수점 다섯째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
}

// GetOverseasRiseFallByDate 는 미국주식 특정일자 상승/하락 (주식/업종)(usa24120) 이다.
//
// 메뉴: 미국주식 > 순위정보 > 미국주식 특정일자 상승/하락 (주식/업종)(usa24120)
// URL:  /api/us/rkinfo
func (c *Client) GetOverseasRiseFallByDate(ctx context.Context, req GetOverseasRiseFallByDateRequest, opts ...transport.Option) (*GetOverseasRiseFallByDateResponse, transport.Meta, error) {
	var out GetOverseasRiseFallByDateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa24120",
		Path:  "/api/us/rkinfo",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
