// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockDailyPriceRequest 는 미국주식 일별주가(usa20590) 요청이다.
type GetOverseasStockDailyPriceRequest struct {
	// 거래소구분 (NA:AMEX,ND:NASDAQ,NY:NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 기준일자 (기준일자 이전 내역 조회)
	BaseDt string `json:"base_dt"`
}

// GetOverseasStockDailyPriceResponse 는 미국주식 일별주가(usa20590) 응답이다.
type GetOverseasStockDailyPriceResponse struct {
	// 결과리스트
	ResultList []GetOverseasStockDailyPriceResultListItem `json:"result_list"`
}

// GetOverseasStockDailyPriceResultListItem 는 ResultList 의 원소다.
type GetOverseasStockDailyPriceResultListItem struct {
	// 일자 (YYYYMMDD)
	Dt string `json:"dt"`
	// 현재가(종가) (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적금액 (단위: 천USD)
	TrdePrica string `json:"trde_prica"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 기준가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BasePric string `json:"base_pric"`
	// 기준가대비 시가등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BaseOpenFluRt string `json:"base_open_flu_rt"`
	// 기준가대비 고가등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BaseHighFluRt string `json:"base_high_flu_rt"`
	// 기준가대비 저가등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	BaseLowFluRt string `json:"base_low_flu_rt"`
}

// GetOverseasStockDailyPrice 는 미국주식 일별주가(usa20590) 이다.
//
// 메뉴: 미국주식 > 시세 > 미국주식 일별주가(usa20590)
// URL:  /api/us/mrkcond
func (c *Client) GetOverseasStockDailyPrice(ctx context.Context, req GetOverseasStockDailyPriceRequest, opts ...transport.Option) (*GetOverseasStockDailyPriceResponse, transport.Meta, error) {
	var out GetOverseasStockDailyPriceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20590",
		Path:  "/api/us/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
