// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockQuoteRequest 는 미국주식 현재가 종목정보(usa20100) 요청이다.
type GetOverseasStockQuoteRequest struct {
	// 거래소구분 (필수, NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasStockQuoteResponse 는 미국주식 현재가 종목정보(usa20100) 응답이다.
type GetOverseasStockQuoteResponse struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 52주 최고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	N52wkHgstPric string `json:"52wk_hgst_pric"`
	// 52주 최고가 대비율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N52wkHgstPricPreRt string `json:"52wk_hgst_pric_pre_rt"`
	// 52주 최고가일 (YYYYMMDD)
	N52wkHgstPricDt string `json:"52wk_hgst_pric_dt"`
	// 52주 최저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	N52wkLwstPric string `json:"52wk_lwst_pric"`
	// 52주 최저가 대비율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	N52wkLwstPricPreRt string `json:"52wk_lwst_pric_pre_rt"`
	// 52주 최저가일 (YYYYMMDD)
	N52wkLwstPricDt string `json:"52wk_lwst_pric_dt"`
	// 주식수 (단위: 1주)
	StkCnt string `json:"stk_cnt"`
	// 시가총액 (단위: 천USD)
	Mac string `json:"mac"`
	// 결산월
	SetlMm string `json:"setl_mm"`
	// 대업종구분
	LgIndsCd string `json:"lg_inds_cd"`
	// 소업종구분
	SmIndsCd string `json:"sm_inds_cd"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량 (단위: 1주)
	AccTrdeQty string `json:"acc_trde_qty"`
	// 연중최고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OyrHgst string `json:"oyr_hgst"`
	// 연중최고가일 (YYYYMMDD)
	OyrHgstDt string `json:"oyr_hgst_dt"`
	// 연중최고가 대비율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	OyrHgstPreRt string `json:"oyr_hgst_pre_rt"`
	// 연중최저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OyrLwst string `json:"oyr_lwst"`
	// 연중최저가일 (YYYYMMDD)
	OyrLwstDt string `json:"oyr_lwst_dt"`
	// 연중최저가 대비율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	OyrLwstPreRt string `json:"oyr_lwst_pre_rt"`
	// 전일시가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	PreOpenPric string `json:"pre_open_pric"`
	// 전일고가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	PreHighPric string `json:"pre_high_pric"`
	// 전일저가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	PreLowPric string `json:"pre_low_pric"`
	// 전일종가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BaseClosePric string `json:"base_close_pric"`
	// 상한가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	UplPric string `json:"upl_pric"`
	// 하한가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	LstPric string `json:"lst_pric"`
	// 매매수량단위
	TrdeQtyUnit string `json:"trde_qty_unit"`
	// 불확실성
	UncertLv string `json:"uncert_lv"`
	// 경쟁우위
	CompAdvTp string `json:"comp_adv_tp"`
	// 통화단위
	CurrUnit string `json:"curr_unit"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 거래정지여부
	TrdSuspTp string `json:"trd_susp_tp"`
	// 환율 (소수점 둘째 자리까지 포맷된 숫자)
	BaseExrt string `json:"base_exrt"`
}

// GetOverseasStockQuote 는 미국주식 현재가 종목정보(usa20100) 이다.
//
// 메뉴: 미국주식 > 시세 > 미국주식 현재가 종목정보(usa20100)
// URL:  /api/us/mrkcond
func (c *Client) GetOverseasStockQuote(ctx context.Context, req GetOverseasStockQuoteRequest, opts ...transport.Option) (*GetOverseasStockQuoteResponse, transport.Meta, error) {
	var out GetOverseasStockQuoteResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20100",
		Path:  "/api/us/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
