// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasOrderBookRequest 는 미국주식 현재가 10호가(usa20101) 요청이다.
type GetOverseasOrderBookRequest struct {
	// 거래소구분 (필수, NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasOrderBookResponse 는 미국주식 현재가 10호가(usa20101) 응답이다.
type GetOverseasOrderBookResponse struct {
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 종목영문명
	StkEnm string `json:"stk_enm"`
	// 현재가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 거래대금 (단위: 천USD)
	TrdePrica string `json:"trde_prica"`
	// 시가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 호가시간 (HH:mm)
	BidTm string `json:"bid_tm"`
	// 일자 (YYYYMMDD)
	Dt string `json:"dt"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
	// 최우선매도호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	FprSelBid string `json:"fpr_sel_bid"`
	// 최우선매수호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	FprBuyBid string `json:"fpr_buy_bid"`
	// 전일거래대비 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PreTrdeRt string `json:"pre_trde_rt"`
	// 거래회전율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TrdeTernRt string `json:"trde_tern_rt"`
	// 매도1호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel1bid string `json:"sel_1bid"`
	// 매도2호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel2bid string `json:"sel_2bid"`
	// 매도3호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel3bid string `json:"sel_3bid"`
	// 매도4호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel4bid string `json:"sel_4bid"`
	// 매도5호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel5bid string `json:"sel_5bid"`
	// 매도6호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel6bid string `json:"sel_6bid"`
	// 매도7호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel7bid string `json:"sel_7bid"`
	// 매도8호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel8bid string `json:"sel_8bid"`
	// 매도9호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel9bid string `json:"sel_9bid"`
	// 매도10호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Sel10bid string `json:"sel_10bid"`
	// 매수1호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy1bid string `json:"buy_1bid"`
	// 매수2호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy2bid string `json:"buy_2bid"`
	// 매수3호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy3bid string `json:"buy_3bid"`
	// 매수4호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy4bid string `json:"buy_4bid"`
	// 매수5호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy5bid string `json:"buy_5bid"`
	// 매수6호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy6bid string `json:"buy_6bid"`
	// 매수7호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy7bid string `json:"buy_7bid"`
	// 매수8호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy8bid string `json:"buy_8bid"`
	// 매수9호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy9bid string `json:"buy_9bid"`
	// 매수10호가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	Buy10bid string `json:"buy_10bid"`
	// 매도1호가잔량 (단위: 1주)
	Sel1bidReq string `json:"sel_1bid_req"`
	// 매도2호가잔량 (단위: 1주)
	Sel2bidReq string `json:"sel_2bid_req"`
	// 매도3호가잔량 (단위: 1주)
	Sel3bidReq string `json:"sel_3bid_req"`
	// 매도4호가잔량 (단위: 1주)
	Sel4bidReq string `json:"sel_4bid_req"`
	// 매도5호가잔량 (단위: 1주)
	Sel5bidReq string `json:"sel_5bid_req"`
	// 매도6호가잔량 (단위: 1주)
	Sel6bidReq string `json:"sel_6bid_req"`
	// 매도7호가잔량 (단위: 1주)
	Sel7bidReq string `json:"sel_7bid_req"`
	// 매도8호가잔량 (단위: 1주)
	Sel8bidReq string `json:"sel_8bid_req"`
	// 매도9호가잔량 (단위: 1주)
	Sel9bidReq string `json:"sel_9bid_req"`
	// 매도10호가잔량 (단위: 1주)
	Sel10bidReq string `json:"sel_10bid_req"`
	// 매수1호가잔량 (단위: 1주)
	Buy1bidReq string `json:"buy_1bid_req"`
	// 매수2호가잔량 (단위: 1주)
	Buy2bidReq string `json:"buy_2bid_req"`
	// 매수3호가잔량 (단위: 1주)
	Buy3bidReq string `json:"buy_3bid_req"`
	// 매수4호가잔량 (단위: 1주)
	Buy4bidReq string `json:"buy_4bid_req"`
	// 매수5호가잔량 (단위: 1주)
	Buy5bidReq string `json:"buy_5bid_req"`
	// 매수6호가잔량 (단위: 1주)
	Buy6bidReq string `json:"buy_6bid_req"`
	// 매수7호가잔량 (단위: 1주)
	Buy7bidReq string `json:"buy_7bid_req"`
	// 매수8호가잔량 (단위: 1주)
	Buy8bidReq string `json:"buy_8bid_req"`
	// 매수9호가잔량 (단위: 1주)
	Buy9bidReq string `json:"buy_9bid_req"`
	// 매수10호가잔량 (단위: 1주)
	Buy10bidReq string `json:"buy_10bid_req"`
	// 매도1호가직전대비
	Sel1bidJubPre string `json:"sel_1bid_jub_pre"`
	// 매도2호가직전대비
	Sel2bidJubPre string `json:"sel_2bid_jub_pre"`
	// 매도3호가직전대비
	Sel3bidJubPre string `json:"sel_3bid_jub_pre"`
	// 매도4호가직전대비
	Sel4bidJubPre string `json:"sel_4bid_jub_pre"`
	// 매도5호가직전대비
	Sel5bidJubPre string `json:"sel_5bid_jub_pre"`
	// 매도6호가직전대비
	Sel6bidJubPre string `json:"sel_6bid_jub_pre"`
	// 매도7호가직전대비
	Sel7bidJubPre string `json:"sel_7bid_jub_pre"`
	// 매도8호가직전대비
	Sel8bidJubPre string `json:"sel_8bid_jub_pre"`
	// 매도9호가직전대비
	Sel9bidJubPre string `json:"sel_9bid_jub_pre"`
	// 매도10호가직전대비
	Sel10bidJubPre string `json:"sel_10bid_jub_pre"`
	// 매수1차선잔량대비
	Buy1thPreReqPre string `json:"buy_1th_pre_req_pre"`
	// 매수1호가직전대비
	Buy1bidJubPre string `json:"buy_1bid_jub_pre"`
	// 매수2호가직전대비
	Buy2bidJubPre string `json:"buy_2bid_jub_pre"`
	// 매수3호가직전대비
	Buy3bidJubPre string `json:"buy_3bid_jub_pre"`
	// 매수4호가직전대비
	Buy4bidJubPre string `json:"buy_4bid_jub_pre"`
	// 매수5호가직전대비
	Buy5bidJubPre string `json:"buy_5bid_jub_pre"`
	// 매수6호가직전대비
	Buy6bidJubPre string `json:"buy_6bid_jub_pre"`
	// 매수7호가직전대비
	Buy7bidJubPre string `json:"buy_7bid_jub_pre"`
	// 매수8호가직전대비
	Buy8bidJubPre string `json:"buy_8bid_jub_pre"`
	// 매수9호가직전대비
	Buy9bidJubPre string `json:"buy_9bid_jub_pre"`
	// 매수10호가직전대비
	Buy10bidJubPre string `json:"buy_10bid_jub_pre"`
	// 총매도잔량 (단위: 1주)
	TotSelReq string `json:"tot_sel_req"`
	// 매도호가총잔량직전대비
	SelBidTotReqJubPre string `json:"sel_bid_tot_req_jub_pre"`
	// 총매수잔량 (단위: 1주)
	TotBuyReq string `json:"tot_buy_req"`
	// 매수호가총잔량직전대비
	BuyBidTotReqJubPre string `json:"buy_bid_tot_req_jub_pre"`
	// 순매수잔량 (단위: 1주)
	NetprpsReq string `json:"netprps_req"`
	// 순매도잔량 (단위: 1주)
	NetslmtReq string `json:"netslmt_req"`
	// 상한가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	UplPric string `json:"upl_pric"`
	// 기준가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BasePric string `json:"base_pric"`
}

// GetOverseasOrderBook 는 미국주식 현재가 10호가(usa20101) 이다.
//
// 메뉴: 미국주식 > 시세 > 미국주식 현재가 10호가(usa20101)
// URL:  /api/us/mrkcond
func (c *Client) GetOverseasOrderBook(ctx context.Context, req GetOverseasOrderBookRequest, opts ...transport.Option) (*GetOverseasOrderBookResponse, transport.Meta, error) {
	var out GetOverseasOrderBookResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20101",
		Path:  "/api/us/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
