// Code generated by tools/gen. DO NOT EDIT.

package quote

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockTradeDetailsRequest 는 미국주식 상세 체결내역(usa20150) 요청이다.
type GetOverseasStockTradeDetailsRequest struct {
	// 거래소구분 (필수, NA:AMEX,ND:NASDAQ,NY:NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasStockTradeDetailsResponse 는 미국주식 상세 체결내역(usa20150) 응답이다.
type GetOverseasStockTradeDetailsResponse struct {
	// 결과리스트
	ResultList []GetOverseasStockTradeDetailsResultListItem `json:"result_list"`
}

// GetOverseasStockTradeDetailsResultListItem 는 ResultList 의 원소다.
type GetOverseasStockTradeDetailsResultListItem struct {
	// 현재가, 종가 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (단위: 1주, 부호가 포함된 숫자)
	TrdeQty string `json:"trde_qty"`
	// 체결시간 (HHmmss)
	CntrTm string `json:"cntr_tm"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PredPreSig string `json:"pred_pre_sig"`
}

// GetOverseasStockTradeDetails 는 미국주식 상세 체결내역(usa20150) 이다.
//
// 메뉴: 미국주식 > 시세 > 미국주식 상세 체결내역(usa20150)
// URL:  /api/us/mrkcond
func (c *Client) GetOverseasStockTradeDetails(ctx context.Context, req GetOverseasStockTradeDetailsRequest, opts ...transport.Option) (*GetOverseasStockTradeDetailsResponse, transport.Meta, error) {
	var out GetOverseasStockTradeDetailsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa20150",
		Path:  "/api/us/mrkcond",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
