// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasTodayOrderFillsRequest 는 미국주식 당일 주문체결 확인(ust21510) 요청이다.
type GetOverseasTodayOrderFillsRequest struct {
	// 매도매수구분 (1자, 0:전체,1:매도,2:매수)
	SlbyTp string `json:"slby_tp"`
	// 거래소구분 (2자, 종목코드 입력시)
	StexTp string `json:"stex_tp"`
	// 종목코드 (12자, 미입력시 전체)
	StkCd string `json:"stk_cd"`
}

// GetOverseasTodayOrderFillsResponse 는 미국주식 당일 주문체결 확인(ust21510) 응답이다.
type GetOverseasTodayOrderFillsResponse struct {
	// 조회결과리스트
	ResultList []GetOverseasTodayOrderFillsResultListItem `json:"result_list"`
}

// GetOverseasTodayOrderFillsResultListItem 는 ResultList 의 원소다.
type GetOverseasTodayOrderFillsResultListItem struct {
	// 주문번호 (9자)
	OrdNo string `json:"ord_no"`
	// 원주문번호 (9자)
	OrigOrdNo string `json:"orig_ord_no"`
	// 거래소명 (30자)
	StexNm string `json:"stex_nm"`
	// 통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 종목명 (50자)
	FrgnStkNm string `json:"frgn_stk_nm"`
	// 매매구분 (2자, 00:지정가,03:시장가,11:Enhanced Limit Order,12:Special Limit Order,30:Limit On Close,33:Market On Close,34:Stop Limit,35:Stop Market,36:VWAP,37:TWAP)
	FrgnTrdeTp string `json:"frgn_trde_tp"`
	// 매매구분명 (30자)
	FrgnTrdeNm string `json:"frgn_trde_nm"`
	// 매도매수구분 (1자, 1:매도,2:매수)
	SlbyTp string `json:"slby_tp"`
	// 매도매수구분명 (4자)
	SlbyTpNm string `json:"slby_tp_nm"`
	// 주문수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OrdUv string `json:"ord_uv"`
	// STOP가격 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	StopPric string `json:"stop_pric"`
	// 체결수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	CntrUv string `json:"cntr_uv"`
	// 확인수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CnfmQty string `json:"cnfm_qty"`
	// 주문잔량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdRemnq string `json:"ord_remnq"`
	// 주문시간 (8자, HH:mm:ss)
	OrdTime string `json:"ord_time"`
	// 주문응답시간 (8자, HH:mm:ss)
	OrdRespTime string `json:"ord_resp_time"`
	// 주문상태명 (25자)
	OrdStat string `json:"ord_stat"`
	// 예약주문구분 (12자, 0:일반, 1:예약)
	RsrvTp string `json:"rsrv_tp"`
	// 국가명 (40자)
	NatnNm string `json:"natn_nm"`
	// 체결시간 (8자)
	CntrTime string `json:"cntr_time"`
}

// GetOverseasTodayOrderFills 는 미국주식 당일 주문체결 확인(ust21510) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 당일 주문체결 확인(ust21510)
// URL:  /api/us/acnt
func (c *Client) GetOverseasTodayOrderFills(ctx context.Context, req GetOverseasTodayOrderFillsRequest, opts ...transport.Option) (*GetOverseasTodayOrderFillsResponse, transport.Meta, error) {
	var out GetOverseasTodayOrderFillsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21510",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
