// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasRealizedPnlRequest 는 미국주식 실현손익(ust21530) 요청이다.
type GetOverseasRealizedPnlRequest struct {
	// 시작일자 (8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 외화원화구분 (1자, 0:외화,1:원화)
	FcKrwTp string `json:"fc_krw_tp"`
}

// GetOverseasRealizedPnlResponse 는 미국주식 실현손익(ust21530) 응답이다.
type GetOverseasRealizedPnlResponse struct {
	// 총매도금액 (15자)
	TotSellAmt string `json:"tot_sell_amt"`
	// 총매수금액 (15자)
	TotBuyAmt string `json:"tot_buy_amt"`
	// 총수수료제세금 (15자)
	TotCmsnTax string `json:"tot_cmsn_tax"`
	// 총정산금액 (15자)
	TotExctAmt string `json:"tot_exct_amt"`
	// 총손익금액 (15자)
	TotPlAmt string `json:"tot_pl_amt"`
	// 총실현수익률(%) (12자)
	TotPlRt string `json:"tot_pl_rt"`
	// 결과리스트
	ResultList []GetOverseasRealizedPnlResultListItem `json:"result_list"`
}

// GetOverseasRealizedPnlResultListItem 는 ResultList 의 원소다.
type GetOverseasRealizedPnlResultListItem struct {
	// 매도일자 (8자)
	SellDt string `json:"sell_dt"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 종목명 (50자)
	FrgnStkNm string `json:"frgn_stk_nm"`
	// 청산수량 (12자)
	SellQty string `json:"sell_qty"`
	// 매입평균가 (15자)
	AvgBuyUv string `json:"avg_buy_uv"`
	// 매입금액 (15자)
	BuyAmt string `json:"buy_amt"`
	// 매도평균가 (15자)
	AvgSellUv string `json:"avg_sell_uv"`
	// 매도금액 (15자)
	SellAmt string `json:"sell_amt"`
	// 수수료제세금 (15자)
	CmsnTax string `json:"cmsn_tax"`
	// 손익금액 (15자)
	PlAmt string `json:"pl_amt"`
	// 실현수익률(%) (12자)
	PlRt string `json:"pl_rt"`
	// 매입환율 (12자)
	PrchExrt string `json:"prch_exrt"`
	// 매도환율 (12자)
	SellExrt string `json:"sell_exrt"`
	// 환차손익(원) (15자)
	KrwChgDfrnPlAmt string `json:"krw_chg_dfrn_pl_amt"`
	// 환실현손익(원) (15자)
	KrwChgPlAmt string `json:"krw_chg_pl_amt"`
	// 매체구분 (2자)
	CommOrdTp string `json:"comm_ord_tp"`
	// 거래소명 (30자)
	StexNm string `json:"stex_nm"`
	// 국가명 (40자)
	NatnNm string `json:"natn_nm"`
}

// GetOverseasRealizedPnl 는 미국주식 실현손익(ust21530) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 실현손익(ust21530)
// URL:  /api/us/acnt
func (c *Client) GetOverseasRealizedPnl(ctx context.Context, req GetOverseasRealizedPnlRequest, opts ...transport.Option) (*GetOverseasRealizedPnlResponse, transport.Meta, error) {
	var out GetOverseasRealizedPnlResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21530",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
