// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasOrdersByPeriodRequest 는 미국주식 기간별 주문내역(ust21180) 요청이다.
type GetOverseasOrdersByPeriodRequest struct {
	// 시작주문일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료주문일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 매도수구분 (1자, 0:전체(기본값),1:매도,2:매수)
	SlbyTp string `json:"slby_tp"`
	// 거래소구분 (ND:NASDAQ,NY:NYSE,NA:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목코드 (12자, 미입력시 전체)
	StkCd string `json:"stk_cd"`
	// 반대매매구분 (1자, %:전체,0:일반,1:반대매매)
	OppoTrdeTp string `json:"oppo_trde_tp"`
}

// GetOverseasOrdersByPeriodResponse 는 미국주식 기간별 주문내역(ust21180) 응답이다.
type GetOverseasOrdersByPeriodResponse struct {
	// 결과리스트
	ResultList []GetOverseasOrdersByPeriodResultListItem `json:"result_list"`
}

// GetOverseasOrdersByPeriodResultListItem 는 ResultList 의 원소다.
type GetOverseasOrdersByPeriodResultListItem struct {
	// 주문일 (8자, YYYYMMDD)
	OrdDt string `json:"ord_dt"`
	// 주문번호 (9자)
	OrdNo string `json:"ord_no"`
	// 해당통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 매매구분 (40자)
	TrdeTp string `json:"trde_tp"`
	// 주문수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 체결수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 정정수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	MdfyQty string `json:"mdfy_qty"`
	// 취소수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CnclQty string `json:"cncl_qty"`
	// 예약구분 (12자)
	RsrvTp string `json:"rsrv_tp"`
	// 반대매매구분명 (20자)
	OppoTrdeTpNm string `json:"oppo_trde_tp_nm"`
	// 입력매체명 (20자)
	InptChnlTpNm string `json:"inpt_chnl_tp_nm"`
	// 주문시간 (8자, HH:mm:ss)
	OrdTime string `json:"ord_time"`
	// 통화명 (20자)
	CrncNm string `json:"crnc_nm"`
	// 거래소명 (20자)
	StexNm string `json:"stex_nm"`
	// 종목명 (50자)
	StkNm string `json:"stk_nm"`
	// 매도매수구분명 (20자, "1:매도)
	SlbyTpNm string `json:"slby_tp_nm"`
	// 주문단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OrdUv string `json:"ord_uv"`
	// STOP가격 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	StopPric string `json:"stop_pric"`
	// 체결단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	CntrUv string `json:"cntr_uv"`
	// 정정단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	MdfyUv string `json:"mdfy_uv"`
	// 주문잔량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdRemnq string `json:"ord_remnq"`
	// 체결금액 (12자)
	CntrAmt string `json:"cntr_amt"`
	// 통신주문구분명 (20자)
	CommOrdTpNm string `json:"comm_ord_tp_nm"`
}

// GetOverseasOrdersByPeriod 는 미국주식 기간별 주문내역(ust21180) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 기간별 주문내역(ust21180)
// URL:  /api/us/acnt
func (c *Client) GetOverseasOrdersByPeriod(ctx context.Context, req GetOverseasOrdersByPeriodRequest, opts ...transport.Option) (*GetOverseasOrdersByPeriodResponse, transport.Meta, error) {
	var out GetOverseasOrdersByPeriodResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21180",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
