// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasDepositDetailRequest 는 미국주식 예수금 상세(ust21160) 요청이다.
type GetOverseasDepositDetailRequest struct {
}

// GetOverseasDepositDetailResponse 는 미국주식 예수금 상세(ust21160) 응답이다.
type GetOverseasDepositDetailResponse struct {
	// 원화 예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	WonEntr string `json:"won_entr"`
	// 미수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	WonDfrAmt string `json:"won_dfr_amt"`
	// 기타 대여금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	WonEtcLoana string `json:"won_etc_loana"`
	// 해외원화주문설정금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	KrwOrdSetAmt string `json:"krw_ord_set_amt"`
	// 매도환율(USD) (12자, 세자릿수 콤마, 소수점 둘째 자리까지 포맷된 숫자)
	UsdExchRate string `json:"usd_exch_rate"`
	// D0 국내결제일자 (8자, YYYYMMDD)
	D0SetlDt string `json:"d0_setl_dt"`
	// D0 원화환산추정인출가능금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D0WonConvAlowCh string `json:"d0_won_conv_alow_ch"`
	// D0 외화예수금(USD) (15자)
	D0UsdFxEntr string `json:"d0_usd_fx_entr"`
	// D1 국내결제일자 (8자)
	D1SetlDt string `json:"d1_setl_dt"`
	// D1 원화환산추정인출가능금 (15자)
	D1WonConvAlowCh string `json:"d1_won_conv_alow_ch"`
	// D1 외화예수금(USD) (15자)
	D1UsdFxEntr string `json:"d1_usd_fx_entr"`
	// D1 해외정산금(USD) (15자)
	D1UsdExctAmt string `json:"d1_usd_exct_amt"`
	// D1 해외매수정산금(USD) (15자)
	D1UsdBuyExcta string `json:"d1_usd_buy_excta"`
	// D1 해외매도정산금(USD) (15자)
	D1UsdSellExcta string `json:"d1_usd_sell_excta"`
	// D2 국내결제일자 (8자, YYYYMMDD)
	D2SetlDt string `json:"d2_setl_dt"`
	// D2 원화환산추정인출가능금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2WonConvAlowCh string `json:"d2_won_conv_alow_ch"`
	// D2 외화예수금(USD) (15자)
	D2UsdFxEntr string `json:"d2_usd_fx_entr"`
	// D2 해외정산금(USD) (15자)
	D2UsdExctAmt string `json:"d2_usd_exct_amt"`
	// D2 해외매수정산금(USD) (15자)
	D2UsdBuyExcta string `json:"d2_usd_buy_excta"`
	// D2 해외매도정산금(USD) (15자)
	D2UsdSellExcta string `json:"d2_usd_sell_excta"`
	// D3 국내결제일자 (8자, YYYYMMDD)
	D3SetlDt string `json:"d3_setl_dt"`
	// D3 원화환산추정인출가능금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D3WonConvAlowCh string `json:"d3_won_conv_alow_ch"`
	// D3 외화예수금(USD) (15자)
	D3UsdFxEntr string `json:"d3_usd_fx_entr"`
	// D3 해외정산금(USD) (15자)
	D3UsdExctAmt string `json:"d3_usd_exct_amt"`
	// D3 해외매수정산금(USD) (15자)
	D3UsdBuyExcta string `json:"d3_usd_buy_excta"`
	// D3 해외매도정산금(USD) (15자)
	D3UsdSellExcta string `json:"d3_usd_sell_excta"`
	// D4 국내결제일자 (8자, YYYYMMDD)
	D4SetlDt string `json:"d4_setl_dt"`
	// D4 원화환산추정인출가능금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D4WonConvAlowCh string `json:"d4_won_conv_alow_ch"`
	// D4 외화예수금(USD) (15자)
	D4UsdFxEntr string `json:"d4_usd_fx_entr"`
	// D4 해외정산금(USD) (15자)
	D4UsdExctAmt string `json:"d4_usd_exct_amt"`
	// D4 해외매수정산금(USD) (15자)
	D4UsdBuyExcta string `json:"d4_usd_buy_excta"`
	// D4 해외매도정산금(USD) (15자)
	D4UsdSellExcta string `json:"d4_usd_sell_excta"`
}

// GetOverseasDepositDetail 는 미국주식 예수금 상세(ust21160) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 예수금 상세(ust21160)
// URL:  /api/us/acnt
func (c *Client) GetOverseasDepositDetail(ctx context.Context, req GetOverseasDepositDetailRequest, opts ...transport.Option) (*GetOverseasDepositDetailResponse, transport.Meta, error) {
	var out GetOverseasDepositDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21160",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
