// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasMonthlyRealizedPnlRequest 는 미국주식 월별 실현손익(ust21661) 요청이다.
type GetOverseasMonthlyRealizedPnlRequest struct {
	// 시작일자 (6자, YYYYMM)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (6자, YYYYMM)
	EndDt string `json:"end_dt"`
}

// GetOverseasMonthlyRealizedPnlResponse 는 미국주식 월별 실현손익(ust21661) 응답이다.
type GetOverseasMonthlyRealizedPnlResponse struct {
	// 총매수금액 (12자)
	TotBuyAmt string `json:"tot_buy_amt"`
	// 총매도금액 (12자)
	TotSellAmt string `json:"tot_sell_amt"`
	// 총실현손익금액 (12자)
	TotPlAmt string `json:"tot_pl_amt"`
	// 수수료합 (12자)
	TotCmsn string `json:"tot_cmsn"`
	// 세금합 (12자)
	TotTax string `json:"tot_tax"`
	// 결과리스트
	ResultList []GetOverseasMonthlyRealizedPnlResultListItem `json:"result_list"`
}

// GetOverseasMonthlyRealizedPnlResultListItem 는 ResultList 의 원소다.
type GetOverseasMonthlyRealizedPnlResultListItem struct {
	// 매매일자 (8자)
	TrdeDt string `json:"trde_dt"`
	// 매수금액 (12자)
	BuyAmt string `json:"buy_amt"`
	// 매도금액 (12자)
	SellAmt string `json:"sell_amt"`
	// 실현손익금액 (12자)
	PlAmt string `json:"pl_amt"`
	// 수수료 (12자)
	Cmsn string `json:"cmsn"`
	// 세금 (12자)
	Tax string `json:"tax"`
}

// GetOverseasMonthlyRealizedPnl 는 미국주식 월별 실현손익(ust21661) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 월별 실현손익(ust21661)
// URL:  /api/us/acnt
func (c *Client) GetOverseasMonthlyRealizedPnl(ctx context.Context, req GetOverseasMonthlyRealizedPnlRequest, opts ...transport.Option) (*GetOverseasMonthlyRealizedPnlResponse, transport.Meta, error) {
	var out GetOverseasMonthlyRealizedPnlResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21661",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
