// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasMonthlyAccountReturnRateRequest 는 미국주식 월별계좌수익률현황(usa21680) 요청이다.
type GetOverseasMonthlyAccountReturnRateRequest struct {
	// from 년월 (필수, YYYYMM)
	From string `json:"from"`
	// to 년월 (필수, YYYYMM)
	To string `json:"to"`
}

// GetOverseasMonthlyAccountReturnRateResponse 는 미국주식 월별계좌수익률현황(usa21680) 응답이다.
type GetOverseasMonthlyAccountReturnRateResponse struct {
	// 결과리스트
	ResultList []GetOverseasMonthlyAccountReturnRateResultListItem `json:"result_list"`
}

// GetOverseasMonthlyAccountReturnRateResultListItem 는 ResultList 의 원소다.
type GetOverseasMonthlyAccountReturnRateResultListItem struct {
	// 기준일
	BaseDt string `json:"base_dt"`
	// 주식평가금
	StkEvlta string `json:"stk_evlta"`
	// 손익금액
	PlAmt string `json:"pl_amt"`
	// 배당금액
	DvidAmt string `json:"dvid_amt"`
	// 수수료+세금
	CmsnTax string `json:"cmsn_tax"`
	// 누적손익
	AcumPlAmt string `json:"acum_pl_amt"`
	// 출금금액
	PymnAmt string `json:"pymn_amt"`
	// 예탁자산
	Dast string `json:"dast"`
	// 연체금액
	DlyAmt string `json:"dly_amt"`
	// 매도금액
	SellAmt string `json:"sell_amt"`
	// 매수금액
	BuyAmt string `json:"buy_amt"`
	// 수익률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PrftRt string `json:"prft_rt"`
	// 출고금액
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	// 입고금액
	FrgnStkInqAmt string `json:"frgn_stk_inq_amt"`
	// 입금금액
	InaAmt string `json:"ina_amt"`
	// 환율
	Exrt string `json:"exrt"`
}

// GetOverseasMonthlyAccountReturnRate 는 미국주식 월별계좌수익률현황(usa21680) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 월별계좌수익률현황(usa21680)
// URL:  /api/us/acnt
func (c *Client) GetOverseasMonthlyAccountReturnRate(ctx context.Context, req GetOverseasMonthlyAccountReturnRateRequest, opts ...transport.Option) (*GetOverseasMonthlyAccountReturnRateResponse, transport.Meta, error) {
	var out GetOverseasMonthlyAccountReturnRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa21680",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
