// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasLedgerValuationRequest 는 해외증권 원장 평가금액현황(ust21121) 요청이다.
type GetOverseasLedgerValuationRequest struct {
	// 수수료포함구분 (1자, 0:미포함,1:포함)
	CmsnInclTp string `json:"cmsn_incl_tp"`
	// 환율구분 (1자, 0:기준환율,1:계좌적용환율,2:전일최종환율)
	ExrtTp string `json:"exrt_tp"`
}

// GetOverseasLedgerValuationResponse 는 해외증권 원장 평가금액현황(ust21121) 응답이다.
type GetOverseasLedgerValuationResponse struct {
	// 결과리스트
	ResultList []GetOverseasLedgerValuationResultListItem `json:"result_list"`
}

// GetOverseasLedgerValuationResultListItem 는 ResultList 의 원소다.
type GetOverseasLedgerValuationResultListItem struct {
	// 국가명 (20자)
	NatnNm string `json:"natn_nm"`
	// 거래소코드명 (20자)
	StexNm string `json:"stex_nm"`
	// 통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 통화코드명 (20자)
	CrncNm string `json:"crnc_nm"`
	// 평가금액 (15자)
	EvltAmt string `json:"evlt_amt"`
	// 환전평가금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ChgEvltAmt string `json:"chg_evlt_amt"`
	// 평가수익율(%) (12자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PlRt string `json:"pl_rt"`
	// 평가손익 (15자)
	PlAmt string `json:"pl_amt"`
	// 환전평가손익 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ChgProfitAmt string `json:"chg_profit_amt"`
	// 평가금액비중 (7자, 소수점 둘째 자리까지 포맷된 숫자)
	EvltAmtWght string `json:"evlt_amt_wght"`
}

// GetOverseasLedgerValuation 는 해외증권 원장 평가금액현황(ust21121) 이다.
//
// 메뉴: 미국주식 > 계좌 > 해외증권 원장 평가금액현황(ust21121)
// URL:  /api/us/acnt
func (c *Client) GetOverseasLedgerValuation(ctx context.Context, req GetOverseasLedgerValuationRequest, opts ...transport.Option) (*GetOverseasLedgerValuationResponse, transport.Meta, error) {
	var out GetOverseasLedgerValuationResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21121",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
