// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasTodayTradesRequest 는 미국주식 당일매매(ust21610) 요청이다.
type GetOverseasTodayTradesRequest struct {
	// 기준일자 (8자, YYYYMMDD)
	BaseDt string `json:"base_dt"`
	// 조회구분 (필수, 1자, 0:당일매수에대한당일매도,1:당일매도전체)
	QryTp string `json:"qry_tp"`
	// 외화원화구분 (필수, 1자, 0:외화,1:원화)
	FcKrwTp string `json:"fc_krw_tp"`
}

// GetOverseasTodayTradesResponse 는 미국주식 당일매매(ust21610) 응답이다.
type GetOverseasTodayTradesResponse struct {
	// 총매도금액 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TotSellAmt string `json:"tot_sell_amt"`
	// 총매수금액 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TotBuyAmt string `json:"tot_buy_amt"`
	// 총수수료제세금 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TotCmsnAltx string `json:"tot_cmsn_altx"`
	// 총정산금액 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TotExctAmt string `json:"tot_exct_amt"`
	// 총실현손익 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TotPlAmt string `json:"tot_pl_amt"`
	// 총실현손익률 (15자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TotPlRt string `json:"tot_pl_rt"`
	// 기준환율 (15자, 소수점 둘째 자리까지 포맷된 숫자)
	ExchRate string `json:"exch_rate"`
	// 결과리스트
	ResultList []GetOverseasTodayTradesResultListItem `json:"result_list"`
}

// GetOverseasTodayTradesResultListItem 는 ResultList 의 원소다.
type GetOverseasTodayTradesResultListItem struct {
	// 거래소코드명 (20자)
	StexNm string `json:"stex_nm"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 종목명 (50자)
	StkNm string `json:"stk_nm"`
	// 금일매수평균가 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TdyAvgBuyUv string `json:"tdy_avg_buy_uv"`
	// 금일매수수량 (15자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyBuyq string `json:"tdy_buyq"`
	// 금일매입금액 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TdyBuyAmt string `json:"tdy_buy_amt"`
	// 금일매도평균가 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TdyAvgSellUv string `json:"tdy_avg_sell_uv"`
	// 금일매도수량 (15자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdySellq string `json:"tdy_sellq"`
	// 금일매도금액 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	TdySellAmt string `json:"tdy_sell_amt"`
	// 수수료제세금 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	CmsnAltx string `json:"cmsn_altx"`
	// 실현손익 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	PlAmt string `json:"pl_amt"`
	// 실현손익률 (15자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PlRt string `json:"pl_rt"`
	// 이전매입가 (15자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	BfPrchUv string `json:"bf_prch_uv"`
	// 기준환율 (15자, 소수점 둘째 자리까지 포맷된 숫자)
	ExchRate string `json:"exch_rate"`
}

// GetOverseasTodayTrades 는 미국주식 당일매매(ust21610) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 당일매매(ust21610)
// URL:  /api/us/acnt
func (c *Client) GetOverseasTodayTrades(ctx context.Context, req GetOverseasTodayTradesRequest, opts ...transport.Option) (*GetOverseasTodayTradesResponse, transport.Meta, error) {
	var out GetOverseasTodayTradesResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21610",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
