// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasMonthlyStockReturnRateRequest 는 미국주식 월별종목수익률현황(usa21731) 요청이다.
type GetOverseasMonthlyStockReturnRateRequest struct {
	// from 년월 (필수, YYYYMM)
	From string `json:"from"`
	// to 년월 (필수, YYYYMM)
	To string `json:"to"`
	// 거래소구분 (NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
}

// GetOverseasMonthlyStockReturnRateResponse 는 미국주식 월별종목수익률현황(usa21731) 응답이다.
type GetOverseasMonthlyStockReturnRateResponse struct {
	// 결과리스트
	ResultList []GetOverseasMonthlyStockReturnRateResultListItem `json:"result_list"`
}

// GetOverseasMonthlyStockReturnRateResultListItem 는 ResultList 의 원소다.
type GetOverseasMonthlyStockReturnRateResultListItem struct {
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 종목명
	StkNm string `json:"stk_nm"`
	// 최초기준일
	FrstBaseDt string `json:"frst_base_dt"`
	// 최종기준일
	LastBaseDt string `json:"last_base_dt"`
	// 매매수익
	PlAmt string `json:"pl_amt"`
	// 수익률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PrftRt string `json:"prft_rt"`
	// 최초주식평가금
	FrstStkEvlta string `json:"frst_stk_evlta"`
	// 최종주식평가금
	LastStkEvlta string `json:"last_stk_evlta"`
	// 최초수량
	FrstQty string `json:"frst_qty"`
	// 최종수량
	LastQty string `json:"last_qty"`
	// 매수수량 (단위: 1주)
	BuyQty string `json:"buy_qty"`
	// 매도수량 (단위: 1주)
	SellQty string `json:"sell_qty"`
	// 매수금 (단위: 1주)
	BuyAmt string `json:"buy_amt"`
	// 매도금 (단위: 1주)
	SellAmt string `json:"sell_amt"`
	// 입고평가금
	FrgnStkInqAmt string `json:"frgn_stk_inq_amt"`
	// 출고평가금
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	// 수수료+세금
	CmsnTax string `json:"cmsn_tax"`
	// 배당금
	DvidAmt string `json:"dvid_amt"`
	// 통화코드
	CrncCode string `json:"crnc_code"`
}

// GetOverseasMonthlyStockReturnRate 는 미국주식 월별종목수익률현황(usa21731) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 월별종목수익률현황(usa21731)
// URL:  /api/us/acnt
func (c *Client) GetOverseasMonthlyStockReturnRate(ctx context.Context, req GetOverseasMonthlyStockReturnRateRequest, opts ...transport.Option) (*GetOverseasMonthlyStockReturnRateResponse, transport.Meta, error) {
	var out GetOverseasMonthlyStockReturnRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa21731",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
