// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasDepositRequest 는 해외주식 예수금(ust21110) 요청이다.
type GetOverseasDepositRequest struct {
}

// GetOverseasDepositResponse 는 해외주식 예수금(ust21110) 응답이다.
type GetOverseasDepositResponse struct {
	// 원화예수금 (15자)
	KrwEntra string `json:"krw_entra"`
	// 현금미수금 (15자)
	ChUncla string `json:"ch_uncla"`
	// 기타대여금 (15자)
	EtcLoana string `json:"etc_loana"`
	// 결과리스트 (50)
	ResultList []GetOverseasDepositResultListItem `json:"result_list"`
}

// GetOverseasDepositResultListItem 는 ResultList 의 원소다.
type GetOverseasDepositResultListItem struct {
	// 통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 통화명 (20자)
	CrncNm string `json:"crnc_nm"`
	// 외화예수금 (15자)
	FcEntra string `json:"fc_entra"`
	// 외화출금가능금액 (15자)
	FcPymnAlowa string `json:"fc_pymn_alowa"`
	// 선물대용증거금 (15자)
	FutrReplProfa string `json:"futr_repl_profa"`
	// 외화장부금액 (15자)
	FcBooka string `json:"fc_booka"`
	// 외화주문가능금액 (15자)
	FcOrdAlowa string `json:"fc_ord_alowa"`
	// 선물증거금장부금액 (15자)
	FutrProfaBooka string `json:"futr_profa_booka"`
	// 외화현금미수금 (15자)
	FcChUncla string `json:"fc_ch_uncla"`
	// 외화기타대여금 (15자)
	FcEtcLoana string `json:"fc_etc_loana"`
}

// GetOverseasDeposit 는 해외주식 예수금(ust21110) 이다.
//
// 메뉴: 미국주식 > 계좌 > 해외주식 예수금(ust21110)
// URL:  /api/us/acnt
func (c *Client) GetOverseasDeposit(ctx context.Context, req GetOverseasDepositRequest, opts ...transport.Option) (*GetOverseasDepositResponse, transport.Meta, error) {
	var out GetOverseasDepositResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21110",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
