// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasRealizedPnlByDateAndStockRequest 는 미국주식 일별 종목별 실현손익(ust21640) 요청이다.
type GetOverseasRealizedPnlByDateAndStockRequest struct {
	// 거래소구분 (ND:NASDAQ,NY:NYSE,NA:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 체결일자 (필수, 8자, YYYYMMDD)
	CntrDt string `json:"cntr_dt"`
	// 외화원화구분 (필수, 1자, 0:외화,1:원화)
	FcKrwTp string `json:"fc_krw_tp"`
}

// GetOverseasRealizedPnlByDateAndStockResponse 는 미국주식 일별 종목별 실현손익(ust21640) 응답이다.
type GetOverseasRealizedPnlByDateAndStockResponse struct {
	// 총실현손익 (15자)
	TotPlAmt string `json:"tot_pl_amt"`
	// 총실현손익(원) (15자)
	TotPlAmtKrw string `json:"tot_pl_amt_krw"`
	// 결과리스트
	ResultList []GetOverseasRealizedPnlByDateAndStockResultListItem `json:"result_list"`
}

// GetOverseasRealizedPnlByDateAndStockResultListItem 는 ResultList 의 원소다.
type GetOverseasRealizedPnlByDateAndStockResultListItem struct {
	// 거래소코드명 (20자)
	StexNm string `json:"stex_nm"`
	// 종목명 (50자)
	StkNm string `json:"stk_nm"`
	// 통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 체결매도수량 (20자)
	CntrSellq string `json:"cntr_sellq"`
	// 매입평균가 (12자)
	AvgBuyUv string `json:"avg_buy_uv"`
	// 체결매도가 (20자)
	CntrSella string `json:"cntr_sella"`
	// 실현손익 (15자)
	PlAmt string `json:"pl_amt"`
	// 실현수익률 (12자)
	PlRt string `json:"pl_rt"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 수수료 (15자)
	Cmsn string `json:"cmsn"`
	// 제세금 (15자)
	Altx string `json:"altx"`
	// 환율 (12자)
	ExchRate string `json:"exch_rate"`
	// 국가명 (40자)
	NatnNm string `json:"natn_nm"`
}

// GetOverseasRealizedPnlByDateAndStock 는 미국주식 일별 종목별 실현손익(ust21640) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 일별 종목별 실현손익(ust21640)
// URL:  /api/us/acnt
func (c *Client) GetOverseasRealizedPnlByDateAndStock(ctx context.Context, req GetOverseasRealizedPnlByDateAndStockRequest, opts ...transport.Option) (*GetOverseasRealizedPnlByDateAndStockResponse, transport.Meta, error) {
	var out GetOverseasRealizedPnlByDateAndStockResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21640",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
