// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasDepositAndValuationByCurrencyRequest 는 통화별 예수금 및 증권 평가금현황(ust21120) 요청이다.
type GetOverseasDepositAndValuationByCurrencyRequest struct {
	// 수수료포함구분 (1자, 0:미포함,1:포함)
	CmsnInclTp string `json:"cmsn_incl_tp"`
	// 환율구분 (1자, 0:기준환율,1:계좌적용환율,2:전일최종환율)
	ExrtTp string `json:"exrt_tp"`
}

// GetOverseasDepositAndValuationByCurrencyResponse 는 통화별 예수금 및 증권 평가금현황(ust21120) 응답이다.
type GetOverseasDepositAndValuationByCurrencyResponse struct {
	// 예수금 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	WonEntr string `json:"won_entr"`
	// 원화추정자산 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	AsetEvltAmt string `json:"aset_evlt_amt"`
	// 결과리스트
	ResultList []GetOverseasDepositAndValuationByCurrencyResultListItem `json:"result_list"`
}

// GetOverseasDepositAndValuationByCurrencyResultListItem 는 ResultList 의 원소다.
type GetOverseasDepositAndValuationByCurrencyResultListItem struct {
	// 통화코드 (3자)
	CrncCode string `json:"crnc_code"`
	// 외화예수금 (12자, 소수점 및 소수점 이하2자리 포함)
	FxEntr string `json:"fx_entr"`
	// 해외증권평가금 (15자, 소수점 및 소수점 이하2자리 포함)
	EvltAmt string `json:"evlt_amt"`
	// 기준환율 (12자, 소수점 및 소수점 이하2자리 포함)
	CrncRt string `json:"crnc_rt"`
	// 환전예수금 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	ChgEntr string `json:"chg_entr"`
	// 환전평가금 (12자, 단위: 원, 좌측 0-padding 처리된 12자리 숫자)
	ChgEvltAmt string `json:"chg_evlt_amt"`
	// 평가금액비중 (7자, 소수점 둘째 자리까지 포맷된 숫자)
	EvltAmtWght string `json:"evlt_amt_wght"`
}

// GetOverseasDepositAndValuationByCurrency 는 통화별 예수금 및 증권 평가금현황(ust21120) 이다.
//
// 메뉴: 미국주식 > 계좌 > 통화별 예수금 및 증권 평가금현황(ust21120)
// URL:  /api/us/acnt
func (c *Client) GetOverseasDepositAndValuationByCurrency(ctx context.Context, req GetOverseasDepositAndValuationByCurrencyRequest, opts ...transport.Option) (*GetOverseasDepositAndValuationByCurrencyResponse, transport.Meta, error) {
	var out GetOverseasDepositAndValuationByCurrencyResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21120",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
