// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasKrwWithdrawableAmountRequest 는 원화출금가능 금액 조회(원화대용 포함)(ust21111) 요청이다.
type GetOverseasKrwWithdrawableAmountRequest struct {
}

// GetOverseasKrwWithdrawableAmountResponse 는 원화출금가능 금액 조회(원화대용 포함)(ust21111) 응답이다.
type GetOverseasKrwWithdrawableAmountResponse struct {
	// 원화대용등록해지구분 (1자, 원화대용약정등록상태 1:신청,2:해지 또는 미신청)
	RgstAbndTp string `json:"rgst_abnd_tp"`
	// 원화출금가능금액 (15자, 원화대용포함한 원화출금가능금액)
	KrwPymnAlowAmt string `json:"krw_pymn_alow_amt"`
	// 원화대용해지가능금액 (15자)
	KrwReplAbndAmt string `json:"krw_repl_abnd_amt"`
}

// GetOverseasKrwWithdrawableAmount 는 원화출금가능 금액 조회(원화대용 포함)(ust21111) 이다.
//
// 메뉴: 미국주식 > 계좌 > 원화출금가능 금액 조회(원화대용 포함)(ust21111)
// URL:  /api/us/acnt
func (c *Client) GetOverseasKrwWithdrawableAmount(ctx context.Context, req GetOverseasKrwWithdrawableAmountRequest, opts ...transport.Option) (*GetOverseasKrwWithdrawableAmountResponse, transport.Meta, error) {
	var out GetOverseasKrwWithdrawableAmountResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21111",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
