// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// ListOverseasOpenOrdersRequest 는 미국주식 원장 미체결(ust21050) 요청이다.
type ListOverseasOpenOrdersRequest struct {
	// 주문일자 (8자, 미입력시 오늘 날짜로 조회)
	OrdDt string `json:"ord_dt"`
	// 매도매수구분 (1자, 0:전체(기본값),1:매도,2:매수)
	SlbyTp string `json:"slby_tp"`
	// 거래소구분 (2자, 미입력시 전체, ND:NASDAQ,NY:NYSE,NA:AMEX)
	StexTp string `json:"stex_tp"`
	// 종목코드 (12자, 미입력시 전체)
	StkCd string `json:"stk_cd"`
}

// ListOverseasOpenOrdersResponse 는 미국주식 원장 미체결(ust21050) 응답이다.
type ListOverseasOpenOrdersResponse struct {
	// 결과리스트
	ResultList []ListOverseasOpenOrdersResultListItem `json:"result_list"`
}

// ListOverseasOpenOrdersResultListItem 는 ResultList 의 원소다.
type ListOverseasOpenOrdersResultListItem struct {
	// 주문종류 (2자, 10:원주문,11:정정주문,12:취소주문)
	OrdCntrTp string `json:"ord_cntr_tp"`
	// 주문번호 (9자)
	OrdNo string `json:"ord_no"`
	// 원주문번호 (9자, 원 주문이 없는 경우 '000000000'으로 출력)
	OrigOrdNo string `json:"orig_ord_no"`
	// 거래소명 (30자)
	StexNm string `json:"stex_nm"`
	// 통화코드 (3자, USD)
	CrncCode string `json:"crnc_code"`
	// 종목코드 (12자)
	StkCd string `json:"stk_cd"`
	// 종목명 (50자)
	FrgnStkNm string `json:"frgn_stk_nm"`
	// 매매구분 (2자, 00:지정가,03:시장가,11:Enhanced Limit Order,12:Special Limit Order,30:Limit On Close,33:Market On Close,34:Stop Limit,35:Stop Market,36:VWAP,37:TWAP)
	FrgnTrdeTp string `json:"frgn_trde_tp"`
	// 매매구분명 (40자, 00:지정가,03:시장가,11:Enhanced Limit Order,12:Special Limit Order,30:Limit On Close,33:Market On Close,34:Stop Limit,35:Stop Market,36:VWAP,37:TWAP)
	FrgnTrdeNm string `json:"frgn_trde_nm"`
	// 매도매수구분 (1자, 1:매도,2:매수)
	SlbyTp string `json:"slby_tp"`
	// 매도매수구분명 (20자, 1:매도,2:매수)
	SlbyTpNm string `json:"slby_tp_nm"`
	// 주문수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OrdUv string `json:"ord_uv"`
	// STOP가격 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	StopPric string `json:"stop_pric"`
	// 체결수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	CntrUv string `json:"cntr_uv"`
	// 정정수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	MdfyQty string `json:"mdfy_qty"`
	// 정정단가 (12자, 단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	MdfyUv string `json:"mdfy_uv"`
	// 취소수량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	CnclQty string `json:"cncl_qty"`
	// 주문잔량 (12자, 단위: 1주, 좌측 0-padding 처리된 12자리 숫자)
	OrdRemnq string `json:"ord_remnq"`
	// 주문시간 (8자, HH:mm:ss)
	OrdTime string `json:"ord_time"`
	// 주문응답시간 (8자, HH:mm:ss)
	OrdRespTime string `json:"ord_resp_time"`
	// 주문상태명 (25자)
	OrdStat string `json:"ord_stat"`
	// 예약주문구분 (12자, 0:일반,1:예약)
	RsrvTp string `json:"rsrv_tp"`
	// 국가명 (40자)
	NatnNm string `json:"natn_nm"`
}

// ListOverseasOpenOrders 는 미국주식 원장 미체결(ust21050) 이다.
//
// 메뉴: 미국주식 > 계좌 > 미국주식 원장 미체결(ust21050)
// URL:  /api/us/acnt
func (c *Client) ListOverseasOpenOrders(ctx context.Context, req ListOverseasOpenOrdersRequest, opts ...transport.Option) (*ListOverseasOpenOrdersResponse, transport.Meta, error) {
	var out ListOverseasOpenOrdersResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ust21050",
		Path:  "/api/us/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
