// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAllGoldSpotOrderFillsRequest 는 금현물 주문체결전체조회(kt50030) 요청이다.
type GetDomesticAllGoldSpotOrderFillsRequest struct {
	// 주문일자 (필수, 8자, YYYYMMDD)
	OrdDt string `json:"ord_dt"`
	// 조회구분 (1자, 1: 주문순, 2: 역순)
	QryTp string `json:"qry_tp"`
	// 시장구분 (필수, 1자, 5:KRX금현물, 5값으로 고정)
	MrktDealTp string `json:"mrkt_deal_tp"`
	// 주식채권구분 (필수, 1자, 0:전체, 1:주식, 2:채권)
	StkBondTp string `json:"stk_bond_tp"`
	// 매도수구분 (필수, 1자, 0:전체, 1:매도, 2:매수)
	SlbyTp string `json:"slby_tp"`
	// 종목코드 (12자, M04020000: 금 99.99_1kg, M04020100: 미니금 99.99_100g, 전체 조회는 빈값('')으로 설정)
	StkCd string `json:"stk_cd"`
	// 시작주문번호 (7자, 시작주문번호 입력 시 이전 주문은 조회되지 않음, 전체 조회는 빈값('')으로 설정)
	FrOrdNo string `json:"fr_ord_no"`
	// 국내거래소구분 (6자, %:(전체), KRX, NXT, SOR)
	DmstStexTp string `json:"dmst_stex_tp"`
}

// GetDomesticAllGoldSpotOrderFillsResponse 는 금현물 주문체결전체조회(kt50030) 응답이다.
type GetDomesticAllGoldSpotOrderFillsResponse struct {
	// 계좌별주문체결현황
	AcntOrdCntrPrst []GetDomesticAllGoldSpotOrderFillsAcntOrdCntrPrstItem `json:"acnt_ord_cntr_prst"`
}

// GetDomesticAllGoldSpotOrderFillsAcntOrdCntrPrstItem 는 AcntOrdCntrPrst 의 원소다.
type GetDomesticAllGoldSpotOrderFillsAcntOrdCntrPrstItem struct {
	// 주식채권구분 (1자)
	StkBondTp string `json:"stk_bond_tp"`
	// 주문번호 (7자, 주문번호 7자리)
	OrdNo string `json:"ord_no"`
	// 상품코드 (12자, 금 종목코드 9자리)
	StkCd string `json:"stk_cd"`
	// 매매구분 (12자)
	TrdeTp string `json:"trde_tp"`
	// 주문유형구분 (20자)
	IoTpNm string `json:"io_tp_nm"`
	// 주문수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdUv string `json:"ord_uv"`
	// 확인수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CnfmQty string `json:"cnfm_qty"`
	// 접수구분 (12자)
	DataSendEndTp string `json:"data_send_end_tp"`
	// 시장구분 (1자)
	MrktDealTp string `json:"mrkt_deal_tp"`
	// 예약/반대여부 (4자)
	RsrvTp string `json:"rsrv_tp"`
	// 원주문번호 (7자, 원 주문이 없는 경우 '0000000'으로 출력)
	OrigOrdNo string `json:"orig_ord_no"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 결제구분 (4자)
	DcdTpNm string `json:"dcd_tp_nm"`
	// 신용거래구분 (20자)
	CrdDealTp string `json:"crd_deal_tp"`
	// 체결수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrUv string `json:"cntr_uv"`
	// 미체결수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdRemnq string `json:"ord_remnq"`
	// 통신구분 (10자)
	CommOrdTp string `json:"comm_ord_tp"`
	// 정정취소구분 (20자)
	MdfyCnclTp string `json:"mdfy_cncl_tp"`
	// 국내거래소구분 (6자)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 스톱가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CondUv string `json:"cond_uv"`
}

// GetDomesticAllGoldSpotOrderFills 는 금현물 주문체결전체조회(kt50030) 이다.
//
// 메뉴: 국내주식 > 계좌 > 금현물 주문체결전체조회(kt50030)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticAllGoldSpotOrderFills(ctx context.Context, req GetDomesticAllGoldSpotOrderFillsRequest, opts ...transport.Option) (*GetDomesticAllGoldSpotOrderFillsResponse, transport.Meta, error) {
	var out GetDomesticAllGoldSpotOrderFillsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt50030",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
