// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAccountNextDaySettlementRequest 는 계좌별익일결제예정내역요청(kt00008) 요청이다.
type GetDomesticAccountNextDaySettlementRequest struct {
	// 시작결제번호 (7자)
	StrtDcdSeq string `json:"strt_dcd_seq"`
}

// GetDomesticAccountNextDaySettlementResponse 는 계좌별익일결제예정내역요청(kt00008) 응답이다.
type GetDomesticAccountNextDaySettlementResponse struct {
	// 매매일자 (8자, YYYYMMDD)
	TrdeDt string `json:"trde_dt"`
	// 결제일자 (8자, YYYYMMDD)
	SetlDt string `json:"setl_dt"`
	// 매도정산합 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	SellAmtSum string `json:"sell_amt_sum"`
	// 매수정산합 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	BuyAmtSum string `json:"buy_amt_sum"`
	// 계좌별익일결제예정내역배열
	AcntNxdySetlFrcsPrpsArray []GetDomesticAccountNextDaySettlementAcntNxdySetlFrcsPrpsArrayItem `json:"acnt_nxdy_setl_frcs_prps_array"`
}

// GetDomesticAccountNextDaySettlementAcntNxdySetlFrcsPrpsArrayItem 는 AcntNxdySetlFrcsPrpsArray 의 원소다.
type GetDomesticAccountNextDaySettlementAcntNxdySetlFrcsPrpsArrayItem struct {
	// 일련번호 (7자, 7자리 숫자)
	Seq string `json:"seq"`
	// 종목번호 (12자, 접두어 1자리 + 종목코드 6자리, 접두어(A: 주식 / J: ELW / Q: ETN))
	StkCd string `json:"stk_cd"`
	// 대출일 (8자)
	LoanDt string `json:"loan_dt"`
	// 수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Qty string `json:"qty"`
	// 약정금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EnggAmt string `json:"engg_amt"`
	// 수수료 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Cmsn string `json:"cmsn"`
	// 소득세 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	IncmTax string `json:"incm_tax"`
	// 농특세 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Rstx string `json:"rstx"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 매도수구분 (10자)
	SellTp string `json:"sell_tp"`
	// 단가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Unp string `json:"unp"`
	// 정산금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ExctAmt string `json:"exct_amt"`
	// 거래세 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TrdeTax string `json:"trde_tax"`
	// 주민세 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ResiTax string `json:"resi_tax"`
	// 신용구분 (20자)
	CrdTp string `json:"crd_tp"`
}

// GetDomesticAccountNextDaySettlement 는 계좌별익일결제예정내역요청(kt00008) 이다.
//
// 메뉴: 국내주식 > 계좌 > 계좌별익일결제예정내역요청(kt00008)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticAccountNextDaySettlement(ctx context.Context, req GetDomesticAccountNextDaySettlementRequest, opts ...transport.Option) (*GetDomesticAccountNextDaySettlementResponse, transport.Meta, error) {
	var out GetDomesticAccountNextDaySettlementResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00008",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
