// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotTransactionHistoryRequest 는 금현물 거래내역조회(kt50032) 요청이다.
type GetDomesticGoldSpotTransactionHistoryRequest struct {
	// 시작일자 (8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 구분 (1자, 0:전체, 1:입출금, 2:출고, 3:매매, 4:매수, 5:매도, 6:입금, 7:출금)
	Tp string `json:"tp"`
	// 종목코드 (12자, M04020000: 금 99.99_1kg, M04020100: 미니금 99.99_100g, 전체 조회는 빈값('')으로 설정)
	StkCd string `json:"stk_cd"`
}

// GetDomesticGoldSpotTransactionHistoryResponse 는 금현물 거래내역조회(kt50032) 응답이다.
type GetDomesticGoldSpotTransactionHistoryResponse struct {
	// 계좌번호 (62자, 계좌번호 출력용)
	AcntPrint string `json:"acnt_print"`
	// 금현물거래내역
	GoldTrdeHist []GetDomesticGoldSpotTransactionHistoryGoldTrdeHistItem `json:"gold_trde_hist"`
}

// GetDomesticGoldSpotTransactionHistoryGoldTrdeHistItem 는 GoldTrdeHist 의 원소다.
type GetDomesticGoldSpotTransactionHistoryGoldTrdeHistItem struct {
	// 거래일자 (8자, YYYYMMDD)
	DealDt string `json:"deal_dt"`
	// 거래번호 (9자, 거래번호 9자리)
	DealNo string `json:"deal_no"`
	// 적요명 (60자)
	RmrkNm string `json:"rmrk_nm"`
	// 거래수량 (15자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DealQty string `json:"deal_qty"`
	// 금현물부가가치세 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	GoldSpotVat string `json:"gold_spot_vat"`
	// 정산금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ExctAmt string `json:"exct_amt"`
	// 연체합 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DlySum string `json:"dly_sum"`
	// 예수금잔고 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EntraRemn string `json:"entra_remn"`
	// 메체구분명 (20자)
	MdiaNm string `json:"mdia_nm"`
	// 원거래번호 (7자, 원 주문이 없는 경우 '0000000'으로 출력)
	OrigDealNo string `json:"orig_deal_no"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 거래단가 (15자)
	UvExrt string `json:"uv_exrt"`
	// 수수료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	Cmsn string `json:"cmsn"`
	// 미수(원/g) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UnclOcr string `json:"uncl_ocr"`
	// 변제합 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	RpymSum string `json:"rpym_sum"`
	// 현물잔고 (15자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	SpotRemn string `json:"spot_remn"`
	// 처리시간 (8자, HH:mm:ss)
	ProcTime string `json:"proc_time"`
	// 출납번호 (9자, 출납번호 9자리)
	RcpyNo string `json:"rcpy_no"`
	// 종목코드 (12자, 금 종목 코드)
	StkCd string `json:"stk_cd"`
	// 거래금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DealAmt string `json:"deal_amt"`
	// 소득/주민세 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TaxTotAmt string `json:"tax_tot_amt"`
	// 체결일 (8자, YYYYMMDD)
	CntrDt string `json:"cntr_dt"`
	// 처리점 (20자)
	ProcBrchNm string `json:"proc_brch_nm"`
	// 처리자 (20자)
	Prcsr string `json:"prcsr"`
}

// GetDomesticGoldSpotTransactionHistory 는 금현물 거래내역조회(kt50032) 이다.
//
// 메뉴: 국내주식 > 계좌 > 금현물 거래내역조회(kt50032)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticGoldSpotTransactionHistory(ctx context.Context, req GetDomesticGoldSpotTransactionHistoryRequest, opts ...transport.Option) (*GetDomesticGoldSpotTransactionHistoryResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotTransactionHistoryResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt50032",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
