// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticMarginDetailRequest 는 증거금세부내역조회요청(kt00013) 요청이다.
type GetDomesticMarginDetailRequest struct {
}

// GetDomesticMarginDetailResponse 는 증거금세부내역조회요청(kt00013) 응답이다.
type GetDomesticMarginDetailResponse struct {
	// 금일재사용대상금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyReuObjtAmt string `json:"tdy_reu_objt_amt"`
	// 금일재사용사용금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyReuUseAmt string `json:"tdy_reu_use_amt"`
	// 금일재사용가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyReuAlowa string `json:"tdy_reu_alowa"`
	// 금일재사용제한금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyReuLmttAmt string `json:"tdy_reu_lmtt_amt"`
	// 금일재사용가능금액최종 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyReuAlowaFin string `json:"tdy_reu_alowa_fin"`
	// 전일재사용대상금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredReuObjtAmt string `json:"pred_reu_objt_amt"`
	// 전일재사용사용금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredReuUseAmt string `json:"pred_reu_use_amt"`
	// 전일재사용가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredReuAlowa string `json:"pred_reu_alowa"`
	// 전일재사용제한금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredReuLmttAmt string `json:"pred_reu_lmtt_amt"`
	// 전일재사용가능금액최종 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredReuAlowaFin string `json:"pred_reu_alowa_fin"`
	// 현금금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChAmt string `json:"ch_amt"`
	// 현금증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChProfa string `json:"ch_profa"`
	// 사용가능현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UsePosCh string `json:"use_pos_ch"`
	// 현금사용제한금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChUseLmttAmt string `json:"ch_use_lmtt_amt"`
	// 사용가능현금최종 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UsePosChFin string `json:"use_pos_ch_fin"`
	// 대용금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplAmtAmt string `json:"repl_amt_amt"`
	// 대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplProfa string `json:"repl_profa"`
	// 사용가능대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UsePosRepl string `json:"use_pos_repl"`
	// 대용사용제한금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplUseLmttAmt string `json:"repl_use_lmtt_amt"`
	// 사용가능대용최종 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UsePosReplFin string `json:"use_pos_repl_fin"`
	// 신용보증금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntaCh string `json:"crd_grnta_ch"`
	// 신용보증금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntaRepl string `json:"crd_grnta_repl"`
	// 신용담보금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntCh string `json:"crd_grnt_ch"`
	// 신용담보금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntRepl string `json:"crd_grnt_repl"`
	// 미수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	Uncla string `json:"uncla"`
	// 대주담보금재사용금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LsGrntReuGold string `json:"ls_grnt_reu_gold"`
	// 20%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N20ordAlowAmt string `json:"20ord_alow_amt"`
	// 30%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N30ordAlowAmt string `json:"30ord_alow_amt"`
	// 40%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N40ordAlowAmt string `json:"40ord_alow_amt"`
	// 50%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N50ordAlowAmt string `json:"50ord_alow_amt"`
	// 60%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N60ordAlowAmt string `json:"60ord_alow_amt"`
	// 100%주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N100ordAlowAmt string `json:"100ord_alow_amt"`
	// 금일신용상환손실금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyCrdRpyaLossAmt string `json:"tdy_crd_rpya_loss_amt"`
	// 전일신용상환손실금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredCrdRpyaLossAmt string `json:"pred_crd_rpya_loss_amt"`
	// 금일대주상환손실대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TdyLsRpyaLossReplProfa string `json:"tdy_ls_rpya_loss_repl_profa"`
	// 전일대주상환손실대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PredLsRpyaLossReplProfa string `json:"pred_ls_rpya_loss_repl_profa"`
	// 평가대용금(현물사용제외) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EvltReplAmtSpgUseSkip string `json:"evlt_repl_amt_spg_use_skip"`
	// 평가대용비율 (15자, 단위: %, 소수점 일곱번째 자리까지 포맷된 백분율)
	EvltReplRt string `json:"evlt_repl_rt"`
	// 신용대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdReplProfa string `json:"crd_repl_profa"`
	// 현금주문대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChOrdReplProfa string `json:"ch_ord_repl_profa"`
	// 신용주문대용증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdOrdReplProfa string `json:"crd_ord_repl_profa"`
	// 신용대용환산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdReplConvGold string `json:"crd_repl_conv_gold"`
	// 대용가능금액(현금제한) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplAlowa string `json:"repl_alowa"`
	// 대용가능금액2(신용제한) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplAlowa2 string `json:"repl_alowa_2"`
	// 현금대용부족금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChReplLckGold string `json:"ch_repl_lck_gold"`
	// 신용대용부족금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdReplLckGold string `json:"crd_repl_lck_gold"`
	// 현금주문가능대용금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChOrdAlowRepla string `json:"ch_ord_alow_repla"`
	// 신용주문가능대용금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdOrdAlowRepla string `json:"crd_ord_alow_repla"`
	// D2가정산예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2vexctEntr string `json:"d2vexct_entr"`
	// D2현금주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2chOrdAlowAmt string `json:"d2ch_ord_alow_amt"`
}

// GetDomesticMarginDetail 는 증거금세부내역조회요청(kt00013) 이다.
//
// 메뉴: 국내주식 > 계좌 > 증거금세부내역조회요청(kt00013)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticMarginDetail(ctx context.Context, req GetDomesticMarginDetailRequest, opts ...transport.Option) (*GetDomesticMarginDetailResponse, transport.Meta, error) {
	var out GetDomesticMarginDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00013",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
