// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticBrokerageAccountTransactionHistoryRequest 는 위탁종합거래내역요청(kt00015) 요청이다.
type GetDomesticBrokerageAccountTransactionHistoryRequest struct {
	// 시작일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
	// 구분 (필수, 1자, 0:전체,1:입출금,2:입출고,3:매매,4:매수,5:매도,6:입금,7:출금,A:예탁담보대출입금,B:매도담보대출입금,C:현금상환(융자,담보상환),F:환전,M:입출금+환전,G:외화매수,H:외화매도,I:환전정산입금,J:환전정산출금)
	Tp string `json:"tp"`
	// 종목코드 (12자, 종목 코드 입력)
	StkCd string `json:"stk_cd"`
	// 통화코드 (3자, 통화코드 3자리)
	CrncCd string `json:"crnc_cd"`
	// 상품구분 (필수, 1자, 0:전체, 1:국내주식, 2:수익증권, 3:해외주식, 4:금융상품)
	GdsTp string `json:"gds_tp"`
	// 해외거래소코드 (10자)
	FrgnStexCode string `json:"frgn_stex_code"`
	// 국내거래소구분 (필수, 6자, %:(전체),KRX:한국거래소,NXT:넥스트트레이드)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 조회정렬구분 (1자, 1:최근거래순, 2:과거거래순(미입력시 과거거래순))
	QrySortTp string `json:"qry_sort_tp"`
}

// GetDomesticBrokerageAccountTransactionHistoryResponse 는 위탁종합거래내역요청(kt00015) 응답이다.
type GetDomesticBrokerageAccountTransactionHistoryResponse struct {
	// 위탁종합거래내역배열
	TrstOvrlTrdePrpsArray []GetDomesticBrokerageAccountTransactionHistoryTrstOvrlTrdePrpsArrayItem `json:"trst_ovrl_trde_prps_array"`
}

// GetDomesticBrokerageAccountTransactionHistoryTrstOvrlTrdePrpsArrayItem 는 TrstOvrlTrdePrpsArray 의 원소다.
type GetDomesticBrokerageAccountTransactionHistoryTrstOvrlTrdePrpsArrayItem struct {
	// 거래일자 (8자, YYYYMMDD)
	TrdeDt string `json:"trde_dt"`
	// 거래번호 (9자, 거래번호 9자리)
	TrdeNo string `json:"trde_no"`
	// 적요명 (60자)
	RmrkNm string `json:"rmrk_nm"`
	// 신용거래구분명 (20자)
	CrdDealTpNm string `json:"crd_deal_tp_nm"`
	// 정산금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ExctAmt string `json:"exct_amt"`
	// 대출금상환 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LoanAmtRpya string `json:"loan_amt_rpya"`
	// 거래금액(외) (15자)
	FcTrdeAmt string `json:"fc_trde_amt"`
	// 정산금액(외) (15자)
	FcExctAmt string `json:"fc_exct_amt"`
	// 예수금잔고 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EntraRemn string `json:"entra_remn"`
	// 통화코드 (3자)
	CrncCd string `json:"crnc_cd"`
	// 거래종류구분 (2자, 1:입출금, 2:펀드, 3:ELS, 4:채권, 5:해외채권, 6:외화RP, 7:외화발행어음)
	TrdeOcrTp string `json:"trde_ocr_tp"`
	// 거래종류명 (20자, 거래종류구분자(trde_ocr_tp)의 한글명)
	TrdeKindNm string `json:"trde_kind_nm"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 거래금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TrdeAmt string `json:"trde_amt"`
	// 거래및농특세 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TrdeAgriTax string `json:"trde_agri_tax"`
	// 상환차금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	RpyDiffa string `json:"rpy_diffa"`
	// 거래세(외) (15자)
	FcTrdeTax string `json:"fc_trde_tax"`
	// 연체합 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DlySum string `json:"dly_sum"`
	// 외화예수금잔고 (15자)
	FcEntra string `json:"fc_entra"`
	// 매체구분명 (20자)
	MdiaTpNm string `json:"mdia_tp_nm"`
	// 입출구분 (1자)
	IoTp string `json:"io_tp"`
	// 입출구분명 (10자)
	IoTpNm string `json:"io_tp_nm"`
	// 원거래번호 (9자, 원 거래가 없는 경우 '000000000'으로 출력)
	OrigDealNo string `json:"orig_deal_no"`
	// 종목코드 (12자, 접두어 1자리 + 종목코드 6자리, 접두어(A: 주식 / J: ELW / Q: ETN))
	StkCd string `json:"stk_cd"`
	// 거래수량/좌수 (30자)
	TrdeQtyJwaCnt string `json:"trde_qty_jwa_cnt"`
	// 수수료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	Cmsn string `json:"cmsn"`
	// 이자/대주이용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	IntLsUsfe string `json:"int_ls_usfe"`
	// 수수료(외) (15자)
	FcCmsn string `json:"fc_cmsn"`
	// 연체합(외) (15자)
	FcDlySum string `json:"fc_dly_sum"`
	// 유가금잔 (30자)
	VlblNowrm string `json:"vlbl_nowrm"`
	// 처리시간 (111자, HH:mm:ss)
	ProcTm string `json:"proc_tm"`
	// ISIN코드 (12자)
	IsinCd string `json:"isin_cd"`
	// 거래소코드 (10자)
	StexCd string `json:"stex_cd"`
	// 거래소명 (20자)
	StexNm string `json:"stex_nm"`
	// 거래단가/환율 (20자)
	TrdeUnit string `json:"trde_unit"`
	// 소득/주민세 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	IncmResiTax string `json:"incm_resi_tax"`
	// 대출일 (8자, YYYYMMDD)
	LoanDt string `json:"loan_dt"`
	// 미수(원/주) (30자)
	UnclOcr string `json:"uncl_ocr"`
	// 변제합 (30자)
	RpymSum string `json:"rpym_sum"`
	// 체결일 (8자, YYYYMMDD)
	CntrDt string `json:"cntr_dt"`
	// 출납번호 (20자)
	RcpyNo string `json:"rcpy_no"`
	// 처리자 (20자)
	Prcsr string `json:"prcsr"`
	// 처리점 (20자)
	ProcBrch string `json:"proc_brch"`
	// 매매형태 (40자)
	TrdeStle string `json:"trde_stle"`
	// 과세기준가 (15자)
	TxonBasePric string `json:"txon_base_pric"`
	// 세금수수료합 (15자)
	TaxSumCmsn string `json:"tax_sum_cmsn"`
	// 외국납부세액(외) (15자)
	FrgnPayTxam string `json:"frgn_pay_txam"`
	// 미수(외) (15자)
	FcUnclOcr string `json:"fc_uncl_ocr"`
	// 변제합(외) (30자)
	RpymSumFr string `json:"rpym_sum_fr"`
	// 입금자 (20자)
	Rcpmnyer string `json:"rcpmnyer"`
	// 거래내역구분 (2자)
	TrdePrtcTp string `json:"trde_prtc_tp"`
}

// GetDomesticBrokerageAccountTransactionHistory 는 위탁종합거래내역요청(kt00015) 이다.
//
// 메뉴: 국내주식 > 계좌 > 위탁종합거래내역요청(kt00015)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticBrokerageAccountTransactionHistory(ctx context.Context, req GetDomesticBrokerageAccountTransactionHistoryRequest, opts ...transport.Option) (*GetDomesticBrokerageAccountTransactionHistoryResponse, transport.Meta, error) {
	var out GetDomesticBrokerageAccountTransactionHistoryResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00015",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
