// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotBalanceRequest 는 금현물 잔고확인(kt50020) 요청이다.
type GetDomesticGoldSpotBalanceRequest struct {
}

// GetDomesticGoldSpotBalanceResponse 는 금현물 잔고확인(kt50020) 응답이다.
type GetDomesticGoldSpotBalanceResponse struct {
	// 예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotEntr string `json:"tot_entr"`
	// 추정예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	NetEntr string `json:"net_entr"`
	// 잔고평가액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotEstAmt string `json:"tot_est_amt"`
	// 예탁자산평가액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	NetAmt string `json:"net_amt"`
	// 총매입금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotBookAmt2 string `json:"tot_book_amt2"`
	// 추정예탁자산 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotDepAmt string `json:"tot_dep_amt"`
	// 출금가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PaymAlowa string `json:"paym_alowa"`
	// 실현손익 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PlAmt string `json:"pl_amt"`
	// 금현물계좌평가현황
	GoldAcntEvltPrst []GetDomesticGoldSpotBalanceGoldAcntEvltPrstItem `json:"gold_acnt_evlt_prst"`
}

// GetDomesticGoldSpotBalanceGoldAcntEvltPrstItem 는 GoldAcntEvltPrst 의 원소다.
type GetDomesticGoldSpotBalanceGoldAcntEvltPrstItem struct {
	// 종목코드 (30자, 금 종목 코드)
	StkCd string `json:"stk_cd"`
	// 종목명 (12자, 금 종목 코드 설명)
	StkNm string `json:"stk_nm"`
	// 보유수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	RealQty string `json:"real_qty"`
	// 평균단가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	AvgPrc string `json:"avg_prc"`
	// 현재가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CurPrc string `json:"cur_prc"`
	// 평가금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EstAmt string `json:"est_amt"`
	// 손익금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EstLspft string `json:"est_lspft"`
	// 손익율 (12자, 단위: %, 소수점 넷째 자리까지 포맷된 백분율)
	EstRatio string `json:"est_ratio"`
	// 수수료 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Cmsn string `json:"cmsn"`
	// 부가가치세 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	VladTax string `json:"vlad_tax"`
	// 매입금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	BookAmt2 string `json:"book_amt2"`
	// 손익분기매입가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PlPrchPrc string `json:"pl_prch_prc"`
	// 결제잔고 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Qty string `json:"qty"`
	// 매수수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	BuyQty string `json:"buy_qty"`
	// 매도수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	SellQty string `json:"sell_qty"`
	// 가능수량 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	AbleQty string `json:"able_qty"`
}

// GetDomesticGoldSpotBalance 는 금현물 잔고확인(kt50020) 이다.
//
// 메뉴: 국내주식 > 계좌 > 금현물 잔고확인(kt50020)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticGoldSpotBalance(ctx context.Context, req GetDomesticGoldSpotBalanceRequest, opts ...transport.Option) (*GetDomesticGoldSpotBalanceResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotBalanceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt50020",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
