// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAccountOrderFillStatusRequest 는 계좌별주문체결현황요청(kt00009) 요청이다.
type GetDomesticAccountOrderFillStatusRequest struct {
	// 주문일자 (8자, YYYYMMDD)
	OrdDt string `json:"ord_dt"`
	// 주식채권구분 (필수, 1자, 0:전체, 1:주식, 2:채권)
	StkBondTp string `json:"stk_bond_tp"`
	// 시장구분 (필수, 1자, 0:전체, 1:코스피, 2:코스닥, 3:OTCBB, 4:ECN)
	MrktTp string `json:"mrkt_tp"`
	// 매도수구분 (필수, 1자, 0:전체, 1:매도, 2:매수)
	SellTp string `json:"sell_tp"`
	// 조회구분 (필수, 1자, 0:전체, 1:체결)
	QryTp string `json:"qry_tp"`
	// 종목코드 (12자, 전문 조회할 종목코드)
	StkCd string `json:"stk_cd"`
	// 시작주문번호 (7자, 시작주문번호의 이전 주문은 조회 되지 않으며 약정금액에도 포함 되지 않음)
	FrOrdNo string `json:"fr_ord_no"`
	// 국내거래소구분 (필수, 6자, %:(전체),KRX:한국거래소,NXT:넥스트트레이드,SOR:최선주문집행)
	DmstStexTp string `json:"dmst_stex_tp"`
}

// GetDomesticAccountOrderFillStatusResponse 는 계좌별주문체결현황요청(kt00009) 응답이다.
type GetDomesticAccountOrderFillStatusResponse struct {
	// 매도약정금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	SellGrntlEnggAmt string `json:"sell_grntl_engg_amt"`
	// 매수약정금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	BuyEnggAmt string `json:"buy_engg_amt"`
	// 약정금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EnggAmt string `json:"engg_amt"`
	// 계좌별주문체결현황배열
	AcntOrdCntrPrstArray []GetDomesticAccountOrderFillStatusAcntOrdCntrPrstArrayItem `json:"acnt_ord_cntr_prst_array"`
}

// GetDomesticAccountOrderFillStatusAcntOrdCntrPrstArrayItem 는 AcntOrdCntrPrstArray 의 원소다.
type GetDomesticAccountOrderFillStatusAcntOrdCntrPrstArrayItem struct {
	// 주식채권구분 (1자)
	StkBondTp string `json:"stk_bond_tp"`
	// 주문번호 (7자, 고유 주문번호 7자리)
	OrdNo string `json:"ord_no"`
	// 종목번호 (12자, 접두어 1자리 + 종목코드 6자리, 접두어(A: 주식 / J: ELW / Q: ETN))
	StkCd string `json:"stk_cd"`
	// 매매구분 (15자)
	TrdeTp string `json:"trde_tp"`
	// 주문유형구분 (20자)
	IoTpNm string `json:"io_tp_nm"`
	// 주문수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdUv string `json:"ord_uv"`
	// 확인수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CnfmQty string `json:"cnfm_qty"`
	// 예약/반대 (4자)
	RsrvOppo string `json:"rsrv_oppo"`
	// 체결번호 (7자, 체결번호 7자리)
	CntrNo string `json:"cntr_no"`
	// 접수구분 (8자)
	AcptTp string `json:"acpt_tp"`
	// 원주문번호 (7자, 원 주문이 없는 경우 '0000000'으로 출력)
	OrigOrdNo string `json:"orig_ord_no"`
	// 종목명 (20자)
	StkNm string `json:"stk_nm"`
	// 결제구분 (8자)
	SetlTp string `json:"setl_tp"`
	// 신용거래구분 (20자)
	CrdDealTp string `json:"crd_deal_tp"`
	// 체결수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrUv string `json:"cntr_uv"`
	// 통신구분 (8자)
	CommOrdTp string `json:"comm_ord_tp"`
	// 정정/취소구분 (12자)
	MdfyCnclTp string `json:"mdfy_cncl_tp"`
	// 체결시간 (8자, HH:mm:ss)
	CntrTm string `json:"cntr_tm"`
	// 국내거래소구분 (6자)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 스톱가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CondUv string `json:"cond_uv"`
}

// GetDomesticAccountOrderFillStatus 는 계좌별주문체결현황요청(kt00009) 이다.
//
// 메뉴: 국내주식 > 계좌 > 계좌별주문체결현황요청(kt00009)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticAccountOrderFillStatus(ctx context.Context, req GetDomesticAccountOrderFillStatusRequest, opts ...transport.Option) (*GetDomesticAccountOrderFillStatusResponse, transport.Meta, error) {
	var out GetDomesticAccountOrderFillStatusResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00009",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
