// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticGoldSpotOrderFillsRequest 는 금현물 주문체결조회(kt50031) 요청이다.
type GetDomesticGoldSpotOrderFillsRequest struct {
	// 주문일자 (8자, YYYYMMDD)
	OrdDt string `json:"ord_dt"`
	// 조회구분 (필수, 1자, 1:주문순, 2:역순, 3:미체결, 4:체결내역만)
	QryTp string `json:"qry_tp"`
	// 주식채권구분 (필수, 1자, 0:전체, 1:주식, 2:채권)
	StkBondTp string `json:"stk_bond_tp"`
	// 매도수구분 (필수, 1자, 0:전체, 1:매도, 2:매수)
	SellTp string `json:"sell_tp"`
	// 종목코드 (12자, M04020000: 금 99.99_1kg, M04020100: 미니금 99.99_100g, 전체 조회는 빈값('')으로 설정)
	StkCd string `json:"stk_cd"`
	// 시작주문번호 (7자, 시작주문번호 입력 시 이전 주문은 조회되지 않음, 전체 조회는 빈값('')으로 설정)
	FrOrdNo string `json:"fr_ord_no"`
	// 국내거래소구분 (필수, 6자, %:(전체),KRX:한국거래소,NXT:넥스트트레이드,SOR:최선주문집행)
	DmstStexTp string `json:"dmst_stex_tp"`
}

// GetDomesticGoldSpotOrderFillsResponse 는 금현물 주문체결조회(kt50031) 응답이다.
type GetDomesticGoldSpotOrderFillsResponse struct {
	// 계좌별주문체결내역상세
	AcntOrdCntrPrpsDtl []GetDomesticGoldSpotOrderFillsAcntOrdCntrPrpsDtlItem `json:"acnt_ord_cntr_prps_dtl"`
}

// GetDomesticGoldSpotOrderFillsAcntOrdCntrPrpsDtlItem 는 AcntOrdCntrPrpsDtl 의 원소다.
type GetDomesticGoldSpotOrderFillsAcntOrdCntrPrpsDtlItem struct {
	// 주문번호 (7자, 주문번호 7자리)
	OrdNo string `json:"ord_no"`
	// 종목번호 (12자, 금 종목코드 9자리)
	StkCd string `json:"stk_cd"`
	// 매매구분 (20자)
	TrdeTp string `json:"trde_tp"`
	// 신용구분 (20자)
	CrdTp string `json:"crd_tp"`
	// 주문수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdQty string `json:"ord_qty"`
	// 주문단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdUv string `json:"ord_uv"`
	// 확인수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CnfmQty string `json:"cnfm_qty"`
	// 접수구분 (20자)
	AcptTp string `json:"acpt_tp"`
	// 반대여부 (20자)
	RsrvTp string `json:"rsrv_tp"`
	// 주문시간 (8자, HH:mm:ss)
	OrdTm string `json:"ord_tm"`
	// 원주문 (7자, 원 주문이 없는 경우 '0000000'으로 출력)
	OriOrd string `json:"ori_ord"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 주문구분 (20자)
	IoTpNm string `json:"io_tp_nm"`
	// 대출일 (8자, YYYYMMDD)
	LoanDt string `json:"loan_dt"`
	// 체결수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrQty string `json:"cntr_qty"`
	// 체결단가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CntrUv string `json:"cntr_uv"`
	// 주문잔량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	OrdRemnq string `json:"ord_remnq"`
	// 통신구분 (20자)
	CommOrdTp string `json:"comm_ord_tp"`
	// 정정취소 (20자)
	MdfyCncl string `json:"mdfy_cncl"`
	// 확인시간 (8자, HH:mm:ss)
	CnfmTm string `json:"cnfm_tm"`
	// 국내거래소구분 (8자)
	DmstStexTp string `json:"dmst_stex_tp"`
	// 스톱가 (10자, 단위: 원, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	CondUv string `json:"cond_uv"`
}

// GetDomesticGoldSpotOrderFills 는 금현물 주문체결조회(kt50031) 이다.
//
// 메뉴: 국내주식 > 계좌 > 금현물 주문체결조회(kt50031)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticGoldSpotOrderFills(ctx context.Context, req GetDomesticGoldSpotOrderFillsRequest, opts ...transport.Option) (*GetDomesticGoldSpotOrderFillsResponse, transport.Meta, error) {
	var out GetDomesticGoldSpotOrderFillsResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt50031",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
