// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDailyBalanceReturnRateRequest 는 일별잔고수익률(ka01690) 요청이다.
type GetDomesticDailyBalanceReturnRateRequest struct {
	// 조회일자 (필수, 8자, YYYYMMDD)
	QryDt string `json:"qry_dt"`
}

// GetDomesticDailyBalanceReturnRateResponse 는 일별잔고수익률(ka01690) 응답이다.
type GetDomesticDailyBalanceReturnRateResponse struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 총 매입가 (20자, 단위 : 원)
	TotBuyAmt string `json:"tot_buy_amt"`
	// 총 평가금액 (20자, 단위 : 원)
	TotEvltAmt string `json:"tot_evlt_amt"`
	// 총 평가손익 (20자, 단위 : 원)
	TotEvltvPrft string `json:"tot_evltv_prft"`
	// 수익률 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	TotPrftRt string `json:"tot_prft_rt"`
	// 예수금 (20자, 단위 : 원)
	DbstBal string `json:"dbst_bal"`
	// 추정자산 (20자, 단위 : 원)
	DayStkAsst string `json:"day_stk_asst"`
	// 현금비중 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	BuyWght string `json:"buy_wght"`
	// 일별잔고수익률
	DayBalRt []GetDomesticDailyBalanceReturnRateDayBalRtItem `json:"day_bal_rt"`
}

// GetDomesticDailyBalanceReturnRateDayBalRtItem 는 DayBalRt 의 원소다.
type GetDomesticDailyBalanceReturnRateDayBalRtItem struct {
	// 현재가 (20자, 단위 : 원)
	CurPrc string `json:"cur_prc"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (20자)
	StkNm string `json:"stk_nm"`
	// 보유 수량 (20자, 단위 : 1주)
	RmndQty string `json:"rmnd_qty"`
	// 매입 단가 (20자, 단위 : 원)
	BuyUv string `json:"buy_uv"`
	// 매수비중 (20자, 단위: %, 소수점 첫째 자리까지 포맷된 백분율)
	BuyWght string `json:"buy_wght"`
	// 평가손익 (20자, 단위 : 원)
	EvltvPrft string `json:"evltv_prft"`
	// 수익률 (20자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	PrftRt string `json:"prft_rt"`
	// 평가금액 (20자, 단위 : 원)
	EvltAmt string `json:"evlt_amt"`
	// 평가비중 (20자, 단위: %, 소수점 첫째 자리까지 포맷된 백분율)
	EvltWght string `json:"evlt_wght"`
}

// GetDomesticDailyBalanceReturnRate 는 일별잔고수익률(ka01690) 이다.
//
// 메뉴: 국내주식 > 계좌 > 일별잔고수익률(ka01690)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticDailyBalanceReturnRate(ctx context.Context, req GetDomesticDailyBalanceReturnRateRequest, opts ...transport.Option) (*GetDomesticDailyBalanceReturnRateResponse, transport.Meta, error) {
	var out GetDomesticDailyBalanceReturnRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka01690",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
