// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticAccountReturnRateRequest 는 계좌수익률요청(ka10085) 요청이다.
type GetDomesticAccountReturnRateRequest struct {
	// 거래소구분 (필수, 1자, 0 : 통합, 1 : KRX, 2 : NXT)
	StexTp string `json:"stex_tp"`
}

// GetDomesticAccountReturnRateResponse 는 계좌수익률요청(ka10085) 응답이다.
type GetDomesticAccountReturnRateResponse struct {
	// 계좌수익률
	AcntPrftRt []GetDomesticAccountReturnRateAcntPrftRtItem `json:"acnt_prft_rt"`
}

// GetDomesticAccountReturnRateAcntPrftRtItem 는 AcntPrftRt 의 원소다.
type GetDomesticAccountReturnRateAcntPrftRtItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 현재가 (20자, 단위: 원)
	CurPrc string `json:"cur_prc"`
	// 매입가 (20자, 단위: 원)
	PurPric string `json:"pur_pric"`
	// 매입금액 (20자, 단위: 원)
	PurAmt string `json:"pur_amt"`
	// 보유수량 (20자, 단위: 1주)
	RmndQty string `json:"rmnd_qty"`
	// 당일매도손익 (20자, 단위: 원)
	TdySelPl string `json:"tdy_sel_pl"`
	// 당일매매수수료 (20자, 단위: 원)
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	// 당일매매세금 (20자, 단위: 원)
	TdyTrdeTax string `json:"tdy_trde_tax"`
	// 신용구분 (20자)
	CrdTp string `json:"crd_tp"`
	// 대출일 (20자, YYYYMMDD, 대출일이 없는 경우 '00000000'로 출력)
	LoanDt string `json:"loan_dt"`
	// 결제잔고 (20자, 단위: 원)
	SetlRemn string `json:"setl_remn"`
	// 청산가능수량 (20자, 단위: 1주)
	ClrnAlowQty string `json:"clrn_alow_qty"`
	// 신용금액 (20자, 단위: 원)
	CrdAmt string `json:"crd_amt"`
	// 신용이자 (20자, 단위: 원)
	CrdInt string `json:"crd_int"`
	// 만기일 (20자, YYYYMMDD, 만기일이 없는 경우 '00000000'로 출력)
	ExprDt string `json:"expr_dt"`
}

// GetDomesticAccountReturnRate 는 계좌수익률요청(ka10085) 이다.
//
// 메뉴: 국내주식 > 계좌 > 계좌수익률요청(ka10085)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticAccountReturnRate(ctx context.Context, req GetDomesticAccountReturnRateRequest, opts ...transport.Option) (*GetDomesticAccountReturnRateResponse, transport.Meta, error) {
	var out GetDomesticAccountReturnRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10085",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
