// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticUnfilledOrdersRequest 는 미체결요청(ka10075) 요청이다.
type GetDomesticUnfilledOrdersRequest struct {
	// 전체종목구분 (필수, 1자, 0:전체, 1:종목)
	AllStkTp string `json:"all_stk_tp"`
	// 매매구분 (필수, 1자, 0:전체, 1:매도, 2:매수)
	TrdeTp string `json:"trde_tp"`
	// 종목코드 (6자, 종목코드 6자리)
	StkCd string `json:"stk_cd"`
	// 거래소구분 (필수, 1자, 0 : 통합, 1 : KRX, 2 : NXT)
	StexTp string `json:"stex_tp"`
}

// GetDomesticUnfilledOrdersResponse 는 미체결요청(ka10075) 응답이다.
type GetDomesticUnfilledOrdersResponse struct {
	// 미체결
	Oso []GetDomesticUnfilledOrdersOsoItem `json:"oso"`
}

// GetDomesticUnfilledOrdersOsoItem 는 Oso 의 원소다.
type GetDomesticUnfilledOrdersOsoItem struct {
	// 계좌번호 (20자, 고유 계좌번호 10자리 숫자)
	AcntNo string `json:"acnt_no"`
	// 주문번호 (20자, 고유 주문번호 7자리 숫자)
	OrdNo string `json:"ord_no"`
	// 관리사번 (20자)
	MangEmpno string `json:"mang_empno"`
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 업무구분 (20자)
	TskTp string `json:"tsk_tp"`
	// 주문상태 (20자)
	OrdStt string `json:"ord_stt"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 주문수량 (20자, 단위: 1주)
	OrdQty string `json:"ord_qty"`
	// 주문가격 (20자, 단위: 원)
	OrdPric string `json:"ord_pric"`
	// 미체결수량 (20자, 단위: 1주)
	OsoQty string `json:"oso_qty"`
	// 체결누계금액 (20자, 단위: 원)
	CntrTotAmt string `json:"cntr_tot_amt"`
	// 원주문번호 (20자, 원 주문이 없는 경우 '0000000'으로 출력)
	OrigOrdNo string `json:"orig_ord_no"`
	// 주문구분 (20자)
	IoTpNm string `json:"io_tp_nm"`
	// 매매구분 (20자)
	TrdeTp string `json:"trde_tp"`
	// 시간 (20자, 주문 시간, HHmmss)
	Tm string `json:"tm"`
	// 체결번호 (20자)
	CntrNo string `json:"cntr_no"`
	// 체결가 (20자, 단위: 원)
	CntrPric string `json:"cntr_pric"`
	// 체결량 (20자, 단위: 1주)
	CntrQty string `json:"cntr_qty"`
	// 현재가 (20자)
	CurPrc string `json:"cur_prc"`
	// 매도호가 (20자, 단위: 원, 현재 첫번째 매도호가)
	SelBid string `json:"sel_bid"`
	// 매수호가 (20자, 단위: 원, 현재 첫번째 매수호가)
	BuyBid string `json:"buy_bid"`
	// 단위체결가 (20자, 단위: 원)
	UnitCntrPric string `json:"unit_cntr_pric"`
	// 단위체결량 (20자, 단위: 1주)
	UnitCntrQty string `json:"unit_cntr_qty"`
	// 당일매매수수료 (20자, 단위: 원)
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	// 당일매매세금 (20자, 단위: 원)
	TdyTrdeTax string `json:"tdy_trde_tax"`
	// 개인투자자 (20자)
	IndInvsr string `json:"ind_invsr"`
	// 거래소구분 (20자, 0 : 통합, 1 : KRX, 2 : NXT)
	StexTp string `json:"stex_tp"`
	// 거래소구분텍스트 (20자, 통합,KRX,NXT)
	StexTpTxt string `json:"stex_tp_txt"`
	// SOR 여부값 (20자, Y,N)
	SorYn string `json:"sor_yn"`
	// 스톱가 (20자, 스톱지정가주문 스톱가)
	StopPric string `json:"stop_pric"`
}

// GetDomesticUnfilledOrders 는 미체결요청(ka10075) 이다.
//
// 메뉴: 국내주식 > 계좌 > 미체결요청(ka10075)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticUnfilledOrders(ctx context.Context, req GetDomesticUnfilledOrdersRequest, opts ...transport.Option) (*GetDomesticUnfilledOrdersResponse, transport.Meta, error) {
	var out GetDomesticUnfilledOrdersResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10075",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
