// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDailyEstimatedDepositAssetRequest 는 일별추정예탁자산현황요청(kt00002) 요청이다.
type GetDomesticDailyEstimatedDepositAssetRequest struct {
	// 시작조회기간 (필수, 8자, YYYYMMDD)
	StartDt string `json:"start_dt"`
	// 종료조회기간 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
}

// GetDomesticDailyEstimatedDepositAssetResponse 는 일별추정예탁자산현황요청(kt00002) 응답이다.
type GetDomesticDailyEstimatedDepositAssetResponse struct {
	// 일별추정예탁자산현황
	DalyPrsmDpstAsetAmtPrst []GetDomesticDailyEstimatedDepositAssetDalyPrsmDpstAsetAmtPrstItem `json:"daly_prsm_dpst_aset_amt_prst"`
}

// GetDomesticDailyEstimatedDepositAssetDalyPrsmDpstAsetAmtPrstItem 는 DalyPrsmDpstAsetAmtPrst 의 원소다.
type GetDomesticDailyEstimatedDepositAssetDalyPrsmDpstAsetAmtPrstItem struct {
	// 일자 (8자, YYYYMMDD)
	Dt string `json:"dt"`
	// 예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Entr string `json:"entr"`
	// 담보대출금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	GrntUseAmt string `json:"grnt_use_amt"`
	// 신용융자금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CrdLoan string `json:"crd_loan"`
	// 대주담보금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	LsGrnt string `json:"ls_grnt"`
	// 대용금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ReplAmt string `json:"repl_amt"`
	// 추정예탁자산 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PrsmDpstAsetAmt string `json:"prsm_dpst_aset_amt"`
	// 추정예탁자산수익증권제외 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PrsmDpstAsetAmtBncrSkip string `json:"prsm_dpst_aset_amt_bncr_skip"`
}

// GetDomesticDailyEstimatedDepositAsset 는 일별추정예탁자산현황요청(kt00002) 이다.
//
// 메뉴: 국내주식 > 계좌 > 일별추정예탁자산현황요청(kt00002)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticDailyEstimatedDepositAsset(ctx context.Context, req GetDomesticDailyEstimatedDepositAssetRequest, opts ...transport.Option) (*GetDomesticDailyEstimatedDepositAssetResponse, transport.Meta, error) {
	var out GetDomesticDailyEstimatedDepositAssetResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00002",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
