// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticOrderFillBalanceRequest 는 체결잔고요청(kt00005) 요청이다.
type GetDomesticOrderFillBalanceRequest struct {
	// 국내거래소구분 (필수, 6자, KRX:한국거래소,NXT:넥스트트레이드)
	DmstStexTp string `json:"dmst_stex_tp"`
}

// GetDomesticOrderFillBalanceResponse 는 체결잔고요청(kt00005) 응답이다.
type GetDomesticOrderFillBalanceResponse struct {
	// 예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Entr string `json:"entr"`
	// 예수금D+1 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EntrD1 string `json:"entr_d1"`
	// 예수금D+2 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EntrD2 string `json:"entr_d2"`
	// 출금가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PymnAlowAmt string `json:"pymn_alow_amt"`
	// 미수확보금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	UnclStkAmt string `json:"uncl_stk_amt"`
	// 대용금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ReplAmt string `json:"repl_amt"`
	// 권리대용금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	RghtReplAmt string `json:"rght_repl_amt"`
	// 주문가능현금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	OrdAlowa string `json:"ord_alowa"`
	// 현금미수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ChUncla string `json:"ch_uncla"`
	// 신용이자미납금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CrdIntNpayGold string `json:"crd_int_npay_gold"`
	// 기타대여금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EtcLoana string `json:"etc_loana"`
	// 미상환융자금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	NrpyLoan string `json:"nrpy_loan"`
	// 증거금현금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ProfaCh string `json:"profa_ch"`
	// 증거금대용 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ReplProfa string `json:"repl_profa"`
	// 주식매수총액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	StkBuyTotAmt string `json:"stk_buy_tot_amt"`
	// 평가금액합계 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EvltAmtTot string `json:"evlt_amt_tot"`
	// 총손익합계 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotPlTot string `json:"tot_pl_tot"`
	// 총손익률 (12자, 단위: %, 소수점 넷째 자리까지 포맷된 백분율)
	TotPlRt string `json:"tot_pl_rt"`
	// 총재매수가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TotReBuyAlowa string `json:"tot_re_buy_alowa"`
	// 20%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N20ordAlowAmt string `json:"20ord_alow_amt"`
	// 30%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N30ordAlowAmt string `json:"30ord_alow_amt"`
	// 40%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N40ordAlowAmt string `json:"40ord_alow_amt"`
	// 50%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N50ordAlowAmt string `json:"50ord_alow_amt"`
	// 60%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N60ordAlowAmt string `json:"60ord_alow_amt"`
	// 100%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	N100ordAlowAmt string `json:"100ord_alow_amt"`
	// 신용융자합계 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CrdLoanTot string `json:"crd_loan_tot"`
	// 신용융자대주합계 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CrdLoanLsTot string `json:"crd_loan_ls_tot"`
	// 신용담보비율 (12자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CrdGrntRt string `json:"crd_grnt_rt"`
	// 예탁담보대출금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	DpstGrntUseAmtAmt string `json:"dpst_grnt_use_amt_amt"`
	// 매도담보대출금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	GrntLoanAmt string `json:"grnt_loan_amt"`
	// 종목별체결잔고
	StkCntrRemn []GetDomesticOrderFillBalanceStkCntrRemnItem `json:"stk_cntr_remn"`
}

// GetDomesticOrderFillBalanceStkCntrRemnItem 는 StkCntrRemn 의 원소다.
type GetDomesticOrderFillBalanceStkCntrRemnItem struct {
	// 신용구분 (2자)
	CrdTp string `json:"crd_tp"`
	// 대출일 (8자, YYYMMDD)
	LoanDt string `json:"loan_dt"`
	// 만기일 (8자, YYYMMDD)
	ExprDt string `json:"expr_dt"`
	// 종목번호 (12자, 접두어 1자리 + 종목코드 6자리, 접두어(A: 주식 / J: ELW / Q: ETN))
	StkCd string `json:"stk_cd"`
	// 종목명 (30자)
	StkNm string `json:"stk_nm"`
	// 결제잔고 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	SetlRemn string `json:"setl_remn"`
	// 현재잔고 (12자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CurQty string `json:"cur_qty"`
	// 현재가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	CurPrc string `json:"cur_prc"`
	// 매입단가 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	BuyUv string `json:"buy_uv"`
	// 매입금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PurAmt string `json:"pur_amt"`
	// 평가금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EvltAmt string `json:"evlt_amt"`
	// 평가손익 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	EvltvPrft string `json:"evltv_prft"`
	// 손익률 (12자, 단위: %, 소수점 넷째 자리까지 포맷된 백분율)
	PlRt string `json:"pl_rt"`
}

// GetDomesticOrderFillBalance 는 체결잔고요청(kt00005) 이다.
//
// 메뉴: 국내주식 > 계좌 > 체결잔고요청(kt00005)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticOrderFillBalance(ctx context.Context, req GetDomesticOrderFillBalanceRequest, opts ...transport.Option) (*GetDomesticOrderFillBalanceResponse, transport.Meta, error) {
	var out GetDomesticOrderFillBalanceResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00005",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
