// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticFilledOrdersRequest 는 체결요청(ka10076) 요청이다.
type GetDomesticFilledOrdersRequest struct {
	// 종목코드 (6자, 종목코드 6자리)
	StkCd string `json:"stk_cd"`
	// 조회구분 (필수, 1자, 0:전체, 1:종목)
	QryTp string `json:"qry_tp"`
	// 매도수구분 (필수, 1자, 0:전체, 1:매도, 2:매수)
	SellTp string `json:"sell_tp"`
	// 주문번호 (10자, 검색 기준 값으로 입력한 주문번호 보다 과거에 체결된 내역이 조회됩니다.)
	OrdNo string `json:"ord_no"`
	// 거래소구분 (필수, 1자, 0 : 통합, 1 : KRX, 2 : NXT)
	StexTp string `json:"stex_tp"`
}

// GetDomesticFilledOrdersResponse 는 체결요청(ka10076) 응답이다.
type GetDomesticFilledOrdersResponse struct {
	// 체결
	Cntr []GetDomesticFilledOrdersCntrItem `json:"cntr"`
}

// GetDomesticFilledOrdersCntrItem 는 Cntr 의 원소다.
type GetDomesticFilledOrdersCntrItem struct {
	// 주문번호 (20자, 주문번호 7자리)
	OrdNo string `json:"ord_no"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 주문구분 (20자)
	IoTpNm string `json:"io_tp_nm"`
	// 주문가격 (20자, 단위: 원)
	OrdPric string `json:"ord_pric"`
	// 주문수량 (20자, 단위: 1주)
	OrdQty string `json:"ord_qty"`
	// 체결가 (20자, 단위: 원)
	CntrPric string `json:"cntr_pric"`
	// 체결량 (20자, 단위: 1주)
	CntrQty string `json:"cntr_qty"`
	// 미체결수량 (20자, 단위: 1주)
	OsoQty string `json:"oso_qty"`
	// 당일매매수수료 (20자, 단위: 원)
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	// 당일매매세금 (20자, 단위: 원)
	TdyTrdeTax string `json:"tdy_trde_tax"`
	// 주문상태 (20자)
	OrdStt string `json:"ord_stt"`
	// 매매구분 (20자)
	TrdeTp string `json:"trde_tp"`
	// 원주문번호 (20자, 원 주문이 없는 경우 '0000000'으로 출력)
	OrigOrdNo string `json:"orig_ord_no"`
	// 주문시간 (20자, HHmmss)
	OrdTm string `json:"ord_tm"`
	// 종목코드 (20자, 종목코드 6자리)
	StkCd string `json:"stk_cd"`
	// 거래소구분 (20자, 0 : 통합, 1 : KRX, 2 : NXT)
	StexTp string `json:"stex_tp"`
	// 거래소구분텍스트 (20자, 통합,KRX,NXT)
	StexTpTxt string `json:"stex_tp_txt"`
	// SOR 여부값 (20자, Y,N)
	SorYn string `json:"sor_yn"`
	// 스톱가 (20자, 스톱지정가주문 스톱가)
	StopPric string `json:"stop_pric"`
}

// GetDomesticFilledOrders 는 체결요청(ka10076) 이다.
//
// 메뉴: 국내주식 > 계좌 > 체결요청(ka10076)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticFilledOrders(ctx context.Context, req GetDomesticFilledOrdersRequest, opts ...transport.Option) (*GetDomesticFilledOrdersResponse, transport.Meta, error) {
	var out GetDomesticFilledOrdersResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10076",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
