// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDailyRealizedPnlRequest 는 일자별실현손익요청(ka10074) 요청이다.
type GetDomesticDailyRealizedPnlRequest struct {
	// 시작일자 (필수, 8자, YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 종료일자 (필수, 8자, YYYYMMDD)
	EndDt string `json:"end_dt"`
}

// GetDomesticDailyRealizedPnlResponse 는 일자별실현손익요청(ka10074) 응답이다.
type GetDomesticDailyRealizedPnlResponse struct {
	// 총매수금액 (단위: 원)
	TotBuyAmt string `json:"tot_buy_amt"`
	// 총매도금액 (단위: 원)
	TotSellAmt string `json:"tot_sell_amt"`
	// 실현손익 (단위: 원)
	RlztPl string `json:"rlzt_pl"`
	// 매매수수료 (단위: 원)
	TrdeCmsn string `json:"trde_cmsn"`
	// 매매세금 (단위: 원)
	TrdeTax string `json:"trde_tax"`
	// 일자별실현손익
	DtRlztPl []GetDomesticDailyRealizedPnlDtRlztPlItem `json:"dt_rlzt_pl"`
}

// GetDomesticDailyRealizedPnlDtRlztPlItem 는 DtRlztPl 의 원소다.
type GetDomesticDailyRealizedPnlDtRlztPlItem struct {
	// 일자 (20자, YYYYMMDD)
	Dt string `json:"dt"`
	// 매수금액 (20자, 단위: 원)
	BuyAmt string `json:"buy_amt"`
	// 매도금액 (20자, 단위: 원)
	SellAmt string `json:"sell_amt"`
	// 당일매도손익 (20자, 단위: 원)
	TdySelPl string `json:"tdy_sel_pl"`
	// 당일매매수수료 (20자, 단위: 원)
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	// 당일매매세금 (20자, 단위: 원)
	TdyTrdeTax string `json:"tdy_trde_tax"`
}

// GetDomesticDailyRealizedPnl 는 일자별실현손익요청(ka10074) 이다.
//
// 메뉴: 국내주식 > 계좌 > 일자별실현손익요청(ka10074)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticDailyRealizedPnl(ctx context.Context, req GetDomesticDailyRealizedPnlRequest, opts ...transport.Option) (*GetDomesticDailyRealizedPnlResponse, transport.Meta, error) {
	var out GetDomesticDailyRealizedPnlResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka10074",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
