// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEstimatedAssetRequest 는 추정자산조회요청(kt00003) 요청이다.
type GetDomesticEstimatedAssetRequest struct {
	// 상장폐지조회구분 (필수, 1자, 0:전체, 1:상장폐지종목제외)
	QryTp string `json:"qry_tp"`
}

// GetDomesticEstimatedAssetResponse 는 추정자산조회요청(kt00003) 응답이다.
type GetDomesticEstimatedAssetResponse struct {
	// 추정예탁자산 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PrsmDpstAsetAmt string `json:"prsm_dpst_aset_amt"`
}

// GetDomesticEstimatedAsset 는 추정자산조회요청(kt00003) 이다.
//
// 메뉴: 국내주식 > 계좌 > 추정자산조회요청(kt00003)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticEstimatedAsset(ctx context.Context, req GetDomesticEstimatedAssetRequest, opts ...transport.Option) (*GetDomesticEstimatedAssetResponse, transport.Meta, error) {
	var out GetDomesticEstimatedAssetResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00003",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
