// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticOrderWithdrawableAmountRequest 는 주문인출가능금액요청(kt00010) 요청이다.
type GetDomesticOrderWithdrawableAmountRequest struct {
	// 입출금액 (12자, 단위: 원)
	IoAmt string `json:"io_amt"`
	// 종목번호 (필수, 12자, 종목 코드 입력)
	StkCd string `json:"stk_cd"`
	// 매매구분 (필수, 1자, 1:매도, 2:매수)
	TrdeTp string `json:"trde_tp"`
	// 매매수량 (10자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 매수가격 (필수, 10자, 단위: 원)
	Uv string `json:"uv"`
	// 예상매수단가 (10자, 단위: 원)
	ExpBuyUnp string `json:"exp_buy_unp"`
}

// GetDomesticOrderWithdrawableAmountResponse 는 주문인출가능금액요청(kt00010) 응답이다.
type GetDomesticOrderWithdrawableAmountResponse struct {
	// 증거금20%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa20ordAlowAmt string `json:"profa_20ord_alow_amt"`
	// 증거금20%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa20ordAlowq string `json:"profa_20ord_alowq"`
	// 증거금30%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa30ordAlowAmt string `json:"profa_30ord_alow_amt"`
	// 증거금30%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa30ordAlowq string `json:"profa_30ord_alowq"`
	// 증거금40%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa40ordAlowAmt string `json:"profa_40ord_alow_amt"`
	// 증거금40%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa40ordAlowq string `json:"profa_40ord_alowq"`
	// 증거금50%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa50ordAlowAmt string `json:"profa_50ord_alow_amt"`
	// 증거금50%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa50ordAlowq string `json:"profa_50ord_alowq"`
	// 증거금60%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa60ordAlowAmt string `json:"profa_60ord_alow_amt"`
	// 증거금60%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa60ordAlowq string `json:"profa_60ord_alowq"`
	// 증거금감면60%주문가능금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ProfaRdex60ordAlowAmt string `json:"profa_rdex_60ord_alow_amt"`
	// 증거금감면60%주문가능수 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	ProfaRdex60ordAlowq string `json:"profa_rdex_60ord_alowq"`
	// 증거금100%주문가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Profa100ordAlowAmt string `json:"profa_100ord_alow_amt"`
	// 증거금100%주문가능수량 (10자, 단위: 1주, 좌측 0-padding 처리된 부호 포함 10자리 숫자)
	Profa100ordAlowq string `json:"profa_100ord_alowq"`
	// 전일재사용가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PredReuAlowa string `json:"pred_reu_alowa"`
	// 금일재사용가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	TdyReuAlowa string `json:"tdy_reu_alowa"`
	// 예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Entr string `json:"entr"`
	// 대용금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	ReplAmt string `json:"repl_amt"`
	// 미수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Uncla string `json:"uncla"`
	// 주문가능대용 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	OrdPosRepl string `json:"ord_pos_repl"`
	// 주문가능현금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	OrdAlowa string `json:"ord_alowa"`
	// 인출가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	WthdAlowa string `json:"wthd_alowa"`
	// 익일인출가능금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	NxdyWthdAlowa string `json:"nxdy_wthd_alowa"`
	// 매입금액 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PurAmt string `json:"pur_amt"`
	// 수수료 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	Cmsn string `json:"cmsn"`
	// 매입정산금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	PurExctAmt string `json:"pur_exct_amt"`
	// D2추정예수금 (12자, 단위: 원, 좌측 0-padding 처리된 부호 포함 12자리 숫자)
	D2entra string `json:"d2entra"`
	// 증거금감면적용구분 (1자, 0:일반,1:60%감면)
	ProfaRdexAplcTp string `json:"profa_rdex_aplc_tp"`
}

// GetDomesticOrderWithdrawableAmount 는 주문인출가능금액요청(kt00010) 이다.
//
// 메뉴: 국내주식 > 계좌 > 주문인출가능금액요청(kt00010)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticOrderWithdrawableAmount(ctx context.Context, req GetDomesticOrderWithdrawableAmountRequest, opts ...transport.Option) (*GetDomesticOrderWithdrawableAmountResponse, transport.Meta, error) {
	var out GetDomesticOrderWithdrawableAmountResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00010",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
