// Code generated by tools/gen. DO NOT EDIT.

package account

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticDepositDetailRequest 는 예수금상세현황요청(kt00001) 요청이다.
type GetDomesticDepositDetailRequest struct {
	// 조회구분 (필수, 1자, 3:추정조회, 2:일반조회)
	QryTp string `json:"qry_tp"`
}

// GetDomesticDepositDetailResponse 는 예수금상세현황요청(kt00001) 응답이다.
type GetDomesticDepositDetailResponse struct {
	// 예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	Entr string `json:"entr"`
	// 주식증거금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ProfaCh string `json:"profa_ch"`
	// 수익증권증거금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	BncrProfaCh string `json:"bncr_profa_ch"`
	// 익일수익증권매도정산대금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	NxdyBncrSellExct string `json:"nxdy_bncr_sell_exct"`
	// 해외주식원화대용설정금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FcStkKrwReplSetAmt string `json:"fc_stk_krw_repl_set_amt"`
	// 신용보증금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntaCh string `json:"crd_grnta_ch"`
	// 신용담보금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntCh string `json:"crd_grnt_ch"`
	// 추가담보금현금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	AddGrntCh string `json:"add_grnt_ch"`
	// 기타증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EtcProfa string `json:"etc_profa"`
	// 미수확보금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	UnclStkAmt string `json:"uncl_stk_amt"`
	// 공매도대금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ShrtsPrica string `json:"shrts_prica"`
	// 신용설정평가금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdSetGrnta string `json:"crd_set_grnta"`
	// 수표입금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChckInaAmt string `json:"chck_ina_amt"`
	// 기타수표입금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EtcChckInaAmt string `json:"etc_chck_ina_amt"`
	// 신용담보재사용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntRuse string `json:"crd_grnt_ruse"`
	// 코넥스기본예탁금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	KnxAssetEvltv string `json:"knx_asset_evltv"`
	// ELW예탁평가금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ElwdpstEvlta string `json:"elwdpst_evlta"`
	// 신용대주권리예정금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdLsRghtFrcsAmt string `json:"crd_ls_rght_frcs_amt"`
	// 생계형가입금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LvlhJoinAmt string `json:"lvlh_join_amt"`
	// 생계형입금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LvlhTrnsAlowa string `json:"lvlh_trns_alowa"`
	// 대용금평가금액(합계) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ReplAmt string `json:"repl_amt"`
	// 잔고대용평가금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	RemnReplEvlta string `json:"remn_repl_evlta"`
	// 위탁대용잔고평가금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	TrstRemnReplEvlta string `json:"trst_remn_repl_evlta"`
	// 수익증권대용평가금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	BncrRemnReplEvlta string `json:"bncr_remn_repl_evlta"`
	// 위탁증거금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ProfaRepl string `json:"profa_repl"`
	// 신용보증금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntaRepl string `json:"crd_grnta_repl"`
	// 신용담보금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdGrntRepl string `json:"crd_grnt_repl"`
	// 추가담보금대용 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	AddGrntRepl string `json:"add_grnt_repl"`
	// 권리대용금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	RghtReplAmt string `json:"rght_repl_amt"`
	// 출금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PymnAlowAmt string `json:"pymn_alow_amt"`
	// 랩출금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	WrapPymnAlowAmt string `json:"wrap_pymn_alow_amt"`
	// 주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	OrdAlowAmt string `json:"ord_alow_amt"`
	// 수익증권매수가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	BncrBuyAlowa string `json:"bncr_buy_alowa"`
	// 20%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N20stkOrdAlowAmt string `json:"20stk_ord_alow_amt"`
	// 30%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N30stkOrdAlowAmt string `json:"30stk_ord_alow_amt"`
	// 40%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N40stkOrdAlowAmt string `json:"40stk_ord_alow_amt"`
	// 100%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N100stkOrdAlowAmt string `json:"100stk_ord_alow_amt"`
	// 현금미수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChUncla string `json:"ch_uncla"`
	// 현금미수연체료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChUnclaDlfe string `json:"ch_uncla_dlfe"`
	// 현금미수금합계 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	ChUnclaTot string `json:"ch_uncla_tot"`
	// 신용이자미납 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	CrdIntNpay string `json:"crd_int_npay"`
	// 신용이자미납연체료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	IntNpayAmtDlfe string `json:"int_npay_amt_dlfe"`
	// 신용이자미납합계 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	IntNpayAmtTot string `json:"int_npay_amt_tot"`
	// 기타대여금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EtcLoana string `json:"etc_loana"`
	// 기타대여금연체료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EtcLoanaDlfe string `json:"etc_loana_dlfe"`
	// 기타대여금합계 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	EtcLoanTot string `json:"etc_loan_tot"`
	// 미상환융자금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	NrpyLoan string `json:"nrpy_loan"`
	// 융자금합계 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LoanSum string `json:"loan_sum"`
	// 대주금합계 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LsSum string `json:"ls_sum"`
	// 신용담보비율 (15자, 단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	CrdGrntRt string `json:"crd_grnt_rt"`
	// 중도이용료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	MdstrmUsfe string `json:"mdstrm_usfe"`
	// 최소주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	MinOrdAlowYn string `json:"min_ord_alow_yn"`
	// 대출총평가금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	LoanRemnEvltAmt string `json:"loan_remn_evlt_amt"`
	// 예탁담보대출잔고 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DpstGrntlRemn string `json:"dpst_grntl_remn"`
	// 매도담보대출잔고 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	SellGrntlRemn string `json:"sell_grntl_remn"`
	// d+1추정예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1Entra string `json:"d1_entra"`
	// d+1매도매수정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1SlbyExctAmt string `json:"d1_slby_exct_amt"`
	// d+1매수정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1BuyExctAmt string `json:"d1_buy_exct_amt"`
	// d+1미수변제소요금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1OutRepMor string `json:"d1_out_rep_mor"`
	// d+1매도정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1SelExctAmt string `json:"d1_sel_exct_amt"`
	// d+1출금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1PymnAlowAmt string `json:"d1_pymn_alow_amt"`
	// d+2추정예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2Entra string `json:"d2_entra"`
	// d+2매도매수정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2SlbyExctAmt string `json:"d2_slby_exct_amt"`
	// d+2매수정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2BuyExctAmt string `json:"d2_buy_exct_amt"`
	// d+2미수변제소요금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2OutRepMor string `json:"d2_out_rep_mor"`
	// d+2매도정산금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2SelExctAmt string `json:"d2_sel_exct_amt"`
	// d+2출금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2PymnAlowAmt string `json:"d2_pymn_alow_amt"`
	// 50%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N50stkOrdAlowAmt string `json:"50stk_ord_alow_amt"`
	// 60%종목주문가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	N60stkOrdAlowAmt string `json:"60stk_ord_alow_amt"`
	// 종목별예수금
	StkEntrPrst []GetDomesticDepositDetailStkEntrPrstItem `json:"stk_entr_prst"`
}

// GetDomesticDepositDetailStkEntrPrstItem 는 StkEntrPrst 의 원소다.
type GetDomesticDepositDetailStkEntrPrstItem struct {
	// 통화코드 (3자, 통화코드 3자리)
	CrncCd string `json:"crnc_cd"`
	// 외화예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FxEntr string `json:"fx_entr"`
	// 원화대용평가금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FcKrwReplEvlta string `json:"fc_krw_repl_evlta"`
	// 해외주식증거금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FcTrstProfa string `json:"fc_trst_profa"`
	// 출금가능금액 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PymnAlowAmt string `json:"pymn_alow_amt"`
	// 출금가능금액(예수금) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	PymnAlowAmtEntr string `json:"pymn_alow_amt_entr"`
	// 주문가능금액(예수금) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	OrdAlowAmtEntr string `json:"ord_alow_amt_entr"`
	// 외화미수(합계) (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FcUncla string `json:"fc_uncla"`
	// 외화현금미수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	FcChUncla string `json:"fc_ch_uncla"`
	// 연체료 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	DlyAmt string `json:"dly_amt"`
	// d+1외화예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D1FxEntr string `json:"d1_fx_entr"`
	// d+2외화예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D2FxEntr string `json:"d2_fx_entr"`
	// d+3외화예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D3FxEntr string `json:"d3_fx_entr"`
	// d+4외화예수금 (15자, 단위: 원, 좌측 0-padding 처리된 부호 포함 15자리 숫자)
	D4FxEntr string `json:"d4_fx_entr"`
}

// GetDomesticDepositDetail 는 예수금상세현황요청(kt00001) 이다.
//
// 메뉴: 국내주식 > 계좌 > 예수금상세현황요청(kt00001)
// URL:  /api/dostk/acnt
func (c *Client) GetDomesticDepositDetail(ctx context.Context, req GetDomesticDepositDetailRequest, opts ...transport.Option) (*GetDomesticDepositDetailResponse, transport.Meta, error) {
	var out GetDomesticDepositDetailResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "kt00001",
		Path:  "/api/dostk/acnt",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
