// Code generated by tools/gen. DO NOT EDIT.

package condition

import "context"

// ListOverseasConditionSearchesRequest 는 미국주식 조건검색 목록조회(usa20280) 요청이다.
//
// trnm 은 여기 없다. 값이 GCNSRLST 하나로 정해져 있어 호출자가 고를 것이 없고, 비워 두면
// 서버 응답이 짝을 찾지 못해 ctx 만료까지 조용히 매달린다 — 전송 직전에 아래 메서드가 넣는다.
type ListOverseasConditionSearchesRequest struct {
}

// ListOverseasConditionSearchesResponse 는 미국주식 조건검색 목록조회(usa20280) 응답이다.
//
// return_code·return_msg 는 여기 없다. 전송 계층이 return_code != 0 을 *kiwoom.WSAPIError
// 로 바꿔 주므로, 이 구조체를 받았다는 것 자체가 이미 정상이라는 뜻이다(정상이면 스펙상
// return_msg 도 비어 있다). 게다가 스펙은 결과코드를 String 이라 적었지만 서버는 int 로
// 보내 — 남겨 두면 응답 파싱이 통째로 실패한다.
type ListOverseasConditionSearchesResponse struct {
	// 서비스명 (GCNSRLT고정값)
	Trnm string `json:"trnm"`
	// 조건검색식 목록
	Data []ListOverseasConditionSearchesDataItem `json:"data"`
}

// ListOverseasConditionSearchesDataItem 는 Data 의 원소다.
type ListOverseasConditionSearchesDataItem struct {
	// 조건검색식 일련번호
	Seq string `json:"seq"`
	// 조건검색식 명
	Name string `json:"name"`
}

// ListOverseasConditionSearches 는 미국주식 조건검색 목록조회(usa20280) 이다. WebSocket 위의 요청/응답이다.
//
// 메뉴: 미국주식 > 조건검색 > 미국주식 조건검색 목록조회(usa20280)
// URL:  /api/us/websocket  (trnm: GCNSRLST)
func (c *Client) ListOverseasConditionSearches(ctx context.Context, req ListOverseasConditionSearchesRequest) (*ListOverseasConditionSearchesResponse, error) {
	// 익명 래퍼로 trnm 을 끼운다. 임베드한 필드는 encoding/json 이 바깥으로 끌어올리므로
	// 나가는 본문은 {"trnm":"GCNSRLST", ...req} 가 된다.
	body := struct {
		Trnm string `json:"trnm"`
		ListOverseasConditionSearchesRequest
	}{Trnm: "GCNSRLST", ListOverseasConditionSearchesRequest: req}

	var out ListOverseasConditionSearchesResponse
	if err := c.ws.Request(ctx, "GCNSRLST", body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
