// 이 파일은 **손으로 쓴 것이다.** 생성하지 않는다 — tools/gen/groups.go 의 handWritten 참고.
//
// 생성물 헤더("Code generated by tools/gen. DO NOT EDIT.")를 붙이지 마라. 붙이는 순간
// cleanGenerated 가 다음 생성 때 이 파일을 지우고, 골든 테스트는 "생성 대상이 아닌데
// 헤더가 붙었다"(orphan)로 터진다. 헤더가 없으면 둘 다 이 파일을 건드리지 않는다.
//
// usa20290 을 빼는 이유는 국내 짝(ka10173)과 **다르다.** 이쪽은 스펙이 갈라지지 않아
// 생성기의 BuildTree 를 통과한다. 문제는 푸시 쪽이다 — 푸시는 실제로 오는데(공식 예제가
// 실시간을 모은다) 스펙에 그 FID 표가 통째로 비어 있다. 예제도 COLUMNS = {} 에 "수동
// 생성 필요" 마커를 달아 두었다(tools/spec/SOURCE.md 참고).
//
// 그래서 조회 응답에는 타입을 붙이고, 푸시는 Raw 맵으로만 낸다. FID 이름을 지어내지
// 않는다 — 스펙에 없는 것을 있는 것처럼 만들지 않는다.

package condition

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/stream"
)

// RequestOverseasRealtimeConditionSearchRequest 는 미국주식 조건검색 요청 실시간(usa20290) 요청이다.
//
// trnm 은 여기 없다. 값이 GCNSRREQ 하나로 정해져 있어 호출자가 고를 것이 없고, 비워 두면
// 서버 응답이 짝을 찾지 못해 ctx 만료까지 조용히 매달린다 — 전송 직전에 아래 메서드가 넣는다.
type RequestOverseasRealtimeConditionSearchRequest struct {
	// 조건검색식 일련번호 (필수, 3자)
	Seq string `json:"seq"`
	// 조회타입 (필수, 1: 조건검색+실시간조건검색)
	SearchType string `json:"search_type"`
}

// RequestOverseasRealtimeConditionSearchResponse 는 미국주식 조건검색 요청 실시간(usa20290) 의
// **조회 응답**이다. 푸시 이전에 한 번 온다.
//
// return_code·return_msg 는 여기 없다. 전송 계층이 return_code != 0 을 *kiwoom.WSAPIError
// 로 바꿔 주므로, 이 구조체를 받았다는 것 자체가 이미 정상이라는 뜻이다(정상이면 스펙상
// return_msg 도 비어 있다). 게다가 스펙은 결과코드를 String 이라 적었지만 서버는 int 로
// 보내 — 남겨 두면 응답 파싱이 통째로 실패한다.
type RequestOverseasRealtimeConditionSearchResponse struct {
	// 서비스명 (GCNSRREQ)
	Trnm string `json:"trnm"`
	// 조건검색식 일련번호
	Seq string `json:"seq"`
	// 검색결과데이터
	Data []RequestOverseasRealtimeConditionSearchDataItem `json:"data"`
}

// RequestOverseasRealtimeConditionSearchDataItem 는 Data 의 원소다.
type RequestOverseasRealtimeConditionSearchDataItem struct {
	// 종목코드
	Jmcode string `json:"jmcode"`
	// 거래소구분 (ND 등)
	StexTp string `json:"stex_tp"`
}

// UnmarshalJSON 은 거래소구분을 두 철자 모두에서 읽는다.
//
// 스펙 표는 이 요소를 stexTp 라 적었는데 같은 문서의 응답 예제는 stex_tp 로 보낸다
// (미국 조건검색 요청 일반 usa20281 의 스펙도 stex_tp 다). 둘 중 하나를 골라 태그를 달면
// 반대쪽이 올 때 필드가 조용히 빈 채로 남는다 — 어느 쪽이 맞는지 문서가 스스로 어긋나
// 있으니, 고르지 않고 둘 다 받는다.
func (it *RequestOverseasRealtimeConditionSearchDataItem) UnmarshalJSON(b []byte) error {
	var raw struct {
		Jmcode string `json:"jmcode"`
		Snake  string `json:"stex_tp"`
		Camel  string `json:"stexTp"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	it.Jmcode = raw.Jmcode
	it.StexTp = raw.Snake
	if it.StexTp == "" {
		it.StexTp = raw.Camel
	}
	return nil
}

// OverseasRealtimeConditionMatch 는 미국 조건검색 푸시의 값 타입이다. **늘 비어 있다.**
//
// 337개 중 이것 하나만 이렇다. "푸시를 지원하지 않는다" 가 아니라 **"이름표가 없다"** 가
// 사실이고, 둘은 다르다 — 푸시는 실제로 오고 stream.Event.Raw 에 받은 FID 가 전부 들어
// 있다. 다만 스펙에 그 FID 들의 한글명 표가 통째로 비어 있어(공식 예제도 COLUMNS = {})
// 어느 숫자가 무엇인지 문서가 말해 주지 않는다. 그래서 Go 필드 이름을 지어내지 않는다.
//
// 값을 읽으려면 Raw 를 쓰라. 예: ev.Raw["9001"].
//
// 빈 구조체를 익명 struct{} 대신 이름 붙여 두는 이유는 나중을 위해서다 — 키움이 표를
// 채우면 여기에 필드를 더하기만 하면 되고, 메서드 서명은 그대로다. stream.Event[struct{}]
// 로 냈다면 그때 서명이 바뀌어 쓰던 코드가 깨진다.
type OverseasRealtimeConditionMatch struct{}

// RequestOverseasRealtimeConditionSearch 는 미국주식 조건검색 요청 실시간(usa20290) 이다.
// WebSocket 위의 요청/응답이고, 그 뒤로 편입·이탈 푸시가 이어진다.
//
// 조회 응답은 타입이 붙지만 **푸시는 Raw 맵뿐이다** — 스펙에 FID 이름표가 없다
// (OverseasRealtimeConditionMatch 주석 참고). ev.Value 는 늘 영값이고, 받은 FID 는
// 전부 ev.Raw 에 있다. 푸시 원소에 붙는 stexTp 는 실시간 봉투가 싣지 않는다 —
// 그 자리는 values 안이 아니라 밖이고, 실시간 23종 어디에도 없는 필드다.
//
// 푸시는 종목별 등록(REG)이 아니라 **이 요청 자체가 등록**이라, 채널은 조건검색식
// 일련번호(req.Seq)로 갈린다.
//
// ctx 를 취소하면 채널이 닫힌다. 다만 그것은 받기를 그만두는 것일 뿐 **서버에 해제를
// 보내지 않는다** — 실시간 해제는 StopOverseasRealtimeConditionSearch(usa20291)로 따로
// 보내야 한다. 그러지 않으면 서버는 계속 밀어 보낸다.
//
// 채널이 가득 차면 이벤트를 버리고 *kiwoom.SlowConsumerError 를 흘린다. 끊겼다 붙으면
// *kiwoom.GapError 가 온다 — 조건검색 등록은 재연결이 되살리지 못하므로, 이 채널에서
// 그것을 받으면 이 메서드를 다시 불러 등록을 새로 세워야 한다.
//
// 메뉴: 미국주식 > 조건검색 > 미국주식 조건검색 요청 실시간(usa20290)
// URL:  /api/us/websocket  (trnm: GCNSRREQ, 이후 REAL 푸시)
func (c *Client) RequestOverseasRealtimeConditionSearch(
	ctx context.Context, req RequestOverseasRealtimeConditionSearchRequest,
) (*RequestOverseasRealtimeConditionSearchResponse, <-chan stream.Event[OverseasRealtimeConditionMatch], error) {
	// 라우팅을 **요청보다 먼저** 붙인다. 이유는 국내 짝과 같다 — 응답을 기다렸다 붙이면
	// 그 사이에 온 첫 푸시가 갈 곳이 없어 버려진다.
	subCtx, cancel := context.WithCancel(ctx)
	// 실패해서 돌아가는 길에는 라우팅을 뗀다. 채널을 넘겨준 뒤에는 ctx 가 그 일을 맡는다.
	handedOff := false
	defer func() {
		if !handedOff {
			cancel()
		}
	}()

	src, err := c.ws.SubscribeCondition(subCtx, req.Seq, defaultBuffer)
	if err != nil {
		return nil, nil, err
	}

	body := struct {
		Trnm string `json:"trnm"`
		RequestOverseasRealtimeConditionSearchRequest
	}{Trnm: "GCNSRREQ", RequestOverseasRealtimeConditionSearchRequest: req}

	var out RequestOverseasRealtimeConditionSearchResponse
	if err := c.ws.Request(ctx, "GCNSRREQ", body, &out); err != nil {
		return nil, nil, err
	}

	ch := make(chan stream.Event[OverseasRealtimeConditionMatch], defaultBuffer)
	go func() {
		defer close(ch)
		for d := range src {
			ev := stream.Event[OverseasRealtimeConditionMatch]{
				Symbol: d.Item, Name: d.Name, Time: d.Time, Err: d.Err,
			}
			// 한 번만 푼다. 국내 짝은 구조체와 Raw 를 함께 채우지만 여기는 채울 구조체가
			// 없다 — 이름표가 없으니 Raw 가 전부다.
			if d.Err == nil {
				if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
					ev.Err = err
				}
			}
			ch <- ev
		}
	}()
	handedOff = true
	return &out, ch, nil
}
