// Code generated by tools/gen. DO NOT EDIT.

package condition

import "context"

// StopOverseasRealtimeConditionSearchRequest 는 미국주식 조건검색 실시간 해제(usa20291) 요청이다.
//
// trnm 은 여기 없다. 값이 GCNSRCLR 하나로 정해져 있어 호출자가 고를 것이 없고, 비워 두면
// 서버 응답이 짝을 찾지 못해 ctx 만료까지 조용히 매달린다 — 전송 직전에 아래 메서드가 넣는다.
type StopOverseasRealtimeConditionSearchRequest struct {
	// 조건검색식 일련번호 (필수)
	Seq string `json:"seq"`
}

// StopOverseasRealtimeConditionSearchResponse 는 미국주식 조건검색 실시간 해제(usa20291) 응답이다.
type StopOverseasRealtimeConditionSearchResponse struct {
	// 결과코드 (필수, 정상:0 나머지:에러)
	ReturnCode string `json:"return_code"`
	// 결과메시지 (필수, 정상인 경우는 메시지 없음)
	ReturnMsg string `json:"return_msg"`
	// 서비스명 (필수, GCNSRCLR 고정값)
	Trnm string `json:"trnm"`
	// 조건검색식 일련번호 (필수)
	Seq string `json:"seq"`
}

// StopOverseasRealtimeConditionSearch 는 미국주식 조건검색 실시간 해제(usa20291) 이다. WebSocket 위의 요청/응답이다.
//
// 메뉴: 미국주식 > 조건검색 > 미국주식 조건검색 실시간 해제(usa20291)
// URL:  /api/us/websocket  (trnm: GCNSRCLR)
func (c *Client) StopOverseasRealtimeConditionSearch(ctx context.Context, req StopOverseasRealtimeConditionSearchRequest) (*StopOverseasRealtimeConditionSearchResponse, error) {
	// 익명 래퍼로 trnm 을 끼운다. 임베드한 필드는 encoding/json 이 바깥으로 끌어올리므로
	// 나가는 본문은 {"trnm":"GCNSRCLR", ...req} 가 된다.
	body := struct {
		Trnm string `json:"trnm"`
		StopOverseasRealtimeConditionSearchRequest
	}{Trnm: "GCNSRCLR", StopOverseasRealtimeConditionSearchRequest: req}

	var out StopOverseasRealtimeConditionSearchResponse
	if err := c.ws.Request(ctx, "GCNSRCLR", body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
