// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfAllQuotesRequest 는 ETF전체시세요청(ka40004) 요청이다.
type GetDomesticEtfAllQuotesRequest struct {
	// 과세유형 (필수, 1자, 0:전체, 1:비과세, 2:보유기간과세, 3:회사형, 4:외국, 5:비과세해외(보유기간관세))
	TxonType string `json:"txon_type"`
	// NAV대비 (필수, 1자, 0:전체, 1:NAV > 전일종가, 2:NAV < 전일종가)
	Navpre string `json:"navpre"`
	// 운용사 (필수, 4자, 0000:전체, 3020:KODEX(삼성), 3027:KOSEF(키움), 3191:TIGER(미래에셋), 3228:KINDEX(한국투자), 3023:KStar(KB), 3022:아리랑(한화), 9999:기타운용사)
	Mngmcomp string `json:"mngmcomp"`
	// 과세여부 (필수, 1자, 0:전체, 1:과세, 2:비과세)
	TxonYn string `json:"txon_yn"`
	// 추적지수 (필수, 1자, 0:전체)
	TraceIdex string `json:"trace_idex"`
	// 거래소구분 (필수, 1자, 1:KRX, 2:NXT, 3:통합)
	StexTp string `json:"stex_tp"`
}

// GetDomesticEtfAllQuotesResponse 는 ETF전체시세요청(ka40004) 응답이다.
type GetDomesticEtfAllQuotesResponse struct {
	// ETF전체시세
	EtfallMrpr []GetDomesticEtfAllQuotesEtfallMrprItem `json:"etfall_mrpr"`
}

// GetDomesticEtfAllQuotesEtfallMrprItem 는 EtfallMrpr 의 원소다.
type GetDomesticEtfAllQuotesEtfallMrprItem struct {
	// 종목코드 (20자)
	StkCd string `json:"stk_cd"`
	// 종목분류 (20자)
	StkCls string `json:"stk_cls"`
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 대비율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PreRt string `json:"pre_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// NAV (20자, 부호 포함 소수점 둘째 자리까지 포맷된 숫자)
	Nav string `json:"nav"`
	// 추적오차율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TraceEorRt string `json:"trace_eor_rt"`
	// 과표기준 (20자)
	Txbs string `json:"txbs"`
	// 배당전기준 (20자)
	DvidBfBase string `json:"dvid_bf_base"`
	// 전일배당금 (20자)
	PredDvida string `json:"pred_dvida"`
	// 추적지수명 (20자)
	TraceIdexNm string `json:"trace_idex_nm"`
	// 배수 (20자)
	Drng string `json:"drng"`
	// 추적지수코드 (20자)
	TraceIdexCd string `json:"trace_idex_cd"`
	// 추적지수 (20자)
	TraceIdex string `json:"trace_idex"`
	// 추적등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	TraceFluRt string `json:"trace_flu_rt"`
}

// GetDomesticEtfAllQuotes 는 ETF전체시세요청(ka40004) 이다.
//
// 메뉴: 국내주식 > ETF > ETF전체시세요청(ka40004)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfAllQuotes(ctx context.Context, req GetDomesticEtfAllQuotesRequest, opts ...transport.Option) (*GetDomesticEtfAllQuotesResponse, transport.Meta, error) {
	var out GetDomesticEtfAllQuotesResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40004",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
