// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfIntradayNavStatusRequest 는 ETF시간대별NAV현황(ka40009) 요청이다.
type GetDomesticEtfIntradayNavStatusRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticEtfIntradayNavStatusResponse 는 ETF시간대별NAV현황(ka40009) 응답이다.
type GetDomesticEtfIntradayNavStatusResponse struct {
	// ETFNAV배열
	Etfnavarray []GetDomesticEtfIntradayNavStatusEtfnavarrayItem `json:"etfnavarray"`
}

// GetDomesticEtfIntradayNavStatusEtfnavarrayItem 는 Etfnavarray 의 원소다.
type GetDomesticEtfIntradayNavStatusEtfnavarrayItem struct {
	// NAV (20자)
	Nav string `json:"nav"`
	// NAV전일대비 (20자)
	NavpredPre string `json:"navpred_pre"`
	// NAV등락율 (20자)
	NavfluRt string `json:"navflu_rt"`
	// 추적오차율 (20자)
	TraceEorRt string `json:"trace_eor_rt"`
	// 괴리율 (20자)
	DisptyRt string `json:"dispty_rt"`
	// 주식수 (20자)
	Stkcnt string `json:"stkcnt"`
	// 기준가 (20자)
	BasePric string `json:"base_pric"`
	// 외인보유수량 (20자)
	ForRmndQty string `json:"for_rmnd_qty"`
	// 대용가 (20자)
	ReplPric string `json:"repl_pric"`
	// 환산가격 (20자)
	ConvPric string `json:"conv_pric"`
	// DR/주 (20자)
	Drstk string `json:"drstk"`
	// 원주가격 (20자)
	WonjuPric string `json:"wonju_pric"`
}

// GetDomesticEtfIntradayNavStatus 는 ETF시간대별NAV현황(ka40009) 이다.
//
// 메뉴: 국내주식 > ETF > ETF시간대별NAV현황(ka40009)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfIntradayNavStatus(ctx context.Context, req GetDomesticEtfIntradayNavStatusRequest, opts ...transport.Option) (*GetDomesticEtfIntradayNavStatusResponse, transport.Meta, error) {
	var out GetDomesticEtfIntradayNavStatusResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40009",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
