// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfIntradayTrendRequest 는 ETF시간대별추이요청(ka40006) 요청이다.
type GetDomesticEtfIntradayTrendRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticEtfIntradayTrendResponse 는 ETF시간대별추이요청(ka40006) 응답이다.
type GetDomesticEtfIntradayTrendResponse struct {
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// ETF대상지수명 (20자)
	EtfobjtIdexNm string `json:"etfobjt_idex_nm"`
	// 원주가격 (20자)
	WonjuPric string `json:"wonju_pric"`
	// ETF과세유형 (20자)
	EtftxonType string `json:"etftxon_type"`
	// ETN과세유형 (20자)
	EtntxonType string `json:"etntxon_type"`
	// ETF시간대별추이
	EtftislTrnsn []GetDomesticEtfIntradayTrendEtftislTrnsnItem `json:"etftisl_trnsn"`
}

// GetDomesticEtfIntradayTrendEtftislTrnsnItem 는 EtftislTrnsn 의 원소다.
type GetDomesticEtfIntradayTrendEtftislTrnsnItem struct {
	// 시간 (20자, HHmmss)
	Tm string `json:"tm"`
	// 종가 (20자, 단위: 원, 부호가 포함된 숫자)
	ClosePric string `json:"close_pric"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// NAV (20자, 부호 포함 소수점 둘째 자리까지 포맷된 숫자)
	Nav string `json:"nav"`
	// 거래대금 (20자, 단위: 백만원)
	TrdePrica string `json:"trde_prica"`
	// NAV지수 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Navidex string `json:"navidex"`
	// 괴리율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Navetf string `json:"navetf"`
	// 추적오차율 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	Trace string `json:"trace"`
	// 추적지수 (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"값은 26.58을 의미합니다.)
	TraceIdex string `json:"trace_idex"`
	// 추적지수전일대비 (20자, 소수점 제거 된 100배 값으로 제공 예) "2658"값은 26.58을 의미합니다.)
	TraceIdexPredPre string `json:"trace_idex_pred_pre"`
	// 추적지수전일대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	TraceIdexPredPreSig string `json:"trace_idex_pred_pre_sig"`
}

// GetDomesticEtfIntradayTrend 는 ETF시간대별추이요청(ka40006) 이다.
//
// 메뉴: 국내주식 > ETF > ETF시간대별추이요청(ka40006)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfIntradayTrend(ctx context.Context, req GetDomesticEtfIntradayTrendRequest, opts ...transport.Option) (*GetDomesticEtfIntradayTrendResponse, transport.Meta, error) {
	var out GetDomesticEtfIntradayTrendResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40006",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
