// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfInfoRequest 는 ETF종목정보요청(ka40002) 요청이다.
type GetDomesticEtfInfoRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticEtfInfoResponse 는 ETF종목정보요청(ka40002) 응답이다.
type GetDomesticEtfInfoResponse struct {
	// 종목명 (40자)
	StkNm string `json:"stk_nm"`
	// ETF대상지수명 (20자)
	EtfobjtIdexNm string `json:"etfobjt_idex_nm"`
	// 원주가격 (20자)
	WonjuPric string `json:"wonju_pric"`
	// ETF과세유형 (20자)
	EtftxonType string `json:"etftxon_type"`
	// ETN과세유형 (20자)
	EtntxonType string `json:"etntxon_type"`
}

// GetDomesticEtfInfo 는 ETF종목정보요청(ka40002) 이다.
//
// 메뉴: 국내주식 > ETF > ETF종목정보요청(ka40002)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfInfo(ctx context.Context, req GetDomesticEtfInfoRequest, opts ...transport.Option) (*GetDomesticEtfInfoResponse, transport.Meta, error) {
	var out GetDomesticEtfInfoResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40002",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
