// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfReturnRateRequest 는 ETF수익율요청(ka40001) 요청이다.
type GetDomesticEtfReturnRateRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
	// ETF대상지수코드 (필수, 3자)
	EtfobjtIdexCd string `json:"etfobjt_idex_cd"`
	// 기간 (필수, 1자, 0:1주, 1:1달, 2:6개월, 3:1년)
	Dt string `json:"dt"`
}

// GetDomesticEtfReturnRateResponse 는 ETF수익율요청(ka40001) 응답이다.
type GetDomesticEtfReturnRateResponse struct {
	// ETF수익율
	EtfprftRtLst []GetDomesticEtfReturnRateEtfprftRtLstItem `json:"etfprft_rt_lst"`
}

// GetDomesticEtfReturnRateEtfprftRtLstItem 는 EtfprftRtLst 의 원소다.
type GetDomesticEtfReturnRateEtfprftRtLstItem struct {
	// ETF수익률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	EtfprftRt string `json:"etfprft_rt"`
	// 체결수익률 (20자, 단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	CntrPrftRt string `json:"cntr_prft_rt"`
	// 외인순매수수량 (20자)
	ForNetprpsQty string `json:"for_netprps_qty"`
	// 기관순매수수량 (20자)
	OrgnNetprpsQty string `json:"orgn_netprps_qty"`
}

// GetDomesticEtfReturnRate 는 ETF수익율요청(ka40001) 이다.
//
// 메뉴: 국내주식 > ETF > ETF수익율요청(ka40001)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfReturnRate(ctx context.Context, req GetDomesticEtfReturnRateRequest, opts ...transport.Option) (*GetDomesticEtfReturnRateResponse, transport.Meta, error) {
	var out GetDomesticEtfReturnRateResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40001",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
