// Code generated by tools/gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetDomesticEtfIntradaySupplyDemandStatusRequest 는 ETF시간대별수급현황(ka40010) 요청이다.
type GetDomesticEtfIntradaySupplyDemandStatusRequest struct {
	// 종목코드 (필수, 6자)
	StkCd string `json:"stk_cd"`
}

// GetDomesticEtfIntradaySupplyDemandStatusResponse 는 ETF시간대별수급현황(ka40010) 응답이다.
type GetDomesticEtfIntradaySupplyDemandStatusResponse struct {
	// ETF시간대별추이
	EtftislTrnsn []GetDomesticEtfIntradaySupplyDemandStatusEtftislTrnsnItem `json:"etftisl_trnsn"`
}

// GetDomesticEtfIntradaySupplyDemandStatusEtftislTrnsnItem 는 EtftislTrnsn 의 원소다.
type GetDomesticEtfIntradaySupplyDemandStatusEtftislTrnsnItem struct {
	// 현재가 (20자, 단위: 원, 부호가 포함된 숫자)
	CurPrc string `json:"cur_prc"`
	// 대비기호 (20자, 1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PreSig string `json:"pre_sig"`
	// 전일대비 (20자, 단위: 원, 부호가 포함된 숫자)
	PredPre string `json:"pred_pre"`
	// 거래량 (20자, 단위: 1주)
	TrdeQty string `json:"trde_qty"`
	// 외인순매수 (20자, 단위: 1주, 부호가 포함된 숫자)
	ForNetprps string `json:"for_netprps"`
}

// GetDomesticEtfIntradaySupplyDemandStatus 는 ETF시간대별수급현황(ka40010) 이다.
//
// 메뉴: 국내주식 > ETF > ETF시간대별수급현황(ka40010)
// URL:  /api/dostk/etf
func (c *Client) GetDomesticEtfIntradaySupplyDemandStatus(ctx context.Context, req GetDomesticEtfIntradaySupplyDemandStatusRequest, opts ...transport.Option) (*GetDomesticEtfIntradaySupplyDemandStatusResponse, transport.Meta, error) {
	var out GetDomesticEtfIntradaySupplyDemandStatusResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "ka40010",
		Path:  "/api/dostk/etf",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
