// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockTickChartRequest 는 미국주식 틱 차트(usa06010) 요청이다.
type GetOverseasStockTickChartRequest struct {
	// 거래소구분 (필수)
	StexTp string `json:"stex_tp"`
	// 종목코드 (필수)
	StkCd string `json:"stk_cd"`
	// 틱범위
	TicScope string `json:"tic_scope"`
	// 수정주가구분 (0:미적용, 1:적용)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	// 환율적용구분 (0:미적용, 1:적용)
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// GetOverseasStockTickChartResponse 는 미국주식 틱 차트(usa06010) 응답이다.
type GetOverseasStockTickChartResponse struct {
	// 결과리스트
	ResultList []GetOverseasStockTickChartResultListItem `json:"result_list"`
}

// GetOverseasStockTickChartResultListItem 는 ResultList 의 원소다.
type GetOverseasStockTickChartResultListItem struct {
	// 현재가(종가)
	CurPrc string `json:"cur_prc"`
	// 거래량
	TrdeQty string `json:"trde_qty"`
	// 시가
	OpenPric string `json:"open_pric"`
	// 고가
	HighPric string `json:"high_pric"`
	// 저가
	LowPric string `json:"low_pric"`
	// 체결시간
	CntrTm string `json:"cntr_tm"`
	// 영업일자
	BusDt string `json:"bus_dt"`
	// 수정주가구분
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	// 수정비율
	UpdRt string `json:"upd_rt"`
}

// GetOverseasStockTickChart 는 미국주식 틱 차트(usa06010) 이다.
//
// 메뉴: 미국주식 > 차트 > 미국주식 틱 차트(usa06010)
// URL:  /api/us/chart
func (c *Client) GetOverseasStockTickChart(ctx context.Context, req GetOverseasStockTickChartRequest, opts ...transport.Option) (*GetOverseasStockTickChartResponse, transport.Meta, error) {
	var out GetOverseasStockTickChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa06010",
		Path:  "/api/us/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
