// Code generated by tools/gen. DO NOT EDIT.

package chart

import (
	"context"

	"github.com/kenshin579/kiwoom-go/internal/transport"
)

// GetOverseasStockDailyChartRequest 는 미국주식 일 차트(usa06012) 요청이다.
type GetOverseasStockDailyChartRequest struct {
	// 거래소구분 (필수, NA: AMEX, ND: NASDAQ, NY: NYSE)
	StexTp string `json:"stex_tp"`
	// 종목코드
	StkCd string `json:"stk_cd"`
	// 시작일자 (YYYYMMDD)
	StrtDt string `json:"strt_dt"`
	// 수정주가구분 (0:미적용, 1:적용)
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	// 환율적용구분 (0:미적용, 1:적용)
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// GetOverseasStockDailyChartResponse 는 미국주식 일 차트(usa06012) 응답이다.
type GetOverseasStockDailyChartResponse struct {
	// 결과리스트
	ResultList []GetOverseasStockDailyChartResultListItem `json:"result_list"`
}

// GetOverseasStockDailyChartResultListItem 는 ResultList 의 원소다.
type GetOverseasStockDailyChartResultListItem struct {
	// 현재가(종가) (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	CurPrc string `json:"cur_prc"`
	// 전일대비 (단위: USD, 부호 포함 소수점 넷째 자리까지 포맷된 숫자)
	PredPre string `json:"pred_pre"`
	// 등락률 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	FluRt string `json:"flu_rt"`
	// 누적거래량
	AccTrdeQty string `json:"acc_trde_qty"`
	// 누적거래대금
	AccTrdePrica string `json:"acc_trde_prica"`
	// 시가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	OpenPric string `json:"open_pric"`
	// 고가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	HighPric string `json:"high_pric"`
	// 저가 (단위: USD, 소수점 넷째 자리까지 포맷된 숫자)
	LowPric string `json:"low_pric"`
	// 일자 (YYYYMMDD)
	Dt string `json:"dt"`
	// 수정주가구분
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	// 수정비율
	UpdRt string `json:"upd_rt"`
}

// GetOverseasStockDailyChart 는 미국주식 일 차트(usa06012) 이다.
//
// 메뉴: 미국주식 > 차트 > 미국주식 일 차트(usa06012)
// URL:  /api/us/chart
func (c *Client) GetOverseasStockDailyChart(ctx context.Context, req GetOverseasStockDailyChartRequest, opts ...transport.Option) (*GetOverseasStockDailyChartResponse, transport.Meta, error) {
	var out GetOverseasStockDailyChartResponse
	meta, err := c.http.Do(ctx, transport.Request{
		APIID: "usa06012",
		Path:  "/api/us/chart",
		Body:  req,
	}, &out, opts...)
	if err != nil {
		return nil, meta, err
	}
	return &out, meta, nil
}
