// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockExpectedExecution 는 주식예상체결(0H) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockExpectedExecution struct {
	// 체결시간
	TradeTime string `json:"20"`
	// 현재가
	CurrentPrice string `json:"10"`
	// 전일대비
	PrevDayDiff string `json:"11"`
	// 등락율
	ChangeRate string `json:"12"`
	// 거래량
	TradeVolume string `json:"15"`
	// 누적거래량
	CumulativeVolume string `json:"13"`
	// 전일대비기호
	PrevDayDiffSign string `json:"25"`
}

// SubscribeDomesticStockExpectedExecution 은 주식예상체결(0H) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockExpectedExecution(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockExpectedExecution], error) {
	src, err := c.ws.Subscribe(ctx, "0H", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockExpectedExecution], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockExpectedExecution(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockExpectedExecution(d wstransport.Delivery) stream.Event[DomesticStockExpectedExecution] {
	ev := stream.Event[DomesticStockExpectedExecution]{Symbol: d.Item, Name: d.Name, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
