// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockSurge 는 주식기세(0A) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockSurge struct {
	// 현재가 (단위: 원, 부호가 포함된 숫자)
	CurrentPrice string `json:"10"`
	// 전일대비 (단위: 원, 부호가 포함된 숫자)
	PrevDayDiff string `json:"11"`
	// 등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ChangeRate string `json:"12"`
	// (최우선)매도호가 (단위: 원, 부호가 포함된 숫자)
	BestAskPrice string `json:"27"`
	// (최우선)매수호가 (단위: 원, 부호가 포함된 숫자)
	BestBidPrice string `json:"28"`
	// 누적거래량 (단위: 1주)
	CumulativeVolume string `json:"13"`
	// 누적거래대금 (단위: 백만원)
	CumulativeTradeAmount string `json:"14"`
	// 시가 (단위: 원, 부호가 포함된 숫자)
	OpenPrice string `json:"16"`
	// 고가 (단위: 원, 부호가 포함된 숫자)
	HighPrice string `json:"17"`
	// 저가 (단위: 원, 부호가 포함된 숫자)
	LowPrice string `json:"18"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PrevDayDiffSign string `json:"25"`
	// 전일거래량대비(계약,주) (단위: 1주, 부호가 포함된 숫자)
	PrevDayVolumeDiff string `json:"26"`
	// 거래대금증감 (단위: 원, 부호가 포함된 숫자)
	TradeAmountChange string `json:"29"`
	// 전일거래량대비(비율) (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	PrevDayVolumeRatio string `json:"30"`
	// 거래회전율 (단위: %, 소수점 둘째 자리까지 포맷된 백분율)
	TurnoverRate string `json:"31"`
	// 거래비용
	TradeCost string `json:"32"`
	// 시가총액(억) (단위: 억원)
	MarketCapHundredMillionWon string `json:"311"`
	// 상한가발생시간 (HHmmss)
	UpperLimitTime string `json:"567"`
	// 하한가발생시간 (HHmmss)
	LowerLimitTime string `json:"568"`
}

// SubscribeDomesticStockSurge 은 주식기세(0A) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockSurge(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockSurge], error) {
	src, err := c.ws.Subscribe(ctx, "0A", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockSurge], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockSurge(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockSurge(d wstransport.Delivery) stream.Event[DomesticStockSurge] {
	// 봉투는 봉투째 옮긴다. StexTp 는 실시간 23종에는 없어 늘 빈 문자열이지만, 한 곳에서만
	// 옮기고 다른 곳에서 빠뜨리면 키움이 이 필드를 더하는 날 조용히 사라진다.
	ev := stream.Event[DomesticStockSurge]{Symbol: d.Item, Name: d.Name, StexTp: d.StexTp, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
