// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockTodayBrokers 는 주식당일거래원(0F) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockTodayBrokers struct {
	// 매도거래원1
	SellMember1 string `json:"141"`
	// 매도거래원수량1 (단위: 1주)
	SellMemberQuantity1 string `json:"161"`
	// 매도거래원별증감1 (단위: 1주, 부호가 포함된 숫자)
	SellMemberChange1 string `json:"166"`
	// 매도거래원코드1
	SellMemberCode1 string `json:"146"`
	// 매도거래원색깔1
	SellMemberColor1 string `json:"271"`
	// 매수거래원1
	BuyMember1 string `json:"151"`
	// 매수거래원수량1 (단위: 1주)
	BuyMemberQuantity1 string `json:"171"`
	// 매수거래원별증감1 (단위: 1주, 부호가 포함된 숫자)
	BuyMemberChange1 string `json:"176"`
	// 매수거래원코드1
	BuyMemberCode1 string `json:"156"`
	// 매수거래원색깔1
	BuyMemberColor1 string `json:"281"`
	// 매도거래원2
	SellMember2 string `json:"142"`
	// 매도거래원수량2 (단위: 1주)
	SellMemberQuantity2 string `json:"162"`
	// 매도거래원별증감2 (단위: 1주, 부호가 포함된 숫자)
	SellMemberChange2 string `json:"167"`
	// 매도거래원코드2
	SellMemberCode2 string `json:"147"`
	// 매도거래원색깔2
	SellMemberColor2 string `json:"272"`
	// 매수거래원2
	BuyMember2 string `json:"152"`
	// 매수거래원수량2 (단위: 1주)
	BuyMemberQuantity2 string `json:"172"`
	// 매수거래원별증감2 (단위: 1주, 부호가 포함된 숫자)
	BuyMemberChange2 string `json:"177"`
	// 매수거래원코드2
	BuyMemberCode2 string `json:"157"`
	// 매수거래원색깔2
	BuyMemberColor2 string `json:"282"`
	// 매도거래원3
	SellMember3 string `json:"143"`
	// 매도거래원수량3 (단위: 1주)
	SellMemberQuantity3 string `json:"163"`
	// 매도거래원별증감3 (단위: 1주, 부호가 포함된 숫자)
	SellMemberChange3 string `json:"168"`
	// 매도거래원코드3
	SellMemberCode3 string `json:"148"`
	// 매도거래원색깔3
	SellMemberColor3 string `json:"273"`
	// 매수거래원3
	BuyMember3 string `json:"153"`
	// 매수거래원수량3 (단위: 1주)
	BuyMemberQuantity3 string `json:"173"`
	// 매수거래원별증감3 (단위: 1주, 부호가 포함된 숫자)
	BuyMemberChange3 string `json:"178"`
	// 매수거래원코드3
	BuyMemberCode3 string `json:"158"`
	// 매수거래원색깔3
	BuyMemberColor3 string `json:"283"`
	// 매도거래원4
	SellMember4 string `json:"144"`
	// 매도거래원수량4 (단위: 1주)
	SellMemberQuantity4 string `json:"164"`
	// 매도거래원별증감4 (단위: 1주, 부호가 포함된 숫자)
	SellMemberChange4 string `json:"169"`
	// 매도거래원코드4
	SellMemberCode4 string `json:"149"`
	// 매도거래원색깔4
	SellMemberColor4 string `json:"274"`
	// 매수거래원4
	BuyMember4 string `json:"154"`
	// 매수거래원수량4 (단위: 1주)
	BuyMemberQuantity4 string `json:"174"`
	// 매수거래원별증감4 (단위: 1주, 부호가 포함된 숫자)
	BuyMemberChange4 string `json:"179"`
	// 매수거래원코드4
	BuyMemberCode4 string `json:"159"`
	// 매수거래원색깔4
	BuyMemberColor4 string `json:"284"`
	// 매도거래원5
	SellMember5 string `json:"145"`
	// 매도거래원수량5 (단위: 1주)
	SellMemberQuantity5 string `json:"165"`
	// 매도거래원별증감5 (단위: 1주, 부호가 포함된 숫자)
	SellMemberChange5 string `json:"170"`
	// 매도거래원코드5
	SellMemberCode5 string `json:"150"`
	// 매도거래원색깔5
	SellMemberColor5 string `json:"275"`
	// 매수거래원5
	BuyMember5 string `json:"155"`
	// 매수거래원수량5 (단위: 1주)
	BuyMemberQuantity5 string `json:"175"`
	// 매수거래원별증감5 (단위: 1주, 부호가 포함된 숫자)
	BuyMemberChange5 string `json:"180"`
	// 매수거래원코드5
	BuyMemberCode5 string `json:"160"`
	// 매수거래원색깔5
	BuyMemberColor5 string `json:"285"`
	// 외국계매도추정합
	ForeignSellEstimateTotal string `json:"261"`
	// 외국계매도추정합변동
	ForeignSellEstimateTotalChange string `json:"262"`
	// 외국계매수추정합
	ForeignBuyEstimateTotal string `json:"263"`
	// 외국계매수추정합변동
	ForeignBuyEstimateTotalChange string `json:"264"`
	// 외국계순매수추정합
	ForeignNetBuyEstimateTotal string `json:"267"`
	// 외국계순매수변동
	ForeignNetBuyChange string `json:"268"`
	// 거래소구분
	ExchangeType string `json:"337"`
}

// SubscribeDomesticStockTodayBrokers 은 주식당일거래원(0F) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockTodayBrokers(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockTodayBrokers], error) {
	src, err := c.ws.Subscribe(ctx, "0F", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockTodayBrokers], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockTodayBrokers(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockTodayBrokers(d wstransport.Delivery) stream.Event[DomesticStockTodayBrokers] {
	// 봉투는 봉투째 옮긴다. StexTp 는 실시간 23종에는 없어 늘 빈 문자열이지만, 한 곳에서만
	// 옮기고 다른 곳에서 빠뜨리면 키움이 이 필드를 더하는 날 조용히 사라진다.
	ev := stream.Event[DomesticStockTodayBrokers]{Symbol: d.Item, Name: d.Name, StexTp: d.StexTp, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
