// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockSurge 는 주식기세(0A) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockSurge struct {
	// 현재가
	CurrentPrice string `json:"10"`
	// 전일대비
	PrevDayDiff string `json:"11"`
	// 등락율
	ChangeRate string `json:"12"`
	// (최우선)매도호가
	BestAskPrice string `json:"27"`
	// (최우선)매수호가
	BestBidPrice string `json:"28"`
	// 누적거래량
	CumulativeVolume string `json:"13"`
	// 누적거래대금
	CumulativeTradeAmount string `json:"14"`
	// 시가
	OpenPrice string `json:"16"`
	// 고가
	HighPrice string `json:"17"`
	// 저가
	LowPrice string `json:"18"`
	// 전일대비기호
	PrevDayDiffSign string `json:"25"`
	// 전일거래량대비(계약,주)
	PrevDayVolumeDiff string `json:"26"`
	// 거래대금증감
	TradeAmountChange string `json:"29"`
	// 전일거래량대비(비율)
	PrevDayVolumeRatio string `json:"30"`
	// 거래회전율
	TurnoverRate string `json:"31"`
	// 거래비용
	TradeCost string `json:"32"`
	// 시가총액(억)
	MarketCapHundredMillionWon string `json:"311"`
	// 상한가발생시간
	UpperLimitTime string `json:"567"`
	// 하한가발생시간
	LowerLimitTime string `json:"568"`
}

// SubscribeDomesticStockSurge 은 주식기세(0A) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockSurge(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockSurge], error) {
	src, err := c.ws.Subscribe(ctx, "0A", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockSurge], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockSurge(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockSurge(d wstransport.Delivery) stream.Event[DomesticStockSurge] {
	ev := stream.Event[DomesticStockSurge]{Symbol: d.Item, Name: d.Name, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
