// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockProgramTrade 는 종목프로그램매매(0w) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockProgramTrade struct {
	// 체결시간 (HHmmss)
	TradeTime string `json:"20"`
	// 현재가 (단위: 원, 부호가 포함된 숫자)
	CurrentPrice string `json:"10"`
	// 전일대비기호 (1: 상한가, 2:상승, 3:보합, 4:하한가, 5:하락)
	PrevDayDiffSign string `json:"25"`
	// 전일대비 (단위: 원, 부호가 포함된 숫자)
	PrevDayDiff string `json:"11"`
	// 등락율 (단위: %, 부호 포함 소수점 둘째 자리까지 포맷된 백분율)
	ChangeRate string `json:"12"`
	// 누적거래량 (단위: 1주)
	CumulativeVolume string `json:"13"`
	// 매도수량 (단위: 1주)
	SellQuantity string `json:"202"`
	// 매도금액 (단위: 원)
	SellAmount string `json:"204"`
	// 매수수량 (단위: 1주)
	BuyQuantity string `json:"206"`
	// 매수금액
	BuyAmount string `json:"208"`
	// 순매수수량
	NetBuyQuantity string `json:"210"`
	// 순매수수량증감 (계약,주)
	NetBuyQuantityChange string `json:"211"`
	// 순매수금액
	NetBuyAmount string `json:"212"`
	// 순매수금액증감
	NetBuyAmountChange string `json:"213"`
	// 장시작예상잔여시간
	MarketOpenRemainingTime string `json:"214"`
	// 장운영구분
	MarketOperationType string `json:"215"`
	// 투자자별ticker
	InvestorTicker string `json:"216"`
}

// SubscribeDomesticStockProgramTrade 은 종목프로그램매매(0w) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockProgramTrade(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockProgramTrade], error) {
	src, err := c.ws.Subscribe(ctx, "0w", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockProgramTrade], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockProgramTrade(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockProgramTrade(d wstransport.Delivery) stream.Event[DomesticStockProgramTrade] {
	// 봉투는 봉투째 옮긴다. StexTp 는 실시간 23종에는 없어 늘 빈 문자열이지만, 한 곳에서만
	// 옮기고 다른 곳에서 빠뜨리면 키움이 이 필드를 더하는 날 조용히 사라진다.
	ev := stream.Event[DomesticStockProgramTrade]{Symbol: d.Item, Name: d.Name, StexTp: d.StexTp, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
