// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticElwTheoreticalPrice 는 ELW 이론가(0m) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticElwTheoreticalPrice struct {
	// 체결시간 (HHmmss)
	TradeTime string `json:"20"`
	// 현재가 (단위: 원, 부호가 포함된 숫자)
	CurrentPrice string `json:"10"`
	// ELW이론가
	ELWTheoreticalPrice string `json:"670"`
	// ELW내재변동성
	ELWImpliedVolatility string `json:"671"`
	// ELW델타
	ELWDelta string `json:"672"`
	// ELW감마
	ELWGamma string `json:"673"`
	// ELW쎄타
	ELWTheta string `json:"674"`
	// ELW베가
	ELWVega string `json:"675"`
	// ELW로
	ELWRho string `json:"676"`
	// LP호가내재변동성
	LPQuoteImpliedVolatility string `json:"706"`
}

// SubscribeDomesticElwTheoreticalPrice 은 ELW 이론가(0m) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticElwTheoreticalPrice(ctx context.Context, items ...string) (<-chan stream.Event[DomesticElwTheoreticalPrice], error) {
	src, err := c.ws.Subscribe(ctx, "0m", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticElwTheoreticalPrice], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticElwTheoreticalPrice(d)
		}
	}()
	return out, nil
}

func decodeDomesticElwTheoreticalPrice(d wstransport.Delivery) stream.Event[DomesticElwTheoreticalPrice] {
	// 봉투는 봉투째 옮긴다. StexTp 는 실시간 23종에는 없어 늘 빈 문자열이지만, 한 곳에서만
	// 옮기고 다른 곳에서 빠뜨리면 키움이 이 필드를 더하는 날 조용히 사라진다.
	ev := stream.Event[DomesticElwTheoreticalPrice]{Symbol: d.Item, Name: d.Name, StexTp: d.StexTp, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
