// Code generated by tools/gen. DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"

	"github.com/kenshin579/kiwoom-go/internal/wstransport"
	"github.com/kenshin579/kiwoom-go/stream"
)

// DomesticStockTrade 는 주식체결(0B) 의 실시간 값이다.
//
// 필드 이름은 tools/gen/fids.go 의 표에서 온다 — 스펙은 FID 숫자와 한글명만 준다.
type DomesticStockTrade struct {
	// 체결시간
	TradeTime string `json:"20"`
	// 현재가
	CurrentPrice string `json:"10"`
	// 전일대비
	PrevDayDiff string `json:"11"`
	// 등락율
	ChangeRate string `json:"12"`
	// (최우선)매도호가
	BestAskPrice string `json:"27"`
	// (최우선)매수호가
	BestBidPrice string `json:"28"`
	// 거래량
	TradeVolume string `json:"15"`
	// 누적거래량
	CumulativeVolume string `json:"13"`
	// 누적거래대금
	CumulativeTradeAmount string `json:"14"`
	// 시가
	OpenPrice string `json:"16"`
	// 고가
	HighPrice string `json:"17"`
	// 저가
	LowPrice string `json:"18"`
	// 전일대비기호
	PrevDayDiffSign string `json:"25"`
	// 전일거래량대비(계약,주)
	PrevDayVolumeDiff string `json:"26"`
	// 거래대금증감
	TradeAmountChange string `json:"29"`
	// 전일거래량대비(비율)
	PrevDayVolumeRatio string `json:"30"`
	// 거래회전율
	TurnoverRate string `json:"31"`
	// 거래비용
	TradeCost string `json:"32"`
	// 체결강도
	TradeStrength string `json:"228"`
	// 시가총액(억)
	MarketCapHundredMillionWon string `json:"311"`
	// 장구분
	SessionType string `json:"290"`
	// K.O 접근도
	KnockOutProximity string `json:"691"`
	// 상한가발생시간
	UpperLimitTime string `json:"567"`
	// 하한가발생시간
	LowerLimitTime string `json:"568"`
	// 전일 동시간 거래량 비율
	PrevDaySameTimeVolumeRatio string `json:"851"`
	// 시가시간
	OpenTime string `json:"1890"`
	// 고가시간
	HighTime string `json:"1891"`
	// 저가시간
	LowTime string `json:"1892"`
	// 매도체결량
	SellExecutionVolume string `json:"1030"`
	// 매수체결량
	BuyExecutionVolume string `json:"1031"`
	// 매수비율
	BuyRatio string `json:"1032"`
	// 매도체결건수
	SellExecutionCount string `json:"1071"`
	// 매수체결건수
	BuyExecutionCount string `json:"1072"`
	// 순간거래대금
	InstantTradeAmount string `json:"1313"`
	// 매도체결량_단건
	SingleSellExecutionVolume string `json:"1315"`
	// 매수체결량_단건
	SingleBuyExecutionVolume string `json:"1316"`
	// 순매수체결량
	NetBuyExecutionVolume string `json:"1314"`
	// CFD증거금
	CFDMargin string `json:"1497"`
	// 유지증거금
	MaintenanceMargin string `json:"1498"`
	// 당일거래평균가
	TodayAveragePrice string `json:"620"`
	// CFD거래비용
	CFDTradeCost string `json:"732"`
	// 대주거래비용
	StockLoanTradeCost string `json:"852"`
	// 거래소구분
	TradeExchangeType string `json:"9081"`
}

// SubscribeDomesticStockTrade 은 주식체결(0B) 을 구독한다.
//
// ctx 를 취소하면 등록을 해제하고 채널을 닫는다. 채널이 가득 차면 이벤트를 버리고
// *kiwoom.SlowConsumerError 를 흘린다 — 한 구독의 느림이 다른 구독을 굶기지 않는다.
// 끊겼다 붙으면 *kiwoom.GapError 가 온다. 그 사이 이벤트는 받지 못한 것이다.
func (c *Client) SubscribeDomesticStockTrade(ctx context.Context, items ...string) (<-chan stream.Event[DomesticStockTrade], error) {
	src, err := c.ws.Subscribe(ctx, "0B", items, defaultBuffer)
	if err != nil {
		return nil, err
	}
	out := make(chan stream.Event[DomesticStockTrade], defaultBuffer)
	go func() {
		defer close(out)
		for d := range src {
			out <- decodeDomesticStockTrade(d)
		}
	}()
	return out, nil
}

func decodeDomesticStockTrade(d wstransport.Delivery) stream.Event[DomesticStockTrade] {
	ev := stream.Event[DomesticStockTrade]{Symbol: d.Item, Name: d.Name, Time: d.Time, Err: d.Err}
	if d.Err != nil {
		return ev
	}
	// 두 번 푼다. 구조체는 표에 있는 FID 만 받고, Raw 는 전부 받는다 —
	// 키움이 FID 를 추가했을 때 encoding/json 이 조용히 버리지 않게 한다.
	if err := json.Unmarshal(d.Values, &ev.Value); err != nil {
		ev.Err = err
		return ev
	}
	if err := json.Unmarshal(d.Values, &ev.Raw); err != nil {
		ev.Err = err
	}
	return ev
}
